### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by winterheart** [naev/naev#1001]
Hello.

Currently there 0.7.0 release available which has issue with new GCC 10:
* https://bugs.gentoo.org/710198
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957575

Usually distributions creates simple patches that solves these problems, but this one not trivial. I see that GCC 10 compiling issue already solved by switching to Galogen GL generator (https://github.com/naev/naev/commit/97e0a890d56d0b2db98882ba5f734c291cfeb650), but I as package maintainer, cannot just cherry-pick this commit since there a lot commits before and resulting package will eventually fail. So can you please prepare and release new version?

**Comment by ids1024** [comment]
Yeah, we probably should do a release soon. For various reasons.

Just compiling with `./configure CFLAGS=-fcommon` should fix the build, right? Is there any issue with passing that while building distro packages, as a temporary solution?

**Comment by winterheart** [comment]
Well, most of distribution either pass -fcommon to compiler, or blocked GCC 10 to release. At least for Gentoo we tracking failed packages (our tracker https://bugs.gentoo.org/705764) and get them fixed. Until that GCC 10 is blocked for end users.

**Comment by bobbens** [comment]
0.8.0-beta1 has been released. If all goes well expect 0.8.0 in a few weeks.

**Comment by SoapGentoo** [comment]
Any movement on releasing 0.8.0? We don't want to backport the big GCC 10 fix.

**Comment by UncombedCoconut** [comment]
> Any movement on releasing 0.8.0? We don't want to backport the big GCC 10 fix.

Yes, the tracker for pre-release issues yet to be resolved is here: https://github.com/naev/naev/projects/1
Some build/release automation improvements just landed and with luck will allow for an imminent 0.8.0-beta.4.

**Comment by bobbens** [comment]
0.8.0 released! Closing.
