### ISSUE TITLE
Sound on ubuntu 20.04

### ISSUE THREAD

**Issue by agb32** [naev/naev#1003]
Running naev on ubuntu 20.04 seems to crash:
Crashing ALSOFT version detected, disabling EFX
Naev received SIGSEGV (address not mapped to object)!
./naev(+0x8e2d2) [0x556ad0a3c2d2] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f9e7db2a210] ??(...):0 ??
Report this to project maintainer with the backtrace.
AL lib: (EE) alc_cleanup: 1 device not closed

A gdb backtrace yields:
Thread 1 "naev" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000055555563ab09 in sound_al_env (env=env@entry=SOUND_ENV_NORMAL, 
    param=param@entry=0) at sound_openal.c:1120
#2  0x000055555563aea9 in sound_al_init () at sound_openal.c:349
#3  0x0000555555638300 in sound_init () at sound.c:244
#4  0x0000555555582f1f in main (argc=<optimised out>, argv=<optimised out>)
    at naev.c:360

**Comment by ids1024** [comment]
Perhaps related to #806? Using the sdl-mixer backend instead of openal might help.

**Comment by agb32** [comment]
Yes - same problem, I think.  Will close this one.
