### ISSUE TITLE
Clicking on minimap doesn't work when scaled

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1024]
Just noticed this when I decided to increase to 2x scaling because my eyes were tired. Clicking on the minimap (that's a part of the GUI) doesn't seem to work at all when scaling is enabled. Other parts (overlay map, clicking on ships themselves) work just fine.

**Comment by bobbens** [comment]
Fixed in 4cd59cca3b9fb0103385dd1666385b6891dc48b5 .

**Comment by onpon4** [comment]
We're going to need to reopen this. The fix actually ended up breaking it when unscaled, and when the view port is at something other than (0, 0)

It's not visible in Brushed anymore because it sets a full-screen viewport now but should be visible in Slim. I'm not entirely sure what to make of it.
