### ISSUE TITLE
Sightseeing mission issues/suggestions

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1027]
Version: 0.8.0 beta

Bug: If I start a sightseeing mission without a luxury yacht, I get reduced pay and I am warned about it. But if I open the list of accepted missions, the mission still displays the full pay
Suggestion: Put the "soft" requirement of luxury yacht into the mission description (planet screen)
Suggestion: When you complete the sightseeing mission, display the pay again (the true pay, of course)

**Comment by onpon4** [comment]
Fixed in #1103.
