### ISSUE TITLE
Make commodities searchable

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1028]
I find it very hard to remember which planets offer which commodities, so I suggest to add them to the search (like the System/Planet/Outfit/Ship search).

**Comment by onpon4** [comment]
I was suggesting on Discord that commodities should generally be available everywhere, just with price adjustments. If we were to do that then it would help with this (as well as other issues).

**Comment by agb32** [comment]
These are now basically searchable using the new trade function on the map (currently in a pull request)

**Comment by bobbens** [comment]
I don't think this is an issue anymore.
