### ISSUE TITLE
[Proposal] Markdown Support

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1029]
Implement some markdown for the general text in Naev. A basic wishlist would be:

1. Bold font (`**text**`)
2. Italic font (`*text*`)
3. underline (`_text_`)
4. tooltips (on hover, either automatically generated from keywords and/or user specified) (`^[text]`?)
5. colour (improve current system to be more consistent with standard markdowns)

Fancy approach would be to use some sort of markdown library and/or html/css to render very nice stuff to textures/framebuffers, then display them in a "batch" setting. Would be much more efficient than the current approach, but much more work. It could use similar API as currently, but internally use a hash table and garbage collector to manage it.

**Comment by Moth-Tolias** [comment]
what about italics as /text/ ?

**Comment by bobbens** [comment]
`/text/` would also be possible, but I would rather stick to [markdown specification](https://daringfireball.net/projects/markdown/) unless there is a reason not to, mainly so I don't have to learn yet another syntax ;)

**Comment by bobbens** [comment]
I added a markdown luatk module, so this is pretty much solved. Probably will be replaced by rust iced library if we go that way. #2617
