### ISSUE TITLE
Define planet classes

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1033]
IIRC the planet classes have never been strictly defined. Or at least, there's no public document (anymore?).

The only thing that is certain that numbers 0-9 are used for space stations and letters A-Z for planets.

If I remember correctly, planet classes A-Z are based on Star Trek. <https://memory-beta.fandom.com/wiki/Planet> seems to be the closest, although it's not perfectly matching Naev.

For example, Naev has many planets of class D, but in Star Trek it seems to be moon-only? Clearly Naev is using D for something else (presumably rocky planets).

I think Naev should define the planet classes explicitly because relying on an external document is not a good idea. Even if most classes are same as Star Trek, I think Naev / the wiki should have a list in their own words, just so all contributors are on the same page.

So I suggest: Make a list of what each letter/number means and put it on the wiki.

Note the game itself does not need to be touched at all for this, this issue could be counted as lore.

**Comment by onpon4** [comment]
bobbens said he thinks this is what it's based on originally:

https://stexpanded.fandom.com/wiki/Planet_classifications

The old wiki had an entry for them explaining classifications. We should get that (and other missing stuff from the old wiki) onto the GitHub wiki.

**Comment by Wuzzy2** [comment]
The Internet Archive Wayback Machine has archives of some of the Naev wiki pages, the planet classes did, however, not make it. :/

**Comment by onpon4** [comment]
Yeah, that was what I thought too. I'm sure the folks who wrote the classification should be able to recall the important bits. :wink:

**Comment by onpon4** [comment]
Ah, I didn't realize you had two of these.

I made the page on the wiki here: https://github.com/naev/naev/wiki/Planetary-Classes

**Comment by onpon4** [comment]
So regarding class D, I did a grep and there's really not that many. The only inhabited one is Jorlan which is definitely rock-like. If any of the rest (I think they're all uninhabited) aren't a match that can be fixed.

**Comment by bobbens** [comment]
Closing as fixed. The link should also be somewhere in the code.
