### ISSUE TITLE
Consolidate planet classes X, Y and Z

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1034]
What's the difference between planet classes X, Y and Z? It seems those are the same, all are meant for planets with highly toxic atmosphere.

So I suggest to combine the 3 classes into one. Unless there's an actual difference that I'm not aware of.

**Comment by onpon4** [comment]
I believe the old wiki used to define a particular difference (there were some discrepancy from Star Trek classifications IIRC, though not many). I'm not entirely sure about this, though, so maybe one of the project members can clarify.

**Comment by onpon4** [comment]
I've added an entry on the GitHub wiki, should be good as a starting point: https://github.com/naev/naev/wiki/Planetary-Classes

**Comment by onpon4** [comment]
I've taken a look and written down what I think the distinction between the classes are on the wiki page. Anyone who knows better can correct me if needed.

> * Class X: Demon (very hot (500K+), inhospitable)
> * Class Y: Toxic (very toxic, inhospitable, containing valuable minerals)
> * Class Z: Shattered (formerly hospitable planet which has become hot and/or toxic and inhospitable)
