### ISSUE TITLE
Portraits we still need

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1037]
Pulling https://opengameart.org/content/portraits-for-naev into Naev has made a massive difference as far as our portrait lineup goes. That said, we still don't have all the portraits we need, so I'm opening this issue to document what is still needed from artists as far as portraits go.

The current portraits (as of this writing) are based on a layered XCF file:

https://github.com/onpon4/naev-artwork/blob/master/2D/portraits/portrait_nihilos.xcf

Ideally artists should add what's needed to that, preferably as components that can be swapped out with the rest of the components. Completely custom portraits would also be helpful, though.

Just a note: this issue necessarily discusses big spoilers since that's part of what we're missing for portraits.

Anyway, here's what we're currently missing (which the current XCF doesn't have the components for):

* All Soromid portraits. Soromid should look genetically modified, and Soromid military should probably have some kind of uniform (like other factions).
* All Proteron portraits. The way Proteron society is structured suggests that all Proteron civilians should probably be dressed in an almost militaristic way, and we also need military uniforms for officials.
* Serra-class Sirius civilian portraits. We probably don't usually want these in bars (I think Serra is the highest class; correct me if I'm wrong), but they would probably be useful in Sirius campaigns.
* Thurion civilian portraits. I tend to assume the Thurion should somehow look different from the rest of the galaxy, though I'm not sure how. Obviously some of them can be robots (physical embodiments of uploaded Thurion), but it seems to me that organic Thurions should have some defining characteristics too. (Note: we probably don't need Thurion military portraits since we can probably assume the Thurion leaders to be mostly uploaded, and thus not hanging out in bars for any reason. But if we do want Thurion "uniforms", maybe just a background that looks like a computer screen of some sort, or possibly components that look like holographic projections if you want to get more involved.)
* Za'lek military portraits. We probably need military uniforms for the Za'lek, though I assume military officials would be uncommon in Za'lek space; this would most likely just be for the Proteron invasion.
* Frontier portraits. We don't have military uniforms for the Frontier, though I'm not entirely sure we want that (we might want them to depend exclusively on the FLF for war). In any case, maybe we should have some sort of defined look for Frontier civilians (maybe a look shared with the FLF pilots). I'm not sure what that would be, though.
* Empire civilian portraits. Not essential, but it could be nice to have some sort of defining Empire civilian characteristic clothing. I'm not sure what that would be.
* Trader portraits. Again, not essential, but it could be nice to have some defining feature for traders, though I'm not sure what that could be.
* More variation for people of color. Right now options for making non-white portraits are very limited and this could really use some expansion. More specifically: very few components match with the darker skin tones, and not many different skin tones are available. This could use some work. (See #1006 for a related issue.)

**Comment by Wuzzy2** [comment]
* “An unfamiliar man” has missing portrait.

**Comment by onpon4** [comment]
Huh, looks like I made a mistake with that one. I'll fix that.

**Comment by bobbens** [comment]
I think that it might be easier for people to add and remove needed artwork with a wiki page rather than an issue as you can get lost with what is needed here while the wiki page can be more structured. Created https://github.com/naev/naev/wiki/Needed-Artwork%3A-Characters from this issue. Closing issue for now.
