### ISSUE TITLE
Engine continues to consider a key "pressed" when leaving a dialog if it was before.

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1050]
I suppose I should have reported this ages ago, but it's been a problem ever since I got here, so it never seemed like a "new" thing to me.

Anyway, when you enter a dialog with a key pressed, the engine continues to register that key as "pressed" when the dialog closes, even if the key isn't actually pressed. This would be a result of code that redirects keypresses to the dialog. Pressing the key again causes the problem to end any time it happens (since that triggers a key release event).

Fix for this would be to check the status of keys when returning to the main screen and adjust as appropriate (or, alternatively, intentionally "ghost" all keys by resetting all the key states to unpressed).

**Comment by UncombedCoconut** [comment]
For posterity: some stuck-key effects aren't this. They're this: https://github.com/libsdl-org/SDL/issues/4018 (in case of Wayland and SDL <=2.0.14).
With the latest git versions of SDL2 and Naev, I actually have a very hard time hitting the issue described here.
Potential example:
- Remap the controls so the "accelerate" key is Enter (a key that dialogs are interested in)
- Start a new game and accept the tutorial mission.
- Start flying toward the planet, coast until a dialog pops up.
- Press and hold Enter, for as long as you please. You will not accelerate.
Does the above seem like a representative example of the issue? Does it get worse?

**Comment by onpon4** [comment]
Ok, I've downloaded the Naev nightly to confirm my suspicion: Naev still has this problem on my end in the latest nightly. The above steps reproduce the problem for me on Naev as well. I don't see the issue with the thrust key, but it could be that the bug affects only certain keys. I know it at least affects the autoface key.

🕵️

**Comment by onpon4** [comment]
Some further testing shows that the bug seems to specifically affect the autoface key and instant mode weapon keys. It doesn't seem to affect anything else.

🕵️

**Comment by UncombedCoconut** [comment]
Thanks. The reason it triggers inconsistently (not for all keys and all dialogs) is that a dialog's input handler is allowed to say "I'm not interested" -- and this is the norm, and this lets the usual input handler see the keystroke.
Of course, the goal is to have things be consistently correct, irrespective of the specific scenario (autoface vs. weapon set vs. remapped keys). But it's important to have test cases, in case I miss a bit of hidden state that must be synced up.

**Comment by onpon4** [comment]
Just did some work on this, this patch seems to fix the issue:

```diff
diff --git a/src/input.c b/src/input.c
index 299134b76..31f512bea 100644
--- a/src/input.c
+++ b/src/input.c
@@ -32,6 +32,7 @@
 #include "nstring.h"
 #include "pause.h"
 #include "pilot.h"
+#include "pilot_weapon.h"
 #include "player.h"
 #include "toolkit.h"
 #include "weapon.h"
@@ -691,6 +692,7 @@ void input_update( double dt )
 !pilot_isFlag(player.p,PILOT_HYPERSPACE)) /**< Make sure the player isn't jumping. */
 #define NODEAD()  ((player.p != NULL) && !pilot_isFlag(player.p,PILOT_DEAD)) /**< Player isn't dead. */
 #define NOLAND()  ((player.p != NULL) && (!landed && !pilot_isFlag(player.p,PILOT_LANDING))) /**< Player isn't landed. */
+#define NEEDWSET(id) (INGAME() || (pilot_weapSet(player.p,id)->type == WEAPSET_TYPE_WEAPON)) /**< Need to update weaponset. */
 /**
  * @brief Runs the input command.
  *
@@ -808,6 +810,15 @@ static void input_key( int keynum, double value, double kabs, int repeat )
             player_accelOver();
       }
 
+   /* face the target */
+   } else if (KEY("face") && !repeat) {
+      if (value==KEY_PRESS) {
+         player_restoreControl( PINPUT_MOVEMENT, NULL );
+         player_setFlag(PLAYER_FACE);
+      }
+      else if ((value==KEY_RELEASE) && player_isFlag(PLAYER_FACE))
+         player_rmFlag(PLAYER_FACE);
+
 
    /*
     * combat
@@ -834,14 +845,6 @@ static void input_key( int keynum, double value, double kabs, int repeat )
       if (value==KEY_PRESS) player_targetHostile();
    } else if (INGAME() && NODEAD() && KEY("target_clear")) {
       if (value==KEY_PRESS) player_targetClear();
-   /* face the target */
-   } else if (INGAME() && NODEAD() && KEY("face") && !repeat) {
-      if (value==KEY_PRESS) {
-         player_restoreControl( PINPUT_MOVEMENT, NULL );
-         player_setFlag(PLAYER_FACE);
-      }
-      else if ((value==KEY_RELEASE) && player_isFlag(PLAYER_FACE))
-         player_rmFlag(PLAYER_FACE);
 
    /* board them ships */
    } else if (KEY("board") && INGAME() && NOHYP() && NODEAD() && !repeat) {
@@ -880,25 +883,25 @@ static void input_key( int keynum, double value, double kabs, int repeat )
          player_rmFlag(PLAYER_SECONDARY);
 
    /* Weapon sets. */
-   } else if (INGAME() && NODEAD() && KEY("weapset1")) {
+   } else if (NEEDWSET(0) && NODEAD() && KEY("weapset1")) {
       player_weapSetPress( 0, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset2")) {
+   } else if (NEEDWSET(1) && NODEAD() && KEY("weapset2")) {
       player_weapSetPress( 1, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset3")) {
+   } else if (NEEDWSET(2) && NODEAD() && KEY("weapset3")) {
       player_weapSetPress( 2, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset4")) {
+   } else if (NEEDWSET(3) && NODEAD() && KEY("weapset4")) {
       player_weapSetPress( 3, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset5")) {
+   } else if (NEEDWSET(4) && NODEAD() && KEY("weapset5")) {
       player_weapSetPress( 4, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset6")) {
+   } else if (NEEDWSET(5) && NODEAD() && KEY("weapset6")) {
       player_weapSetPress( 5, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset7")) {
+   } else if (NEEDWSET(6) && NODEAD() && KEY("weapset7")) {
       player_weapSetPress( 6, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset8")) {
+   } else if (NEEDWSET(7) && NODEAD() && KEY("weapset8")) {
       player_weapSetPress( 7, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset9")) {
+   } else if (NEEDWSET(8) && NODEAD() && KEY("weapset9")) {
       player_weapSetPress( 8, value, repeat );
-   } else if (INGAME() && NODEAD() && KEY("weapset0")) {
+   } else if (NEEDWSET(9) && NODEAD() && KEY("weapset0")) {
       player_weapSetPress( 9, value, repeat );
 
    /*
diff --git a/src/pilot_weapon.c b/src/pilot_weapon.c
index a3f37d106..7fcdcbb12 100644
--- a/src/pilot_weapon.c
+++ b/src/pilot_weapon.c
@@ -45,7 +45,6 @@
  * Prototypes.
  */
 static void pilot_weapSetUpdateOutfits( Pilot* p, PilotWeaponSet *ws );
-static PilotWeaponSet* pilot_weapSet( Pilot* p, int id );
 static int pilot_weapSetFire( Pilot *p, PilotWeaponSet *ws, int level );
 static int pilot_shootWeaponSetOutfit( Pilot* p, PilotWeaponSet *ws, Outfit *o, int level, double time );
 static int pilot_shootWeapon( Pilot* p, PilotOutfitSlot* w, double time );
@@ -59,7 +58,7 @@ static void pilot_weapSetUpdateRange( PilotWeaponSet *ws );
  *    @param id ID of the weapon set.
  *    @return The weapon set matching id.
  */
-static PilotWeaponSet* pilot_weapSet( Pilot* p, int id )
+PilotWeaponSet* pilot_weapSet( Pilot* p, int id )
 {
    return &p->weapon_sets[ id ];
 }
diff --git a/src/pilot_weapon.h b/src/pilot_weapon.h
index ae3595326..228d566de 100644
--- a/src/pilot_weapon.h
+++ b/src/pilot_weapon.h
@@ -36,6 +36,7 @@ void pilot_weapSetUpdate( Pilot* p );
 
 
 /* Weapon Set. */
+PilotWeaponSet* pilot_weapSet( Pilot* p, int id );
 const char *pilot_weapSetName( Pilot* p, int id );
 void pilot_weapSetRmSlot( Pilot *p, int id, OutfitSlotType type );
 void pilot_weapSetAdd( Pilot* p, int id, PilotOutfitSlot *o, int level );
```

**Comment by UncombedCoconut** [comment]
Aha! So nothing to do with the dialog's handler eating events it shouldn't have, and everything to do with the glorious `input_key` machine checking `INGAME()`.
This looks like the right thing to fix.

**Comment by UncombedCoconut** [comment]
This patch will cherry-pick cleanly onto naev/main, and I'm inclined to do that.
However, I'm unclear on how the weapon-set change would affect the outcome. `pilot_weapSetPress` will itself check `toolkit_isOpen()`, i.e., `!INGAME()`, before doing anything.

The easy solution is to remove the `INGAME`/`NEEDWSET` check entirely, and have `pilot_weapSetPress` decide what to do along the lines suggested by `NEEDWSET`.

It seems like the ideal, correct-by-construction, annoying-to-code approach could be to shrink the `input_key` function's job, so it merely records what actions the player intends to take at the start of the frame (e.g., yes auto-face, yes weapset1, not weapset2..), and apply them in the main loop where we currently `player_updateAutonav`.

\* This "set" could be as simple as a few more PLAYER_* flags.

More moderately, it might be easy to manage the `PLAYER_FACE` flag in `input_key` while deferring the `player_restoreControl` step. This would prevent weird side effects of pressing `q` while paused.

**Comment by onpon4** [comment]
Well I did test it and what I wrote does result in fixing the bug with instant mode keys (I even checked them all individually just to make sure). I don't see any `toolkit_isOpen()` isn't called in `pilot_weapSetPress` on my end. Is that a recent change?

🕵️

**Comment by UncombedCoconut** [comment]
Aha. I don't get notified of edits (only new posts), so I didn't notice you were doing a simplification at the same time. Pardon the mess...

**Comment by onpon4** [comment]
No worries! Anyway I believe this should be solved, so I guess I'll close it now. Feel free to reopen it if I'm wrong.

🕵️
