### ISSUE TITLE
Escort woes

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1051]
A few things regarding escorts...

Firstly, let me get the small thing out of the way: there's no display for the escort's standing to you, presumably because there's no faction definition. I see that its nominal faction name is "Escort", but adding a static "Escort" faction entry doesn't seem to help.

That's pretty minor though. Now for the important stuff: interaction with missions.

I've known for a while that escorts aren't handled well by missions (since their kills don't count as your kills; hooks for damage and death won't set you as the killer). That should be fixed somehow, presumably by somehow telling missions that the player is the killer when an escort is. But this has to take the cake for escorts breaking missions:

You can hail escorts, and they respond like any pilot in the system.

What this really matters for (rather than just being an oddity) is the Seek And Destroy mission, where you can hail your own escorts for info on the person you're hunting down. I built a ship with tons of fighter bays and was able to get the clue just by hailing all my own fighters; chances were good that it would yield good results.

I think we should get rid of the ability tot hail your own escorts (make them not respond to hails, like drones do; many of them are drones after all). That said, it doesn't  seem to be possible to do this, so far as I can tell. I assume the AI used for escorts is the "escort_player" AI, but setting a comm_no message there doesn't seem to have the intended effect.

Anyway, all of this is worth looking into.

**Comment by ids1024** [comment]
> . I see that its nominal faction name is "Escort", but adding a static "Escort" faction entry doesn't seem to help.

I believe player escorts, when launched from fighter bays, are displayed as part of the "Player" faction, which is set to display as "Escort". This is a bit of a hack, and could potentially be done better.

> I think we should get rid of the ability tot hail your own escorts

That, or make hailing do something that makes sense (like open a special menu for giving commands to an escort). Just disabling it is good for now; we can consider if it should do something interesting later.

**Comment by onpon4** [comment]
> That, or make hailing do something that makes sense (like open a special menu for giving commands to an escort). Just disabling it is good for now; we can consider if it should do something interesting later.

Yes, that is something I did consider. Though in all honesty giving commands to a specific escort wouldn't have much utility. Still, having that feature wouldn't hurt.

**Comment by ids1024** [comment]
I think it's an open question exactly how we want to command individual escorts or groups of them. It's amusing launching as many Light Drones as a Hephaestus can hold, and then ordering them all to attack a single pilot. But that seems a bit too crude, and not granular enough... Even if commanding pilots individually is too granular.

I'm not sure what design would allow the player to govern a large fleet's strategy at a relatively high level, so an appropriate number of an appropriate class of ships carry out an attack.

I suppose looking at fleet systems in other similar games could help. Perhaps we shouldn't get too carried away; fleet vs fleet combat could easily evolve into a full game of its own right (an RTS, I guess) if we try to develop it too fully... But then we need to decide where to stop.

**Comment by onpon4** [comment]
RTS games would be the most applicable. I don't know if we want to add a full-on RTS interface, though, espeicially for such a small part of the game.

If anything, I would think the most Naev-like solution would be to not require intervention from the player at all: make their AI automatically handle most cases. I would even say that they come close to that already, they just need to support each other and the player when attacked is all. (Bonus: doing it this way would improve enemy fleets as well.)

That said, it can't hurt to be able to give commands to individual ships to override their default behavior. The main utility would I think actually be to tell a nearly dead unit to fall back and return to the ship, or to attack a target as a diversion, or something like that.

**Comment by ids1024** [comment]
Yeah, the amount of player intervention required should be reduced if we improve AI support for coordinating fleets (currently, the only coordination they do is maintaining formations).

But we'll want some degree of control. I don't know if we want either "command all escorts to attack target" like now, or "command ship X to attack target". But we probably want the player to be able to do *something* that provides a feeling of control over the fleet.

Probably it would be good to have some relatively high level commands, like instructing a group of fighters to defend a particular ship. Or instructing a ship to be defensive and try to escape danger (some support for that kind of behavior already exists in the AI code). So each pilot could be set to any of several goals/modes (with some reasonable default), and it's AI would determine how to meet that goal.

Or perhaps on the other end of the spectrum, we could have things like the current "order escorts to attack target command", but some fleet AI logic would try to determine what pilot(s) are best to carry out the action.

**Comment by PhoenixRiver** [comment]
Since RTSs were mentioned most have a "standing order" / "default
stance" that the player can set individually or for entire types of
unit; normally you get to pick from "attack on sight / aggressive",
"stand ground / do not move", "fall back / retreat to player base" -
these translate quite nicely to NAEV and could be used to govern the
thrust ofthe escort ships; "attack enemies of the player wherever they
are in the system", "stay where they are (in formation?) but attack
any ship that comes within range and is hostile" and "form up close to
the player and only attack ships that come within range and are
hostile / attack the player".

As already mentioned, the issue of escort co-ordination is a general
AI co-ordination problem, though even just dividing the escorts evenly
between all the enemies ships currently considered targets (see above)
would be something - there is the range problem but having a second
line of defence keeping an eye on targets currently too far to attack
is not necessarily a bad thing - though I guess this would only apply
when escorts are told to stand their ground or form on the player, but
in those cases the player is choosing to dosomething specific and be
defensive so it makes sense, I think.

Just my two cents,

River

**Comment by onpon4** [comment]
I really am not a fan of implementing what are effectively RTS mechanics in Naev. If we should look to any RTS for inspiration I would argue that it's Globulation 2 that we should look toward. That one just has the player set goals and uses AI to determine how best to achieve those goals, not unlike what @ids1024 was suggesting. This would be much more in-line with Naev's gameplay as a whole.

**Comment by Mutos** [comment]
Maybe a squad method ?

- A "New squad" key, launch escorts up to another "New squad" command, and so on;
- Max 9 squads numbered 1 to 9 from creation and shifted down if one is destroyed or retrieved;
- Regular forms of orders (Ctrl+Key) display currently active squads and ask for a squad number;
- Same order with a modifier (Ctrl+Shift+Key) be overrides and apply to all escorts;
- Player hailing an escort just display the orders menu, that applies only to that particular escort and placing it into a squad 0 "individual orders escorts" not reachable by regular squad orders;
- Special "reaffect" order in the hailing menu, active for all escorts including squad 0, asking for an active squad number.
