### ISSUE TITLE
ngettext is unavailable in Lua

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1056]
ngettext is the preferred way to handle plurals, but the Lua API doesn't offer this function.

There are multiple places where it should ideally be used, but the Dvaered Championship mission is the most noteworthy I think; it counts down 5, 4, 3, 2, 1, and just uses plural form for all of them. (For English this could be fixed with two strings but it's not acceptable for all languages since some have different rules for plural forms.)

**Comment by bobbens** [comment]
There is isn't there?
https://www.gnu.org/software/gettext/manual/html_node/Lua.html says gettext.ngettext should work.

**Comment by onpon4** [comment]
Ahhhhh, ok, my bad!
