### ISSUE TITLE
make install creates weird @GETTEXT_PACKAGE@.mo file

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1065]
If I do `.configure`, `make`, `make install`, Naev creates weird files in `/usr/local/share/locale/`.

I see the file `/usr/local/share/locale/ja/LC_MESSAGES/@GETTEXT_PACKAGE@.mo`.
When I was working on the German translation, same thing for `de`.

I suppose the `@GETTEXT_PACKAGE@.mo` was meant to be `naev.mo` but some script failed to use the correct name.

8363e21d3e5edcc594bb032d2a6c15e9df8d5d0a

**Comment by bobbens** [comment]
Should be fixed in e8a9f90e16833f35f0406b38959f157d7bcec774
