### ISSUE TITLE
More typos

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1070]
Two more typos I found in 0.8.0 beta:

Short mission HUD description of a PIRACY mission:

> Kill target Trader ship
> Patrol of %s

(the “%s“ was litereally displayed on-screen)

Pirate civilian text:

> I tried to get get into pirate clanworlds, but they wouldn't let me because I'm a \"small-time pirate\"!

Again, literally `\"` instead of `"`.

**Comment by onpon4** [comment]
Fixed those in #1069.
