### ISSUE TITLE
Za'lex Test gives trillions of credits

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1071]
I did the Za'lex Test mission a few times to build up my reputation. Initially, these missions paid “normal” amounts of money, nothing special.

But after I built up my reputation a little, the Za'lex Test missions eventually paid out absurd amounts. First I have seen a mission that paid 400 MILLION credits. After I completed it, I got another mission in the TRILLIONS. Thanks for all the cash, but I think that was not supposed to happen. xD

It seemed to happen most likely when taking the mission on the Straight Row system.

**Comment by onpon4** [comment]
Fixed that in #1069. It was using the "avgrisk" value where the "tier" value belonged and that led to it getting large numbers for that in dangerous areas.

**Comment by Wuzzy2** [comment]
I think it's a very bad idea to mix GUI fixes with gameplay fixes in the same PR.
