### ISSUE TITLE
Escort formation button misplaced

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1072]
The button for escort formation is misplaced somehow. OK, not really, but when you hover it with the mouse, the focus is a little off. You must put the cursor a little BELOW the button to make it clickable.

How to reproduce: Get Lancelot Fighter Bay, launch fighters, get the button.
Tested with `slim` GUI only.

Version: 0.8.0 beta

**Comment by onpon4** [comment]
Fixed this in #1069.

**Comment by Wuzzy2** [comment]
But #1069 only claims to fix it in Brushed, not Slim …

**Comment by onpon4** [comment]
I fixed it in e4277f1, which was a part of #1069.
