### ISSUE TITLE
Crash when viewing empty outfitter tab in translated game

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1074]
How to reproduce:

* Activate German translation (or any translation that translated “None”)
* Go to planet Pauldur in the Nixon system
* Open outfitter
* Click the U tab
* BOOM! Crash!

Error message:

> Achtung: [outfit_get] Ausstattung „Keine“ nicht im Stack gefunden

(Warning [outfit_get] Outfit '%s' not found in stack)

**Comment by onpon4** [comment]
The error message looks like an outfit name was translated. (The outfit name is supposed to be where %s is but I don't see any valid outfit name there.) This shouldn't be possible, outfit names are used in the code as an identifier and need to remain the same.

Which outfit is this, do you know? I'm not sure what "Keine" is translated from.

**Comment by Wuzzy2** [comment]
No, you don't understand. The U tab is EMPTY on this planet. So in English it only displays a fake outfit called “None”.
In English it doesn't crash but in German it does.
“None” = “Keine”.

**Comment by bobbens** [comment]
Should be fixed in f8245b007d2743c1c38b11ad9b83555e94c5c198 .

**Comment by bobbens** [comment]
On a side note, why are there outfitters with no outfits?

**Comment by Wuzzy2** [comment]
No no no. This is not an outfitter with no outfits. This is an outfitter without utilities. But it still has weapons, structures, and cores.

**Comment by bobbens** [comment]
Assuming fixed.
