### ISSUE TITLE
Translation space is too short

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1075]
This issue is to list all places in which space for translation is too small. I use German as a reference.

This leads to button texts to “bleed over” or label texts to be forced into a 2nd (ugly) line.

Here's the list:

* Main menu / Small menu:
    * Options button
* Options menu:
    * Gameplay: Checkbox texts, speedup stop label
    * Input: Key setting button, window for setting key is too small
* Mission computer:
    * Space for word “Reward” is too short, German translation overlaps with credits count
* Mission tab in info screen:
    * Same problem as in mission computer
* Equipment screen:
    * German translation for „Available ships“/“Available outfits“ goes into 2nd line ...
    * Too short: Swap ship, Sell ship, Rename, Remaining mass limit
* GUI selection screen:
    * Too short: Override GUI, Load, Close
* Search screen:
    * Too short: Outfits, caption
* Search result screen:
    * Way too small overall
    * Cancel button too small

Hint: As a rule of thumb, always give a little more space than English needs. English is rather compact, many other languages (like German) are more wordy.

Another option is to shorten the English text if you can safely remove some unneccessary words somehow.

Version: 0.8.0-beta1

**Comment by Zireael07** [comment]
German is one of the wordiest languages I know, especially due to their love of compound nouns (unlike English compound nouns, with no spaces)

**Comment by onpon4** [comment]
For some of these what we ultimately need is a more dynamic way of placing text.

**Comment by bobbens** [comment]
My recommended solution, which should work generally without increasing sizes, would be:
1. Give a bit more space.
2. Shrink caption as necessary to fit in space.

**Comment by onpon4** [comment]
As far as the reward text goes, the "Reward" header could simply be placed above the reward description rather than to the left of it.

For buttons, the toolkit should probably be deciding size based on the text. (If they're doing this already it could be that they're doing so before gettext is loaded I suppose. I'm not very familiar with the toolkit system.)

**Comment by onpon4** [comment]
I've just pushed a number of changes which should fix most of these and might fix all of them. There were a couple buttons I couldn't make bigger (most notably those in the equipment screen). But I made button text use the small font and increased the size of most buttons and some windows.

🕷️

**Comment by onpon4** [comment]
f44e477ae (which I just pushed) should fix the rest of this issue I think.
