### ISSUE TITLE
String concatenation in translated game

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1076]
There are a couple of bugs with the translation. I have tested this with German for reference.

The game concatenates translatable strings. I probably should explain in detail:

* Audio options:
    * Volume sliders have bad translation: “Sound volume” should be “Tonlautstärke” in German but it's “Ton Lautstärke”. The space is forced by Naev, as translator I have no control over it. IIRC “Sound” and “volume” are separate strings …
    * Same for “Music volume”
    * My guess is that you concatenated strings, which should NOT be done for translation because concatenation assumes a word order, but translations frequently like to flip words around (and for various other reasons). ;-)
    * Suggestion: Turn “Sound volume” and “Music volume” into full strings, no concatenation
* Star map:
    * Translation of interference and nebula variants (dense/light/dangerous/...) is tricky because just like in the Audio options, it all seems concatenated. This makes it hard/impossible to translate every possible nebula/interference variant properly in German, because of grammar rules
    * Suggestion: Instead of concatenating strings, create an individual translatable string for each nebula/interference variant. Basically it's the same problem as with Audio
    
Version: 0.8.0-beta1

**Comment by onpon4** [comment]
I've pushed a fix to both of these in #1069.
