### ISSUE TITLE
Standing with Space Traders Guild is -2147483648%

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1079]
I somehow managed to get a standing of -2147483648% with the Space Traders Guild.

I did a Piracy mission to kill a trader, which got my standing to -4% initially. Then I took the rehabilitation mission. Standing returned to 0%. After a long time I decided to abort the mission. Somewhen after that (I did not check immediately) I noticed the standing has changed to this ridiculous percentage.

0.8.0-beta1

 Sorry, that's all I can tell you.

**Comment by ids1024** [comment]
Hm. I'm not sure exactly what computation would go wrong to result in that.

-2147483648 is -2^31, the minimum value for a 32-bit signed integer. So it looks like an integer overflow. But you shouldn't have a rating of over 2147483647 either. But some combination of operations has resulted in this...

**Comment by Wuzzy2** [comment]
Yeah, the problem is that I cannot tell you what happened behind the scenes that resulted in this number. :-(

I wonder if it happened to anyone else, or if it is reproducible.

**Comment by bobbens** [comment]
Probably related to #1087 and thus fixed.
