### ISSUE TITLE
Allow player to select UI language

### ISSUE THREAD

**Issue by gunchleoc** [naev/naev#1083]
I was considering translating this game, but I can't get my translation to display.

I listed the locale in `po/LINGUAS`, added a po and a gmo file and reran `./autogen.sh && ./configure && make`.

Test branch: https://github.com/gunchleoc/naev/tree/gd-translation

It should also be possible to use a language different from the operating system locale.

**Comment by onpon4** [comment]
There's nothing in the options menu but you can set which language is used with the LANG environment variable. (It defaults to your system language).

That said your translation might simply not work because the gettext system is buggy at the moment.

**Comment by gunchleoc** [comment]
My translation is working, but we need a solution for people who don't know how to set environment variables. Not all players are programmers.

**Comment by onpon4** [comment]
Right, it would be useful to have that.

**Comment by bobbens** [comment]
It should be possible to read from `po/LINGUAS` which could be added to the ndata (just copied into `dat/` when creating the ndata) and allow setting that. I'm not sure if it can be update online with "setlocale(...)", but worst case, set the language name in the config and then load it up after a restart.

**Comment by gunchleoc** [comment]
Maybe you can reuse some code from https://github.com/GNOME/gcompris/blob/master/src/gcompris/config.c or https://github.com/Neverball/neverball/blob/master/share/lang.c

**Comment by bobbens** [comment]
Implemented in 11a3d2717b9f72ef7b70a910db1609a3f8ae01ac .

**Comment by gunchleoc** [comment]
Language selection is now broken. I tried selecting German both by running

`LANGUAGE=de ./naev`

and by selecting if from the Options menu.

**Comment by bobbens** [comment]
> Language selection is now broken. I tried selecting German both by running
> 
> `LANGUAGE=de ./naev`
> 
> and by selecting if from the Options menu.

A current limitation is that you have to run `sudo make install` as the translation files are searched for in the canonical paths. This is something that has to be improved (issue #772 )
