### ISSUE TITLE
No main graphics under Ubuntu 18.04.LTS

### ISSUE THREAD

**Issue by Mutos** [naev/naev#1087]
After upgrading to latest commit a4febefa949c851ac4a4c8b623595e087522dcc6, the following thing happens : 
- At first run, everything works well, there are just messages : 
        Several messages on outfits, on elements 'delay', 'mass', 'track', lockon', 'ew_target';
        "Warning: [load_game] Old version detected. Sanitizing ships for slots".
- Then, some graphics, including the main ones, that is the screen contents when flying, are missing.

Tried on 2 different machines, both on Ubuntu 18.04.LTS, one with all updates, the other with a pending after-update reboot. Same issue.

Didn't test under Windows because for now I can't reboot my dual-boot machine. I'll provide results asap.

Graphics still displayed : 
- Splash screen with ships displayed;
- Menus;
- Editors;
- Planetside windows;
- Map overlay;
- In-flight GUI items including text, selected planets and ships.

Missing graphics : 
- On splash screen, stars are not displayed;
- Main in-flight display.

Since a few months, there are sometimes such issues with main graphics not displaying. When signaled, they are fixed, then reappear. I have no clue as to their cause...

**Comment by Mutos** [comment]
Found the issue, it has nothing to do with the graphics, but all with the conf.lua file and regional numbers format !

The conf.lua file is rewritten with "," instead of "." as decimal separators. And it seems to expect "." on re-reading it, so it messes up everything that was changed...

**Comment by Mutos** [comment]
Worked around the issue to keep running : added the following line to conf.lua : 
        conf_nosave = true

Thus, the conf.lua is never rewritten and never gets corrupted.

**Comment by Mutos** [comment]
Saving is done in conf.c, by a define : 

> #define  conf_saveFloat(n,f)    \
> pos += nsnprintf(&buf[pos], sizeof(buf)-pos, "%s = %f\n", n, f);

**Comment by Mutos** [comment]
Found this useful Q&A on StackOverflow : https://stackoverflow.com/questions/14753505/c-c-printf-use-commas-instead-of-dots-as-decimal-separator

So something could be done to force the decimal separator to a dot.

**Comment by nenau-again** [comment]
It looks like an issue encountered by @Wuzzy2 and I. See https://github.com/naev/naev/issues/1085 and https://github.com/naev/naev/issues/1041 (there are 3 different linked issues in this one, probably some of them have been solved by now).
Do you have the same collection of warnings ?

And yes, on discord, we saw that the conf file had something to do with it.

**Comment by ids1024** [comment]
Ah! I'm vaguely aware of this sort of problem; it's related to the `setlocale()` function.

Looking at git history, history, 233aebf5288d7f4d6a1673157598a2ac11466d04 is probably the cause. That seems to effectively revert 08c47163d55a52c48c48d4e93beeca0d89c60bd9, which was a fix for #754. I suppose @bobbens forgot what that was meant to fix?

I'm not sure that was the right fix. Localization can be a hard problem, and the way the C library deals with locales is perhaps not the best design.

**Comment by bobbens** [comment]
If I don't write codes in the notes I forget. Anyway, the previous "fix" broke gettext, the new fix in 41c8f97e8ba405e5ffb79b5266a547cf40b56537 should work with everything now.

**Comment by Mutos** [comment]
Thanks, OK for me under Linux, didn't test under Windows, I'll do it asap for sake of being 100% sure.
