### ISSUE TITLE
Adding assets with Unidiff seems to sometimes stop other (virtual) assets from working.

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1091]
This is something currently witnessed in the "FLF_base" unidiff. The Sigur system by default has three assets: "Virtual Sindbad", "Virtual Empire Unpresence", and "Virtual Soromid Unpresence". (That said, this bug happened when it only had the latter two as well; it's actually been around for years, I checked pretty far back with git bisect.) These are all virtual assets: Virtual Sindbad increases FLF presence, and Virtual Empire Unpresence and Virtual Soromid Unpresence remove Empire and Soromid presence, respectively. This works as normal when the game is started.

However, when the FLF_base diff is applied, which adds the "Sindbad" asset (a station) to the Sigur system, the Virtual Empire Unpresence asset stops working, leading to Empire ships appearing in Sigur. The virtual assets still technically exist; when the "flf_dead" diff is applied on top of this, it removes both the Virtual Empire Unpresence and the Virtual Soromid Unpresence assets, and this doesn't cause any warnings.

Thus far I haven't witnessed this in any other system, but that would largely be because there aren't any other systems where this bug would cause noticeable results. The only other places where assets are added are in the "Fury_Station" diff and the "Thurion_found" diff; in both cases, a new asset is added into a generally empty system with no virtual assets and no important real assets.

**Comment by bobbens** [comment]
Somehow we had some clean up code that removed negative presences in the middle of processing, messing everything up. I have changed it to not remove them in c85ec8ecf203a2cedd9eaeff9ef9ceec60959103 so this should be fixed.
