### ISSUE TITLE
Planets in Collective systems disappear after defeating the Collective

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1092]
After you defeat the final Collective mission (the one that ultimately destroys the Collective faction), almost all planets (not just space stations) disappear from the collective Systems (C-00, C-14, ...), with only one exception: Eirok in C-43.

It makes sense that the space stations disappear, I suppose they are meant to be factories that got destroyed by the Empire.
But it does not make sense that all the planets disappear as well.

f502b70c4c20f517f0bec79de222c1897696ba92

**Comment by onpon4** [comment]
Fixed in #1099.
