### ISSUE TITLE
Resolution warning when confirming settings without changing anything.

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1094]
If I open the Options, do nothing and click OK, I always get the warning the resolution cannot be changed while it is maximized.
But I didn't touch the resolution, nor do I play in windowed mode.

For the record, my settings are: fullscreen @ 1920×1080.

Random guess: Could it be that Naev uses a “fake fullscreen” and Naev then thinks it is a maximized window?

f502b70c4c20f517f0bec79de222c1897696ba92

**Comment by onpon4** [comment]
Fixed in #1102.
