### ISSUE TITLE
Incorrect Pirate Civilian text

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1096]
A pirate civilian said to me: "I tried to get into the pirate clanworlds, but they wouldn't let me in because I'm a 'small-time pirate'! (...)”

But this was said on New Haven, clearly a pirate clanworld!

f502b70c4c20f517f0bec79de222c1897696ba92

**Comment by onpon4** [comment]
I've tweaked the wording in #1100.

**Comment by Wuzzy2** [comment]
That still doesn't make sense. If the pirate is complaining they couldn't get into *a* pirate clanworld *while they are standing on one*, it doesn't make sense.

**Comment by onpon4** [comment]
The clanworlds aren't connected. Each one is independently controlled. In fact New Haven is one of the easiest to get to.

**Comment by Wuzzy2** [comment]
I know. But the sentence still doesn't make sense. The pirate is already on a clanworld, and wants to go on a clanworld …

Maybe change it to: “can't get to one of the OTHER clanworlds“?

But then it won't work when you're on a pirate spacestation.

The sentence, as is, would work best if only used on pirate spacestations.

**Comment by onpon4** [comment]
There's not a mechanism in the NPC script to do that, and there's no class difference between pirate worlds.

Pedantry I can do, but this is a little bit much. Your original complaint was that the string was incorrect, and that's fair. It's not incorrect anymore. The statement is in the past-tense, so it's easy enough to fill in the blanks and say that the NPC was rejected from entering one clanworld but was then allowed entry into the one you're currently standing on.

**Comment by Wuzzy2** [comment]
Heh. Fair enough.
