### ISSUE TITLE
[Proposal] Hypergates

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1106]
Hypergates are a major part of Naev's story, but we don't have them implemented yet.

Story for hypergates is here: https://github.com/naev/naev/wiki/Spoilers#The-Hypergate

So far as I understand (@bobbens can correct me wherever I'm wrong):

* Hypergates won't appear until later on in the game, roughly the second half.
* You can warp from any hypergate to any other hypergate, like an instant teleportation network.
* Hypergates are supposed to be controlled by the major factions. You can't use them without the permission (i.e. good graces) of the respective faction they're located in, possibly for a nominal fee.
* The Proteron will be launching an invasions against all of the factions utilizing their own hypergates. (I assume this would end factions' ability to control who warps out of their hypergates? Or possibly this would be an exclusive feature of the Proteron hypergate.)

Thoughts on how hypergates could be implemented:

* They could open a menu allowing you to select where to warp to, then warp you there as normal (other than the direction you go in possibly being different than the direction you come out). This would be not very immersive, but simple.
* A special "hub" system could be implemented, which has no location and contains a collection of hypergate entry points, not unlike QuasiSpace in The Ur-Quan Masters. More immersive, but a bit more complex.

**Comment by ids1024** [comment]
> (I assume this would end factions' ability to control who warps out of their hypergates? Or possibly this would be an exclusive feature of the Proteron hypergate.)

This seems like it would provide about the dynamic we want:

* A gate is a powered device that must be activated to jump out, which is under control of the owning faction.
* It is not, however, possible to control who can jump in. Once constructed, the gate cannot easily be disabled without damage to space-time and a new incident.
* The Proteron are thus stranded on this side of the nebula... unless they are able to seize control of gates and reprogram them. The same applies to other factions who attempt to enter Proteron space.

This last point seems like it could provide for quite interesting narrative and missions. As long as we make sure the player can't strand themself in Proteron space. This is easy enough; either the faction controlling the gate won't let them, or they find their ship destroyed if they attempt to jump to Protera.

> A special "hub" system could be implemented, which has no location and contains a collection of hypergate entry points, not unlike QuasiSpace in The Ur-Quan Masters. More immersive, but a bit more complex.

In addition to the implementation complexity, this would probably prevent factions from controlling where someone can jump to from their gates. Which could be an interesting dynamic.

**Comment by onpon4** [comment]
Yes, that's true!

I do rather like the idea of a dynamic of factitons only being able to control who jumps out, not who jumps in. Then they'd need to rely on regular military forces to prevent enemies from jumping in. (Though presumably pirates wouldn't be allowed through hypergates most of the time, barring corruption.)

**Comment by ids1024** [comment]
> barring corruption

...which is also a fun dynamic this can add. Bribery can potentially be used to gain access to a hypergate. Or maybe you're not supposed to be able to jump to a particular destination, but it can be done for the right price.

**Comment by bobbens** [comment]
One of the ideas was them to exist and be powered down until mid-game something triggers them, which would vary depending on the campaign, etc.

**Comment by Mutos** [comment]
Reminds me the Hypernet in the Lost Fleet books series ^-^

**Comment by bobbens** [comment]
Closing as superseded by #1862
