### ISSUE TITLE
Economy system gives commodities a price of zero on assets added by unidiff

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1118]
This is a defect that I noticed: assets that do not exist in a system at game start but are then added via unidiff, like Sindbad, do not seem to have prices generated for commodities properly; instead all prices are set to zero. You can witness the bug by enabling and going to Sindbad:

```
diff.apply("FLF_base")
player.teleport("Sindbad")
```

In addition to the FLF, this also affects the Thurion:

```
diff.apply("Thurion_found")
player.teleport("HS-232")
```

**Comment by bobbens** [comment]
Solved.
