### ISSUE TITLE
"make clean" deletes naev.pot

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1119]
Recently every time I do make clean, the file po/naev.pot gets deleted. I think that's unintentional, right?

**Comment by bobbens** [comment]
Not sure if you are supposed to package it, but it seems like wesnoth does... Maybe it should be eliminated and regenerated everytime seeing that the makefiles automatically want to remove it.

**Comment by onpon4** [comment]
Possibly. Either way making it so that make clean doesn't have an effect on the repository would make working on Naev a lot easier.

**Comment by bobbens** [comment]
Removed from repo and compiled each time. Should be solved.
