### ISSUE TITLE
Translatable debug messages: Really needed?

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1126]
I see a lot of debug messages are made translatable. Was this really needed?
Especially if a e.g. German player has an error, their logs will be in German.
I doubt this is what you want, it can make analyzing logs "fun". :P

I doubt that it was a good idea to make the logfiles translated …

Maybe consider removing the translatablility for all debug messages (to be specific: Messages that appear only in logfiles, so are never seen during normal gameplay). Or maybe separate those strings into a different Gettext catalog.

**Comment by onpon4** [comment]
I don't know that they're "really needed" for us, but it could also be useful for accessibility for theoretical non-English-speaking developers. In truth programming languages are unfortunately English-centric, but even so, learning the various English-isms of most programming languages is probably easier than actually learning English.

Besides, it doesn't necessarily cause a problem. We have the PO files so if we need to know what something means we can just open that and do a Ctrl+F search.

By the way, these messages don't only appear in log files. They're also printed to the terminal. I've actually never looked at a log file, I look at the messages in real-time. If my native language were something other than English I can imagine I might have an easier time reading debug messages and warnings in my native language even if I know English. So even in the case of developers who do speak English it could potentially be an accessibility feature.

Anyway, we could debate the usefulness of this all day, but does it really need to be removed now that it's in there? I'm not really convinced so far.

**Comment by 2ndBillingCycle** [comment]
Missions are supposed to be one of the easiest ways to contribute, and being able to develop missions is made much easier with translated error messages.

**Comment by bobbens** [comment]
Is there any framework for translating documentation? That might be useful, but we could run into stuff like people developing missions in German and then having to translate into English :P

**Comment by bobbens** [comment]
Closing as @2ndBillingCycle makes a good point on having warnings being translated for mission developers, etc.
