### ISSUE TITLE
Social Media?

### ISSUE THREAD

**Issue by Doomsdayrs** [naev/naev#1154]
A few things would be useful to have officially for this game
- Discord server
- Reddit
- Twitter

off the top of my head

**Comment by BTAxis** [comment]
A discord server exists already.
https://discord.gg/UdzHm2S

**Comment by bobbens** [comment]
IIRC someone also made a reddit (https://www.reddit.com/r/Naev/), however, it is not very active. We also had a twitter back in the day (connected to the old blog), but I can't find it anymore.

**Comment by Doomsdayrs** [comment]
This info should be posted on the website @-@, So others can come communicate easily

**Comment by BTAxis** [comment]
The Discord invite already is on the website. The other channels are pretty much unused, so there's not much point adding them, in my opinion. Even the IRC channel has effectively been abandoned.

**Comment by Doomsdayrs** [comment]
Nowww i see that, But having at the end of a paragraph is not a good way to get people to see that it is there

A dedicated place on the side or top would be better, with an icon

**Comment by onpon4** [comment]
Perhaps the Discord invite could be linked in the header of the website? @bobbens would have to do that.

🕵️

**Comment by ids1024** [comment]
> Perhaps the Discord invite could be linked in the header of the website? @bobbens would have to do that.

One can submit a pull request: https://github.com/naev/naev-website

But yes, Bobbens would have to merge it, or change who has write access. And then, I don't know if that's currently deployed manually.

**Comment by bobbens** [comment]
Gave write access to devmembers to naev/naev-artwork ;)

**Comment by onpon4** [comment]
Ok, I added a Discord invite link to the header on naev-website. I assume it updates automatically?

**Comment by bobbens** [comment]
> Ok, I added a Discord invite link to the header on naev-website. Does it update automatically or does that have to happen manually?

At the current time you have to compile, copy the "output/" stuff to "naev.github.io" repo and then push that... Could be made automatic probably. I've made "make install" do that automatically if you have ssh keys set up.

Regarding this issue, I think we can close it atm.
