### ISSUE TITLE
Dark Shadow quest end doesn't make much sense if the Genbu is destroyed

### ISSUE THREAD

**Issue by ifreund** [naev/naev#1155]
I ended up destroying the Genbu and presumably killing Giornio as I was in a very slow capital ship. However, this final message of the mission ("You find yourself back on the Seiryuu...") doesn't make as much sense if Giornio is dead.

**Comment by onpon4** [comment]
Alrighty, I've fixed this in #1158. (Simple matter, I just made the Genbu set to "no death").

🕵️
