### ISSUE TITLE
Mission "The one with the Shopping" broken

### ISSUE THREAD

**Issue by ifreund** [naev/naev#1156]
On speaking to the Trader I get the "With what can I help you..." message, but on pressing OK the conversation ends and the mission is not updated. The same behavior repeats it I talk with the trader again, making it impossible to proceed.

**Comment by onpon4** [comment]
I assume you're playing the beta? The beta has a whole host of bugs that I fixed last month shortly after the beta was released. That campaign was one of a couple that got more or less a complete makeover.

**Comment by ifreund** [comment]
My bad, should've said that I'm playing off master. This happened on commit e3f3f34e5534aa1b1b01a4304aeeef6cc73226ce.

**Comment by onpon4** [comment]
Alrightie, thanks for the heads up. Probably the opposite then, a regression. I'll look into this when I'm more awake if someone else doesn't first (and also fix that other bug you posted, that one's a simple matter).

**Comment by onpon4** [comment]
Should be fixed in #1158. I found that it was using some variables that stored planet/system names as if they were planet/system objects, which would have caused the mission to crash. Please let me know if the fix doesn't work.

🕵️
