### ISSUE TITLE
NAEV crashes on OpenGL context creation on W7 on my DELL laptop

### ISSUE THREAD

**Issue by Mutos** [naev/naev#1157]
Hello all,

I got a problem at launch with my DELL. It crashes with a popup titled `Microsoft Visul C++ Runtime Library` saying `This application has requested the runtime to terminate it in an unusual way. Please contact the application's support team for more information.`

`stderr.txt` just says :
`ERROR ../../../src/opengl.c:406 [gl_createWindow]: Unable to create OpenGL context!`

Line 406 of `opengl.c` is the `ERR` line in :

`   /* Create the OpenGL context, note we don't need an actual renderer. */`
`   gl_screen.context = SDL_GL_CreateContext( gl_screen.window );`
`   if (!gl_screen.context)`
`      ERR(_("Unable to create OpenGL context!"));`

Same exact error in win32 and win64 builds. On the same machine, works well in lin64 on Ubuntu 18.04.4 LTS.

I got an Intel HD 3000 GPU and OpenGL is 3.1 :
`Rendereur: Intel(R) HD Graphics 3000
Fournisseur: Intel
Version: 3.1.0 - Build 9.17.10.4229
Version GLSL: 1.40 - Intel Build 9.17.10.4229`

Here I'm stuck and unable to track the issue further. For instance, where could I find further information about how exactly the context creation failed ? Thanks for any hint !

**Comment by ids1024** [comment]
> I got an Intel HD 3000 GPU and OpenGL is 3.1

Hm, OpenGL 3.1?

Try changing the `SDL_GL_CONTEXT_MINOR_VERSION` attribute in `src/opengl.c` to `1`. Currently Naev requests an OpenGL 3.2 context, but I don't *think* it uses any features that wouldn't be available in 3.1.

**Comment by ids1024** [comment]
It seems HD Graphics 3000 is capable of OpenGL 3.3 under Linux/Mesa, but I guess Intel hasn't bothered to add support for that to the Windows driver.

**Comment by bobbens** [comment]
Any updates? Did requiring a 3.1 context work?

**Comment by Mutos** [comment]
Hello bobbens,

I didn't get the opportunity to check that. I'll try to check it that afternoon if I got time. I keep you informed.

**Comment by Mutos** [comment]
Hi bobbens, sorry, no access to the DELL, it's not my usual machine and my wife needs it today. One day I'll get the time to reboot into Windows and try your OpenGL 3.1 hack... I'll tell you ^-^

**Comment by ids1024** [comment]
45d3cb3 should fix this, hopefully. I don't have a system of an appropriate age running Windows to test.

**Comment by bobbens** [comment]
Closing, reopen if issue persists.
