### ISSUE TITLE
Create some sort of 'nightly' automated build using Github Actions

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1171]
Title..

This should be reasonably doable, my only concern would be dealing with changes to ndata.
Due to the fact that this is a public GitHub repository it does not appear that there are any limits to storage in respects to Github Actions
See [here](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts)

As for packaging these builds:

1. Should the windows installer be modified to allow for 'updates' which should (hopefully) make it a bit easier to update windows users.
2. Should some sort of repository be created for various Linux distros for easy installation.

**Comment by onpon4** [comment]
Ndata issues could easily be solved by removing use of ndata (which would also help with the problems gettext apparently has).

**Comment by ProjectSynchro** [comment]
I have a draft PR #1177 
It's mainly to test if the cron timing that GitHub Actions works, and also to test if everything compiles correctly.

AppImage may require some additional work, so I will read up on it and see what I can dig up.

**Comment by ProjectSynchro** [comment]
A little update:
So far, I have achieved most of the functionality. 

Some issues I have come across so far:
- [ ]  MacOS builds are not generating correctly (unsure if this is due to another issue)
- [ ]  MinGW32 binaries don't work with cygcheck/ldd, therefore collecting DLLs programmatically is problematic

What works so far:
- [ ] 64bit Linux builds
- [ ] MinGW64 builds
- [ ] Automatic releases, asset uploads, release tags

You can see an example of how a release would look [here](https://github.com/ProjectSynchro/naev/releases/tag/nightly)

Assuming that the above issues can be sorted out, there is nothing stopping the workflow configuration from being modified for beta/rc releases and regular releases.

**Comment by onpon4** [comment]
Honestly I would be perfectly happy if we only had what works now. Apple has made it clear that they want to be a walled garden with no non-Apple software, and 32-bit Windows... eh, does anyone even use that anymore?

Honestly, in terms of priorities, static builds strike me as most important, followed by win32, and MacOS... eh, solve it if you want, I couldn't care less. 😛

🕷️

**Comment by ProjectSynchro** [comment]
Static builds are proving a bit tricky, as I personally don't know how to configure autotools to only statically-link _SOME_ libraries.

Targeting win32 only would be ideal for windows.
Unfortunately it's a PITA and requires a manually updated list of required libs, as ldd isn't an option for scripting... something about not having seh on MinGW32.
That way only one installer/zip would be needed, and seeing as the application uses less than 3.2GiB of memory.. and multilib isn't really an issue in Windows world.. may as well. Doesn't hurt to keep win64 in CI though.

Technically it should be possible to statically link MinGW stuff on Windows as well; but again I'm unsure how to configure that.

As for MacOS, so long as Homebrew still works.. may as well ship it; after endless years of Linux being a second class citizen in countless applications and games especially... there isn't a need for platform hostility imo.
I'm sure there's a few mac users that might get some enjoyment out of it (assuming the builds even work :P, compiling is one thing).

**Comment by ProjectSynchro** [comment]
I have completed all work to get nightly releases working.
Work is viewable here #1177 

Next thing that would be nice would definitely be automated releases in general. 

In due time I suppose

**Comment by ProjectSynchro** [comment]
Seeing that #1177 is now merged this can be closed.
