### ISSUE TITLE
Even more typos

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1187]
While translating I found even more typos in the source strings:

* "I knew I could count on you," Lieutenant Czesc exclaims. "These missions will be long distance, meaning that you'll usually have to go at least 3 jumps to make the delivery. In addition, you'll often find yourself in the territory of other factions, where the Empire may not be able to protect you. In return, you will be nicely compensated. He hits a couple buttons on his wrist computer. [...]
    * No closing quotation mark before „He hits“

* Lieutenant Czesc sits at the bar. He really does seem to handle business all across the Empire. You take the seat next to him. "Thanks to your help, the Empire Aramda Shipping Division will soon operate across the galaxy. Our next mission is to get House Za'lek on board. Interested in helping out again?"
    * Aramda or Armada?

* As you approach, you notice that Benito has an unusually annoyed expression. But when she seems you, she calms down somewhat. [...]
    * When she seems me?

* "Yes, finally!" It's as if a massive weight has been lifted off of Benito's chest. "Everyone trusts you a lot, so I'm sure this will convince them that,  yes, killing traitors
    * double space after „convince them that,“
* While polite,  something seems off about the smile plastered on the official who hands you your pay.
    * double space after comma
* The offial takes an inordinate amount of time to do so, but eventually hands you your pay as promised.
    * offial

* There is an Empire patrol with %d ships in the %s system. Eliminate this patrol.
    * No proper plural support
* There is a Dvaered patrol with %d ships in the %s system. Eliminate this patrol.
    * Same.
*  You will be accompanied by %d other FLF pilots for this mission.
    * Same.
* There is a pirate group with %d ships disturbing FLF operations in the %s system. Eliminate this group.
    * Same.
* "Oh, and she put in a nice bonus for you of %s credits for such a speedy delivery."
    * Same.

* "Oh, thank the ancestors! I knew you were the man to help me!"
    * Player character is a man?

* "Thank you for responding %s, are you coming in from %s?
    * Is there a missing comma before the first %s?
* A Familiar looking young woman is looking at you
    * Familiar → familiar. Also, missing period at end
* "I must find my dear brother! Please! Please help me. I think he is in danger! I don't have a ship and he is the only family I have left Could you please help me? Please!!"
    * Missing period between sentences. Double exclamation mark
* "I don't thnk he is here. He must be in one of the other systems. Please, hurry!"
    * thnk
* "How can you be such a heartless person?" asks you the woman half weepingly. " What has this universe become?..."
    * space after opening quotation mark
* Reynir walks out of the ship. You notice that he's bleeding out of both ears. "Where have you taken me?! Get me back to %s right now!!"
    * double exclamation mark

**Comment by onpon4** [comment]
> Aramda or Armada?

These were all fixed a few days ago. There were a few cases of "Armada" being misspelled. 🕷️

> "Oh, and she put in a nice bonus for you of %s credits for such a speedy delivery."
> Same.

This one is always going to be plural (in the realm of tens of thousands). The same goes for anything else counting credits, 1 credit is so small that we never talk about just one credit, so having a singular form is probably unnecessary. 🕷️

> Missing period between sentences. Double exclamation mark

Another thing corrected in the last few days. I don't think the double exclamation mark is necessarily a problem (it can be useful sometimes even though it's non-standard), but incidentally we removed that recently as well. The dialog for that mission was written in a way that was supposed to sound desperate but came across as annoying instead. 🕵️

> thnk
> space after opening quotation mark

Haha, more stuff we fixed a few days ago. We're starting to catch up to you on this. 😉 🕵️

> double exclamation mark

I think this is a case where the double-exclamation mark is warranted. It's supposed to convey loud yelling. Nonstandard, but then again so is "?!".

We've fixed the rest in eebccd2. Thanks for the report!

🕵️

**Comment by Wuzzy2** [comment]
> This one is always going to be plural (in the realm of tens of thousands)

Ugh. You're clearly not knowing what you're knowing about. Grammatical number systems in other languages can be much more complex than singular/plural. Not going into much detail here, but for example, the type of word to use might depend in the last digit. The fact that the number can be in the tens of thausands is irrelevant. Thus, whenever there is something like “%d bananas”, the string should support “plural forms”, if possible.

Just trust someone who has been dealing with translation systems for years. :P

**Comment by onpon4** [comment]
Oh yeah? Well in that case there's a lot more where that came from. There's dozens of uses of "%s credits" in mission Lua code.

I'll get started on that, though maybe we should have an issue about ngettext (non-)usage specifically.

🕵️

**Comment by onpon4** [comment]
Here's a new issue: #1189 

🕵️
