### ISSUE TITLE
Make updating of PO files easier or automatic

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1190]
I haven't found any info on that. So far. Is there any script I can run?

And if there is an answer, I wish it'd be written down somewhere.

**Comment by onpon4** [comment]
msgmerge is what you want: https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html#msgmerge-Invocation

Perhaps we should create an article on the wiki explaining the ins and outs of translating Naev text? I don't know where to begin on that one, but any user with a GitHub account can edit the wiki, so feel free to get started on that.

🕵️

**Comment by Wuzzy2** [comment]
Ah, I see, it's all “manual”. I thought there was some kind of script or something. It's common practice in many FOSS projects I saw to have some script or something.

**Comment by onpon4** [comment]
Yeah, a wrapper script could be useful for sure (perhaps as a part of POT file generation).

**Comment by Wuzzy2** [comment]
I still haven't figured it out. `msgmerge` can't be the answer since there's no POT file to merge with. The locale files must have been generated some other way.

I wish the person who updates the PO files would step up and just tell us the exact commands that they invoke to update things. Then the script basically writes itself.

**Comment by onpon4** [comment]
You don't have a file called naev.pot under the po directory after building?

🕷️

**Comment by bobbens** [comment]
It's a bit ugly, but the way it currently works is you have to do something like:
```
./extras/update-po.sh # only necessary if files have changed
make
make -C po update-po
```
That should update everything. That said, this is done manually, because otherwise it'll do lots of fuzzy stuff and we'll get weird text if it's updated every time something is committed (not to mention it'll bloat every commit by a lot).

**Comment by Wuzzy2** [comment]
I would have never expected the script to be hidden in the extras directory …
Why not tools?

**Comment by bobbens** [comment]
> I would have never expected the script to be hidden in the extras directory …
> Why not tools?

Because we don't have a tools directory I have been stuffing scripts in `extras/`, however, `utils/` might make more sense. I'll move them over there.

**Comment by ProjectSynchro** [comment]
I have seen other FOSS projects use this site and/or service to manage localizations:
https://crowdin.com/

I have also seen mention of using POEdit
perhaps that might be useful in this case?
https://github.com/vslavik/poedit

**Comment by onpon4** [comment]
I've added a note on how to update the PO files via c704a70. That should solve this issue I think.

🕷️
