### ISSUE TITLE
Text and asset visuals can get clobbered together on the overlay map

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1201]
This is something I started thinking about when I had to "fix" a problem where text getting clobbered together caused the outlines to be a no-go on the overlay. But this goes beyond that: even changing the font could easily introduce problems rendering assets invisible.

So I have an idea to make the overlay much better: instead of listing names directly on the overlay, use some kind of "key" (could be a letter of the alphabet for example, but anything is possible) that's used to look up the actual planet name on a list which is separated from the overlay. This would involve redesigning the overlay so that it only shows up on part of the screen to make room for said list.

This method comes with disadvantages too. In particular it would make a 4:3 aspect ratio have a much smaller map, but we could make up for that by changing the default windowed resolution to a widescreen one.

I'd be interested in hearing any other ideas people have for solving the problem, as well.

🕵️

**Comment by agb32** [comment]
Can you post an image of the problem?  I think having to look at a key to find the correct planet to fly to would be a disadvantage...

**Comment by onpon4** [comment]
Well the problem is nothing more glamorous than, the text can overlap, and it can overlap with asset indicators (the little diamons that represent the assets). So in essence the problem is just that this is possible because names are printed on the overlay. There's actually lots of examples but they're hard to notice without the outlines, and when you do notice it's not really something a screenshot can portray because the problem is that some information gets hidden behind other information.

🕵️

**Comment by bobbens** [comment]
Wouldn't it be better to just "nudge" the text so that it avoids getting on top of the visuals instead of rendering at a fixed position? The thing that I find to be more the problem is that it should also consider the mission "+ GOTO" indicators that sometimes are hard to find and also named ships. Although it should be possible to write some sort of a general framework that first renders indicators then tries to render the text so it doesn't overlap using a mask of the indicators.

**Comment by onpon4** [comment]
I believe this is solved now. We have a separate problem of text often ending up in illogical places, but as far as text overlapping assets, that's been solved.

🕵️
