### ISSUE TITLE
Replace use of system fonts with font files.

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1218]
Naev right now loads some kind of system-defined font. However, it could look much better - and also guarantee that all text displays properly - by using font files instead.

Of course, one issue was raised: this could lead to use of fonts that don't work for the current locale. So this is my solution, and it's what we did with Project: Starfighter: we use gettext to "translate" the font file name.

So, as an example, suppose we choose DejaVu Sans Bold as our font file. There would be a gettext string for the name of the file (probably "DejaVuSans-Bold.ttf" or similar). Then suppose a Japanese translation needs Japanese characters. The Japanese translation could "translate" this string to, say, "TakaoPGothic.ttf" (or some other Japanese font), and said font would also be added to Naev's data. So in effect, the translation would choose the fonts to use.

If we do this, it will just be a matter of what fonts to use. I personally think, for the English version, a bold font would be a good choice. But we can tinker with this, of course, and pretty much any font would be acceptable.

🕷️

**Comment by bobbens** [comment]
It does sound good. One thing that probably should be done is fallback fonts like X does. That is, load multiple fonts and try to find the glyph in the first font, if that fails go to the second font, then the third, etc... This would allow using the same English font everywhere by default, but also supporting other glyphs. Even if the player is playing in English, they could be writing their name and shipnames in other fonts that we may not have support in the default font.

**Comment by onpon4** [comment]
That would be better, yeah. Then you would just add another font to the collection of fonts any time a new language is introduced (and you might even do that before then for names and such, as you mentioned). I suppose an array or linked list of glFont objects for each type would be the way to go for that?

Actually, a linked list might be better. That way the code could still specify font objects when choosing font size and stuff. You could even then make the monospace font fall back to the regular fonts to simplify things.

🕵️

**Comment by bobbens** [comment]
Either works fine since the data will only be loaded at runtime and be done sequentially. I don't think there will be >10 fonts either way.

**Comment by nloewen** [comment]
Is this closed by #1225?

**Comment by bobbens** [comment]
> Is this closed by #1225?

I didn't close it as currently a single font is only supported. Ideally, we need to be able to support multiple fonts at the same time (processed in order), and a mix of system and packaged fonts to be able to support most languages.

**Comment by bobbens** [comment]
Closing as everything is solved.
