### ISSUE TITLE
[Proposal] Automate Steam Releases

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1220]
I have done some investigation and it appears that it is indeed possible to automate pushing releases to Steam, however I don't know how to configure these things without being able to look at the interfaces and tools that Valve supplies.. 

I have created automated release workflows here: #1219 and it doesn't seem out of the realm of possibility to rope Steam into all this.
Making sure the releases there are up to date is a good thing.

[This](https://steamcommunity.com/app/598530/discussions/0/2686880925146867989/) is a good example of making sure that people know stuff is happening. :wink:

Some Valve Documentation I have been reading (see [here](https://partner.steamgames.com/doc/sdk/uploading)) details some information behind how to write build scripts, and how to manage deployments via the SteamPipe Content System. 
It also shows how stuff like the Steam Guard sentry file can be used for multiple runs. (This can be achieved similarly to what was going on in Travis for uploading to api.naev.org, by encrypting the file and decrypting it for each run.

```If you are using steamcmd from a machine or VM that gets re-imaged frequently, you should include the sentry and config file in your image so you won't be prompted for a Steam Guard every time. The sentry file is located in <Steam>\ssfn<hashOfNumbers>, and the config file is located in <Steam>\config\config.vdf.```

I think some final goals should look something like this:
- nightly branch
    - would mirror what is pushed on the github releases page, should be able to be fully automated.

- beta/prerelease branch
    - would be enabled during beta/prerelease periods for major releases, with any releases pushed during that time being added to that branch. Would probably want a human prompt to make it live / release any notes or updates.

- Separate builds available on any of the above branches (including the 'default' branch):
    - Win32, Win64, Lin32, Lin64, and MacOS versions available

Let me know what your thoughts are on this!

**Comment by bobbens** [comment]
Sounds good! Automation is always better in this case. Will it be possible to do everything with github actions or will something else be needed also? This should also be documented (except passwords) so we can figure it out if something goes wrong ;)

**Comment by ProjectSynchro** [comment]
as #1219 has been merged I'll close this. 
Documenting how everything works is next on my TODO.
