### ISSUE TITLE
[Proposal] Proselint checks for missions and events

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1223]
This is mainly so I don't forget and to leave it out here, but the tool [proselint](https://github.com/amperser/proselint/) seems like it could be an interesting way to try to improve the quality of the Naev writing. It should be possible to either provide a script to manually check or be integrated with the build tools.

**Comment by onpon4** [comment]
It can help if you're not confident in your writing ability for sure, but try not to take the results of it too too much to heart, eh? 😉 In that sense, any use of it should be manual (mainly useful for non-native English speakers and those who don't have a lot of confidence in their writing).

I myself wouldn't use such a tool, I have rather good confidence in my writing ability (to the point where I would be able to point out and correct instances where such a tool might be wrong about something).

🕵️

**Comment by bobbens** [comment]
Closing as it's likely to have more false positives than anything for now.
