### ISSUE TITLE
[Discussion] Player Growth

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1224]
One thing that is not present in Naev, but could play an important role is player growth. Currently, the player can only get things similar to NPCs and can't really be better than NPCs. The idea would be to incorporate different mechanisms to have the player slowly get stronger so that missions can ramp up in difficulty as time progresses. This would be more important if we adopt the "chapter" view of Naev where the game would be split into 4ish chapters: early-game, mid-game, late-game, end-game. The challenges and missions would basically ramp up in difficulty and thus the player would need to be stronger to compensate.

Some mechanisms I can think off the top of my head.
1. **Unique outfits/ships**. These are planned with the new overlay stuff to be able to identify them. They would be better than default versions
   * I'm not entirely sold on the idea of unique ships because it would sort of "force" the player to chose them instead of normal ships. Something would need to be done so the player can fly their ship of choice. This is not an issue with outfits.
1. **Additional special slot(s)** for each ship in the form of "accessories".
   * These would be reward-only outfits that you could equip on different ships and be an alternative to innate bonuses. They would allow the player to get stronger, but since the number you can equip is limited, you would never grow "too" strong.
1. **Innate bonuses**. Have the player get sort of passive bonuses from doing missions and campaigns. These would stack implicitly on the ship.
   * It might be hard to balance as the player could get too strong just by questing, so not a big fan.
1. **Fleets** (Discussed in #832 )
   * While not making the player stronger by themselves, it does give more firepower overall.
   * A concept of fleet power would be needed to avoid having the player be able to farm for larger fleets (or just temporarily hire to trivialize missions).

Overall I think **unique outfits**, **accessory slots**, and **fleets** does seem like the way to go down the line. **Unique outfits** is already implementable, just would need many outfits created and added as mission rewards. **Accessory slots** would need a bit of code, but it should be fairly "straight forward". Easiest implementation would just be to add a special core slot to utilities/structural/weapons and would only require XML changes. **Fleets** is a really large change though and is not trivial to doo.

**Comment by agb32** [comment]
Also how about some categories of "high scores" - depending on what route the player takes.  Could be high scores for e.g. number of ships destroyed, number of jumps made, number of commodities delivered, number of missions completed, etc.  Perhaps a new tab in the info window.

**Comment by bobbens** [comment]
> Also how about some categories of "high scores" - depending on what route the player takes. Could be high scores for e.g. number of ships destroyed, number of jumps made, number of commodities delivered, number of missions completed, etc. Perhaps a new tab in the info window.

It should be possible, but it's a bit tricky. What does it mean that the player killed a ship? I think we use threshold of damage, but since ships also regenerate it's tricky to compute. However, this doesn't relate too much with the issue at hand which is player growth, as in getting stronger over-time.

**Comment by agb32** [comment]
True - how about "total damage" instead. Distance travelled (or number of jumps) could be another "high score".  I could imagine lots of different criteria that could be used to create high scores!
Yes, sorry, I had mistaken player growth to mean something else, rather than advancement.  Perhaps player achievement - or player achievement growth!

**Comment by agb32** [comment]
For player growth, it would be great to be able to access faction ships.  I know that is intended long-term, once faction missions are completed, but then if I understand correctly, it might be limited to a single faction per save - i.e. you make your choice, and go with that faction.  However, I think it might be better to allow for several factions (though some might be mutually exclusive).
Perhaps for now, until those missions appear, we should reduce the landing cap at faction shipyards, so that once the player reaches the current possible maximum, they can land there...
(ok, there is always the steal a ship option too).

Fleets is a difficult one.  Related to that, I guess we could also have remote control fleets - which don't sit around the player, but can be given a (repeated) task to do.  So, e.g. you could set a mule off trading between 2 points, and over time your money would accrue.  Then naev becomes more a management game - you can sit at a management console without flying and just order your fleets around, give them a task list etc... (so we need a way for time to pass while landed...!)

**Comment by onpon4** [comment]
I actually agree with agb32 on the method: access to factional ships, though I don't necessarily agree with giving the player factional ships of many factions (before postgame that is). In that sense I see accessories / unique outfits as wholly unnecessary and if the factional ships aren't enough better to make enough of a difference, widening that gap would be preferable to the accessory slot. More control over the end result and avoids overwhelming the player with viable choices.

I'd still like to completely get rid of accessory slots and any sort of unique outfits. I think unique stuff would be better placed as random "trophy" grabs in asteroid fields (things that have no in-game effect but exist as like a status symbol).

🕵️

**Comment by bobbens** [comment]
> EDIT: Also, I'd like to add that this whole idea of "player growth" doesn't need to be present in Naev to begin with. Naev isn't an RPG as much as you like to say it is and it's never been about the player getting stronger. I don't think it has to be or even should be. Any "growth" that does exist should consist _only_ of being given access to military-grade ships and outfits, not through "unique outfits" or "innate bonuses" or "artifacts". 

As you mention, player growth already exists by military-grade stuff being locked until the player advances missions, and is a fundamental part of Naev. However, there is no reason to limit player growth to this. Unique outfits can complement this and give different vectors for growth and can help make outfits still interesting once the player has all the licenses and "standard" outfits, instead of having the game reach staleness in terms of new acquisitions. This is something that is not really possible to do only with licenses due to their coarse granularity.

> One of the biggest appeals of Naev for me is that it's not about growth - it's about optimization (tweaking ships to be in their ideal configuration), and mastery (figuring out how to pilot ships and getting better at it). In other words, I don't _want_ my Hyena to get stronger, I want to optimize it and be able to meaningfully use it in said optimized form (possibly with adjustments depending on the situation) for the entirety of the game. Unique outfits of _any_ kind go against that because then I have to go back and reconfigure the ships I have any time I get one, and passive bonuses of _any_ kind go against that because then the way I control my ships changes and I have to rewire my muscle memory.

This is your personal opinion though. For your play style, unique stuff seems to be detractive. However, for me, and I would argue many other players, would find being able to change and modify ships as new outfits are obtained something exciting and enjoyable. Furthermore, while unique outfits do and should allow opening up more different type of play styles, they shouldn't be necessary, so you can completely ignore them if you prefer. That doesn't mean they are meaningless, only that they complement and don't replace other sources of player growth such as military-spec and factional gear.

> This isn't even mentioning the immersion penalties I feel these kinds of player-specific bonuses create; sure, giving enemies unique stuff would make it "fair", but it's not solving the core problem for me, which is that do not want "player growth" to begin with. Leave player growth to RPGs, let Naev be its own thing. Just because other games do something doesn't mean we have to do it as well.

I don't see the immersion penalty you say there is. Sure, many of the unique outfits I added are wacky at the moment, but that doesn't mean they have to be. I find they have more personality this way, but it should be trivial to change them all to be "serious" (although Naev has never been a 100% serious game).

Regarding unique outfits, these have been something I have intended to implement for a while. I haven't been able to find the IRC logs, but, for example, there is a passing mention in #736 (circa 2017).

At the end of the day, it seems like it all boils down to the question on whether or not all pilots (including the player) are all equal. If they all are equal, this basically makes it so that no pilot can really excel with respect to others (unless you change the AI or something), and that at the end of the day what will really matter are numbers and thus fleets (which is a different can of worms). Is this really the direction we want to go? For me Naev is fundamentally about storytelling (and thus a RPG), and having this limitation does not seem like something we want to have to provide players with more interesting and engaging experiences.

**Comment by onpon4** [comment]
> If they all are equal, this basically makes it so that no pilot can really excel with respect to others (unless you change the AI or something), and that at the end of the day what will really matter are numbers and thus fleets (which is a different can of worms). Is this really the direction we want to go?

From my perspective? Yes, absolutely.

> For me Naev is fundamentally about storytelling (and thus a RPG), and having this limitation does not seem like something we want to have to provide players with more interesting and engaging experiences.

We don't need to change the player to give more interesting and engaging experiences. Missions can do literally anything they want, including adding fleets. Missions can also be designed to work with different kinds of ships, no problem.

> the player can buy collective ships, while no other NPCs use them.

I already mentioned this on Discord, the only reason for that is because giving the AI fighter bays doesn't work correctly. That's why this commented out bit of code exists:

```
   --[[
   if diff.isApplied( "collective_dead" ) then
      equip_typeOutfits_weapons["Peacemaker"] = {
         {
            num = 2, varied = true;
            "Turbolaser", "Heavy Laser", "Ragnarok Beam", "Grave Beam"
         },
         {
            varied = true;
            "Empire Lancelot Fighter Bay", "Drone Fighter Bay"
         },
         {
            varied = true;
            "Heavy Ripper Turret", "Laser Turret MK3"
         }
      }
   else
      equip_typeOutfits_weapons["Peacemaker"] = {
         {
            num = 2, varied = true;
            "Turbolaser", "Heavy Laser", "Ragnarok Beam", "Grave Beam"
         },
         {
            varied = true;
            "Empire Lancelot Fighter Bay"
         },
         {
            varied = true;
            "Heavy Ripper Turret", "Laser Turret MK3"
         }
      }
   end
   --]]
```

**Comment by bobbens** [comment]
> > If they all are equal, this basically makes it so that no pilot can really excel with respect to others (unless you change the AI or something), and that at the end of the day what will really matter are numbers and thus fleets (which is a different can of worms). Is this really the direction we want to go?
> 
> From my perspective? Yes, absolutely.

I'm don't agree at all with you on this point.

> > For me Naev is fundamentally about storytelling (and thus a RPG), and having this limitation does not seem like something we want to have to provide players with more interesting and engaging experiences.
> 
> We don't need to change the player to give more interesting and engaging experiences. Missions can do literally anything they want, including adding fleets. Missions can also be designed to work with different kinds of ships, no problem.

Yes, but that doesn't mean that adding another vector for player growth won't allow improving the experience.

> > the player can buy collective ships, while no other NPCs use them.
> 
> I already mentioned this on Discord, the only reason for that is because giving the AI fighter bays doesn't work correctly. That's why this commented out bit of code exists:

Despite that code existing, I don't agree that having the player defeat the collective making automatically all Empire ships be able to use the same outfits makes sense. From the role-playing perspective, there would be logistic issues with mass-producing right away, and from the gameplay perspective, giving the NPCs the same stuff the player unlocks does not really give a rewarding feeling.

That said, the main reason we didn't have unique stuff up until now is basically me slacking off. The only campaign I've actually written for Naev was the collective campaign (which by the way is basically the mission Lua API tech demo and original missions I wrote), and that already gives the player unique gear.

Furthermore, Naev has been a RPG since the origins if you look at the different metadata available. In particular,
```
naev.appdata.xml: <summary>2D action/rpg space trading combat game</summary>
```
