### ISSUE TITLE
[Proposal] itch.io Releases

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1230]
Title.
@onpon4 had mentioned this previously in Discord, and Naev would definitely be a good fit on those platforms in my opinion as well.

The feasibility of getting these releases set up with the rest of what is configured right now (Github and Steam) should be relatively easy (no 2FA to deal with).

The only downside I can think of will be more pages to maintain/moderate, however that should be a pretty easy thing to do.

From some investigation:

itch.io has a CLI tool for uploading stuff called [butler](https://itch.io/docs/butler/).
This can be configured to push stuff up in a similar manner to Steam.

Game Jolt is working on a tool called [gjpush](https://github.com/gamejolt/cli).
There is a pre-release available but it looks like you'll have to get in touch with the Game Jolt employee in charge of it to get it working.

**Comment by bobbens** [comment]
It would awesome if we could somehow push as much meta-data as possible directly from the repo. I know with steam it's not really possible, but it might be with other platforms to try to automate as much as possible. We have to try to keep it as low maintenance as possible ;)

**Comment by ProjectSynchro** [comment]
Minor update to this: gamejolt's cli utility is now publically available
https://github.com/gamejolt/cli

**Comment by ProjectSynchro** [comment]
Game Jolt's CLI is not ready in time for 0.8.0's release, dropping it from the title.

**Comment by bobbens** [comment]
And thus the last 0.8.0 issue (open atm) died ;)
