### ISSUE TITLE
[Proposal] macOS release on Steam

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1231]
Title,

Bringing this up as I had noticed a message or two in the Steam discussions forum. 
Seeing as currently Steam has been integrated into Github Actions CD, and macOS builds are being generated (not sure about people using it however) it would make sense to also release them on Steam.

Since there is no macOS build for 0.7.0 (That I can see anywhere) this would need to be done at or after the release of 0.8.0.

Since macOS applications are stored in a 'bundle', `dat/` would need to be located in `naev.app/Contents/Resources/`.

The current depots on steam are the game data depot and platform specific depots. The game data depot is 'mounted' in the root of the game install location. 

Unfortunately it doesn't appear that we can 'mount' the game data depot anywhere we want within the game install location (it's just plopped down in the root).

This means that either 
A) somewhere there's some documentation proving the above statement wrong and we can just upload the app bundle.
or
B) there will need to be a macOS specific depot that includes everything (game data and the app bundle).

Would love some thoughts on this. (input from macOS people would be nice too)

**Comment by bobbens** [comment]
I'm fine with uploading everything together (not like we pay for bandwidth) if there is no better solution.

**Comment by ProjectSynchro** [comment]
Closing as this is merged
