### ISSUE TITLE
[Proposal] Remove ndata

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1234]
We've talked about this a bit on Discord before, but I just wanted to make an issue since it's something I very much believe we should do. I can't think of any particular advantage ndata gives us rather than avoiding the redundancy of copying data into all different builds. That's worth considering but the use of ndata also has a number of downsides:

* End-user difficulty: adding separate downloads the user has to pair together adds complexity for the user downloading the game. It's a lot easier to download one thing than to download two things and put them together following instructions.
* Problems with gettext: gettext needs to be in a directory to bind to. This has been discussed before and while solving the issue would be very hard with ndata, it would be a non-issue without ndata.
* Discouraging modding / contributing: since the ndata is effectively a monolith, it sort of presents the game as "closed off". I know from personal experience that this can have an effect because it discouraged us from even looking at the data until we were sure enough we wanted to contribute that we checked out the repo. This is likely to be a small effect but still worth mentioning.
* Sucking away development time: it's not uncommon for us to have to help troubleshoot problems with ndata because of the first point. We'd have a much easier time giving support when the game doesn't work if we don't have to first check to make sure that the ndata was placed in the proper location.

As for the one advantage ndata has, there's a simple way to solve that: just pack all binaries together in one zip along with the data, like Xonotic does. That said, considering we automate builds now I don't see how even that is necessary; the extra downloads shouldn't cause a problem if a developer doesn't have to manually upload them. So I think either just having separate builds all with the dat directory included or packing all binaries in one zip would be fine.

🕷️

**Comment by ProjectSynchro** [comment]
Technically distributing with the `--disable-libzip` flag (like what's done on steam) and just including `dat/` in what's distributed is an easy way to avoid the issues with ndata (at least in terms of distribution and troubleshooting headaches). 

However removing ndata outright would require packagers to rewrite how they generate their packages. (lots make use of a `naev-data` package) (I can't really speak to the technical changes to the engine to achieve this as I am purely a mere moral)

If distributing with the`--disable-libzip` flag we would remove the need to link libzip, as there is two major versions that are distributed over various distros (`libzip.4.so` and `libzip.5.so`) 
This can cause issues when running the automatically generated linux binaries on distros that ship older versions (Debian and older Ubuntu versions).

**Comment by onpon4** [comment]
Separating them out shouldn't be a problem as long as distros can choose whatever directory they want for the installation path of the dat directory. In Automake that's handled by the pkgdata_DATA variables (like `nobase_dist_pkgdata_DATA`; that's what Project: Starfighter uses), and you can make the program able to jive with whatever with a simple -D assignment. Real example from Project: Starfighter for that:

```
if RUN_IN_PLACE
starfighter_CPPFLAGS = $(STARFIGHTER_CPPFLAGS)
else
starfighter_CPPFLAGS = $(STARFIGHTER_CPPFLAGS) -DDATADIR=\"$(pkgdatadir)\"
endif
```

🕵️

**Comment by bobbens** [comment]
Although I like the idea of using an ndata sort of as a cartridge on old-gaming systems. I do believe this notion is a bit out-dated, and wouldn't be against removing the idea altogether. For packaging, I only think we really have to provide the windows (and maybe mac os x) installers. Most linux people should be using package managers or compiling themselves.

**Comment by ids1024** [comment]
> However removing ndata outright would require packagers to rewrite how they generate their packages. (lots make use of a naev-data package) 

Not really rewrite;  I think it should be just a small change. If "remove ndata" amounts to using a directory instead of a zip, they could still have a `naev-data` package, but it would consist of laid out files instead of a single ndata zip.

> Although I like the idea of using an ndata sort of as a cartridge on old-gaming systems. I do believe this notion is a bit out-dated, and wouldn't be against removing the idea altogether.

The drag and drop style Naev uses when it doesn't find the ndata is cool, but I really wouldn't want to use that every time I start the game. If it offered more than one game to choose from, it would make more sense an interface that just lists games and allows adding another like Scummvm or Retroarch.

**Comment by bobbens** [comment]
> > However removing ndata outright would require packagers to rewrite how they generate their packages. (lots make use of a naev-data package)
> 
> Not really rewrite; I think it should be just a small change. If "remove ndata" amounts to using a directory instead of a zip, they could still have a `naev-data` package, but it would consist of laid out files instead of a single ndata zip.

I actually think most package managers aren't using the ndata and are using the laid-out file system already.
