### ISSUE TITLE
Problems with Mission 'Novice Nebula Research'

### ISSUE THREAD

**Issue by LeHeurme** [naev/naev#1239]
Hi, 

**_So happy to see current development efforts for the game!!!_**

I guess this is a bug report. 
Sorry I'm new to this. 

after accepting mission, 
Lua console v0.8.0-beta3 
reports: 

`Mission 'Novice Nebula Research' -> 'accept': [string "dat/missions/zalek/neburesearch/neburesearch_...]:90: bad argument #1 to 'osdCreate' (string expected, got nil)`

There is no Mission Report on main Screen at this point. 

After landing at any Planet, there are no mission offers.
There is a number of issues reported:
`Warning: [misn_runFunc]` 
seems to be always:
`Mission {any type} -> 'create': [string:...]:{any value}: attempt to call global 'getsysatdistance' (a nil value)`
or
`attempt to call global 'cargo_calculateRoute (a nil value)`
also:
`Error loading event file: {...} ... Most likely Lua file has improper syntax, please check`

After entering System Doeston, nothing happens.
Landing on Cerberus: same issue with the mission computer and same reports in Lua console.
There is one type of mission, that is not effected: Delivery Missions are still offered.

After aborting the mission, there is no change in these issues. 
I had to restart the game. 

Cheers!

**Comment by bobbens** [comment]
> Hi,
> 
> **_So happy to see current development efforts for the game!!!_**

> `Mission 'Novice Nebula Research' -> 'accept': [string "dat/missions/zalek/neburesearch/neburesearch_...]:90: bad argument #1 to 'osdCreate' (string expected, got nil)`

This should be fixed.

> There is no Mission Report on main Screen at this point.
> 
> After landing at any Planet, there are no mission offers.
> There is a number of issues reported:
> `Warning: [misn_runFunc]`
> seems to be always:
> `Mission {any type} -> 'create': [string:...]:{any value}: attempt to call global 'getsysatdistance' (a nil value)`
> or
> `attempt to call global 'cargo_calculateRoute (a nil value)`
> also:
> `Error loading event file: {...} ... Most likely Lua file has improper syntax, please check`

What operating system and how are you launching the game? I can't seem to reproduce although someone else has reported it.

**Comment by bobbens** [comment]
OK, should be fixed in master. Thanks!
