### ISSUE TITLE
Make Install does not install dat/ correctly.

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1253]
dat/ is not correctly installed when a `make install` is run.

I can't seem to figure out recursively installing all of dat/ when you run make install
I can't seem to use globs to achieve it
I can't use the output of `find` to achieve it (argument limit is hit, and yes I increased the max)
I tried a recursive wildcard `rwildcard=$(foreach d,$(wildcard $(1:=/*)),$(call rwildcard,$d,$2) $(filter $(subst *,%,$2),$d))` this also doesn't appear to work either
so I'm at a loss until I get some more sleep and continue to read up on stuff

This is directly related to #1234, and occurs after commit https://github.com/naev/naev/commit/5f569c75c8c3891eb71c4e3abcd12c188cab068e

**Comment by bobbens** [comment]
Should be fixed with 624e45c0d772afc70cb80a957b270de8ceca690e .
