### ISSUE TITLE
MacOS related issues

### ISSUE THREAD

**Issue by wraitii** [naev/naev#1258]
I recently tried running Naev on my Mac (10.14.5) and ran into a few issues with running it, though I eventually succeeded.
As a preamble, the documentation is lacking, but thankfully the CI workflow gave me all I needed.

The first issue I ran into is that MacOS doesn't support compatibility profiles in OpenGL, meaning most modern macs will get a 4.1+ GL context when running Naev (since Naev asks for 3.2), and that profile cannot compile `version 130` shaders. I had to manually search/replace to `version 410` to get it to work. I'm not entirely sure if this is specific to my machine or not.

The second issue is that the bundles from nightly/CI don't work.
First issue is they require Catalina (honestly unsure why).
Second reason is they expect ndata, so one must manually start the executable with `-N`. It crashes without warning otherwise because the SDL popup is apparently threaded and Catalina does _not_ like that.

Other than that, I did manage to compile the game and run it on both 10.14 and 10.15, which is good.

(and as a last word, I'm happy to see this project alive and well, I always liked what it tried to do more than endless sky)

**Comment by ids1024** [comment]
> The first issue I ran into is that MacOS doesn't support compatibility profiles in OpenGL, meaning most modern macs will get a 4.1+ GL context when running Naev (since Naev asks for 3.2), and that profile cannot compile version 130 shaders. I had to manually search/replace to version 410 to get it to work. I'm not entirely sure if this is specific to my machine or not.

Weird. Is it not supposed to support older GLSL versions? Hm...

It seems `version 130` is OpenGL 3.0. Would something like `version 140` (OpenGL 3.1) or `version 150` (OpenGL 3.2) work?

**Comment by wraitii** [comment]
I've googled a fair amount and it seems to be a "real" issue in that I'm not alone, but I've not found documentation or anything like that from Apple that explains why. It seems that perhaps they just skipped implementing `version 130`.

Version 140 and 150 work on my machine.

**Comment by bobbens** [comment]
Is there any hw that only supports gl 3.0 and not 3.1? If not, we could just make it be 140. Other solution would be to condition it on mac os x by, for example, injecting the version when loading the file (or just search and replace the version).

**Comment by ids1024** [comment]
45d3cb3 should fix the OpenGL issue. It would be good to have confirmation of that.

**Comment by wraitii** [comment]
Well, I can confirm that it works on my machine.

**Comment by bobbens** [comment]
Seems fixed. Closing.
