### ISSUE TITLE
List of typos (again)

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1268]
List of typos in strings:

* Haw haw haw! you're ridiculous!
    * small "y"
* While you handle the post-land and refuel operations, you get a comm from the flight leader, audio only. He tells you that this will be the last place where you can refuel, and that you need to make sure to have at least %d jumps worth of fuel on board for the next leg of the journey. You will be left behind if you can't keep up.
    * missing "plural form" support
* The Nexus employee greets you as you reach the ground. "Excellent! I will just need to spend a few hectoseconds analyzing these recordings. See if you can find me in the bar soon; I might have another job for you.
    * missing quotation mark at end
* Smith seems to relax as you tell him that everything went according to plan. "Fantastic! I have another mission for you; meet me in the bar when you are ready to bring me to %s in the %s system.
   * missing quotation mark at end
* Nexus Shipyard is in competition with House Sirius.
    * Isn't it "Nexus Shipyards"?
* Nexus Shipyard asks you to help initiate a secret meeting
    * same
* Nexus Shipyard has tasked you with killing four pirates.
    * same
* [...] The shell is responsible both for protecting the organism's internal organs and for creating camoflauge to reduce the risk of being detected by hostiles. [...]
    * camoflauge (2 strings)
* Disable to prototype
    * Probably "Disable the prototype" was meant
* For that purpose, milspec designed a scanner array able to deduce the surface composition from spectroscopy, and, what is more impressive, to infer the internal composition via inverse electrical impedance.
    * lower-case milspec
* "They opened two professor positions on precision machining in Atryssa Central Manufacturing Lab, and none in Bedimann Advanced Process Lab, but everyone knows that the BAPL needs reinforcement ever since three of its professors retired last cycle. People say it's because a member of Atryssa's lab posted a positive review of the president of the Za'lek central scientific recrutement committee."
    * recrutement
* "Displays tend to shorten large number of credits by using SI prefixes: 'K' for thousands of credits, 'M' for millions of credits, 'G' for billions of credits, etc."
    * The SI-prefix for 1000 is lower-case k. Upper-case K is not an SI prefix.
    * Obviously fixing this also needs a game change
* That's it, your going to die here! 
    * your → you are
* [...] Once you get the equipment, please deliver it to %s in the %s system. I will meet you there.
	* Missing closing quotation mark
* Your ship is missing %d core outfit%s. How do you want to resolve this?
	* Bad plural form
* After adding the missing outfit%s, your ship is now spaceworthy, though it may have somewhat lower performance than usual. You should get to a planet with a proper shipyard and outfitter.
	* Bad plural form

**Comment by bobbens** [comment]
Thanks! I have fixed the different spelling and added plural forms when necessary.
