### ISSUE TITLE
Translation string update script does not collect outfit names and descriptions

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1269]
I have updated the PO files (locally) as instructed in `Readme.md`. However, I noticed the outfit names and descriptions (like “Battery II“) (which were previously available in `de.po`) have been removed (more precisely: commented out) from the PO file for some reason.

This looks like either the update script is broken/incomplete, or that the `Readme.md` is missing a crucial instruction.

Can you please help me in figuring out how to get the outfit names back into the PO file after running the update script?

**Comment by bobbens** [comment]
I have reverted some changes that broke this. It should be fixed now. The changes made it so it was ignoring all the xml files. Reopen if it is not fixed on your side.

**Comment by Wuzzy2** [comment]
When I update the PO file, it looks like several weird strings are added (about 100). A lot of bare numbers that seem to be coordinates of planets, or IDs and gfx IDs of things from XML. I don't think these are supposed to be translatable. ;-)

**Comment by bobbens** [comment]
Should be fixed now ;)
