### ISSUE TITLE
Short space for some translations

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1280]
The space for translators is very short for these strings (there is either a forced line-break too early or the string is just cut off):
- "Stop Speedup at:"
- "Volume Levels"
- "Available Outfits:"
- "Overwrite GUI"
- "Automatically save changes"
- "Exit only"

fcb73daf7f9f7f51b8024359b6551a3f0d3c66d9

**Comment by Wuzzy2** [comment]
It seems that everything is fixed now. In German it looks fine now.

**Comment by UncombedCoconut** [comment]
Lovely, thanks!
