### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1281]
List of untranslatable strings:

- "+X Cargo" (where X is a number)
- "+X Fuel" (where X is a number)
- "Civilian", "Empire Civilian", etc.
- "This system is landable"
- Control names
- Settings menu tabs
- Info screen tabs
- Outfit type like "Armour Modifier" or "Cargo Expansion"
- The entire intro screen when you start a game
- The Credits screen
- Large faction names in star map background
- Modes in star map
- (brushed GUI) When you marked a Jump Point to an Unknown system, the target shown at the top says "Unknown (1)"
- (brushed GUI) When no planet is marked, the planet target shown at the top says "None"
- The bottom left text of Star Map in Cost or Trade mode
- System names
- "X jumps" in slimv2 GUI. It's also always in plural form like "1 jumps"
- The word "here" in "No price info for [system] here"
- Slot type letters W/U/S in shipyard
- Slot type letters W/U/S in equipment screen
- "All" (ship log)
- "Add a log entry"
- "Add an entry to your diary:"
- "Your Diary"

Strings which are translatable, but the game seems to ignore the translation currently:
- Outfit tooltip in outfit screen
- The outfit name in the outfit list (button only, the description field to the right is actually fine)
- Commodity names
- Planet names
- Planet description
- Bar description
- "This slot is used to equip accessories that can enhance the ship's performance."
- Commodity names and descriptions in Commodity tab
- (brushed GUI) Service names on the "TARGETED" overlay when a planet is targeted
- Faction names (long and short)
- 2nd line of tooltip of core slots in Equipment screen (e.g. "Core Systems" in "Slot Core Systems")
- "Accessory"
- Special ship names like "Advertiser Hyena"

Commit: fcb73daf7f9f7f51b8024359b6551a3f0d3c66d9

**Comment by Wuzzy2** [comment]
More untranslatable strings can be found in the "legacy" GUI:
* Nav
* 2nd
* Off
* Target
* No Target
* Creds
* Cargo Free
* Cargo
* S (Shield)
* A (Armor)

Other bugs:
* I also noticed the ship names are not translated in the shipyard (on the buttons), but they ARE translated in the long description at the right side. The ship name is also in untranslated form in the "Trade-In" dialogue.
* If you search for outfits or ships in the star map and view the result list, you always see "X jumps" even when X=1.
* The search dialog always displays and searches ship and outfit names in English even when there is a translation available

**Comment by UncombedCoconut** [comment]
Pending a better way to track... partial indication of progress below.
(Lines not crossed out may or may not have been fixed -- I haven't checked -- but probably mostly aren't.)

List of untranslatable strings:
* ~~"+X Cargo" (where X is a number)~~
* ~~"+X Fuel" (where X is a number)~~
* "Civilian", "Empire Civilian", etc.
* ~~"This system is landable"~~
* Control names
* Settings menu tabs
* Info screen tabs
* Outfit type like "Armour Modifier" or "Cargo Expansion"
* The entire intro screen when you start a game
* The Credits screen
* Large faction names in star map background
* Modes in star map
* (brushed GUI) When you marked a Jump Point to an Unknown system, the target shown at the top says "Unknown (1)"
* (brushed GUI) When no planet is marked, the planet target shown at the top says "None"
* The bottom left text of Star Map in Cost or Trade mode
* System names
* "X jumps" in slimv2 GUI. It's also always in plural form like "1 jumps"
* The word "here" in "No price info for [system] here"
* Slot type letters W/U/S in shipyard
* Slot type letters W/U/S in equipment screen
* "All" (ship log)
* ~~"Add a log entry"~~
* ~~"Add an entry to your diary:"~~
* "Your Diary"

Strings which are translatable, but the game seems to ignore the translation currently:
* Outfit tooltip in outfit screen
* The outfit name in the outfit list (button only, the description field to the right is actually fine)
* Commodity names
* Planet names
* Planet description
* Bar description
* "This slot is used to equip accessories that can enhance the ship's performance."
* Commodity names and descriptions in Commodity tab
* (brushed GUI) Service names on the "TARGETED" overlay when a planet is targeted
* Faction names (long and short)
* 2nd line of tooltip of core slots in Equipment screen (e.g. "Core Systems" in "Slot Core Systems")
* "Accessory"
* Special ship names like "Advertiser Hyena"


More untranslatable strings can be found in the "legacy" GUI:
* Nav
* 2nd
* Off
* Target
* No Target
* Creds
* Cargo Free
* Cargo
* S (Shield)
* A (Armor)

Other bugs:
* I also noticed the ship names are not translated in the shipyard (on the buttons), but they ARE translated in the long description at the right side. The ship name is also in untranslated form in the "Trade-In" dialogue.
* If you search for outfits or ships in the star map and view the result list, you always see "X jumps" even when X=1.
* The search dialog always displays and searches ship and outfit names in English even when there is a translation available
