### ISSUE TITLE
Problematic translation of Credits button

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1282]
The "Credits" button in main menu is translatable, but it's tricky at the moment.

This is because currently shares the string with with "Credits" string for currency. So if I translate "Credits", I translate the word both for the button and for the currency.

Note: Gettext offers a "context" feature for cases like this, to disambiguate the context for identical strings with different meanings.

Commit: fcb73daf7f9f7f51b8024359b6551a3f0d3c66d9

**Comment by bobbens** [comment]
Should be fixed in bde3b6b61c9435d9e9aeaeae8fae8819679206db . Thanks!
