### ISSUE TITLE
Add discovery mode to star map

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1286]
I suggest to add a new mode to the star map: Discovery.

In this mode the discovery status of all systems is shown. Each system looks different depending on their discovery status:

- System unknown
- System discovered, but not all planets known
- System discovered and all planets known

**Comment by bobbens** [comment]
Issue is how do you know a system is discovered and all planets/jumps are known? It doesn't really make sense to know what you don't know, although for gameplay purposes it could be implemented this way (helps the player know where he has to explore)

**Comment by Wuzzy2** [comment]
Well, the player already knows when a system's planets are fully explored when the local map cannot be bought anymore. It's not like the player gains new information, it's just that it's made more accessible (OK, with the exception of non-landable systems, true). With “System discovered and all planets known” I basically mean the information you would get from a local map. I believe this includes jump points but NOT hidden jump points.


But yeah, this is mainly a gameplay thing. Still, might need exceptions for special cases like hidden planets or space stations.

**Comment by bobbens** [comment]
I've been playing more lately and I think something along these lines is fairly important to quality of life so bumping up priority.

**Comment by amylaar** [comment]
As a work-around, I've been avoiding buying any maps but local maps, and hidden jumppoint maps (and for the latter I have to explore the systems beforehand or immediately afterwards to avoid missing stuff) .
If the system has a planet with outfits, I can also peek from the map if I 'own' the local map, but that doesn't work when there
is on such planet - for a planet where you can buy the map only from main, you have to land there to check.
It would be useful if you could add notes to star systems, similar to the log system, but organized via the map.

**Comment by PhoenixRiver** [comment]
> I've been playing more lately and I think something along these lines is
> fairly important to quality of life so bumping up priority.

As an explorer type player I heart this :)

Phoenix

**Comment by bobbens** [comment]
I have added a discovery mode to the map. It basically shows systems that are "discovered" in green. This means all jumps and planets are known, excepting hidden ones which are not discoverable atm without special events or maps. It is fairly simple but should get the job done. Any feedback is welcome.
