### ISSUE TITLE
When double-clicking on log entry, show the entry in full

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1287]
Here's a simple suggestion:

When you double-click on an entry in the ship log, show the entry. This is basically a shortcut for the "Show entry" button.

**Comment by onpon4** [comment]
Clicking the list entries is how it originally worked, but Naev's list feature isn't properly equipped to handle that. It leads to the log entry being shown over and over again.

As for double-clicking, that's not an input recognized by lists currently. It would have to be added.

🕵️

**Comment by bobbens** [comment]
This seems to be implemented no? Closing.
