### ISSUE TITLE
Description of Ugly Statue and Satellite Model outfits implies you finished the mission

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1289]
You can buy Ugly Statue and Satellite Model from Mad Maroni. But if you read the description, the description implies you have finished some mission to get these outfits. But that's not true if you bought these items from Mad Maroni.

To fix this, the description needs to be rewritten to make sense no matter how you obtained those items.

Commit: fcb73daf7f9f7f51b8024359b6551a3f0d3c66d9

**Comment by onpon4** [comment]
Those actually only show up if you have completed the respective mission and don't have the item, which normally would only happen if you have an old save from before those items were added.

🕵️

**Comment by Wuzzy2** [comment]
OK, I see.

**Comment by bobbens** [comment]
Closing as it's a non-issue. (it is a bit weird, but this is for backwards save game compatibility and sort of can't be helped).
