### ISSUE TITLE
Pirates attack Mad Maroni en masse

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1290]
If Mad Maroni appears in a Pirate system, Mad Maroni is abused heavily, but he is indestructible.

Commit: fcb73daf7f9f7f51b8024359b6551a3f0d3c66d9

**Comment by Wuzzy2** [comment]
Oh. I should probably mention that I have a positive Pirate standing.

**Comment by bobbens** [comment]
Should be fixed in 81115885924d5074db688a1b04da9a766186112e .
