### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1294]
I have found more typos in Naev (bde3b6b61c9435d9e9aeaeae8fae8819679206db):

* Another entry in the House Zalek Nutrition Space Station program. Nothing of note really exists here; it is solely an extension of the House's economy.
    * Zalek → Za'lek
* The Chief Executive Officer of ship maker Melendez Inc. thinks manufacturers should follow his company's lead in keeping costs down and producing for the mass market.
    * Everywhere else it's called "Melendez Corp." or "Melendez Corporation"
* August is a fairly standard, if cold, world. Rarely for a Za'lek planet, it doesn't have that many research stations on it. IT is almost purely a residential world, primarily for the scientists working on Warnecke who, after a hard week's work, don't want to see another lab for a while.
    * "IT" in all-caps
 * [...] The only sign of being Za'lke in origin is the casual use of bafflingly advanced technology and the fact that at least half of the populace look like scientists, researchers, or engineers.
    * Za'lke?
* Though the world of Corax might, in the distant future, become a semi-inhabitable world there will be precious few ores and minerals left (baring iron) by that point.
    * "baring iron" or "barring iron"?
* So far it seems to be working, as Corinth Foodsproduces enough food to be exported from Za'lek space entirely.
    * Foodsproduces
* The small moon orbiting Rhu IV, named Daal, is easily overlooked but, as it happens, it is quite an important piece of realestate for the Sirii.
    * realestate
* Diabolos Station was constructed especially for the sport that made Totoran famous.
    * In-game this is actually just named "Diabolos", not "Diabolos Station"
* [...]  It even has some merchendise not offered at the nearby clanworld Sanchez.
    * merchendise → merchandise
* It is now known what goes on here, as the Dvaered tightly control the entire planet.
    * Did you mean "It is NOT known ..."?
* [...] They may not be too far off the mark, as lava flows and sullen rubles from the earth are quite common.
    * rubles → rubble?
* As such, it is regarded as an important asset to House Zalek in the area and is guarded.
    * Zalek → Za'lek
* Most civilian visitors, though, immediately head for the sun, sand and surf that they came here to enjoy.
    * sun? More like star, amirite? :D
* [...] It produces ordinance for a variety of ballistic and missile weaponry. The portion of its produce that isn't claimed by Dvaered High Command in tax is sold to Warlords, retailers and civilians for profit.
    * Did you mean “ordnance“?
* The bar still sells of disinfectant and industrial equipment.
    * sells → smells?
* "The bar has a strange old meter on one of the walls that seems to dance erratically. When you ask the bartender about it he mentions it measures the current pressure outside.
    * Pointless quotation mark
* Being a station primarily for merchants, the bar is posh, with comforting seats looking out over big views of the solar system.
    * I would say "star system" instead of "solar system"
* It appears to be a limited edition Nexus Shipyard sandwich holder
    * should be Nexus Shipyards?

Questions:
* Though it doesn't see as much traffic as the more centrally located trade hubs, it provides a good opportunity for traders between the Empire, the Za'lek and the Consortium to meet and greet. Of course, the Imperial Navy also uses this station as a base of operations.
    * Question: What is the Consortium?
* Eclipse Station is the major military outpost in this area of Dvaered space. It serves as a customs checkpoint for Imperial and Consortium traders looking to travel to Dvaer and beyond. Simultaneously, it is charged with minimizing the Pirate threat in this region of space. It therefore should come as no surprise that Eclipse Station supports a sizeable fleet.
    * Question: What is the Consortium?
* Though a fairly unimpressive facility, it still beats the hab complexes that litter the surrounding desert.
    * Maybe not a mistake, but I could not find a translation for “hab” or “hab complex”
* It is a monument to lass and days gone by.
    * What is “lass”?

**Comment by onpon4** [comment]
> I would say "star system" instead of "solar system"

Technically speaking both are wrong. The correct term is "planetary system".

> Question: What is the Consortium?

Something to do with the Za'lek government.

> Maybe not a mistake, but I could not find a translation for “hab” or “hab complex”

"Hab" would be short for "habitat". I did have to think about that one for a while.

> What is “lass”?

I'm actually not sure of this one. I looked at the full context:

> Slofeldt is a floating museum and memorial to the Incident. It contains relics from Old Earth, as well as holos of Sol before the Incident sterilized it. It is a monument to lass and days gone by. A place for quiet contemplation.

And I'm still not sure. "The past"? "Glass"? "Last"? Nothing I can think of makes sense.
