### ISSUE TITLE
[Bug] Racing Skills 2 fails to complete

### ISSUE THREAD

**Issue by Ianator** [naev/naev#1334]
The bar quest "Racing Skills 2" fails to complete upon landing at the destination location. Upon opening the Lua prompt the following messages appear:

`Warning: [misn_runFunc]`
`Mission 'Racing Skills 2' 0> 'land': [string "missions/neutral/race2.lua"]:302: attempt to call field 'numOutfits' (a nil value)`
`Warning: [hook_runMisn]`
`Hook [land] '1615' -> 'land' failed`

**Comment by bobbens** [comment]
Was a type. Should be fixed in master!
