### ISSUE TITLE
Translation: rethink how we avoid writing "License: Large Civilian Vessel License" in land_shipyard.c and map_system.c

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1375]
I refer to this land_shipyard.c code (and its twin in map_system.c), which looks dodgy from an i18n perspective:
```C
   /* Remove the word " License".  It's redundant and makes the text overflow
      into another text box */  
   license_text = ship->license;
   if (license_text) {
      len = strlen(ship->license);
      if (strcmp(" License", ship->license + len - 8) == 0) {
         license_text = malloc(len - 7);
         assert(license_text);
         memcpy(license_text, ship->license, len - 8);
         license_text[len - 8] = '\0';
      }
   }
```
In theory, it could work if the update-po script detected license names and emitted both translatable strings and we _(license_text) after this operation. IMO, that's absurd.
But what instead? Tweak the UI? Add a suitable extra text field?

**Comment by onpon4** [comment]
Yes, that is very very dodgy. There used to be even more stuff like that, like for example `"%d ship%s"` where `"%s"` was replaced with `""` or `"s"`. Probably we should replace that with just a "short name" text field or something.

🕵️

**Comment by bobbens** [comment]
I see a few options:
1. Add a short name field to the outfits (optionally of course). However, this crufts stuff up so it's not best.
2. Change it so that it does not become a problem. Something as simple as Large Civilian Vessel Permit would work, although it could be possible to change how it is displayed instead.

**Comment by onpon4** [comment]
Accepting use of the word "License" twice could be fine too.

🕵️

**Comment by bobbens** [comment]
> Accepting use of the word "License" twice could be fine too.

Could also add a license to be able to buy licenses: `License: License license` ;)

**Comment by UncombedCoconut** [comment]
OK, so the comment's concerns about "overflow into another text box" are averted in the system map. In the shipyard, it looks like the below (en, de). It looks like we must seize more horizontal space, and then any non-silly wording will suffice.

![Schiffswerft-lizenz-lizenz](https://user-images.githubusercontent.com/1224111/99209492-48336100-2791-11eb-8327-1b035894a141.png)
![shipyard-license-license](https://user-images.githubusercontent.com/1224111/99209494-48336100-2791-11eb-8742-7b36f70e888a.png)

**Comment by UncombedCoconut** [comment]
Honestly, I'm feeling pretty unbothered by "License: _ License" now that there's more space for the text. Should we just close this?

**Comment by bobbens** [comment]
Agreed. Closing.
