### ISSUE TITLE
Error when running examples/python/basic.py

### ISSUE THREAD

**Issue by BolunDai0216** [naev/naev#1385]
When running examples/python/basic.py the following error message appears:
```
vizdoom: /build/openal-soft-gstqns/openal-soft-1.19.1/Alc/filters/filter.c:25: BiquadFilter_setParams: Assertion `gain > 0.00001f' failed.
Traceback (most recent call last):
  File "basic.py", line 99, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.
```

Can anyone help me figure out what the issue is? Thanks!

**Comment by bobbens** [comment]
Wrong project? We have no examples/python/basic.py.

**Comment by BolunDai0216** [comment]
> Wrong project? We have no examples/python/basic.py.

Sorry, I opened too many tabs and forgot which one is which.
