### ISSUE TITLE
Button hotkey styling is hard to see in the current GUI

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1390]
I have 3 potential solutions, with mergeable code.

0. Do nothing.
1. [contrast](https://github.com/UncombedCoconut/naev/tree/toolkit-button-contrast): Simply tweak the font color so there's more contrast. Upside: trivial change. Downside: not necessarily sufficient, could potentially make the text itself harder to read.
2. [corner](https://github.com/UncombedCoconut/naev/tree/toolkit-button-corner): Instead of marking up the button's text, display the shortcut in the corner. Upside: Simplest code of all options (including status quo), no restriction to alnum hotkeys, no problem if hotkey is not a "case insensitive substring" of translated text or if it's unclear what that would even mean. Downside: non-standard and noisier UI design, introduces yet another font setting.
3. [underline](https://github.com/UncombedCoconut/naev/tree/toolkit-button-underline): Instead of color markup, put `\a_underline\a_` markup around the hotkey, and add the required functionality to font.c. Upside: standard UI convention. Downside: most complex implementation by far, including even a change to the GLSL (which may or may not be required).

Screenshots below.
Additional ideas from Discord included:
- Layla: "it's been a while since I had my system language set to Japanese but I think it still shows the hotkey, just in parentheses or something"
- ids1024: "I wonder how hard it would be to integrate Pango for text rendering." (That looked likely to be doable, post-0.8.0.)

![menu_master](https://user-images.githubusercontent.com/1224111/99603591-9d5db580-29d1-11eb-9a80-c7038ae1768e.png) ![menu_toolkit-button-contrast](https://user-images.githubusercontent.com/1224111/99603607-a77fb400-29d1-11eb-9bad-9e14ccbf57e6.png) ![menu_toolkit-button-corner](https://user-images.githubusercontent.com/1224111/99603626-b23a4900-29d1-11eb-8945-1b3eb584ad36.png) ![menu_toolkit-button-underline](https://user-images.githubusercontent.com/1224111/99603631-b5353980-29d1-11eb-8cf9-3206f7ae3f13.png)

**Comment by bobbens** [comment]
Corner is probably easiest to understand. Another option would be to make the corner only appear when you hold alt. The only thing I can think of is that if the button is tight it could be a problem. Going with the current style just increasing the contrast as in option 1. would be fine.
