### ISSUE TITLE
Translatability: image assets

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1405]
Naev includes several images which are captioned and used as part of the UI.
This is a tracker to maybe do something about that.

Primary example: dat/gfx/map/ has map background images. They have plot-relevant captions burned in.
Secondary example: dat/gfx/loading has 3D ships with English labels.
Tertiary example: dat/gui/legacy/minimal.png has "Cargo", "Target", "2nd", "Nav" labels. Ugh.
Is dat/gfx/commodity/tractor_capability.png for real?
Same for dat/gfx/commodity/diesel.png? But whatever.
Finally, there's dat/gfx/portraits/news.png, but (to a lesser extent) whatever.

**Comment by onpon4** [comment]
Yeah, I was majorly confused by that when we added the ones we added (which are most of them, excepting the Empire one). Ideally it should be some really large font-drawn text at 50% opacity. I'm not sure how to do that though (in such a way that it can be fully customized for best possible positioning).

🕵️

**Comment by bobbens** [comment]
In general, when possible, I would want to stay away from one image per language. That will bloat the repo + add more work load to translaters.

> Secondary example: dat/gfx/loading has 3D ships with English labels.

This could be done with independent image + text. In fact, I think loading time is long enough that we should probably give loading "hints" or something like that. Would be a good way to teach player about more niche stuff.

> Tertiary example: dat/gui/legacy/minimal.png has "Cargo", "Target", "2nd", "Nav" labels. Ugh.

This would ideally be done all lua-side.

> Yeah, I was majorly confused by that when we added the ones we added (Nebula and Proteron). Ideally it should be some really large font-drawn text at 50% opacity. I'm not sure how to do that though (in such a way that it can be fully customized for best possible positioning).

It should be possible to specify the image + text as separate items, allowing them to be placed independently. What might be tricky is to implement different types of alignment (right/left/center) to give more control.

**Comment by Wuzzy2** [comment]
> Primary example: dat/gfx/map/ has map background images. They have plot-relevant captions burned in.

This is the most important thing IMO because these images are highly visible in the starmap and have a large text.
I suggest to just remove the text from these images entirely. The text itself is not critical anyway, as the faction logos are clearly visible.

> Secondary example: dat/gfx/loading has 3D ships with English labels.

Again, here the text can be just removed from the images.

Maybe the text can be later added back in some other form in both cases (as rendered text), but I think it's not urgent in either case.

> Is dat/gfx/commodity/tractor_capability.png for real?
> Same for dat/gfx/commodity/diesel.png? But whatever.

These seem to be unused images, I have never seen them in the game.

> Finally, there's dat/gfx/portraits/news.png, but (to a lesser extent) whatever.

It seems this image needs to be redrawn from scratch.

**Comment by onpon4** [comment]
> I suggest to just remove the text from these images entirely. The text itself is not critical anyway, as the faction logos are clearly visible.

True, that is an option that would probably work. Curious what @bobbens thinks of it.

> These seem to be unused images, I have never seen them in the game.

Yes, they're unused (as are most images in the commodity directory). I actually removed a couple very iffy ones a while back. There are probably more that should be removed, and tractor_capability in particular is one of the very low-quality ones.

> It seems this image needs to be redrawn from scratch.

It's a pretty simple image, mostly made of plain text on a black background that's been distorted a bit. Honestly, if it were to change, my preferred solution would be to make it say ニュース instead, but that's just me. :stuck_out_tongue: Honestly the text in there I think is mainly intended to convey that there's text there and reading it shouldn't be necessary as long as we have a caption (which we do).

🕵️

**Comment by bobbens** [comment]
Removing the text is fine, but if possible, I would like an alternative way of adding the translatable strings. With the new font changes, we can render text at any size without any penalty, so it should be possible to just add some API to add text (like with images), and just make that translatable.

Regarding `dat/gfx/portraits/news.png`, it should be possible to just have lines of green scribbles (or really downscaled screenshot of the news so it's illegible) as an alternative, and rely on the caption to show that it is news.

**Comment by bobbens** [comment]
I think this is mainly solved, closing.
