### ISSUE TITLE
Overlapping Assets

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1449]
Recent changes to the overlay and radar make it more important than ever to deal with the problem of overlapping information, because now the asset indicators themselves are overlapping:

![Screenshot at 2020-11-26 15-46-35](https://user-images.githubusercontent.com/2217995/100419188-11433200-3052-11eb-978c-051af430eddc.png)

Solutions I'm aware of:

1. Making the indicators smaller
2. Redesigning space so that assets are never this close together

If I'm honest, I'm actually a fan of option 2 if for no other reason then because it would ultimately give us more area to click on for small planets, and so could be a long-term good (whereas shrinking indicator size would be an attempt to return things to the status quo). We could also make it just sort of a policy to always position assets so that names don't overlap.

🕵️

**Comment by bobbens** [comment]
3. avoid overlapping text

I think all three are necessary.

**Comment by nenau-again** [comment]
Uzawa's method for the problem of non-overalpping convex forms!
Sounds like an other piece of fun in there!
Unfortunately, right now, I'm not really avaliable for coding a lot :'( so if someone else has an idea (or does understand what I'm trying to say), go for it.

**Comment by onpon4** [comment]
If you're suggesting moving asset indicators dynamically, bobbens, I tend to disagree with that. That will work fine for text, but moving the asset indicators around will mean that they're not accurate representations of asset location anymore unless you're *also* dynamically moving assets around, which... if you're going that route, wouldn't it make sense to just consider it a design error to put assets that close together?

🕵️

**Comment by UncombedCoconut** [comment]
Right asset indicators would need to be classified as _immovable_ objects in such a scheme.

For dynamic layout, I suspect the interesting part (calculating minimal shifts for convex hulls, or some more humble solution for boxes) could end up being less tricky than the uninteresting part (tracking the movable/immovable objects and only doing the position recalc when necessary).

**Comment by bobbens** [comment]
So I implemented both shrinking + moving. Seems to work fairly well ;)
