### ISSUE TITLE
Make double-clicking a planet or pressing "L" automatically position the ship, slow down, and land

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1455]
This has been a thought bouncing around for years now, but wanted to open an issue for it.

Currently, the player has to manually both position their ship and slow it down; if you're too far away or going too fast, you get an error message and have to try again. It would be better, however, if the "L" key and double-clicking on a planet caused the ship to automatically position itself, slow down, and land, the same way that double-clicking on a jump point does.

It should be noted that this should *not* implicitly happen with Autonav because that would mess up patrol missions and such. It should only be by double-clicking on a planet or indicator, or by selecting a planet and pressing "L", that the player's ship auto-lands.

🕵️

**Comment by bobbens** [comment]
I've always been a bit broken on this in that while it would be useful for new players, it does feel like a bit too much hand holding given that landing is a fairly important part of the game. However, I guess this could be seen as relic of the escape velocity legacy given that we are moving away from being more of a "low-level action" game to having more "high-level" and strategy elements. So I guess it would be fine to implement.

**Comment by amylaar** [comment]
Maybe if you could equip this as a user-interface mod that can be enabled like the different GUIs. If there's a price in credits or
a mission you have to do first, so players have to do it a bit by hand first but can dispense with it before it gets old.  Could even call it auto-landing software for the board computer, landing auto-pilot or something.  Higher level could maybe doing boarding too?  Although that might have to be disabled for racing for balance.
Might also depend on ship: you might argue that a scout can't pack too much seldom-used sensors and electronics, but on a carrier / cruiser with scores of crew, why would the same person have to do the landing / docking procedure while holding off bogeys?
Although the ships that tend to be the most vulnerable to be sniped whilst landing and then fumble the landing procedure while
engaged with pirates are mid-sized cargo ships llike koala or pirate phalanx.   They should still have more than one crew member on the bridge, so the situation is quite bizarre.

**Comment by onpon4** [comment]
I don't like that idea. This is a "quality of life" thing and I think it should just be universally available like it is in Endless Sky. Also, landing is tricky for a beginner and I think is one of our barriers to entry, and that wouldn't be solved if a player has to get good at the finnicky manual landing sequence before they can use it.

🕵️

**Comment by PhoenixRiver** [comment]
> I've always been a bit broken on this in that while it would be useful for
> new players, it does feel like a bit too much hand holding given that
> landing is a fairly important part of the game.

I think i must be broken in the same way as you... (and I think Elite
Dangerous proved that hand-holding is all very well but you can be
successful without almost any! ;)

Phoenix

**Comment by UncombedCoconut** [comment]
So, without opening any can of worms re how the forks work together (please), we should make note of this existing:
```git remote add naikari git@github.com:naikari/naikari.git
git fetch naikari
git cherry-pick d331cc5b57e570ee034fda4da7f89cdeaa7ab89b
git cherry-pick 9b4f9b342b8e9de0e7d461e46dfff4a4969d33e8
git cherry-pick 01f0f4adc2f15b781e508c57610ac7c145d84257
git cherry-pick 379262cc820be747b8b7faed01aadc53134062af
```
NOT tested on naev/main yet, might end in tears, but the implementation is actually mergeable and a logical place to start if we want this ability.

**Comment by UncombedCoconut** [comment]
After a quick read-through and quick testing, that looks like nice work. I'd favor merging it, and giving the `player_land` return codes some names in a separate commit, and closing this.
Also stealing `7dc817598c7c85e1ce38fc91f5eb32c7df59f826` while we're at it. :)
