### ISSUE TITLE
Missing Outfit Graphics

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1460]
This is an issue to track outfit graphics we're currently missing. Many of these are currently using placeholders.

EDIT: Some of these are being removed in my rebalance PR, #1660, so I've crossed those out here.

* All accessories (currently using "placeholder")
* Repeating Railgun (currently using "railgun", same as Railgun)
* Heavy Ripper Cannon (currently using "ripper", same as Ripper Cannon)
* ~~Mass Driver MK2/MK3 (currently using "gatling", same as Mass Driver MK1)~~ [Removed by #1660]
* Heavy Ion Cannon (currently using "ioncannon", same as Ion Cannon)
* Plasma Cluster Cannon MK1/~~MK2/MK3~~ (currently using "plasma2", same as Plasma Blaster MK2) [MK2 and MK3 are removed by #1660, so only oMK1 is needed.]
* Plasma Blaster MK3 (currently using "plasma2", same as Plasma Blaster MK2)
* Razor MK1/MK2/MK3 (currently using "ioncannon", same as Ion Cannon)
* Grave Lance (currently using "orion", same as Orion Lance)
* Shattershield Lance (currently using "orion", same as Orion Lance)
* Particle Lance (currently using "orion", same as Orion Lance)
* Turbolaser (currently using "laserturret2", same as Laser Turret MK2)
* Heavy Laser (currently using "laserturret2", same as Laser Turret MK2)
* Heavy Razor Turret (currently using "ionturret", same as Heavy Ion Turret)
* Razor Turret MK1/MK2/~~MK3~~ (currently using "ionturret", same as Heavy Ion Turret) [MK3 is removed by #1660, so only MK1 and MK2 are needed.]
* ~~Laser Turret MK3 (currently using "laserturret2", same as Laser Turret MK2)~~ [Removed by #1660]
* Plasma Turret MK1/MK2 (currently using "plasma2", same as Plasma Blaster MK2)
* Grave Beam (currently using "ragnarok", same as Ragnarok Beam)
* Orion Beam (currently using "ragnarok", same as Ragnarok Beam)
* Pulse Beam (currently using "ragnarok", same as Ragnarok Beam)
* Particle Beam (currently using "ragnarok", same as Ragnarok Beam)
* TeraCom Vengeance Launcher (currently using "headhunterlauncher", same as Unicorp Headhunter Launcher)
* TeraCom Imperator Launcher (currently using "caesarlauncher", same as Unicorp Caesar IV Launcher)
* TeraCom Headhunter Launcher (currently using "headhunterlauncher", same as Unicorp Headhunter Launcher)
* Enygma Systems Spearhead Launcher (currently using "headhunterlauncher", same as Unicorp Headhunter Launcher)
* Unicorp Vengeance Launcher (currently using "headhunterlauncher", same as Unicorp Headhunter Launcher)
* TeraCom Medusa Launcher (currently using "seekerlauncher", same as Unicorp Medusa Launcher)
* TeraCom Banshee Launcher (currently using "bansheelauncher", same as Unicorp Banshee Launcher)
* TeraCom Mace Launcher (currently using "macelauncher", same as Unicorp Mace Launcher)
* Enygma Systems Turreted Vengeance Launcher (currently using "headhunterlauncher", same as Unicorp Headhunter Launcher)
* Enygma Systems Turreted Headhunter Launcher (currently using "headhunterlauncher", same as Unicorp Headhunter Launcher)
* Drone Fighter Bay (currently using "drone_fighter")
* Za'lek Bomber Drone Fighter Bay (currently using "zalek_drone_bomber_fighter")
* Za'lek Heavy Drone Fighter Bay (currently using "zalek_drone_heavy_fighter")
* Za'lek Light Drone Fighter Bay (currently using "zalek_light_drone_fighter")
* Fidelity Fighter Bay (currently using "fidelity_fighter")
* Hidden Jump Scanner (currently using "jammer1", same as Milspec Jammer)
* Milspec Scrambler (currently using "jammer1", same as Milspec Jammer)
* Sensor Array (currently using "jammer0", same as Unicorp Jammer)
* Emergency Shield Booster (currently using "accuracy_forward", same as Forward Shock Absorbers)
* Unicorp Scrambler (currently using "jammer0", same as Unicorp Jammer)
* Reverse Thrusters (currently using "afterburner", same as Generic Afterburner)
* Jump Scanner (currently using "jammer0", same as Unicorp Jammer)
* Boarding Androids MK1/MK2 (currently using "cargo_pod", same as Cargo Pod)
* Thurion Reactor Class III (currently using "reactor_iii", same as Reactor Class III)
* Thurion Reactor Class II (currently using "reactor_ii", same as Reactor Class II)
* Thurion Reactor Class I (currently using "reactor_i", same as Reactor Class I)
* Medium/Large Shield Booster (currently using "shield", same as Small Shield Booster)
* Medium/Large Cargo Pod (currently using "cargo_pod", same as Cargo Pod)
* Tricon Typhoon II Engine (currently using "engine05", same as Tricon Typhoon Engine)
* Melendez Mammoth XL Engine (currently using "engine12", same as Melendez Mammoth Engine)
* Nexus Bolt 6500 Engine (currently using "engine11", same as Nexus Bolt 4500 Engine)
* Unicorp Eagle 6500 Engine (currently using "engine02", same as Unicorp Eagle 4500 Engine)
* Beat Up Large Engine (currently using "engine02", same as Unicorp Eagle 4500 Engine)
* Tricon Cyclone II Engine (currently using "engine07", same as Tricon Cyclone Engine)
* Melendez Buffalo XL Engine (currently using "engine06", same as Melendez Buffalo Engine)
* Unicorp Falcon 1200 Engine (currently using "engine03", same as Unicorp Falcon 550 Engine)
* Beat Up Medium Engine (currently using "engine03", same as Unicorp Falcon 550 Engine)
* Tricon Zephyr II Engine (currently using "engine10", same as Tricon Zephyr Engine)
* Nexus Dart 300 Engine (currently using "engine09", same as Nexus Dart 150 Engine)
* Unicorp Hawk 300 Engine (currently using "engine04", same as Unicorp Hawk 150 Engine)
* Za'lek Test Engine (currently using "engine04", same as Unicorp Hawk 150 Engine)
* Beat Up Small Engine (currently using "engine04", same as Unicorp Hawk 150 Engine)
* Thurion Engine Reroute (currently using "reroute", same as Engine Reroute)

And here are some where whether or not we should do them is a bit subjective:
* All maps (currently all using "map")
* All licenses (currently all using "license")

**Comment by bobbens** [comment]
Created a wiki page to track missing outfit graphics at https://github.com/naev/naev/wiki/Needed-Artwork%3A-Outfits . This way more people can edit simultaneously and it should be easier to handle as it is concentrated in one place. Closing issue, thanks!
