### ISSUE TITLE
OS shows as 'Unknown OS' in the Options menu when building with meson

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1512]
This is due to the fact that the flag the code is looking for is not being defined.
In options.c (line 313-323) the following code checks for those flags. (or whatever term it's called)
```c
#if defined(LINUX)
         "Linux\n"
#elif defined(FREEBSD)
         "FreeBSD\n"
#elif defined(MACOS)
         "macOS\n"
#elif defined(WIN32)
         "Windows\n"
#else
         "Unknown OS\n"
#endif
```
In meson these will need to be defined.

**Comment by bobbens** [comment]
This should be fixed ;)
