### ISSUE TITLE
Cannot build luajit subproject without 'make' being installed

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1514]
If you do not have 'make' installed building the luajit subproject will fail. This effects building using mingw32-make as it is not installed as 'make' to avoid conflicts with naming.

Since the command that is run to build luajit is hardcoded as 'make' it will fail if make is named something else.
This can be fixed by using find_program instead of a hardcoded string.

subprojects/packagefiles/luajit/meson.build (lines 27-30)
```python
run_command(
    'make', '-C', meson.current_source_dir(), 'amalg',
    check: true,
    env: env)
```

**Comment by ProjectSynchro** [comment]
I forgot to mention but that whole meson.build file should really be rewritten.. (it even says so in the source ;P)

**Comment by bobbens** [comment]
Should be fixed ;)
