### ISSUE TITLE
Finish Itch.io Page

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1517]
It looks like we need to finish up the itch.io page to make it.. err.. presentable..
Current 'secret' URL
https://naev.itch.io/naev?secret=iUAMi1AyWDzLVzWWxHtGwuSpgQ

perhaps we could go for a darker colour scheme.. maybe re-purpose the website's header nebula on this page as well?

**Comment by ProjectSynchro** [comment]
I added the Naev logo in place of plain text, and changed the colour scheme a bit.. not quite sure what the background could be.

**Comment by bobbens** [comment]
I don't really see an issue with how it is now. The only main vector for improvement is making the nebula background properly have a nebula colour and have it tile ;)

**Comment by PhoenixRiver** [comment]
On 06/12/2020, Edgar Simo-Serra <notifications@github.com> wrote:
> I don't really see an issue with how it is now. The only main vector for
> improvement is making the nebula background properly have a nebula colour
> and have it tile ;)

Just had a quick look; does itch.io not support MacOS? FreeBSD? I
thought we were building for those? (Though I have to admit to knowing
almost nothing about the autobuild system! Apologies).

Phoenix

**Comment by UncombedCoconut** [comment]
> On 06/12/2020, Edgar Simo-Serra ***@***.***> wrote: I don't really see an issue with how it is now. The only main vector for improvement is making the nebula background properly have a nebula colour and have it tile ;)
> Just had a quick look; does itch.io not support MacOS? FreeBSD? I thought we were building for those? (Though I have to admit to knowing almost nothing about the autobuild system! Apologies). Phoenix

We're certainly trying to build for those, but we're short on macOS testers this cycle. 1 would be a good number. :)
Based on a quick search, itch.io doesn't specifically support FreeBSD -- no tag for it, no little Daemon icon to befriend the little penguin, etc. IMO, the best way to serve FreeBSD users is to focus on ports.

**Comment by ProjectSynchro** [comment]
> On 06/12/2020, Edgar Simo-Serra ***@***.***> wrote: I don't really see an issue with how it is now. The only main vector for improvement is making the nebula background properly have a nebula colour and have it tile ;)
> Just had a quick look; does itch.io not support MacOS? FreeBSD? I thought we were building for those? (Though I have to admit to knowing almost nothing about the autobuild system! Apologies). Phoenix

We hit some significant blockers with macos working correctly (at least using the current build stuff), but it seems like there's more testing that can't really be done without hardware to help things along.. as for freebsd I have plans to cook something up 😈 Post 0.8.0 maybe?


> I don't really see an issue with how it is now. The only main vector for improvement is making the nebula background properly have a nebula colour and have it tile ;)
 Maybe we could tinker with the header nebula that's used on the website? how did that get generated initially?

**Comment by PhoenixRiver** [comment]
> We're certainly trying to build for those, but we're short on macOS testers
> this cycle. 1 would be a good number. :)

Would love to help but MacOS is not one I have currently :(

> Based on a quick search, itch.io doesn't specifically support FreeBSD -- no
> tag for it, no little Daemon icon to befriend the little penguin, etc. IMO,
> the best way to serve FreeBSD users is to focus on ports.

I had guessed that itch.io might not support FreeBSD though I think
downloads are possible without the itch.io client but if it is not yet
built either... no worries :)

And as for build woes... I can entirely understand, I have a hell of
time trying to get my head around that stuff.

Thank you for all your work :)

Phoenix

**Comment by ProjectSynchro** [comment]
Seems like this is solved with the itch.io page set as public, I'll close this.
