### ISSUE TITLE
Map/Mode minor issues

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1547]
Using naev-0.8.0-beta.4-linux-x86-64.AppImage on Ubuntu 18.04, there are a couple minor issues with the map/mode functions:

1) Geron planet in Goddard system - label missing from travel view at one point ... haven't checked again to see if it is back or not
2) for me, dark blue or indigo used for high value goods is hard to read on black in the economic info Mode
- less color range would be better, using a lighter or medium blue

**Comment by UncombedCoconut** [comment]
Hi @tzargoth! I'm claiming to have fixed this (for tomorrow's nightly).
The code which is responsible for placing the planet/moon/station/jump labels on the overlay has a fierce temper, so we may find a reason to reopen part 1 of this issue, but hopefully not.
