### ISSUE TITLE
Missing/broken main campaign missions

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1548]
Using naev-0.8.0-beta.4-linux-x86-64.AppImage on Ubuntu 18.4

In the past versions of Naev, I've played through the game and the campaign missions came around as I progressed.  The Empire Lieutenant would show up in bars regularly.  This time, I only saw him once, the first time.  He hasn't shown up again, and there have been no ES missions available at any time since completing the first courier mission.  I've increased my standing with 3 of the factions to 15% or more (30% with one), but have not triggered any campaign missions.  Only the side missions.  I have elected not to do several of these (the dissatisfied aristocrat, Rayner, honest looking man, mouse crate guy, etc) ... I am fairly sure these are not dependencies of the main campaign missions.  I could be wrong ... but, I don't think these *should* be dependencies.  So, I am thinking something isn't working.

Blasting pirates and FLV (or whatever they are), is 'fun' only for a while.

**Comment by tzargoth** [comment]
Fairly sure a890f22 fixed this ... still playing through to make sure.

**Comment by bobbens** [comment]
I believe this is fixed in master. Reopen if it is not.
