### ISSUE TITLE
Autonav nebula background jumpy

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1549]
Using naev-0.8.0-beta.4-linux-x86-64.AppImage on Ubuntu 18.04

The nebula (the one that blew up the galaxy) background 'jumps around' when in autonav mode ... this in unpleasant at best.  Is this due to an image swap, cycling through different versions? 
- perhaps render this at normal speed without time dilation?

**Comment by bobbens** [comment]
It should be smooth since it is interpolating in a 3D volume. I can try to look into it (it should be also possible to upgrade to do 4D volume and thus never have issues with interpolation).

**Comment by tzargoth** [comment]
I ran through this nebula at normal speed and it is not smooth either.  Jumps from one distinct view to another every couple seconds, or something like that.

**Comment by onpon4** [comment]
You're probably just witnessing the game trying to speed up to a speed that it can't reach smoothly. Can happen e.g. on laptops with very slow ships.

🕵️

**Comment by tzargoth** [comment]
Not sure how consistent the timing is on the image jump in other systems with the nebula, but in Raelid, it switches/jumps about every 8 (?) seconds (flying a Quicksilver).

[nebula-11s.mp4.zip](https://github.com/naev/naev/files/5686879/nebula-11s.mp4.zip)

**Comment by onpon4** [comment]
Oh wow, I've never seen anything like that before. That's real weird. I wonder why it would be doing that...

🕷️

**Comment by UncombedCoconut** [comment]
I see what's going on here.
There's a checkbox for "Interpolation" in the options dialog's video tab.
If it's not checked, the game sets the stage for a smooth nebula animation and... just doesn't do it.
The game is unable to detect ahead of time whether it can safely turn on the settings marked "*Disable for compatibility" -- getting this wrong could potentially break the entire game for some users... at least, I don't know that it can't. (I'm not an expert on OpenGL. Maybe some auto-detection is possible. Maybe not all of these are even compatibility concerns anymore; Naev's minimum requirements increase sometimes. The general goal is to support computers up to 10 years old.)

**Comment by bobbens** [comment]
I see. Interpolation actually doesn't make sense as an option anymore since we use shaders. When we used fix pipeline, we were using a minimum version and/or extension to do texture interpolation, but now that we require a fancy opengl with shader support, interpolation actually becomes trivial to handle. The option should be removed and it should always be enable.
