### ISSUE TITLE
Segfault when exiting game with dialog open

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1551]
Using naev-0.8.0-beta.4.20201212-linux-x86-64.AppImage on Ubuntu 18.04, the game segfaults when there is a dialog open after landing on a planet.

Warning: [misn_runFunc] Mission 'Cargo' -> 'land': [string "missions/neutral/cargo.lua"]:117: Attempting to get landed planet when player not landed.
Warning: [hook_runMisn] Hook [land] '3806' -> 'land' failed
Warning: [cond_check] Lua Conditional didn't return a boolean
Warning: [events_trigger] Conditional for event 'Flintley' failed to run.
Warning: [event_runLuaFunc] Event 'Generic News' -> 'create': [string "events/neutral/news.lua"]:483: Attempting to get landed planet when player not landed.
Warning: [event_runLuaFunc] Event 'Spaceport Bar NPC' -> 'create': [string "events/neutral/npc.lua"]:295: Attempting to get landed planet when player not landed.
Segmentation fault (core dumped)

Steps to reproduce:
1) accept a cargo mission
2) arrive at destination planet
3) without closing the "cargo delivered" dialog, exit the game

**Comment by bobbens** [comment]
Fixed in master.
