### ISSUE TITLE
Jump time should reset ship stats

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1552]
It takes 1 day to make/complete a jump ... during this time, a ships energy, shields, and heat should all be reset (filled/cleared).  Currently, these remain at the level they were when entering jump.  I'd like to think that the ship and its contest are not in some sort of temporal stasis during the entire jump.  The jump animation implies "in universe" travel, with the stars passing by quickly.

**Comment by bobbens** [comment]
The current lore is that when you jump, the universe time jumps a day (or more depending on ship type), but the ship itself doesn't, as it is sort of bending space-time or something like that. While I don't see an issue with changing this to have it be you actually spending a day at hyperspeeds, the game-play implications are worth thinking a bit.

With current system it is harder to do multiple system missions without rest, but given that systems are so big now, maybe it would be easier and nicer to the player to have it all reset (excepting armor on ships that can't regenerate armor)

**Comment by bobbens** [comment]
Closing as this is not something we will implement in general. I do note that it is possible to reset some stats on jumping with some outfits / bioship skills. Thanks for the discussion!
