### ISSUE TITLE
Proposal:  icon/indicator proportional to ship size

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1554]
Currently, it is difficult to determine the class of ship indicated on the overlay map or radar.  I don't recall if some have larger icons or not (looks like something is marked with a larger triangle, but not sure what ... just a formation?), but a Kestrel appears to be the same size as smaller ships ... so, if one goes pirate hunting, it is not easy to determine that the red blip at the edge of the map is going to cause you significant pain or not.  I recommend the indicators have varying size based on at least 3 classes:  fighters (smallest), medium capital ships (mid-sized), large capital ships (largest)

**Comment by bobbens** [comment]
It used to be based on graphics size, and with all the changes it ended up almost always being set to 1. Changed it based on the ship logical sizes. Should be fixed in master.
