### ISSUE TITLE
A few string mistakes

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1576]
So I have found a few minor mistakes in strings:

* "So no, we didn't win" she adds after taking a few breaths to calm down. "Take us back to %s.
    * Missing closing quotation mark
* Dronain is (...)
    * → But the actual planet name that this string describes is "Drognain"
* Though technically an oceanic world, Jaqueline's oceans are filled  (...)
    * → actual planet name = "Jaqeline"
* Though Jaqueline is a fascinating (...)
    * → actual planet name = "Jaqeline"

**Comment by UncombedCoconut** [comment]
These all seem clear-cut except which spelling of Jaq[u]eline to use. (Or even "Jacqueline", the most common spelling back on planet Earth.) The log says this planet was named by @BTAxis with help from Areze. Not sure if they're available to ask if the planet was named after a specific person.

**Comment by Wuzzy2** [comment]
Another one:

> "Rhanna is one of the outer worlds of Dvaered control. (...)

But planet name is "Rhaana".

**Comment by UncombedCoconut** [comment]
Fixed in https://github.com/naev/naev/commit/198bfc6bc7c287a5a505ec521fcee08c3362bec7. Thanks!
