### ISSUE TITLE
Big outfit image is blurry

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1585]
1. Open the outfit screen in 0.8.0
2. Select any outfit
3. Look at the big outfit image at the right border of the window (NOT THE OUTFIT LIST!)

This outfit image looks blurry to me.

**Comment by onpon4** [comment]
That's because it's being stretched out to 192x192 and its original resolution is smaller than that. This is something that could be fixed by using higher-resolution outfit graphics than 128x128 as we currently have them (probably by re-rendering the 3-D models if we still have them).

🕵️

**Comment by UncombedCoconut** [comment]
Done with some exceptions being tracked at https://github.com/naev/naev-artwork-production/issues/21 :)
