### ISSUE TITLE
Add Naev to hosted.weblate.org

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1587]
hosted.weblate.org is a web service based on Weblate (a FLOSS). Translators can use this site to translate strings online more efficiently.

I suggest to add Naev to hosted.weblate.org. There are other FOSS projects present here, for example, Minetest.

https://hosted.weblate.org

**Comment by ids1024** [comment]
Seems good to use something like this, but when I looked into this, there seemed to be a variety of services open source projects use for translations, and it wasn't clear which would be best.

Do you have experience using Weblate or any of the alternatives?

**Comment by ids1024** [comment]
https://weblate.org/en/hosting/

Looks like the hosted version of Weblate is at least €17/month, which is probably undesirable for Naev. Likewise, I don't think we want to be maintaining the infrastructure of self-hosting it.

**Comment by Wuzzy2** [comment]
Did you actually contact them? To my knowledge, they gladly host uncommercial FOSS projects for free (although they don't advertise that publicly). https://hosted.weblate.org/contact/

Yes, I do have experience of using Weblate *as an user*. It does its job pretty well and makes translations much faster.
To my knowledge, no Minetest translator has ever complained about they using Weblate. And, it's FOSS. Seems like a no-brainer to me.

**Comment by ids1024** [comment]
Ah, I see the do offer the service hosted freely for FOSS projects, though the website only seems to indicate that here:

![Screenshot from 2020-12-18 18-57-37](https://user-images.githubusercontent.com/2263150/102679216-ed5fa180-4162-11eb-8569-445b848092cd.png)

Also mentioned in the blog post: https://weblate.org/en/news/archive/new-free-software-projects-hosted-weblate_3/

I can't say I know how other options compare, but if it's based on open source software, we can use it for free, and it's used by other notable open source projects, it sounds viable.

**Comment by bobbens** [comment]
I would be fine with either way, seeing that other fairly important projects use it. I assume the source string limits won't be an issue with Naev. I can try looking into this later.

**Comment by bobbens** [comment]
I have tried to create an account at https://hosted.weblate.org/projects/naev/ . It seems to be working, but I haven't really set it up all perfectly. Furthermore, it is still in the trial period. Personally, it does feel a bit restrictive in some senses. Are there no better more free/open source alternatives?

**Comment by bobbens** [comment]
We got approved on weblate. I'll close this issue and if there are any more concrete things to do to improve, please open another issue ;)
