### ISSUE TITLE
"Stop Speedup At" thresholds/criteria

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1605]
Older report from Discord when a feature was added:

> Time compression doesn't stop at enemy presence anymore, but when the enemy targets you. Is that intended? Because now, it's really hard to stay far from the enemies' sensors.
...
> Actually, both behaviours are useful. But in different occasions.
> So, I'm in favour of making it activable or not
> Maybe there could be an other way than the slider (a checkbox ?)

New report from Discord:

> different issue ... when escorting a ship, left click + right click, it goes into autonav mode, but the game doesn't slow down when the ship I am escorting gets attacked.  Makes it really difficult to defend.

Opening a tracker for ideas about how best to handle the complex question of when a player would want to drop out of high-speed play.

**Comment by bobbens** [comment]
8bcab5f75c4d9ca6d791cf0161b9e64d21047956 reverts a previous change, so I guess it is somewhat solved now? Probably could still be improved though.

**Comment by onpon4** [comment]
Yeah, that reversion returns us to the way we were before, but it really could be nice to have something like that which works well, and that's optional.

🕵️

**Comment by bobbens** [comment]
This has been changed significantly since the report. Closing.
