### ISSUE TITLE
[Steam] Crash on first start / Segfault & Core dump

### ISSUE THREAD

**Issue by thackel** [naev/naev#1609]
Game crashs after first start:

```
Starting app 598530
>>> Adding process 241552 for game ID 598530
GameAction [AppID 598530, ActionID 16] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 598530, ActionID 16] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
 Naev v0.8.0 (x86_64-pc-linux-gnu)
>>> Adding process 241553 for game ID 598530
>>> Adding process 241554 for game ID 598530
Found ndata: /home/user/.local/share/Steam/steamapps/common/Naev/dat
 Sea of Darkness
Installing breakpad exception handler for appid(gameoverlayui)/version(20201220230711)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
No nebula found, generating (this may take a while).
Generating Nebula of size 1280x720x16
Nebula Generated in 168 ms
[1223/085533.911362:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[1223/085534.037317:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
CAPIJobRequestUserStats - Server response failed 2
Segmentation fault (core dumped)
Game removed: AppID 598530 "", ProcID 241554 
Uploaded AppInterfaceStats to Steam
Exiting app 598530
```

It seems that the resolution was not detected and set correctly?

**Comment by UncombedCoconut** [comment]
Hmm, unfortunately the "ERROR" messages don't tell us much -- they're coming from Steam's add-ons rather than Naev itself, and based on web searches I don't think they're fatal.
This leaves us little to go on besides "Segmentation fault (core dumped)". That's pretty fatal.
An important thing for us to know is whether it's just the Steam version behaving this way or (more likely?) Naev 0.8 in general crashes on your machine / OS. It may help to know which distro and version you're using.

**Comment by thackel** [comment]
Now i also tried the appimage version too.
It also crashes with a coredump:
```
./naev-0.8.0-linux-x86-64.AppImage 
 Naev v0.8.0 (x86_64-pc-linux-gnu)
AppImage detected. Running from: /tmp/.mount_naev-0lJbaWl
Found ndata: /tmp/.mount_naev-0lJbaWl/usr/share/naev/dat
 Sea of Darkness
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

After using `strace` to provide you more information I recognized that after reading `/home/user/.local/share/naev/saves/steam_autocloud.vdf` the game crashes.
When I remove this file i can successfully start the appImage version of the game.

When then running the steam version again, it crashes and after that also the appImage version does no longer start.
This is totally repeatable.

strace output before the crash:
```
openat(AT_FDCWD, "/home/user/.local/share/naev/saves", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 16
fstat(16, {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
getdents64(16, /* 3 entries */, 32768)  = 88
stat("/home/user/.local/share/naev/saves/steam_autocloud.vdf", {st_mode=S_IFREG|0775, st_size=51, ...}) = 0
getdents64(16, /* 0 entries */, 32768)  = 0
close(16)                               = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
```

**Comment by UncombedCoconut** [comment]
Thank you! We can work with that. Naev is expecting only *.ns and *.ns.backup files to be there, but Steam left a present for us. (Could even be because of something set up while solving #1518. Will check.)
The code to load saved games needs to be improved.
Hopefully that's the only problem, but your feedback also tells me what Steam settings to enable so I can find out.

**Comment by UncombedCoconut** [comment]
Fixed a bug, not sure how soon we'll have a Steam update ready, though.
Specifically, Naev would crash if the saves directory contained files and _none_ where .ns/.ns.backup.
Is that your situation, or had you already created saved games too? (If not, doing so in the AppImage version may be a workaround until we release.)

**Comment by thackel** [comment]
Today there was an update in STEAM.
The game is now working!
