### ISSUE TITLE
Make combat music play in tandem with Autonav time compression resetting

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1613]
Currently, combat music plays whenever an enemy becomes "hostile" to, i.e. targets, the player. This often leads to combat music playing when there is no danger. Making combat music play under the same conditions that Autonav's time compression would be reset (as configured by the slider in the Options menu) would be an improvement, both because it would avoid unnecessary combat music and because it would mean that combat music doesn't give extra information.

In doing this, it's important to ensure that the takeoff music doesn't end up getting cut off by ambient music. This can be achieved with some simple edits to the ambient music choosing Lua function, making it refuse to play a track if takeoff music is currently playing

Then it should in theory be a matter of calling up the script every frame and using `autonav_shouldResetSpeed()` to determine if it should request combat or ambient music. Unfortunately, when I tried to do this, combat music ended up always being badly delayed, and I'm not sure why.

🕵️

**Comment by bobbens** [comment]
Solved in main, thanks!
