### ISSUE TITLE
'capture alive' missions fail irrespective of resources

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1634]
From the descriptions, a large crew size and boarding androids should make 'capture alive' missions more likely to succeed, yet
the code uses random values without reference to bounty target vs. player ship crew size or boarding androids.

**Comment by onpon4** [comment]
Specifically, the formula used is: `rnd.rnd() > (0.5 * (10 + pir_crew) / (10 + pl_crew))`. This is actually taken directly from the C code which handles normal boarding. What this means is if both ships' crew size is exactly the same, the chance is 50%, but it increases if your crew size is larger (for example: 75% if your crew is twice that of the pirate's, 90% if your crew is 5 times that of the pirate's).

I do agree that this should be reworked, and I think it should be reworked with the boarding code, too. @bobbens has mentioned an idea of adding a "takeover" minigame (not unlike Freedroid), which I could get behind.

Whatever we do, I would like the method to be the same in both the regular boarding stuff and in "alive" bounty missions.

🕵️

**Comment by bobbens** [comment]
Wrote some stuff on boarding in #1635 .

**Comment by bobbens** [comment]
Given the current difficulty of disabling and boarding a ship, I don't think we need a poorly presented random check. Made it so it always succeeds for now. Thanks!
