### ISSUE TITLE
Better indication of outfitting slot sizes

### ISSUE THREAD

**Issue by JackStorm448** [naev/naev#1639]
The current colour-coding method of denoting the sizes of internal module slot is rather unintuitive for new players, and in particular the colour variation for 'core' modules such as engines and hull plating make it even harder to tell what size they are. Perhaps having the slot size pop up when the cursor hovers over the slot would help.

**Comment by bobbens** [comment]
I have added more color (still colorblind accessible), while also adding it to the hover pop-up too (also color-coded) so I think it should be much easier to understand and follow now. Thanks!
