### ISSUE TITLE
mission markers are hard to distinguish

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1640]
I find it hard to distinguish the active mission markers from the markers for potential missions that I could accept.
I understand you got rid of colours there for colourblind accessibility, but what about making them different shapes, or
use a different phase for the blinking?  I don't mean frequency, too high might trigger epilepsy and too low makes
it hard to discern (there is still some usable range there, but that'd probably better be used for mission priorities),
 but different phase at same frequency would work for proposed mission maker - of which there
is only one - vs. active markers - of which there are usually multiple.  If the phase difference is noticably different
from pi, it will even be possible to tell which is which when both are in view with a bit of getting used to it.
I think something like PI/2 or 2/3 PI should do it (where time between two maxima of the same marker is 2*PI).
Logically, I'd think the phase of markers for missions already taken should lead the phase of markers for missions
that could potentially be taken.

**Comment by onpon4** [comment]
Adjusting the animation would be easier said than done since that's handled globally, and it might be unpleasant to look at, but I certainly wouldn't mind adding a shape-based indication. Main reason I didn't do so is because I'm useless when it comes to drawing shapes with OpenGL.

🕵️

**Comment by UncombedCoconut** [comment]
There's a new mission marker in nightly/git versions.
Is it visible? Are the types distinguishable? Can people tell where it's pointing?

**Comment by onpon4** [comment]
I don't believe the new mission markers make it easier to discern between preview and current mission markers, do they? Incidentally, the fact that it's a shader now should make doing so with a different shape much easier.

Regarding being able to tell where it's pointing, I do have a concern with that: if two planets happened to be just the right distance from each other, the marker might look like it could be pointing to one of two systems. Giving the rhombus a small flat edge on the non-pointing side (and making it technically a pentagon) would eliminate that possibility.

🕵️
