### ISSUE TITLE
Fake ID anomalies

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1642]
I've found I can get a standing of +25 with the Dvaered using a fake ID, while I'm still really considered their enemy, just by
blasting pirates out of the sky.  Well, you could justify this in-story as the Dvaered being gun-nuts, gung-ho when it comes to violence, and not very bright overall, but was that intended?  The pirate stronghold's computer (or is it really a stand-in for another shady character?) may well be an unreliable narrator, and hence the in-game description can be legitimately misleading, but
then I'd expect some comment in the source code that explains the difference between appearance and actual mechanics.
Looking at the source code, I've found no such comments, but it appears that only the standing that can be gained from
missions is capped with temp_cap.  Standing gain with an enemy faction (other than the pirates) doesn't jeopardize the ID,
but it gets annulled when the missions standing cap got raised - and then you've likely hosed your character permanently,
because the flag(s) that you have done the unique mission(s) will be set, but the mission standing cap raise was going to the
fake ID just before it got annulled.  Easy to avoid if you know it, but a new player who tries things out could get caught out accidentally, not even realize it, and invest a lot of time doing storylines with other factions without realizing what happened there
until much later (if at all - they might just conclude that the affected factions don't have much of a storyline).

**Comment by onpon4** [comment]
That is how it's supposed to work, yes. The intention is to avoid making players think they can go through campaigns with a fake ID, since attempting to do so will actually lock you out of them (due to the fact that standing cap raises will get nullified).

🕵️

**Comment by bobbens** [comment]
Perhaps make it more clear to the player that this will happen?

**Comment by bobbens** [comment]
Replaced the fake id with the fake transponder that should be able to solve this by making it all more explicit and straight forward to understand. Thanks!
