### ISSUE TITLE
Soromid bioship senescence

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1644]
Using a build from git with head 08c944057fe93623ffa0102d2f27020b6059e709,
I tied again bopship leveling.  Using a Soromid Nix with Medium-Heavy
Core outfits, Brain stage 4, Fast Fin and Shell Stage5, one BioPlasma Organ stage 1 .
I did a Za'lek search & destroy mission for a bit more than 1e6 credits, and landed
on HZNSS-2 in Straight Row.
The Fast Fin just disappeared.
When I tried what'd happen when I select take-off, I was offered to get a standard outfit for the missing slot, which became a stage 1 Fast Fin.
I made a stop in Rostra to check my outfits, but there wasn't any extra unequipped
Medium-Heavy Fin either.

I've checked stdout, and the first message after "Reached main menu" is:
Warning: [land_stranded] Rescue: 'rescue' : [string "rescue.lua"]:113: attempt to call global '_' (a string value)
stack traceback:
        [string "rescue.lua"]:113: in function <[string "rescue.lua"]:73>'

**Comment by amylaar** [comment]
I've loaded from backup and did the mission again to land on Rostra (which has a Shipyard and Outfits).  This time, the Brain disappeared.

I bought an ancestor, two Unicorp Caesar IV Launchers, and a weapons Ionizer, put these outfits into the ancestor, and sold it.  The BioPlasma Organ disappeared.

**Comment by amylaar** [comment]
It's something that's specific to Medium-Heavy equipment.  The pattern "Medium-Heavy" doesn't match "Medium-Heavy" .
It'd match "MediuHeavy", "MediumHeavy", or even "MediummmmmmmmmmHeavy", though.
"Heavy" matches "Medium-Heavy" .  Should we anchor the match?
I got also lots of interesting effects when I initially copied the original file to bioship_upgrade.lua.orig in the same directory - I wasn't aware that that'd be active code, too.

[amylaar@localhost events]$ diff -u  ../../bioship_upgrade.lua.orig bioship_upgrade.lua 
--- ../../bioship_upgrade.lua.orig      2021-01-08 10:14:04.885381655 +0000
+++ bioship_upgrade.lua 2021-01-08 12:55:19.099837684 +0000
@@ -101,7 +101,8 @@
 -- valid undeveloped part, or nil otherwise.
 function undeveloped_bioship_part_index( s )
    for i, p in ipairs( bioship_parts ) do
-      if string.match( s, p[1]:format( "%d" ) ) then
+      local pat = p[1]:gsub ("-", "[-]")
+      if string.match( s, pat:format( "%d" ) ) then
          return i
       end
    end

FWIW, an easy way to trigger the upgrade is to buy & sell ten Caesar IV Launchers in bulk (pressing shift).

**Comment by amylaar** [comment]
I find I can still loose Bioplasma Organs if I have equipped CPU hungry outfits such that the ship is currently in negative CPU territory.

**Comment by onpon4** [comment]
I'll get to work on this probably in a couple days or so if no one else does. Looks like string.match is more powerful than we thought. 😅

🕵️

**Comment by amylaar** [comment]
> I find I can still loose Bioplasma Organs if I have equipped CPU hungry outfits such that the ship is currently in negative CPU territory.

I've looked at the addOutfit code, and I think the bioship upgrade should just use
addOutfitRaw, maybe followed by calcStats (does this get subsumed in the resetting
at the end of the upgrade?).

pilot_addOutfitTest has three potential reasons to fail: 
- lack of space - that should not happen, because the new outfit should be a drop-in upgrade for the outfit that was just removed.
- lack of cpu - that can legitimately happen when there was a lack of cpu before.
- new outfit can't be equipped - again this should not happen because it's supposed to be a drop-in replacement.

Let me explain further why the lack of cpu can happen legitimately.  It can't (shouldn't) happen in space, and thus, neither when you just land.  But it can happen when you land, switch outfits around, and then get paid.  With 0.8.1, I have seen that selling stuff shouldn't count anymore, but there are two more ways this can happen after landing:
- accepting a waste disposal job
- finishing a mission by meeting someone in the bar.

It's also a bit sad that non-monetary rewards like accessories, faction standing, faction cap raises, or equipment (from the DIY nerds) won't count, although for the latter it's unlikely you do the job with a Soromid bioship, and the value is a pittance if you do.

I'm not sure if any bar-finished job pays enough at the moment to trigger a bioship
upgrade, but the lack of experience carrying over seems to be a bug.  Why read
_bioship_exp when it's never going to be set?  There's even a comment that says
the experience is stored there.

**Comment by amylaar** [comment]
There doesn't seem to be a lua binding for addOutfitRaw, so I have this now instead:
```
--- ../../bioship_upgrade.lua.orig      2021-01-08 10:14:04.885381655 +0000
+++ bioship_upgrade.lua 2021-01-09 12:43:58.118906790 +0000
@@ -101,7 +101,8 @@
 -- valid undeveloped part, or nil otherwise.
 function undeveloped_bioship_part_index( s )
    for i, p in ipairs( bioship_parts ) do
-      if string.match( s, p[1]:format( "%d" ) ) then
+      local pat = p[1]:gsub ("-", "[-]")
+      if string.match( s, pat:format( "%d" ) ) then
          return i
       end
    end
@@ -127,7 +128,9 @@
    local parts = {}
    for i, o in ipairs( player.pilot():outfits() ) do
       local index = undeveloped_bioship_part_index( o:nameRaw() )
-      if index ~= nil then
+      if index ~= nil
+        -- can't add new part in if cpu deficit
+       and (o:cpu() >= 0 or player.pilot():spaceworthy() ) then
          parts[ #parts + 1 ] = { o:nameRaw(), index }
       end
    end
```

**Comment by bobbens** [comment]
Thanks @amylaar ! I have used your regex bit. Regarding lack of CPU/spaceworthiness, you can actually use `addOutfitRaw` by setting `bypass = true` in the `pilot.addOutfit(...)` function, which I have done. Closing, reopen if it is still broken. Thanks!

**Comment by amylaar** [comment]
> Thanks @amylaar ! I have used your regex bit.

Actually, not quite.  You added the line that sets the local variable pat, but you didn't change the string.match check, so it's still
using p[1] unchanged, and thus Medium-Heavy gear of any level below X will still get changed to Heavy gear of level 1.

**Comment by bobbens** [comment]
Ok, fixed other existing issues with disappearing outfits. Tested on several ships and it seems to work fine. Closing. Thanks!
