### ISSUE TITLE
Missing images for Naev v0.8.0+958.g99c4362c3 (linux-x86_64)

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1652]
Right when I load a savefile where I am on waterhole's moon, I see a number of
messages:

Warning: [gl_loadNewImage] Failed to load surface 'gfx/portraits/background.png' from ndata.

More such messages appear when I'm on Minerva Station.

The blackjack and terminal 'persons' have solid black - or green, when selected - thumbnail images.
The cyborg chicken portrait is a nice portrait - of a dude.
I think to a first order of ASCII-approximation, a chicken looks more like this:
```
    /%<
>( )
  A
```
There are also a number of somewhat more detailed illustration of a chickens, like
the one for "The Cock and the Jewel" in
https://www.gutenberg.org/files/18732/18732-h/18732-h.htm
(bibliography here:https://www.gutenberg.org/ebooks/18732 - my understanding is
 that the illustrations are out of Copyright not just in the USA, but worldwide, as this book was released 1884 and the last of its illustrators died 1914.)

After I traded for the fuzzy dice, I noticed error messages:

Warning: [event_runLuaFunc] Event 'Minerva Station Altercation 1' -> 'create': [string "scripts/vn.lua"]:708: vn: character image 'zalek_thug1.png' not found!
stack traceback:
	[C]: in function 'error'
	[string "scripts/vn.lua"]:708: in function 'new'
	[string "events/minerva/altercation1.lua"]:33: in function <[string "events/minerva/altercation1.lua"]:29>
	[C]: in function 'eventStart'
	[string "events/minerva/station.lua"]:132: in function <[string "events/minerva/station.lua"]:131>

**Comment by amylaar** [comment]
I see that the nightly build has some images in dat/gfx/portraits that were not
obtained with git pull.  Are the [build instructions](https://github.com/naev/naev/wiki/Compiling-on-*nix) out of date?

**Comment by bobbens** [comment]
You have to run the following additional commands now:
```sh
git submodule init
git submodule update
```
I have updated the wiki. Regarding the nightly, right now the new files are not properly getting included in some cases and we are working to fix that.

**Comment by UncombedCoconut** [comment]
Fixed now -- releases (nightly and otherwise) include the new files.
