### ISSUE TITLE
'f' in map stands for find something that starts with f

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1654]
When I type 'm' to bring up the map and 'f' to find something, the f gets immediatey entered into the text entry field.
If I want to search for anything that does not start with 'f',  I have then to press backspace.

**Comment by bobbens** [comment]
Fixed in a9406997b4663c3625fd32dfdef85b208b5f0371 although it is a horrible hack. Issue is that SDL is generating both a key+text event, key event generates the find window, which then receives the text event of the same thing...
