### ISSUE TITLE
Tutorial drone can't be beat

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1674]
Reported by JacquelineHyde on discord.

JacquelineHyde今日 14:51
did the tutorial drone get its shields buffed or something? I can't seem to do enough damage with the starting blasters to kill the darn thing XD
bobbens今日 14:54
shouldn't have been touched, but might have been indirectly buffed
JacquelineHyde今日 14:55
not sure if its just the inaccuracy of the blasters, or what, but I can get about 70% of its shields down before the cannons slow fire, at which point it outheals shots and just runs circles around me lol.

**Comment by onpon4** [comment]
There's a number of interrelated issues here and it connects to #1660, so I'll make a point of checking the tutorial drone as a part of that. One particular factor is simply that the Laser Cannon MK1 is absurdly weak right now, which the rebalancing should address. The other is that we'll have to make sure the practice drone has the weakest armor/shields possible (so, the cores that cost 0 credits). I believe it does, so the weakness of the weapons should be the primary issue. If the rebalancing alone doesn't fix it, it should be trivial to add a special even weaker Core Systems for the practice drone.

🕵️

**Comment by amylaar** [comment]
It's easy to take out the drone if you follow a few simple rules.  First, if you got it wrong and your weapons are heated up, cool
them down, just like the instructor said, and start over.

Don't shoot when the target is out of range.  The automatic setting to only shoot weapons that are in range helps to avoid
the most egregious mistakes.
For more damage/heat efficiency, make ure most of your shots actually hit.  A good rule of thumb is to shoot while the drone is
approaching (and you're facing it, of course).  Mindlessly accelerating towards the drone tend to just spin you around.
Take your finger from the accelerator when you get stuck in such a loop, and try to rendez-vous with the drone.  Or just float a bit and then accelerate towards the drone.  If you're already approaching and in shooting range, stop accelerating, to lengthen the in-range approach period.

**Comment by UncombedCoconut** [comment]
Just tested in 0.9.0-alpha.1 (which has the rebalance changes merged), and I totally wrecked that drone. 😤
