### ISSUE TITLE
Ships passing in the nebula at Sigur

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1676]
Now that you don't have to stay close to the FLF ships while they are shooting at you, I decided to re-try the 'deal with the FLF agent' mission using a Schroedinger.  I can escape the ships without even trying (just residual speed from jump-in is 449 and keeps me from getting shot to smithereens, no need to accelerate to 520 or even fire up the afterburner), then after Gregar wakes up, just stop and wait for the FLF ships to catch up.  I then tried following manually, lazily the face button and acceleration, and this is where it got weird.  The Vendetta was leading with a speed of 519.  What outfits do they use?  Even with a Zephir Engine, an improved stabilizer, and an Air Freshener, I only get a max speed of 492 with a Vendetta.  Well, I could go higher with an afterburner, but only for a limited time, and it'd get choppy, but these vendettas fly very smoothly. Except they change directions,
and with my lazy following method, I overshoot before following them.  I seem to 'loose' the ships for a fraction of a second, and the mission ends.  I continue to follow the FLF vendettas and they eventually come to a stop, but there is no station, hailing them gives no exchange of messages, and trying to board says I'd have to disable them first.

Second attempt using auto-follow went fine, except they're doing continously 519 and I'm doing 520, and don't fully catch up till at SIndbad.

**Comment by onpon4** [comment]
Ah! I think I know what happened. It was setting the "speed limit" even if the Vendetta's speed was actually slower than the ship the player has.

I've fixed that in 077f2efa3. It unfortunately wasn't in time for tonight's nightly, but should show up in tomorrow's nightly. When you get access to it, please let me know if it fixes the issue.

It also occurs to me that perhaps the speed limit set may have been unnecessarily high, so I've also reduced it further in 18bba88d0.

🕵️

**Comment by bobbens** [comment]
I believe this is solved, closing.
