### ISSUE TITLE
frontier war text issues

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1679]
Dvaered Escort:
internicine -> internecine
"He is not in par with the ideas of the new generation of generals"  The expression commonly used is to be on par with something
when you are on the same level, and it doesn't fit here either way.  How about: "He disagrees with the ideas.." ?

"As your ship starts to recover its normal speed after jumping in," That text really confused me; I thought I had to accelerate to
catch up with Tam, when actually I (in an Admonisher, no less) was way ahead of him and had to get back to help him.

He will have to answer for this, trust me." answers Tam, "I will refer to the chief.
I suppose you mean: I will refer this matter to the chief.

Dvaered Sabotage:
"It would weaken the Dvaered Nation durably"  I suppose you mean: "It would weaken the Dvaered Nation considerably"
If you want to speak about the nation as if it was just an object, like a hammer, you might say "It would weaken the Dvaered Nation's durability".  Although I would never compare that proud nation to a single hammer.

"H... hi", you say, softly shaking your hand"  I suppose you mean either "waving your hand" or "shaking his hand" .
Waving one or two a hands is a kind of greeting that can be performed at a distance.
Shaking hands was a kind up physical-contact greeting common in western nations before the COVID-19 pandemic,
performed by two people at a time.  The persons involved would extend one hand each (usually each a right hand),
touch their palms together, close the hand to grip the other's hand, and in unison move their joined hands up and down.
Some people would also use it as a demonstration of strength by gripping hard and grinding the carpal bones of the other person painfully against each other.
While it is sort-of possible to join your own two hands together (if you are fortunate enough to have two healthy hands) in
an imitation of hand shaking with yourself (except left and right hand are ill-matched for the purpose of this gesture), this is
not generally recognized as a greeting.
If you are bemused by this explanation, you might be softly shaking your head.

"Very well" you abdicate. "Do what you have to do"
I wasn't royalty to start with.

How about: you answer resignedly.  Or: you give in.  Or: you sigh.

"Once the cargo is loaded and the team has taken place in the cabin,"
The team is not an event.   This should probably be:
"Once the cargo is loaded and the team has taken their places in the cabin,"

a message from Battleaddict to the plumber

Unless there is only a single plumber in the entire galaxy, that should be either "a plumber", "his plumber",
or "the Plumber" - the latter only in case "the Plumber" is a unique person, who recognized by that name.
(After referring to that tradeperson either as "a plumber" or his [Batteladdict's] plumber" once, you can of
course subsequently refer to that person as "the plumber" .)

"We will dock with him"  -> "We will dock with his ship" (they are not applying an enema, after all)

Otherwise, may Dvaerius, the patron saint of mace rockets, have mercy for your souls...
The common phrase for divine clemency is "have mercy on your souls"

"I am guarantor of the fact that this duel is conform to the rules established by our ancestors."
Unless this is supposed to be Dvaered legalese and/or an 'all your base are belong to us' reference,
I think this should be something like:
"I am witness to the fact that this duel  ( conforms | is conforming ) to the rules established by our ancestors."

In the log message:
"You took part to an operation to sabotage Battleaddict's cruiser."
You took part in an operation..

Betray General Klank:
"Lord Battleaddict has been killed in a loyal duel by the General Klank."
A duel is not sentient, hence it can't be loyal nor disloyal.

"Klank soon understood that such a disorganized invasion, with inevitably battle between warlords, would take for several periods,"

either "take several periods", "last for several periods", or "take four periods".  Well, maybe "take for the Ver all periods".  But we'll never know who the Ver are, or what they are doing with all the full stops.

**Comment by UncombedCoconut** [comment]
Good issue spotting and suggestions, thanks.
