### ISSUE TITLE
Lure out the FLF: IFF transponder malfunctions / text issue

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1680]
Before this mission, I followed the instruction to eliminate the FLF ship.  So the FLF were somehow cross with me (although they should have no means of knowing what happened in Surano - otherwise they would have rescued the stranded crew).  They
attacked me on sight - even after the fake FLF IFF transponder was installed.  If the transponder is meant to only work in the Sigur system, there was no indication in the exposition/description that it'd be like that.  A player might conclude that it doesn't work at all.
You might add something in the exposition about the IFF being effective in Sigur because of the specific nebula there still allowing the IFF to function, but blocking scans and/or details of the IFF signal that would reveal you as an imposter.
Or you could say the fake IFF only activates at Sigur to avoid becoming known as a fake prematurely.

There is also an oddity in the text:
"You can then access the ship's computer and download the flight log, which will require the location of the FLF base."

"require" doesn't fit there.  Maybe: "which should contain the location of the FLF base."

**Comment by bobbens** [comment]
Should be fixed in main, thanks!
