### ISSUE TITLE
Frontier war text issues continued

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1681]
Dvaered Sabotage - still has "this duel is conform to the rules"

Dvaered Escape:
I happened to meet Leblanc at the bar of Praxis in Ogat, which is described as follows:
<bar>While not nearly as pristine as many Empire bars, the Praxis bar is remarkably well-kept for a Dvaered bar.</bar>

So the start of Leblanc's text:
,,As you approach, Leblanc recognizes you. "Hello, citizen. The Major told me I would end up finding you by browsing all the shifty places in Dvaered space. He was right!''
feels off in this place.  Instead of "He was right", in such a nice place (by Dvaered standards), it would be more appropriate
if he said something like "Fancy meeting you here!"

I browsed briefly through the Dvaered bar descriptions with
grep -r -l '<faction>Dvaered<' assets|xargs grep '<bar>'|less
and further candidates for 'nice' bars seem to be:

=======================================================

assets/allan.xml:  <bar>Allan does not have the resources for much but the bar looks decent enough, with clean facilities, decent food and strong drink. For its patrons it provides a small respite from the harsh galaxy.</bar>

assets/allous_station.xml:  <bar>This bar looks like something one would expect from Za'lek space. Scientists and soldiers are interacting with surprising friendliness and conviviality. Of course, the local warlords would, and do, tolerate nothing less.</bar>

assets/castellan_iii.xml:  <bar>Castellan III's bar is surprisingly good. Perhaps it has to do with being a favoured haven for Dvaered officers. Perhaps it's that someone in a position of some power or influence decided that a nice place for the miners to relax and recuperate was a good way to show off their philanthropy. Either way, it's appreciated.</bar>

assets/cristen.xml:  <bar>The spaceport bar is one of the best protected facilities on the planet. The local government considers the lives of potential trading partners of greater importance than the lives of its workers. Having said that they do get to wear hazard suits outside of the main domes and they get a rather nice bar too - certainly not something many Dvaereds can claim.</bar>

assets/duran_shipyard.xml:  <bar>The spacedock bar provides visitors with a view
 over part of the assembly line. It is quite impressive to see a spacecraft being
built, even if it is only a relatively small one.</bar>

assets/durumdra.xml:  <bar>Durumdra doesn't have much to distinguish itself by i
n the galaxy but the spaceport bar goes a long way to helping. It has drinks fro
m all over the galaxy, though Draygar's awkward location means that most of them
 are rather pricey. Nevertheless, Durumdra has earned itself a footnote in sever
al noted galactic tourist guides.</bar>

assets/dvnn_central.xml:  <bar>Spaceport bar, waiting lounge, interview room, this
facility is everything at once. It's the only place accessible to non-DVNN
personnel so all dealings with visitors have to take place here. In fact, one of
the Dvaered reality shows is a live feed from the spaceport bar on DVNN Central, 
showing how the various visitors behave. The Dvaered seem to find this entertaining.</bar>
(not really nice but too public to be considered shifty)

assets/godtra.xml:  <bar>A pretty decent place as far as spaceport bars go, Godtra's bar is well equipped to facilitate traders and other offworlders. The data uplinks are decently speedy, which is rare on a Dvaered world. Clearly, the local infrastructure has been well designed.</bar>

assets/golem.xml:  <bar>This bar is shockingly convivial and clean, all things considered. The locals are determined to make their lives that much more enjoyable, and to prove to outsiders that they can conquer their homeworld's harsh environment.</bar>

assets/valt.xml:  <bar>The Valt spaceport bar is nothing special. It's rather clean for a Dvaered bar, though that may speak more about the small size of the settlement than the pride the proprietor takes in keeping his establishment clean.</bar>

A lot of others sound somewhat in-between between nice and shifty, but if Leblanc expects them to be shifty, he might be biased,
so it's all right if he describes them such even if it's a matter of opinion.

====================================================

settle the ambush -> set up an ambush

**Comment by nenau-again** [comment]
Thank you. These missions are really new, so feedback is most welcome

For the sabotage, it's colonel Urnus who says that? If yes, it was an attempt at humor. Both parts are obviously cheating, but the duel commissioner doesn't see anything. Proposals for improvement are welcome.

For Leblanc's dialogue, replacing "He was right" by "Fancy meeting you here!" feels right.
For the last one, I trust native speakers.

**Comment by amylaar** [comment]
> Thank you. These missions are really new, so feedback is most welcome
> 
> For the sabotage, it's colonel Urnus who says that? If yes, it was an attempt at humor. Both parts are obviously cheating, but the duel commissioner doesn't see anything. Proposals for improvement are welcome.

Yes, it's him that says it.  My point is not about the accuracy of his statement, it's about the accuracy of his grammar.
"this duel is conform to the rules" is not proper English grammar, and it mirrors the internet meme 'all your base was belong to
us' (which was also from a video game, in the context of placing a bomb, and the grammar the result of a translation attempt).
You got (noun phrase) + (form of to be) + (infinitive (w/out to)) + ((the preposition 'to') and the rest of the sentence).
The 'all your base' meme has the additional quirk the the noun phrase itself is ungrammatical; it should be 'all your bases' (or
if it' meant to be singular, 'your entire base (is belonging | belongs ) to us.'
The sentence can be made grammatical by replacing the infinitive with the continuous form, i.e. belonging / conforming.
Or drop the form of to be and make the verb after that agree with the subject, i.e. 'all your bases belong to us' / 'this duel conforms to the rules'
> 
> For Leblanc's dialogue, replacing "He was right" by "Fancy meeting you here!" feels right.

"He was right!" would be spot-on in Sudra:
assets/sudra.xml:  <bar>This spaceport bar is unsavory. No other word will describe the place with the same accuracy. A good portion of the bar's clientele are wearing hoods, masks, or other garments to hide their personal features. The lighting is set to quite a dim level, allowing customers to find corners as dark as they please. Despite these obvious signs, the Dvaered officials that sometimes visit the bar don't seem very keen to investigate.</bar>

That being said, that's the only one out of 69 bar description that really gives a shifty impression.  Mannannan seems to have
quite some variety and there might be shifty bars there, but you stick to the most accessible one, which is respectable.
Sola has the illicit rat fights, but since that activity is apparently condoned by the local authorities, that still doesn't quite
amount to being shifty. Omar and Ullnorm have threats of violence by the proprietor and the patrons, respectively, but these
threats are quite open, so these places are not shifty on that account.  Not a comfortable places to stay, all the same.

So maybe say "He was right!" in Sudra and "Fancy meeting you here!" in all the other bars.
(We can assume Leblanc looked for you in lots of shifty places that are not bars.  And the less savoury bars of Mannannan.)

> For the last one, I trust native speakers.

Let me just point out there are two issues there: the verb, and the article of the object.
1) You settle a score, an argument, a dispute, a place, or a group of people.  An ambush is set.
2) The definite article 'the' is used when you refer to a singular entity that is known to speaker and audience.  If you start to
referring to a singular entity out of a group of several, with said entity not having been specified before, (and you don't use 'one' ,) you use an indefinite article, i.e. 'a' or 'an'; usually 'a', except 'an' if the noun starts with a vowel sound (note that this is not the same as the word starting with a vowel, since it might start with a mute consonant (an hour), a consonant that is pronounced as a vowel, or a vowel that is pronounced as if it was a consonant or had one had one prepended (e.g. a iodine solution)).
Once the entity has been introduced into the narration / conversation, you henceforth use the definite article 'the'.

**Comment by nenau-again** [comment]
Dvaered don't respect grammar. Dvaered only respect mace rockets.
Joking aside, you're welcome to propose a PR for those 3 points, I'll merge it.
If you don't, I'll just wait until an other native speaker does.

**Comment by UncombedCoconut** [comment]
That should do it. :)
