### ISSUE TITLE
Idea: make another bar in Mannannan accessible

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1683]
The description says:
<bar>This bar is one of many. The increase in trade has also brought an increase in tastes, so there are several places that cater to particular tastes, even some very unsavory [sic] ones. Fortunately, the most accessible bar seems to be as respectable as bars come.</bar>

Who says I want to stick to the most accessible bar?  Maybe I want to meet a pirate informer, or want to buy a fake ID (could
be sold by an NPC there).

**Comment by bobbens** [comment]
I've thought about this a bit, but it doesn't seem like it would warrant a whole new system to implement multiple bars at the current time. Maybe in the future it could be considered, but just think of it as flavour text for now. Thanks!
