### ISSUE TITLE
Overly clever naming

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1684]
spotted some scripted pilot names to deal with at some point

May translate fine:
dat/events/sirius/preach.lua: `string.format( _("Converted %s"), j:name() )`
Probably not fine:
dat/missions/soromid/comingout/srm_comingout3.lua: `"Thug" .. shiptype`
dat/missions/soromid/comingout/srm_comingout4.lua: `"Thug " .. j`
dat/missions/soromid/comingout/srm_comingout5.lua: `"Thug " .. shiptype`

**Comment by bobbens** [comment]
Just avoiding `..` for string translation and relying on `string.format` should fix this sort of issue.
