### ISSUE TITLE
Stealing Ships

### ISSUE THREAD

**Issue by dwillmot20** [naev/naev#1689]
Hi, I'm loving the game. But I've found a bit of a glitch, when buying details and code to steal a ship from a pirate informer I land on the planet, I am then asked to name the ship, then the bit about 'You manage to enter the codes' etc comes up and I'm then asked to name the ship. This leaves me with two ships (so i'm not complaining as I sell one straight away) The first ship though is always odd. There are things like a jammer where the core should be, or no engine so I usually take these out to use on a future ship that I can tune to whatever mission situation I need.  The warnings about the authorities chasing me down don't seem to happen either and it doesn't affect my standings at all. most odd!
I'm on the latest version naev-0.8.1-linux-x86-64.AppImage  running on Ubuntu 20.10 if that helps.

**Comment by UncombedCoconut** [comment]
Thanks! This has actually been reported before (#1632) and should be fixed in nightly builds.
At present, there are no plans for an 0.8.2 release (as opposed to working toward 0.9.0). If that changes, the fix will be included there too.
