### ISSUE TITLE
Tracker: are trails perfect yet?

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1691]
Ideas for improvement post merge: [edited to reflect progress]

1. "add more definitions for capships" - ~~and now rockets (example: dat/outfits/rockets/fury_missile.xml).~~
2. "tune the colours. fire glow and afterburner are too close for example"
3. "different emitter types should have different afterburner and jump colours"
4. Somehow add nebula-specific trails
5. Make the rendering more optimized, without passing the colours as uniforms, but via the VBO [**EDIT** and maybe a bounding-box check before rendering, but only if faster. GL's stencil check may suffice.]
6. See how to make the trails de-activable, and maybe mutually exclusive with engine glow [**EDIT** or not, see comments]
7. ~~Maybe make the thickness variable (like thicker when afterburning)~~
8. ~~Do we want the noise (random()) in the shader, or is it nicer without?~~

Trails for rockets may be half-baked. We'll see when defining them. I made a guess about how to map their behavior to trail styles. In principle they could vary trail style while turning (seekers) or thrusting (mace rockets).

To expand on #7: in some ways it's more natural to pair colour with thickness as a style in whichever situation. On the other hand, for oddball ships like the Za'lek Mephisto/Diablo, it might be nice if `<trail_generator>` could override the trail's thickness (instead of creating trail definitions like red10 or red12). It's probably incoherent to support both features.

**Comment by bobbens** [comment]
>     4. Somehow add nebula-specific trails

My idea was to add new trails (for example on the tip of the wings and such) that would only be visible in the nebula (and probably be the color of the nebula. Would probably need a different shader to look smoky or cloudy or something like that.

>     5. Make the rendering more optimized, without passing the colours as uniforms, but via the VBO

Probably best to also do it in a single call if possible.

>     6. See how to make the trails de-activable, and maybe mutually exclusive with engine glow

Not entirely sure this is necessary.

>     7. Maybe make the thickness variable (like thicker when afterburning)

That sounds good.

>     8. Do we want the noise (random()) in the shader, or is it nicer without?

I feel like it would be better without.

> Trails for rockets may be half-baked. We'll see when defining them. I made a guess about how to map their behavior to trail styles. In principle they could vary trail style while turning (seekers) or thrusting (mace rockets).

Not sure how complicated trails for weapons should be. Especially with stuff like mace rockets it can lead to significant performance decrease.
 
> To expand on #7: in some ways it's more natural to pair colour with thickness as a style in whichever situation. On the other hand, for oddball ships like the Za'lek Mephisto/Diablo, it might be nice if `<trail_generator>` could override the trail's thickness (instead of creating trail definitions like red10 or red12). It's probably incoherent to support both features.

I would try to keep it all centralized if possible. If we have to start going hunting for overrided thickness and stuff everytime we change a main definition it could be a mess.

**Comment by bobbens** [comment]
While there is room for improvement, I'm considering this basically solved as of current master.
