### ISSUE TITLE
Display ndata path(s) and logs/saves/nebula/collisions path

### ISSUE THREAD

**Issue by Mutos** [naev/naev#1699]
Hello all,

Without being sure exactly where are naev files, it's quite difficult to debug anything. So I would like to have displayed the following paths in stdout : 

- ndata path, or list of pahs if using multiple paths by way of PhysFS;
- 'appdata'-like path, that is the one where logs/saves/nebula/collisions are written.

What it could look like is shown below, added to an actual stdout log : 

```
[...]

OpenAL started: 44100 Hz
Renderer: OpenAL Soft
Version: 1.1 ALSOFT 1.19.1 without EFX

ndata : 
    /mnt/data/dev/NAEV/020-Dev/Repositories/naev/dat/
appdata : 
    /mnt/data/dev/NAEV/020-Dev/Repositories/naev/naev-data/

Loaded 42 Sounds
[...]
Reached main menu

[...]
```
What do you think about that ?

**Comment by nenau-again** [comment]
Hi, nice to see you around!
Many things have changed lately about the ndata. I don't really know how it works unfortunately, but we should also have an "artwork" folder hanging around.
I guess you could have more interactive support on our discord (I never saw you there, did you know it exists at all?)

**Comment by UncombedCoconut** [comment]
Yes, this is a pretty important thing to do. I tweaked the proposal a bit to reflect how the internals work nowadays, but that commit ^^ should check all the boxes. (Collisions are under the "cache location", and beyond that the "read locations" and "write locations" are what you'd expect.)

**Comment by Mutos** [comment]
Thanks @UncombedCoconut,

I tried to de it myself and succeeded, which allowed me to check how PhysFS worked, but you were 1st ^-^
