### ISSUE TITLE
Inexact OSD message in the patrol mission

### ISSUE THREAD

**Issue by sigus** [naev/naev#1700]
There is "Land on the nearest %s planet and collect your pay" message in the patrol mission, but actually player can land on _any_ planet or station owned by paying faction. Although any planet is the nearest at the time of landing on it, I think it would be better to emphasize that it is possible to collect pay on any planet or station of respective faction.

**Comment by onpon4** [comment]
I think that's a pretty minor issue is it not? Change a line and it'll just be marked as "fuzzy" and the translator will just have to go back and update it. No sense being scared of text improvements for that reason.

🕵️

**Comment by UncombedCoconut** [comment]
Fortunately, issues involving these two strings are all minor.
My preference is to be humble when creating work for others which I can't even do*. But sure, happy with anyone's concrete favorite. "on a %s world"? "on any %s planet or station"? "in %s territory"?
*Some of these are so trivial I could retranslate.

**Comment by sigus** [comment]
> Yes, it could be worded a bit better (in 4 missions -- 2 patrol, 2 bounty).

I just noticed that there is `"The crime boss who gave you the mission pays you for your work as promised, though not before trying (and failing) to pick your pocket."` message (not OSD) in the pirate patrol mission. At the same time, this mission actually requires to land on _any_ pirate planet or station in order to collect pay. It turns out that the crime boss always ends up where the player landed (Even if we fantasize that the mission was issued remotely). If we fantasize some more, we can imagine that boss picks pockets by someone else's hands and only pays after an attempt has been made. Or chases the player in an attempt to pay. I just think that immersion is made up of little things too.

> The main downside of rewording (beyond fixing typos/grammar) is that it undoes some of the volunteer translators' progress (in this case, in German).

> I think that's a pretty minor issue is it not? Change a line and it'll just be marked as "fuzzy" and the translator will just have to go back and update it. No sense being scared of text improvements for that reason.

Yes, so, for example, Neutron Disruptor description has been changed recently due to #1678 (and this is definitely not fixing typos/grammar). Corresponding strings are marked for edit now (in German translation).

> "on a %s world"? "on any %s planet or station"? "in %s territory"?

I would suggest an option if I realized what to do with the crime boss.

**Comment by UncombedCoconut** [comment]
went with
```diff
-"Land on the nearest %s planet and collect your pay"
+"Land in %s territory to collect your pay"
 
-"Land on the nearest %s planet and collect your bounty"
+"Land in %s territory to collect your bounty"
 
-"The crime boss who gave you the mission pays you for your work as promised, "
-"though not before trying (and failing) to pick your pocket."
+"The local crime boss pays what you were promised, though not before trying "
+"(and failing) to pick your pocket."

```
