### ISSUE TITLE
Split monolithic XML files

### ISSUE THREAD

**Issue by Mutos** [naev/naev#1707]
As explained in Issue #1116 (and maybe others), some XML files are _monolithic_, mainly in the `dat/` root. They only consist of a series of same type objects, and should be split into s series of files, one per object, stored in a relevant subfolder.

The idea is that, when modifying a series of object and using PhysFS features, it's far easier to play with individual files than to follow changes to a complex file with engine- and universe-parts.

Instances of candidate monolithic files : 
- [x] `asteroids.xml`
- [x] `commodity.xml`
- [x] `damagetype.xml`
- [x] `faction.xml`
- [x] `fleet.xml`
- [x] `map.xml`
- [x] `slots.xml`
- [x] `spfx.xml`
- [x] `tech.xml`
- [x] `trails.xml`
- [x] `landing.lua`

**Comment by bobbens** [comment]
Some updates. Edited the original post to make it a tasklist, and adding `landing.lua` which was missing. Marked `fleet.xml` (removed) and `spfx.xml` (split) as done.

**Comment by bobbens** [comment]
Split tech.xml and faction.xml.

**Comment by bobbens** [comment]
I was motivated in procrastinating work and I finished the remaining xml files. Only the landing.lua is missing, but that needs a rewrite. I have an idea to redo it.

**Comment by bobbens** [comment]
Got rid of landing.lua. Now the lua spob stuff can be used instead to set bribing prices and also do much more complicated things if necessary.
