### ISSUE TITLE
More music control from Lua

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1714]
At the current time Naev is very limited in how music can be manipulated from Lua. In particular only the following functions exist:
```
delay (situation, delay) | Delays a rechoose.
load (name) | Loads a song.
play () | Plays the loaded song.
stop () | Stops playing the current song.
isPlaying () | Checks to see if something is playing.
current () | Gets the name of the current playing song.
```
While this allows playing a specific song or some minimal control, it doesn't allow, for example, to pause the music handling indefinitely, nor overloading how music selection is handled. We need ways of doing fancier music handling. In particular I would propose doing the following:
1. Add API to pause/resume the "normal" music (have fade-in and fade-out as necessary)
2. Add some sort of additional volume control to lower the music (for example when playing a special sound effect). This would be applied on top of the user-set volume control.
3. Create a new module to handle music, it could be based on using a subset of the Love API without requiring it all to run. It could be as simple as allowing to play/stop songs, and have callbacks when a song finishes playing.

**Comment by onpon4** [comment]
It's worth noting that we implemented some vars for controlling certain aspects of music some time ago. See music.lua for details. Mainly these are designed to give control over which faction music plays and halt all regular music playback until a track finishes playing.

🕵️

**Comment by bobbens** [comment]
Well I'm thinking of three particular use cases that appeared in my new missions:
1. Minerva Station should play its own song on loop while landed
2. When fighting drones in a certain mission, the nebula combat music only should play
3. When a certain cutscene happens (after defeated previous said drones), the music should become really quiet with weird noise overlaid ontop
4. When in the spa cutscene, music should become quieter (or changed) with running water and such playing ontop

I don't think any of this usage cases can be done properly. Currently minerva station plays the song once, then I guess it goes to whatever gets played on independent worlds. When fighting the drones, it should play the nebula combat song once, and in the other two cases, I haven't gotten other sound effects, but they would basically get played on the normal music at normal volume, and that is undesirable (especially in the drone cutscene, which has to be creepy).

**Comment by bobbens** [comment]
I have added more api to both `music` and `audio` Lua modules. Also a small Lua sound library is now provided as `lmusic`. It is integrated with the vn and fairly easy to use.

Things left to do would be to allow more control over the music subsystem (change volume and override the choose function as necessary).

**Comment by bobbens** [comment]
I do feel this is good enough now to close.
