### ISSUE TITLE
Mouseover text can disappear off the screen

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1717]
I noticed this recently while doing something with the Equipment screen: with mouseover text, it's possible for it to disappear partially off-screen if your cursor is too close to the bottom. This is a situation that can be inevitable in the Equipment screen in particular. Should be easy enough to solve: the mouseover text box just needs to always be kept within the game window bounds when possible.

🕵️

**Comment by bobbens** [comment]
I'm not sure we have a proper tooltip framework for this or if it's adhoc, but it needs some proper abstractions and would also help work towards #1032 . I do recall that the code is all over the place.

**Comment by bobbens** [comment]
There was a check, but some coordinate change or something broke it. Fixed in 8111f5e46f12e408690db554b5afe5d4176d8732 .
