### ISSUE TITLE
Crash while looking at current system

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1722]
When I try to look through the planets of the current system, naev crashes at an assert.
I have landed on Sternguard in Millstone, I type 'm' to get a map, click on Millstone to peruse the planets
in the system.  I click on Omar, than on Sternguard (or Marauder Station or even the Millstone primary - same result),
then the game crashes.

dat/VERSION:0.8.0+2135.g1cc4b257d.dirty

(no idea why it says dirty, I updated a couple of times with git pull . git submodule update, checked out the new branch main on the way; git diff shows no local changes.

**Comment by amylaar** [comment]
This is the save file:
[tex.ns.gz](https://github.com/naev/naev/files/6135881/tex.ns.gz)

**Comment by amylaar** [comment]
AFAICT, this happens generally when you select a planet that has an outfitters, but no shipyard, and then select another planet / primary.  A work-around is to close the system overview after you see an outfitter,

**Comment by UncombedCoconut** [comment]
Oops!
Re "-dirty", I think the meson.build file is a little naughty -- we give it a recipe for creating the dat/VERSION file which depends on the state of the tree, but we don't tell it that. (I'm not sure how to.)
If it *knows* to redo that work, e.g. if you touch the meson.build file, it will sync up the VERSION file with reality (and, alas, also rebuild the entire project).

**Comment by amylaar** [comment]
On 14/03/2021, Justin Blanchard ***@***.***> wrote:
> Oops!
> Re "-dirty", I think the meson.build file is a little naughty -- we give it
> a recipe for creating the dat/VERSION file which depends on the state of the
> tree, but we don't tell it that. (I'm not sure how to.)
> If it *knows* to redo that work, e.g. if you touch the meson.build file, it
> will sync up the VERSION file with reality (and, alas, also rebuild the
> entire project).

I don't know how meson works (I'm more of a make user), but I suppose
there must be a
way to specify dependencies?
If the naev binary doesn't depend on VERSION, you could make VERSION
depend on the
naev binary .
A contrived way to use the same basic idea in the face of a dependency
of the binary on
VERSION would be to put the VERSION dependency in a separate object file, put
all other object files in a library or a relocatable object, and make
VERSION depend on
that library or relocatable object.
Or you could use a git post-checkout hook to touch a timestamp file
whenever a checkout is made, and make VERSION depend on that timestamp
file.

Of course, with make, it would be possible to always run a rule to
generate the contents
of VERSION, and only replace VERSION (and thus updating its timestamp) with the
new contents if they are different from the old (with a little help
from bash and a move-if-change script), and make would know only to
rebuild files dependent on VERSION if VERSION is then newer; I don't
know if meson can do that.
