### ISSUE TITLE
abort: Outfit search is not reentrant!

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1724]
While flying (I think it doesn't matter where, but at any rate, you can start a new game and reject the tutorial),
type 'm' to get a map. 'f' to find, select outfits, type 'map'  <return>, then when you got he search results (various maps), type
'm' to make the map go away, 'm' and 'f' to get a new map and find anew, type 'map' <return>, and the game aborts.

**Comment by nenau-again** [comment]
Thanks for report.

"the game aborts" it's a polite way to say "crashes to desktop", right?
This only happends when you look for maps, or for any outfit research?
Are you using nightly or .8.* ?
What OS?
Do you have a log file?

**Comment by bobbens** [comment]
Nice catch, fixed. Thanks!
