### ISSUE TITLE
Typo: Some Dvaered thugs are station around the system,

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1728]
Should probably be "stationed" .

This appears in the explanation of the job the "Sketcht Individual" offers at Minerva station after altercation 1.

Later: If you were drag it along - should probably be "to drag it along".

Less certain: Make sure to harass them, but not kill them - "but not to kill them" or "but don't kill them"?  Or maybe that's just how they talk.

At the end, I tried to pull up the star map with 'm', but instead the explanation ended and the Sketchy Individual went away.
Apparently, at this point 'm' is mapped to the any key :-)  Not much of a problem for me as I could read the text again in dat/missions/minerva/pirate1.lua , but it's not that obvious where to look up the mission description when you play Naev from the packaged installation (assuming that'll include Minerva Station in the future).

**Comment by bobbens** [comment]
I've fixed the typos, thanks!

Currently the VN system basically overrides all input, and takes all input keys as an indication to continue (except when a menu choice is open). That probably needs some rethinking
