### ISSUE TITLE
Boarding the Seiryuu

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1741]
After the invitation to Pas - and finishing some business in Za'lek space - I went to meet the Seiryuu in the Pas system.
The Seiryuu appeared boardable - like a derelict ship.
```
Warning: [misn_runFunc] Mission 'Shadow Vigil' -> 'board': [string "missions/shadow/shadowvigil.lua"]:157: Mission trying to claim but already has.
stack traceback:
	[C]: in function 'claim'
	[string "missions/shadow/shadowvigil.lua"]:157: in function 'meeting'
	[string "missions/shadow/shadowvigil.lua"]:633: in function <[string "missions/shadow/shadowvigil.lua"]:629>
Warning: [hook_runMisn] Hook [p_board] '59821' -> 'board' failed
```
This can be reproduced with the attached save file by flying to Pas and boarding the Seiryuu.

[Thorby.ns.gz](https://github.com/naev/naev/files/6215264/Thorby.ns.gz)

git version eef36a27cbf1f9b0103abe0fda80ca8379667220

**Comment by nenau-again** [comment]
Mmm. I guess https://github.com/naev/naev/commit/8d1e4383d2d3097951f379bb7a6297f2957172e7 got a bad interaction with the fact that the system list has a `"__save"` item?
If I'm right, simply putting `misssys["__save"] = true` after the claim should fix it. I don't have time to try it right now. I'll inversigate that this afternoon.
Thanks for the report.

**Comment by nenau-again** [comment]
It wasn't that at all.
Anyway, it should be fixed.
Please complain if not (I tested, but one never knows...)

**Comment by nenau-again** [comment]
It just occured to me that probably the mission will fail anyway (but without error message) on your save because the Goddard system is claimed by the kidnapped mission.
Quick fix for you is to beat first (or abort) the kidnapped mission
And I'll make sure that the mission is never proposed if a system has already been claimed later in order to fix it more permanently.

**Comment by PhoenixRiver** [comment]
> And I'll make sure that the mission is never proposed if a system has
> already been claimed later in order to fix it more permanently.

Generalising this to stop drop missions if they try to claim something
that already has a claim (potentially with text in each mission to
allow for this) would probably be worth doing else this could get
complicated fast! ;)

Phoenix
