### ISSUE TITLE
Shadowvigil won't start

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1743]
After 4ad0c4949259651de6010f9162b9d7ae95bfb9f3, even when clearing out all the other missions, I couldn't board the Seiryuu
from the existing mission:

```Warning: [misn_runFunc] Mission 'Shadow Vigil' -> 'board': [string "missions/shadow/shadowvigil.lua"]:188: attempt to index global 'misssys' (a nil value)
stack traceback:
	[string "missions/shadow/shadowvigil.lua"]:188: in function 'accept_m'
	[string "missions/shadow/shadowvigil.lua"]:167: in function 'meeting'
	[string "missions/shadow/shadowvigil.lua"]:633: in function <[string "missions/shadow/shadowvigil.lua"]:629>
Warning: [hook_runMisn] Hook [p_board] '107447' -> 'board' failed
```

I suppose the started mission in the savefile is not compatible as there was no variable misssys set.  The real question going
forward is if the mission can be properly played when starting anew, so I cancelled the mission and (as the propability is so low)
went about doing other stuff.  During Harja's Revenge, I was finally contacted again to meet in Pas.
FWIW, ""Do you have for to respond to the invitation?" looks like a translation error - is that suposed to be ""Do you intend to respond to the invitation?"

Anyway, the accepted invitation was logged as before, but the mission didn't start.  I was shortly contacted again twice more,
each time accepted, invitation got logged, but mission didn't start.
There was no error message on the console.

Does the event claim in missions/shadow/shadowvigil.lua fail because the same systems have already been claimed in events/neutral/shadow_comm.lua ?

**Comment by nenau-again** [comment]
I'll change the text as you suggested
For the claim, you're right. I did mess up in my tests. I'll try something else.

**Comment by nenau-again** [comment]
Allright. I hope it's fixed now (I've tested it but last time I also thought I had tested it)
I let this open until you confirm that you managed to actually play the mission.

**Comment by amylaar** [comment]
> Allright. I hope it's fixed now (I've tested it but last time I also thought I had tested it)
> I let this open until you confirm that you managed to actually play the mission.

Yes, it worked this time.  I've found a few warnings later in the console, though.
I did re-start the journey from the planet after the meetup with the escorts to the diplomat a couple of times while I tweaked the
ship to be fast enough not to be left behind, so the messages are from these multiple tries.

```
Warning: Could not equip Unicorp PT-100 Core System on pilot Imperial Diplomat!

Warning: Could not equip Nexus Dart 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip Unicorp B-2 Light Plating on pilot Imperial Diplomat!

Warning: Could not equip Milspec Aegis 2201 Core System on pilot Imperial Diplomat!

Warning: Could not equip Nexus Dart 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip Unicorp D-2 Light Plating on pilot Imperial Diplomat!

Warning: Could not equip Milspec Aegis 2201 Core System on pilot Imperial Diplomat!

Warning: Could not equip Nexus Dart 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip Unicorp B-2 Light Plating on pilot Imperial Diplomat!

Warning: Could not equip Unicorp PT-100 Core System on pilot Imperial Diplomat!

Warning: Could not equip Nexus Dart 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip Unicorp B-2 Light Plating on pilot Imperial Diplomat!

Warning: Could not equip Unicorp PT-100 Core System on pilot Imperial Diplomat!

Warning: Could not equip Nexus Dart 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip S&K Ultralight Stealth Plating on pilot Imperial Diplomat!

Warning: Could not equip Unicorp PT-100 Core System on pilot Imperial Diplomat!

Warning: Could not equip Tricon Zephyr Engine on pilot Imperial Diplomat!

Warning: Could not equip S&K Ultralight Stealth Plating on pilot Imperial Diplomat!

Warning: Could not equip Unicorp PT-100 Core System on pilot Imperial Diplomat!

Warning: Could not equip Unicorp Hawk 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip S&K Ultralight Stealth Plating on pilot Imperial Diplomat!

Warning: Could not equip Milspec Aegis 2201 Core System on pilot Imperial Diplomat!

Warning: Could not equip Tricon Zephyr Engine on pilot Imperial Diplomat!

Warning: Could not equip Unicorp B-2 Light Plating on pilot Imperial Diplomat!

Warning: Could not equip Unicorp PT-100 Core System on pilot Imperial Diplomat!

Warning: Could not equip Nexus Dart 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip Unicorp B-2 Light Plating on pilot Imperial Diplomat!

Warning: Could not equip Unicorp PT-100 Core System on pilot Imperial Diplomat!

Warning: Could not equip Nexus Dart 150 Engine on pilot Imperial Diplomat!

Warning: Could not equip Unicorp D-2 Light Plating on pilot Imperial Diplomat!
```

**Comment by nenau-again** [comment]
Yes, those warnings are known, and not that easy to fix.
Thanks for testing!
