### ISSUE TITLE
Runaway ran away again

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1744]
I followed the drone from Xavier to Auger, 'disabled' and loaded it up (boarded), then went on to Astana in order to refuel.
The drone appeared there again outside just after I jumped in, just like in Auger.
I found these messages on the console:
```
Warning: [misn_runFunc] Mission 'The one with the Runaway' -> 'targetIdle': [string "missions/zalek/sciencegonewrong/02_sciwrong.lua"]:362: Pilot is invalid.
stack traceback:
	[C]: in function 'pos'
	[string "missions/zalek/sciencegonewrong/02_sciwrong.lua"]:362: in function <[string "missions/zalek/sciencegonewrong/02_sciwrong.lua"]:361>
Warning: [hook_runMisn] Hook [timer] '111729' -> 'targetIdle' failed
Warning: [misn_runFunc] Mission 'The one with the Runaway' -> 'targetIdle': [string "missions/zalek/sciencegonewrong/02_sciwrong.lua"]:362: Pilot is invalid.
stack traceback:
	[C]: in function 'pos'
	[string "missions/zalek/sciencegonewrong/02_sciwrong.lua"]:362: in function <[string "missions/zalek/sciencegonewrong/02_sciwrong.lua"]:361>
Warning: [hook_runMisn] Hook [timer] '111747' -> 'targetIdle' failed
```

Not sure if all of that was from that attempt, I've been trying what strategy is viable with a Hyena - I first found one that didn't work in Xavier and next had an encounter with a hostile heavy drone in Auger.

git version 4ae7494eff949461b8be78f5a5359db2ca6b9caf
[runaway.tar.gz](https://github.com/naev/naev/files/6220028/runaway.tar.gz)

**Comment by bobbens** [comment]
Thanks for the report. I'm not able to reproduce with your save. Where should I go and what should I do?

**Comment by UncombedCoconut** [comment]
was able to reproduce the double-runaway issue from a new game. a quick fix to the logic took care of it, and bobbens already addressed the console error messages.
