### ISSUE TITLE
Advanced Nebula Research fails to advance to Pultatis

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1745]
I've been doing the Advanced Nebula Research escort mission - that is actually harder when you have high reputation with
the pirates, as it is hard to target the pirates that shoot at the research vessel.  I cycle with 'T', but if there are a lot of other
ships, that takes a long while to find a close pirate.
So, I've been on the way back, departing from the last stop Vilati Vilata and passing from there through the Daan and Provectis Nova systems.  Eventually the Research Shuttle jumped from Provectis Nova to Pultatis - there was the white message to that
effect, too - but when I got to Pultatis myself, the Research Shuttle was not there.  The console showed these messages:

```
Invalid parameter for systemL_jumpPath.
Warning: [misn_runFunc] Mission 'Advanced Nebula Research' -> 'jumpin': [string "scripts/nextjump.lua"]:7: Invalid parameter for systemL_jumpPath.
stack traceback:
	[C]: in function 'jumpPath'
	[string "scripts/nextjump.lua"]:7: in function 'getNextSystem'
	[string "missions/zalek/neburesearch/neburesearch_01.lua"]:171: in function <[string "missions/zalek/neburesearch/neburesearch_01.lua"]:167>
Warning: [hook_runMisn] Hook [jumpin] '111295' -> 'jumpin' failed
```
This is reproducible when I start again from the save point at Vilati Vilata.

[Thorby.ns.gz](https://github.com/naev/naev/files/6222364/Thorby.ns.gz)

**Comment by amylaar** [comment]
When I land in Pultatis, the mission still finishes, apparently successfully.

**Comment by bobbens** [comment]
Fixed in main, thanks!
