### ISSUE TITLE
maikki 2 typo

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1748]
Prof. Stova:
... as far away as possible fro nebula research ...
fro ->from

**Comment by amylaar** [comment]
Dr. Cayne / Calliope:
A pellet of shrimp food releases into the aquarium
releases -> is released
or (if it takes a little longer)-> is being released

**Comment by amylaar** [comment]
For the Strangelove Hologram, it says that it's a terminal where you can redeem tokens.

**Comment by amylaar** [comment]
"She is visibly exciting."  That has various possible meanings, most of which don't quite fit the context.  I think you meant something like "She is visibly excited."

When Maikki gave me her surplus Minerva tokens, I got the message "You receive 4710."   But that was the number of tokens
I had before, what I actually got was 500 tokens.

**Comment by bobbens** [comment]
Should be fixed in main, thanks!
