### ISSUE TITLE
graphic novel dialogue not alwas readable

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1750]
When I was bringing Dr Strangelove the Nebula Artifact recovered from the feral drone, I had the game running in a window
with a border on top, underneath a xfce menue bar on a loptop with 768p squatscreen.  When the dialogue was a bit longer, the bottom was cut off.
That wouldn't have been such a bad thing if I could have used F11 to switch to full screen, but alas, that key is also
intercepted by the graphic novel handling, so the only way is to somehow quit the game, load from backup, switch to full-screen,
eliminate the feral drone again, and bring the Nebula Artifact to Dr Strangelove again.

**Comment by bobbens** [comment]
Should be fixed in main, thanks!
