### ISSUE TITLE
typo in the (spa) tub

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1754]
"getting rid of all the junk from your travels off" that's somewhat redundant, and somewhat of an autopeotomic double-entendre (C and the Soromids notwithstanding - it's something of a niche requirement).
two of the possible alternatives would be
"getting rid of all the contaminants from your travels"
or
"getting all the grime from your travels off"
("getting rid of all the grime from your travels off-planet" would be a possibility if you did this on your home planet, but this is a space-station)

**Comment by bobbens** [comment]
Changed to grime, thanks!

**Comment by amylaar** [comment]
You still have the redundancy "getting rid of ... off"

**Comment by bobbens** [comment]
That's what I get for developing when tired. Should be fixed in main!
