### ISSUE TITLE
Sindbad, interstellar transport hub and tourist spot

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1757]
When you are in a weak Hyena in Alteris and take on the "A Journey To Arandon" job, the logical course of action
under the current rules is to fly to Sindbad to change ships, then go on to Arandon.
But that is really ridiculous - why meet in in Arandon when you've been to Sindbad?
In the first place, Sindbad shouldn't allow you docking when you bring one or more non-FLF person(s) along.
There's also nothing preventing you from taking other people to Sindbad, from sight-seeing tourists to various people who request passage.

**Comment by bobbens** [comment]
> But that is really ridiculous - why meet in in Arandon when you've been to Sindbad?

I believe that campaign was before the FLF missions and Sindbad were made. It should be possible to code in interactions between both the campaigns so you go to Sindbad instead.

> In the first place, Sindbad shouldn't allow you docking when you bring one or more non-FLF person(s) along.
There's also nothing preventing you from taking other people to Sindbad, from sight-seeing tourists to various people who request passage.

This is actually much trickier to do. While ideally we would want to limit this, it may be more trouble than it is worth and it might be best to just hand-wave it away as part of "video game logic".

**Comment by amylaar** [comment]
I suppose the lore could say that tourists are locked in when visiting a secret installation.  For a Llama or other low-comfort vessel, that could be in the brig; for a Gawain, a luxurious entertainment pod (still a golden cage) or a cryosleep facility.
Maybe that could be hinted at during some of the Melendez sales spiel / interaction with Nexus shipyards / ship-based advertising / newsreel at the bar.

**Comment by Lineth** [comment]
Maybe a modest description in Sindbad that says that its identity as a FLF base is not immediately obvious/hidden so that all outsiders see is a rickety old outpost station.

**Comment by bobbens** [comment]
OK, so with the change in the universe layout, it makes more sense for the Shark mission to go to Behar instead, so changed that. The description of Sindbad makes it so it seems like it's a junk station, which I guess would make it a bit inconspicuous. Since it's not practical to write interactions for all the npcs you can drag over there, I guess a bit of hand-waving is best for now. Thanks for the feedback!
