### ISSUE TITLE
I have a 0.5.3/0.6.0 save. Do I need to do anything special to migrate it?

### ISSUE THREAD

**Issue by mark-c** [naev/naev#1766]
For example, will I miss out on new mission rewards, or is there a kind of check for that? I 

[Mark.zip](https://github.com/naev/naev/files/6408851/Mark.zip)

**Comment by bobbens** [comment]
You should be able to buy unique rewards from the traveling merchant if you have done the missions required for them, however, some stuff may be a bit wonky. Overall I don't think much would break except that you will likely lose some outfits due to name changing and reshuffling.

**Comment by bobbens** [comment]
Closing.

**Comment by mark-c** [comment]
Would it be worth to open in 0.6.1 and sell some of them, perhaps?

**Comment by bobbens** [comment]
> Would it be worth to open in 0.6.1 and sell some of them, perhaps?

Honestly, it may be more trouble than it is worth. You might just want to do a few missions to get used to new stuff and make money you may have lost during that time.
