### ISSUE TITLE
map buying considered harmful

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1770]
I find that buying navigation maps makes it harder to explore the galaxy.  You loose track of which systems need scanning for
jump points you haven't found yet.  So I restrict myself to local maps and maps with hidden jump points, and the latter are also
a mixed blessing as they tend to show systems that are not scanned yet.

This is really a shame, since buying navigation maps would otherwise make the early game phase go much smoother.
Also, finding a map in a derelict can actually mess up your navigation permanently.

I think there should be a map viewing mode that shows known systems that are not fully scanned.  If you land on a planet
with a spaceport, it should automatically mark the system as fully scanned if it is (you have the disabled 'but local map' option there so the information is available at that point).

For sytems without accessible spaceports, it should be possible to manually set a bit that says you think you've scanned the system properly.

This way, you could buy maps without worrying about loosing vital information.

**Comment by bobbens** [comment]
Yes, this is also pointed out in #1286 and is something I would like to do.

**Comment by bobbens** [comment]
OK, added a simple discovery mode. More details in #1286. Closing this, if you have any feedback, please leave it in #1286. Thanks!
