### ISSUE TITLE
Harmonize font usage for inputs

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1779]
As pointed out in #1778 there seems to be fairly random font size choices for the different input widgets. It would probably be best to have pop-ups use default font while small embedded widgets to use the small font, and change the behaviour with NULL to default to the default font for consistency with `font.c`.

**Comment by onpon4** [comment]
Well, the current state is that small is used for everything except a single case (the input for the find dialog), to be precise. I don't find usage of the small font to be problematic at all myself, but given the small number of places where the input widget is used, it would be trivial to change them all to the "default" font if you want to. (In fact most specify the font as NULL.)

🕵️

**Comment by bobbens** [comment]
Changed all to default font.
