### ISSUE TITLE
Beams don't heat up

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1790]
This was something pointed out by @bobbens somewhere, but he noted that beams don't lose accuracy, so maybe it makes sense. Beams have a heatup value stored in C, but it's unused and beams never heat up.

At first I thought maybe it makes sense for them to not heat up too, but then I realized that while heatup can't ever hurt a beam's accuracy specifically, it can heat up the ship, which in turn can affect the accuracy of other weapons and eventually force active cooldown, and this heat also makes you more visible. So I think it's probably prudent to make it so that the heatup stat of beams is functional after all, while continuing to not have it affect the accuracy of beams (as there's really no way to do that without making the beams frustrating to deal with, and I think allowing them to have no accuracy penalty for heat is okay as an advantage unique to beams).

🕵️

**Comment by bobbens** [comment]
Another thought would be that it probably would make sense to have heat affect either cooldown or ontime (or both), so that like bolt weapons, beam weapons do drop in DPS if you overheat.

**Comment by onpon4** [comment]
That would work, yeah.

🕵️

**Comment by bobbens** [comment]
Tracking this issue in #1771 .
