### ISSUE TITLE
crash in outfit_isMod

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1792]
Thread 1 "naev" received signal SIGSEGV, Segmentation fault.
It seems like naev has crashed. Please debug with gdb now ;)
outfit_isMod (o=o@entry=0x0) at ../src/outfit.c:505
505	   return (o->type==OUTFIT_TYPE_MODIFICATION);
Missing separate debuginfos, use: dnf debuginfo-install SDL2-2.0.14-3.fc34.x86_64 SDL2_image-2.0.5-6.fc34.x86_64 bzip2-libs-1.0.8-6.fc34.x86_64 dbus-libs-1.12.20-3.fc34.x86_64 elfutils-libelf-0.183-1.fc34.x86_64 expat-2.2.10-2.fc34.x86_64 flac-libs-1.3.3-7.fc34.x86_64 freetype-2.10.4-3.fc34.x86_64 glib2-2.68.1-1.fc34.x86_64 glibc-2.33-8.fc34.x86_64 graphite2-1.3.14-7.fc34.x86_64 gsm-1.0.19-5.fc34.x86_64 harfbuzz-2.7.4-3.fc34.x86_64 libICE-1.0.10-6.fc34.x86_64 libSM-1.2.3-8.fc34.x86_64 libX11-xcb-1.7.0-3.fc34.x86_64 libXScrnSaver-1.2.3-8.fc34.x86_64 libXau-1.0.9-6.fc34.x86_64 libXcursor-1.2.0-5.fc34.x86_64 libXext-1.3.4-6.fc34.x86_64 libXfixes-5.0.3-14.fc34.x86_64 libXrandr-1.5.2-6.fc34.x86_64 libXrender-0.9.10-14.fc34.x86_64 libXtst-1.2.3-14.fc34.x86_64 libXxf86vm-1.1.4-16.fc34.x86_64 libasyncns-0.8-20.fc34.x86_64 libbrotli-1.0.9-4.fc34.x86_64 libcap-2.48-2.fc34.x86_64 libdrm-2.4.105-1.fc34.x86_64 libedit-3.1-36.20210419cvs.fc34.x86_64 libffi-3.1-28.fc34.x86_64 libgcc-11.1.1-1.fc34.x86_64 libgcrypt-1.9.3-2.fc34.x86_64 libglvnd-1.3.3-1.fc34.x86_64 libglvnd-glx-1.3.3-1.fc34.x86_64 libgpg-error-1.42-1.fc34.x86_64 libjpeg-turbo-2.0.90-2.fc34.x86_64 libogg-1.3.4-4.fc34.x86_64 libpng-1.6.37-10.fc34.x86_64 libselinux-3.2-1.fc34.x86_64 libstdc++-11.1.1-1.fc34.x86_64 libtiff-4.2.0-1.fc34.x86_64 libuuid-2.36.2-1.fc34.x86_64 libvorbis-1.3.7-3.fc34.x86_64 libwebp-1.2.0-1.fc34.x86_64 libxcb-1.13.1-7.fc34.x86_64 libxml2-2.9.10-12.fc34.x86_64 libxshmfence-1.3-8.fc34.x86_64 libzstd-1.4.9-1.fc34.x86_64 llvm-libs-12.0.0-0.1.rc1.fc34.x86_64 luajit-2.1.0-0.19beta3.fc34.x86_64 lz4-libs-1.9.3-2.fc34.x86_64 mesa-libGL-21.0.3-2.fc34.x86_64 mesa-libglapi-21.0.3-2.fc34.x86_64 ncurses-libs-6.2-4.20200222.fc34.x86_64 openal-soft-1.19.1-12.fc34.x86_64 pcre-8.44-3.fc34.1.x86_64 physfs-3.0.2-7.fc34.x86_64 sssd-client-2.4.2-3.fc34.x86_64 vulkan-loader-1.2.162.0-2.fc34.x86_64 xz-libs-5.2.5-5.fc34.x86_64 zlib-1.2.11-26.fc34.x86_64
(gdb) bt
#0  outfit_isMod (o=o@entry=0x0) at ../src/outfit.c:505
#1  0x00000000004b3ea3 in pilot_slotIsActive (o=o@entry=0x2be7918)
    at ../src/pilot_outfit.c:1208
#2  0x000000000044e19f in equipment_renderColumn (x=x@entry=578, y=864, 
    y@entry=924, w=40, h=40, lst=0x2be76c0, txt=<optimized out>, 
    selected=selected@entry=-1, o=o@entry=0x0, p=p@entry=0x2c10840, 
    wgt=wgt@entry=0x66e5a0 <info_eq_weaps>) at ../src/equipment.c:390
#3  0x000000000044e577 in equipment_renderSlots (bx=<optimized out>, 
    by=<optimized out>, bw=<optimized out>, bh=<optimized out>, 
    data=0x66e5a0 <info_eq_weaps>) at ../src/equipment.c:512
#4  0x00000000004e7d8a in cst_render (cst=0x280b4c0, bx=<optimized out>, 
    by=<optimized out>) at ../src/tk/widget/cust.c:101
#5  0x00000000004de85d in window_render (w=w@entry=0x2e259a0)
    at ../src/toolkit.c:1470
#6  0x00000000004e86b3 in tab_render (tab=0x2629890, bx=548, by=414)
    at ../src/tk/widget/tabwin.c:382
#7  0x00000000004de85d in window_render (w=w@entry=0x2e45740)
    at ../src/toolkit.c:1470
#8  0x00000000004de903 in toolkit_render () at ../src/toolkit.c:1553
#9  0x00000000004c2070 in render_all (game_dt=<optimized out>, 
    real_dt=0.035663094999999999) at ../src/render.c:237
#10 0x000000000048c9a4 in main_loop (update=update@entry=1)
    at ../src/naev.c:709
#11 0x000000000048d697 in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/naev.c:420
(gdb) bt
#0  outfit_isMod (o=o@entry=0x0) at ../src/outfit.c:505
#1  0x00000000004b3ea3 in pilot_slotIsActive (o=o@entry=0x2be7918)
    at ../src/pilot_outfit.c:1208
#2  0x000000000044e19f in equipment_renderColumn (x=x@entry=578, y=864, 
    y@entry=924, w=40, h=40, lst=0x2be76c0, txt=<optimized out>, 
    selected=selected@entry=-1, o=o@entry=0x0, p=p@entry=0x2c10840, 
    wgt=wgt@entry=0x66e5a0 <info_eq_weaps>) at ../src/equipment.c:390
#3  0x000000000044e577 in equipment_renderSlots (bx=<optimized out>, 
    by=<optimized out>, bw=<optimized out>, bh=<optimized out>, 
    data=0x66e5a0 <info_eq_weaps>) at ../src/equipment.c:512
#4  0x00000000004e7d8a in cst_render (cst=0x280b4c0, bx=<optimized out>, 
    by=<optimized out>) at ../src/tk/widget/cust.c:101
#5  0x00000000004de85d in window_render (w=w@entry=0x2e259a0)
    at ../src/toolkit.c:1470
#6  0x00000000004e86b3 in tab_render (tab=0x2629890, bx=548, by=414)
    at ../src/tk/widget/tabwin.c:382
#7  0x00000000004de85d in window_render (w=w@entry=0x2e45740)
    at ../src/toolkit.c:1470
#8  0x00000000004de903 in toolkit_render () at ../src/toolkit.c:1553
#9  0x00000000004c2070 in render_all (game_dt=<optimized out>, 
    real_dt=0.035663094999999999) at ../src/render.c:237
#10 0x000000000048c9a4 in main_loop (update=update@entry=1)
    at ../src/naev.c:709
#11 0x000000000048d697 in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/naev.c:420
(gdb) frame 1
#1  0x00000000004b3ea3 in pilot_slotIsActive (o=o@entry=0x2be7918)
    at ../src/pilot_outfit.c:1208
1208	   if (outfit_isMod(oo) && !oo->u.mod.active && oo->u.mod.lua_ontoggle == LUA_NOREF)
(gdb) p oo->u.mod.active
Cannot access memory at address 0x90
(gdb) p oo->u.mod.lua_ontoggle
Cannot access memory at address 0x148
(gdb) p oo
$1 = (Outfit *) 0x0
(gdb) frame 0
#0  outfit_isMod (o=o@entry=0x0) at ../src/outfit.c:505
505	   return (o->type==OUTFIT_TYPE_MODIFICATION);
(gdb) frame 1
#1  0x00000000004b3ea3 in pilot_slotIsActive (o=o@entry=0x2be7918)
    at ../src/pilot_outfit.c:1208
1208	   if (outfit_isMod(oo) && !oo->u.mod.active && oo->u.mod.lua_ontoggle == LUA_NOREF)
(gdb) l
1203	   Outfit *oo;
1204	   if (!o->active)
1205	      return 0;
1206	
1207	   oo = o->outfit;
1208	   if (outfit_isMod(oo) && !oo->u.mod.active && oo->u.mod.lua_ontoggle == LUA_NOREF)
1209	      return 0;
1210	
1211	   return 1;
1212	}
(gdb) p o
$2 = (const PilotOutfitSlot *) 0x2be7918
(gdb) p o->outfit
$3 = (Outfit *) 0x0
(gdb) frame 0
#0  outfit_isMod (o=o@entry=0x0) at ../src/outfit.c:505
505	   return (o->type==OUTFIT_TYPE_MODIFICATION);
(gdb) l
500	 *    @param o Outfit to check.
501	 *    @return 1 if o is a ship modification.
502	 */
503	int outfit_isMod( const Outfit* o )
504	{
505	   return (o->type==OUTFIT_TYPE_MODIFICATION);
506	}
507	/**
508	 * @brief Checks if outfit is an afterburner.
509	 *    @param o Outfit to check.
(gdb) frame 1
#1  0x00000000004b3ea3 in pilot_slotIsActive (o=o@entry=0x2be7918)
    at ../src/pilot_outfit.c:1208
1208	   if (outfit_isMod(oo) && !oo->u.mod.active && oo->u.mod.lua_ontoggle == LUA_NOREF)
(gdb) p *o
$4 = {id = 12, outfit = 0x0, active = 1, sslot = 0x1b2f188, heat_T = 250, 
  heat_C = 31850, heat_area = 9.8714031345089932, heat_start = 250, 
  state = PILOT_OUTFIT_OFF, stimer = 0, timer = 0, rtimer = 0, level = -1, 
  weapset = -1, u = {beamid = 0, ammo = {outfit = 0x0, quantity = 0, 
      deployed = 0, lockon_timer = 0, in_arc = 0}}, lua_mem = -2, lua_stats = {
    speed_mod = 0, turn_mod = 0, thrust_mod = 0, cargo_mod = 0, 
    armour_mod = 0, armour_regen_mod = 0, armour_flat = 0, armour_damage = 0, 
    shield_mod = 0, shield_regen_mod = 0, shield_flat = 0, shield_usage = 0, 
    energy_mod = 0, energy_regen_mod = 0, energy_flat = 0, energy_usage = 0, 
    cpu_mod = 0, cpu_max = 0, jump_delay = 0, land_delay = 0, 
    cargo_inertia = 0, ew_hide = 0, ew_detect = 0, ew_jump_detect = 0, 
    heat_dissipation = 0, stress_dissipation = 0, crew_mod = 0, mass_mod = 0, 
    launch_rate = 0, launch_range = 0, launch_damage = 0, ammo_capacity = 0, 
    launch_lockon = 0, fbay_damage = 0, fbay_health = 0, fbay_movement = 0, 
    fbay_capacity = 0, fwd_heat = 0, fwd_damage = 0, fwd_firerate = 0, 
    fwd_energy = 0, fwd_dam_as_dis = 0, tur_heat = 0, tur_damage = 0, 
    tur_tracking = 0, tur_firerate = 0, tur_energy = 0, tur_dam_as_dis = 0, 
    engine_limit_rel = 0, engine_limit = 0, nebu_absorb_shield = 0, 
    nebu_absorb_armour = 0, misc_instant_jump = 0, misc_reverse_thrust = 0, 
    misc_asteroid_scan = 0, misc_hidden_jump_detect = 0, loot_mod = 0, 
    time_mod = 0, time_speedup = 0}}

**Comment by amylaar** [comment]
It might be related to me having the second weapon slot of an empire pacifier emptied so I could use a smaller core outfit.
It previously had a grave beam.

**Comment by bobbens** [comment]
Should be fixed in main. Thanks!
