### ISSUE TITLE
crash in may_system_render

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1793]
I tried if I can see what facilities Qorellia has before landing (bought the Qorel expanse map, otherwise new there) by using the map and clicking on Quorellia.  I suppose this is a no, then:

Thread 1 "naev" received signal SIGSEGV, Segmentation fault.
It seems like naev has crashed. Please debug with gdb now ;)
map_system_render (bx=90, by=130, w=1557, h=1188, data=<optimized out>)
    at ../src/map_system.c:508
508          if ( p->faction > 0 ) {/* show the faction */
(gdb) p p
$1 = (Planet *) 0x0
(gdb) bt
#0  map_system_render (bx=90, by=130, w=1557, h=1188, data=<optimized out>)
    at ../src/map_system.c:508
#1  0x00000000004e7d72 in cst_render (cst=0x2576250, bx=<optimized out>, 
    by=<optimized out>) at ../src/tk/widget/cust.c:101
#2  0x00000000004de845 in window_render (w=w@entry=0x334a580)
    at ../src/toolkit.c:1470
#3  0x00000000004de8eb in toolkit_render () at ../src/toolkit.c:1553
#4  0x00000000004c2058 in render_all (game_dt=<optimized out>, 
    real_dt=0.053809616999999997) at ../src/render.c:237
#5  0x000000000048c9a4 in main_loop (update=update@entry=1)
    at ../src/naev.c:709
#6  0x000000000048d697 in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/naev.c:420

**Comment by bobbens** [comment]
@UncombedCoconut should have fixed it in main. Thanks!
