### ISSUE TITLE
glitch in Kex's transport intercept mission

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1796]
After disabling and boarding the transport, I went on to disable and board the escorts.  At some point the transport came awake again, and amid distraction from left over and re-awakened escorts, it got away to the jump point, and there was a message that the mission failed because the transport got away

When I got back to Minerva Station, Kex still surmised that the transport was a decoy, so I suppose in the end it succeeded/failed the right way but that message when the plundered escort was rather confusing and disconcerting.

Also, what does the message that the crew of the transport doesn't need the 71k credits anymore mean - they obviously survived if they can fly the ship when it re-activates.

**Comment by amylaar** [comment]
There also seems to be a "get" missing in Kex's dialogue: "Let me see if I can this open."

**Comment by bobbens** [comment]
Thanks, should be fixed in main!
