### ISSUE TITLE
[Proposal] Buff/debuff (effect) system

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1820]
Currently it is very hard to implement affecting the target with special effects. Things like damage-over-time weapons and the likes or missiles that slow the enemy down just can't be implemented. This could be implemented easily by the following:

1. Create effects that would consist of shipstats + duration and other properties like maximum stacks that can be applied (or shared stack type) or whether or not the effect is based on the weapon damage or something like that
2. Allow weapons to apply effects on hit (or on shoot)
3. Pilot would apply all effects on calcstats, and would run timers to see when to get rid of an effect and re-apply it

Main issue I can think of:
1. How to make this visible to the player? Not only should we show it in the GUI, but we should also show other pilots afflicted with this

Usage cases I can think of:
* snare missiles that slow down enemies
* give plasma weapons a damage over time component (so like 50% damage up-front and 70% of damage over time)
* weapons that drain energy
* ships that apply auras and buff/debuff nearby ships

**Comment by Lineth** [comment]
- To shamelessly crib from Endless Sky which IMO has a good implementation of certain status effects, the anti-energy effect (say, tesla/electrical damage) would be represented by the affected ship being covered in blue sparks, and maybe the GUI shows a red bar on the side of the energy indicator to represent at a glace that your heavily electrified and are regenerating energy slowly.

- Snare missiles I think can be balanced rather easily by having a static debuff that doesn't stack. Alternatively, have it increase the target's effective mass, compromising its mass limit.

- I'm in favor of the Soromid's damage over time weapon be some kind of acid spitter/capsule launcher, with plasma heating a target ship's hull instead. Good for pirates/Sirius* who don't like an enemy who can fight back.



*On discord, me and bobbens talked about the Sirius being tanks that debuff their enemies' combat abilities could be a good gimmick for them and gives them some much-needed identity.

**Comment by V-ktor** [comment]
Add a bar above or somewhere below the health bar and display icons if debuffs are active? Ideally, there shouldn't be too many types of buffs/debuffs.
Another option would be to put those icons on top of the corresponding indicator, e.g. on top of the health bar for damage over time effects or on top of the velocity indicator for speed or mass debuffs.

**Comment by bobbens** [comment]
> Add a bar above or somewhere below the health bar and display icons if debuffs are active? Ideally, there shouldn't be too many types of buffs/debuffs.
> Another option would be to put those icons on top of the corresponding indicator, e.g. on top of the health bar for damage over time effects or on top of the velocity indicator for speed or mass debuffs.

Yeah, I don't really think there will be too many. I think the bar with icons is probably the most flexible and simple way to do it. If there are very few we might be able to get away with just adding animations ontop of the ship, but that will probably be harder to understand.

**Comment by PhoenixRiver** [comment]
If we're careful about the buffs/debuff added then the icon bar could
have inverted icons for matched pairs of debuffs/buffs e.g. the slow
missile be a mirror of a putting nitro in the engine buff, damage over
time being mirrored with a nanobot swarm repairing damage, plasma
adding heat vs opening the engine up to vacuum while it's running
(which could potentially cause an increase in damage and/or reduction
in power/speed - which is why pilots don't run with it that way all
the time... i.e. balance)...

Anyway, probably enough examples but it doubles the number of effects
without doubling the complexity of the UI; historically I know such a
system would use red and green icons to differentiate but maybe light
blue and orange might be a better choice since these are modifiers
rather than critical (per se) and avoids red/green colourblindess
issues... alternatively or in addition one could be struck through
diagonally to indicate it being the opposite effect.

Hope this helps,

Phoenix

**Comment by bobbens** [comment]
![screenshot028](https://user-images.githubusercontent.com/54677/146673372-93de09c9-bcd8-4951-81ba-6130a76f2fe1.png)
Initial implementation is done as shown in the screenshot (Soromid Arx ship getting **Blood Lust** buff after biting an enemy ship). You can see the icon appearing to the left of the "UST" time display. Seems to work fine, but still has to be hooked into the weapon systems (right now only triggered from active outfits or events). I'll leave this open until at least the weapon stuff is solved. I think making all plasma weapons give a damage over time effect seems like a good way to go.

#### Some Notes:
1. It might also make sense to make the system stuff be treated as an effect instead of invisible modifier to make it more clear to the player
2. Instead of having some hardcoded weapon effect, might make sense to just allow running Lua code on weapon hit as that would also allow doing a lot more fancy things.
3. Might need a simple way to parametrize or override buffs to allow for complicated effects without having to add a dozen effect definitions.
4. Still have to implement ship visuals, most likely done via custom shaders. However, probably would make more sense to move to 3D first and allow for 3D effects instead of only 2D effects via framebuffer magic.

**Comment by bobbens** [comment]
Solved most of the remaining issues.
