### ISSUE TITLE
internal lua missing in tarball for 0.8.2

### ISSUE THREAD

**Issue by hfiguiere** [naev/naev#1827]
The tarball is missing lua. That's because the `DIST_SUBDIRS` is made conditional. (branch 0.8.x)

See:
https://github.com/naev/naev/blob/0.8.x/lib/Makefile.am

`DIST_SUBDIRS` should have both `lua` and `csparse` unconditionally. That's what `DIST_SUBDIRS` is for. Otherwise these never get disted if you have system that doesn't use them.

Use case: building on `aarch64` where luajit doesn't exist.

**Comment by UncombedCoconut** [comment]
Oof, that's a shame. Good catch.
Fair warning: the 0.8 series is essentially done. Even if we commit a fix, I'm not sure if we'll ever end up tagging 0.8.3 with a fixed distribution.
Development versions of Naev exclusively use Meson.
The lib/lua directory is supposed to contain standard Lua 5.1 sources. Could an external package work for this use case?
I'll also note that the latest LuaJIT does support aarch64, albeit not in an official 2.0 or 2.1-beta release. (The main developer has an [interesting attitude](https://github.com/LuaJIT/LuaJIT/issues/665#issuecomment-784452583) toward releases.)

Thank you for pointing out this Flathub project. There may be things the Naev team can do to make an 0.9 release support Flatpak more directly.

**Comment by hfiguiere** [comment]
Our (for the flatpak) workaround is to pull the tagged tree from git.

**Comment by UncombedCoconut** [comment]
Closing this as version 0.9.0-beta is nearly ready. Thanks for reporting, though!
