### ISSUE TITLE
Give shipyard better ship images

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1835]
Best approach would be to probably rerender at a nice angle (or give custom beauty shots), and in the case we can't do that due to missing models, just reuse the comm image.

**Comment by Lineth** [comment]
Certain ships (Like the Mephisto) will probably have to be remade entirely as the comm image sucks and the model is missing.

**Comment by bobbens** [comment]
Set the shipyard to use the comm images when you click on a specific ship. Don't think it's necessary to have separate comm / shipyard images, but I do think it would be nice to have prettier comm images for this purpose.

**Comment by bobbens** [comment]
Solved by 3D ships (for those with 3D ships.
