### ISSUE TITLE
The mission cannot be finished --- Warning: [outfit_get] Outfit 'S&K Ultralight Stealth Plating' not found in stack.

### ISSUE THREAD

**Issue by universe-11** [naev/naev#1845]
Running using:
naev-0.9.0-alpha.1+314.g26c8b95a5.20210622-linux-x86-64.AppImage

Output:
Warning: [ai_run] Pilot 'Kono Purple Kami' ai error: attempt to call a nil value
Warning: [outfit_get] Outfit 'S&K Ultralight Stealth Plating' not found in stack.
Warning: [misn_runFunc] Mission 'The Last Detail' -> 'enter': [string "missions/shark/sh07_pirates.lua"]:195: Outfit is invalid.
Warning: [hook_runMisn] Hook [enter] '1214' -> 'enter' failed
Warning: [ai_run] Pilot 'Kono Purple Kami' ai error: attempt to call a nil value
AL lib: (WW) FreeDevice: (0x1ff4700) Deleting 148 Buffer(s)

Possible fix:
------------ change to 
      baddie:addOutfit("S&K Ultralight Combat Plating")

Result:
The mission can be finished.

**Comment by nenau-again** [comment]
The changes due to the recent rebalancing have not fully (not at all?) been reported to the missions yet. I will try and take care of this campaign this WE.

If you really want to finish the mission today, your suggested fix should do the job.

**Comment by bobbens** [comment]
I did use regex to fix most of them, however, I must have missed a few cases. I have pushed a fix to these. What worries me a bit is the `Warning: [ai_run] Pilot 'Kono Purple Kami' ai error: attempt to call a nil value` seems unrelated to the outfit issue :/.

**Comment by bobbens** [comment]
Some similar AI issues were fixed recently, and the main issue seems fixed so closing issue. Thanks!
