### ISSUE TITLE
Clicking on equipment screen crashes the game

### ISSUE THREAD

**Issue by SlightPersimmon1** [naev/naev#1848]
Clicking on equipment screen crashes the game.
Version: naev-0.9.0-alpha.1+533.gf2ef0dd29.20210703-win64

**Comment by SlightPersimmon1** [comment]
After a clean install of naev-0.9.0-alpha.1+533.gf2ef0dd29.20210703-win64, the issue no longer appears. 

You can close the issue. Thanks.

**Comment by UncombedCoconut** [comment]
Whew! Thanks for the update.
