### ISSUE TITLE
Aborting the Crimson Gauntlet should put the player back on Totoran in a normal state.

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1850]
Split off from #1849. If you start the Crimson gauntlet, open the Info dialog, and abort the mission, you wind up with an open/hidden Info dialogue. (The `i` key does nothing until you take off or re-enter the Crimson gauntlet; as soon as you do so, you'll see the dialogue already open.)
This is so surprising that even we expected it not to happen. :)

**Comment by bobbens** [comment]
I think this should be fixed with a4018aaa89967e86e91a5b0e804c4b8485fece57 . Basically just assume that land window should always be the bottom and lower it when creating. Probably should fix other weird corner cases of landing with the VN open and stuff.
