### ISSUE TITLE
Add support for creating "naked" ships

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1856]
In order to avoid calling the optimization stuff twice when manually equipping ships, and all around make it a smoother experience, we should add an option to create "naked" or unequipped ships. Now, `pilot.add` is getting fairly bloated, so at the same time, we should probably change the optional parameters and make it a table of optional parameters. As discussed on IRC, the best bet is something like:
```
pilot.add( "Llama", "Pirate", nil, { ai="pirate", naked=true, name="Beef Jerky" } )
```
Where ai and name would substitute the optional parameters of AI and name, and naked would be the new parameter.

**Comment by UncombedCoconut** [comment]
Actually didn't move the name over (and it's doable), but decided on Discord that one isn't a big deal.
