### ISSUE TITLE
[Proposal] Simplifying ship classification and names

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1860]
One thing that has bugging me a lot is that there are perhaps too many ship types in Naev. Looking at the original designs. We see that we have the following:
* Military Ships
  * Heavy
    * Carrier
    * Cruiser
  * Medium 
    * Destroyer
    * Corvette
  * Small
    * Fighter
    * Bomber
    * Scout
* Merchant
  * _Bulk Freighter (Large)_
  * Freighter (Medium)
  * Courier (Small)
* Civilian
  * _Cruise Ship (Medium)_
  * Luxury Yacht (Small)
  * Yacht (Small)
* Robotic
  * _Mothership (Large)_
  * Heavy Drone (Medium) (Note: the "Heavy Drone" in-game is actually a small ship)
  * Drone (Small)

Classes in italics have no ships in-game. In particular, the following are things that I think are maybe not ideal:
1. Not sure if we need to distinguish Robotic from Military. They probably could be merged. This would also solve the "ship names overlap with ship categories" issue that the "Drone" and "Heavy Drone" have.
2. Not entirely sure we need to distinguish civilian from merchant. While Luxury Yacht is used in the sightseeing mission, I do think we could just have a Lua list of ships we consider to be luxurious. I don't think there is any other usage case for luxury yachts atm.
3. It's not entirely clear if we do need scouts as a distinguished type. Currently, it does not seem like they have anything really to offer over just calling them fighters. The only thing I can think of is that it gives an easier way for the AI to know if it should fight and run.

My proposal is to:
1. Merge robotic into military (drone -> fighter, heavy drone -> corvette, mothership -> carrier)
2. Merge civilian into merchant (yachts -> courier, cruise ship -> freighter, and adding special treatment for Gawain as luxury yacht in certain missions)
3. Try to get a bulk freighter added into the game

**Comment by nenau-again** [comment]
I agree some work has to be done on ship classes, and most of your propositions seem good to me. However :

* Shouldn't the heavy drone rather be a heavy fighter? Otherwise, one would have to revise its characteristic, as well as those of the Za'lek one.
* Speaking of hvy fighters, should this class be added?
* I'm not sold to the idea of merging the scout with the fighter. Their characteristics are very different (more weapon slots and sometimes more shield for the fighter, more fuel, stealth and detection for the scout, as well as instant jump). Both are very quick, but that's not enough for making them a single class. Unless we somehow put the sensors and scramblers and such in the weapon slots, and make it so that the same ships can be used as stealth fighters or scouts?

**Comment by bobbens** [comment]
> * Shouldn't the heavy drone rather be a heavy fighter? Otherwise, one would have to revise its characteristic, as well as those of the Za'lek one.

In the original classification, the idea was to have a class for small / medium / heavy ships. Heavy drone was meant to be a medium class ship, which otherwise the robots don't have. However, we don't currently have a heavy fighter class.

It is a bit of a tangent, but I do think the "Heavy Drone" should be a corvette, just so that the collective doesn't consist of fighters.

> * Speaking of hvy fighters, should this class be added?

This could be added and would make more clear the distinction between a Hyena and a Lancelot. I think it could be a good idea, but it also opens up the question to whether or not we should split "Light Cruiser" from "Heavy Cruiser" with different classes. The difference between a "Kestrel" and a "Goddard" is the same or more than a "Hyena" and a "Lancelot".

> * I'm not sold to the idea of merging the scout with the fighter. Their characteristics are very different (more weapon slots and sometimes more shield for the fighter, more fuel, stealth and detection for the scout, as well as instant jump). Both are very quick, but that's not enough for making them a single class. Unless we somehow put the sensors and scramblers and such in the weapon slots, and make it so that the same ships can be used as stealth fighters or scouts?

Well the main argument I can think of merging is that there only are two scouts in the game: schrodinger and thurion perspicacity, with the later being more of a mislabeling because it is basically a light fighter. However, as you say, it is nice to have them different which is why **I don't propose to merge them**, because mainly from an AI point of view we want to have a clear distinction between ships that fight (fighters, etc.) and those that don't (scouts, freighters, etc.). Furthermore, I think that if the player ends up able to control fleets properly, scouts can be fitted to play important roles which don't really make sense when they are alone.

**Comment by bobbens** [comment]
Just a stray thought, instead of "Light Fighter" and "Heavy Fighter", something like "Interceptor" and "Fighter" could be better.

**Comment by bobbens** [comment]
Thinking about implementing this with the added distinction between "Interceptor" (Light Fighter) and "Fighter", plus "Cruiser" and "Battleship" (Heavy Cruiser)". Not entirely sure on the name for heavy cruiser. Mainly doubting between "Dreadnought" and "Battleship".

**Comment by bobbens** [comment]
Ok, have this implemented in a branch, will probably merge soon (tm). Ended up not removing "yacht" as it seems to make sense not to get rid of it.

**Comment by bobbens** [comment]
Merged into use_lanes.
