### ISSUE TITLE
[Proposal] System Objects

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1862]
Thinking about how to implement hypergates, I thought that instead of implementing a one-off feature, it might be better to try to do a more general framework that would not only allow hypergates, but all sorts of other in-system objects. We already have the background script which can be used as a base for this.

### Issue
We need to implement hypergates for all the main lore ideas, and this could also be used to create a more flavourful and interesting universe.

### Core Idea
0. Use the current system background stuff as a base.
1. Systems will be able to have an arbitrary number of system objects
2. Each object would consist of a Lua script that would be able to bind the following
   1. Rendering (foreground/background, already in background script)
   2. Updating (already in background script)
   3. Landing
   4. Boarding
   5. Other more general input
3. Objects would be spawned when the player enters the system and would have an API to indicate what they are identified as (asset, ship, none, etc.).
4. Objects would be able to choose how they appear on the mini-map (and if they appear or not)

### Notes
1. Overall this will be more or less like a custom event and background mixed together per system: we get the advantages of being background (runs in the main menu too!), and lots of API like if it were an event.
2. This will not allow for autonav shenanigans, but that might not be a bad thing.
3. Given that we can use the background stuff as a base, I do not think it should be too hard to implement fully.

### Alternatives
1. Implement input stuff directly into the background scripts. Downside is that it becomes harder to mix and match. Proposed approach is very similar though, you can think of it as modifying the background stuff to be not limited to one per system, which shouldn't be too hard to do.
2. Implement this by adding the input API to events. The upside here is you get to use the hook framework, but the downside is that it will only work when the player exists and not on the background of the main menu.
3. Make hypergates their own thing and tightly integrate into the autonav system. #1252 is based on this. While a potentially good option, downsides are it makes hypergates more of a normal and well integrated thing, and not really something special. Probably will also have a ton of unintended consequences. The proposed approach could probably also handle this by adding hypergate-specific API if necessary.

### Other possible usages
1. Have the player find large and impressive derelicts of the original colony ships
2. Wormholes
3. Blackholes

**Comment by UncombedCoconut** [comment]
This is likely to interact with safelanes. The end result should be positive if we do this right. Basically we need:
- ability to list all of them in a system
- they all have a loc (duh), and some indicator of "who wants to go here" (which factions might make it a lane endpoint).
- some common understanding of when an object links to an object in 1+ other system(s).

Probably come back to this point when hypergates are specced out more. What kind of questions *are* there to ask about a link-type system object?

**Comment by bobbens** [comment]
That's a good point. I was originally thinking of having it separate from backgrounds, and the fact it is localized is probably enough of a reason to implement them separately from the background stuff.
