### ISSUE TITLE
[Proposal] Uninhabited Frontier

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1866]
### Issue
Naev's universe is fairly heavily populated. Except for some areas between the major factions, most places are really crowded and filled with ships. There are no real places where the player can sort of explore or get away from all the hubbub.

### Core Idea
Add an uninhabited (and potentially dangerous) edge of systems around the current systems. This is something that you could see in original Escape Velocity that it did very well. These systems could serve lots of purposes such as pirate hideouts, garbage dumps, wormholes, discoveries, etc.

![Original EV map](https://i.redd.it/1yuqgzzeksq51.png)

### Implementation
Just straight forward adding roughly 2-3 system deep layer of systems around the existing populated systems. This would just be a rule of thumb and it should be shallower in some places and deeper in others. Universe Editor should allow for doing this easily, but probably could use a random name generator or random system generator to try to make it less of a pain.

### Potential Issues
1. Lore behind why they are uninhabited. Lack of resources and population?
2. Might slow down universe-wide computations unless we add some heuristics to ignore them such as economy and safe lanes (#897 )

### Other Thoughts
1. Presence and spawning should be rethought too to make systems a bit less crowded after #897 is implemented

### Related Issues
1. #1863 
2. #1859 
3. #1843

**Comment by bobbens** [comment]
Some new systems have been added near the empire area, however, there is a real concern that this will slow down the safe lane computations. I have seen a slow down from 0.34 s to about 0.38 s with the addition of only like 10 systems. Adding a few hundred (likely the number that would be needed) might require us to add some sort of new heuristics to handle this.

**Comment by bobbens** [comment]
Did a large new area around the Za'lek space. Still needs to be made more interesting (tm).

**Comment by PhoenixRiver** [comment]
> Some new systems have been added near the empire area, however, there is a
> real concern that this will slow down the safe lane computations. I have
> seen a slow down from 0.34 s to about 0.38 s with the addition of only like
> 10 systems. Adding a few hundred (likely the number that would be needed)
> might require us to add some sort of new heuristics to handle this.

From the sound of these systems I wouldn't expect safelanes... can
they not be turned off for these systems? I wouldn't have expected
them for The Nebula systems either ;) - which might even save some
time if they are currently being computed :)

Phoenix

**Comment by bobbens** [comment]
> From the sound of these systems I wouldn't expect safelanes... can they not be turned off for these systems? I wouldn't have expected them for The Nebula systems either ;) - which might even save some time if they are currently being computed :) 

That's one option on the table: add an explicit flag to disable these systems from being used in the safe lane computation, it's probably easiest but requires more manual work. Ideally we would want the safe lane system to automatically take this into account without additional flags to make it easier to maintain. I guess some fancier heuristics might be able to handle this.

**Comment by PhoenixRiver** [comment]
> That's one option on the table: add an explicit flag to disable these
> systems from being used in the safe lane computation, it's probably easiest
> but requires more manual work. Ideally we would want the safe lane system to
> automatically take this into account without additional flags to make it
> easier to maintain. I guess some fancier heuristics might be able to handle
> this.

Distance from an empires capital? Maybe moderated by their militancy
(and thus ability to maintain safe lanes)? Could semi-safe lanes exist
(essentially as a warning to the player that they are getting into
"here be dragons" territory much beyond) - maybe the last leg of a
safe lane before it goes no further?

This way you'd only have to mark capitals which would probably be
useful to mark anyway...

Or else have safelanes use the amount of traffic / influence
(excluding pirates and any other group that wouldn't bother making
"safelanes" - Rebels? Borg?) in a system to decide whether to include
it? That might require a bit of balancing what already exists
though...

Hope thi helps,

Phoenix

**Comment by PhoenixRiver** [comment]
I have to say I like that the EV map has a Independant States buffer between the Confederation and the Rebels... with the current situation in Europe and with Russia I feel like we could do with more of a buffer between The Empire and the Rebels (Dvaered), maybe just another couple of Minor Houses but they could be trader ones and resistant to Dvaered and Empire control but the Empire and Dvaered concentrating on these important (to them) systems could explain the lack of attention they have paid to systems on their "outside" border. The fact Sirius and Dvaered Houses are also butt up to each other and are near the FLF which could explain their lack of desire to put resources towards potentially long unprofitable new colonies when they might loose the already built up ones they have... the Frontier might be interested in expanding but is surround by Houses and the Nebula, the Za'lek aren't really that way inclined, more interested in robotic exploration I guess, no need for colonies... and so I guess the Soromid (who already look pretty extended) would be the only ones with any interest but appear to already doing so but with a smaller population base to start from and a more organic growth are likely to be slower and are probably still building up their current territory - they may also have been stymied by the Collective up to a point.

How is that for some Lore explaining the lack of expansion into the galaxy?
I have a couple of systems I'd like to add to that more remote par of the galaxy somewhere near the Soromid... it is a kind of Soromid extremist outpost where they are developing the tech to (more) quickly terraform asteroids to become homes and turn small ones into carrier ships... what they might want to do with those is anyones guess but the Soromid do look a little overstretched and these guys are extremists but then again they are biologists... maybe they are angling to replicate the Za'lek spread so as to become a force in their own right... especially _after_ the Collective...

Thoughts?

**Comment by bobbens** [comment]
> How is that for some Lore explaining the lack of expansion into the galaxy?

Honestly, if I were doing it again, The main thing I dislike is that only some 20ish years have passed since the incident which ripped the galaxy in half and caused a lot of people to move and rehome, and it doesn't really feel too much like that. My main things I don't like is that the Empire should probably be closest to the Nebula (they had Sol and surroundings when it happened). It also doesn't really feel like a lot of people have had to move a lot.

That said, I like to think of the galaxy as being boxed in by various phenomena such as voids, gigantic black holes, pulsars, etc... which explain why people aren't expanding infinitely. Most of my uninhabited frontier changes go in that direction (haze for Soromid, plasma storms for Sirius, black hole for za'lek, etc.). These phenomena either make expansion impossible, or extremely difficult, thus halting expansion.

That said, I wouldn't be against adding spreading out things a bit more and adding more buffer zones with more independent spobs. However, I do feel that it should be possible to get much better effect and make the systems feel more unique and interesting instead of just expanding everything. Things like single-system phenomena, unique happenings in systems (like the new restricted ones), more discoveries, more wormholes, etc. do make things more interesting. I would especially like to see stuff that is just lore-related, like weird deformed planets, small black holes pulling in stars, unique asteroid fields, etc. It could be interesting to let the player scan stuff and get entries in the naev encyclopedia unlocked when implemented. Some missions could even require the player to do that and could create new random things to scan dynamically.

**Comment by amylaar** [comment]
How about we give an excuse in the lore for Naev being a 2D-game?  Namely, we could say that hypergates can only exist
in a plane that happens to intersect the galaxy and did some whacky things to allow FTL flight without leading to time paradoxes.

Now, what if another plane, roughly perpendicular to the known one, appeared or were discovered?  Maybe it has different properties so that its hypergates were only able to be discovered recently with new technology.  Or its existance, or it intersecting with the known hyperspace travel plane, is a result of the incident.

**Comment by bobbens** [comment]
Lots has been added in this direction, I think it is probably safe to close this issue and open smaller ones as needed.
