### ISSUE TITLE
Create outfit upgrade script for 0.8.x -> 0.9.0 transition

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1867]
To be nice to users, we should create an outfit upgrade scrip to try to rename outfits as necessary, and give money in the case they were totally removed. Main tricky part is this will have to be mainly C-side due to the fact the outfits don't exist when being loaded.

**Comment by osetrovich** [comment]
Maybe I can help.
If you point up what and how should be replaced, I may handle it.

**Comment by bobbens** [comment]
> Maybe I can help.
> If you point up what and how should be replaced, I may handle it.

Thanks for the offer! What has to be done is we need a Lua script that maps old outfit names to new outfit names or credit amounts in the case there is no equivalent. It should be something like:
```lua
local outfit_replacements = {
   ["Fuel Pod"] = "Small Fuel Pod", -- Straight forward naming case
   ["Solar Panel"] = 25e3, -- Credit amount in 0.8.2 as there is no alternative
}
```
Although outfits may still change a bit, I don't expect too large shuffles anymore. So it would be necessary to manually compare 0.8.x outfits with main outfits. Once we have the list as above, it should be fairly straight-forward to integrate it in-game to automatically translate not found outfits or give money. I can do the C-side stuff, but would need the Lua list.

If it's easier, I'm attaching csv versions of the outfits of current main and 0.8.2. It might be easier than going through data files manually.

[outfits-2021-07-18.csv](https://github.com/naev/naev/files/6836008/outfits-2021-07-18.csv)
[outfits-0.8.2.csv](https://github.com/naev/naev/files/6836009/outfits-0.8.2.csv)

**Comment by bobbens** [comment]
Implemented support for this C-side. Just have to populate the table in `dat/save_updater.lua`.

**Comment by ProjectSynchro** [comment]
The table in `dat/save_updater.lua` is now populated as of: https://github.com/naev/naev/commit/632b69015c3bf61c21a9a4c3d9acdd283106b6a1.

Hopefully all the mappings are okay, but if not blame me :sweat_smile:
