### ISSUE TITLE
meson build fails on Fedora 33 with: ERROR: Requested variable "SuiteSparse_dep" not found

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1874]
After installing the new dependencies as listed on the Fedora section of https://github.com/naev/naev/wiki/Compiling-on-*nix ,
I got an error:
meson.build:148:9: ERROR: Problem encountered: Failed to find an installation of c[x]sparse. See above note about SuiteSparse.

The 'note' a referred there was, I assume:

Message: Note: Naev needs the following SuiteSparse libraries: amd, colamd, cholmod, and either csparse or cxsparse. It can use its own copies if you run "meson configure --force-fallback-for=SuiteSparse".

I got rid of my old build dir and tried that, and that didn't help at all. I.e. when running 'meson build' after that configure
command, I get the same error again.  I tried to add the option to meson build, i.e.
"meson build --force-fallback-for=SuiteSparse" , which gives me a new error:
Has header "glpk.h" : YES 
Library glpk found: YES

|Executing subproject SuiteSparse method meson 
|
|Project name: SuiteSparse
|Project version: undefined
|Library m found: YES
|Build targets in project: 5
|Subproject SuiteSparse finished.

meson.build:166:6: ERROR: Requested variable "SuiteSparse_dep" not found.

**Comment by UncombedCoconut** [comment]
I don't know what "meson build --force-fallback-for=SuiteSparse" is supposed to do.
Can you try:
`meson configure --force-fallback-for=SuiteSparse`
`meson configure --clearcache  # out of superstition, not for real reasons :)`
`meson compile`
and let us know what happens?

**Comment by amylaar** [comment]
> I don't know what "meson build --force-fallback-for=SuiteSparse" is supposed to do.
> Can you try:
> `meson configure --force-fallback-for=SuiteSparse`
> `meson configure --clearcache # out of superstition, not for real reasons :)`
> `meson compile`
> and let us know what happens?
 
WARNING: The source directory instead of the build directory was specified.
WARNING: Only the default values for the project are printed, and all command line parameters are ignored.
[amylaar@localhost naev]$ meson compile

ERROR: Current directory is not a meson build directory: `/home/amylaar/naev`.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.
[amylaar@localhost naev]$ cd build
[amylaar@localhost build]$ meson compile

ERROR: Current directory is not a meson build directory: `/home/amylaar/naev/build`.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.

**Comment by amylaar** [comment]
I also encountered the same problem on a Fedora 34 system, and there I tried to additionally install suitesparse (was already installed) and then suitesparse-devel.  That got me past the SuiteSparse issue without new configure options, only to get to another error:
[amylaar@damia naev]$ meson build 
The Meson build system
Version: 0.56.2
Source dir: /home/amylaar/naev
Build dir: /home/amylaar/naev/build
Build type: native build
Project name: naev
Project version: 0.9.0-alpha.1
C compiler for the host machine: cc (gcc 11.1.1 "cc (GCC) 11.1.1 20210531 (Red Hat 11.1.1-3)")
C linker for the host machine: cc ld.bfd 2.35.1-41
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program build/gen_version.sh found: YES (/home/amylaar/naev/utils/build/gen_version.sh)
Program utils/build/add_to_package.sh found: YES (/bin/sh /home/amylaar/naev/utils/build/add_to_package.sh)
Program doxygen found: NO
Program dot found: NO
Program ldoc found: NO
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency sdl2 found: YES 2.0.14
Run-time dependency sdl2_image found: YES 2.0.5
Run-time dependency libxml-2.0 found: YES 2.9.12
Run-time dependency physfs found: YES 3.0.2
Run-time dependency freetype2 found: YES 23.4.17
Run-time dependency libpng found: YES 1.6.37
Run-time dependency libwebp found: YES 1.2.0
Run-time dependency luajit found: YES 2.1.0-beta3
Has header "glpk.h" : YES 
Library glpk found: YES
Message: Note: Naev needs the following SuiteSparse libraries: amd, colamd, cholmod, and either csparse or cxsparse. It can use its own copies if you run "meson configure --force-fallback-for=SuiteSparse".
Library csparse found: NO
Library cxsparse found: YES
Has header "suitesparse/cs.h" : YES 
Library cholmod found: YES
Has header "suitesparse/cholmod.h" : YES 
Library amd found: YES
Library ccolamd found: YES
Library colamd found: YES
Library lapack found: NO
Library metis found: NO
Library suitesparseconfig found: YES

meson.build:174:6: ERROR: C shared or static library 'openblas' not found

**Comment by amylaar** [comment]
> meson.build:174:6: ERROR: C shared or static library 'openblas' not found

Fixed that by installing openblas-devel (openblas was already installed).

**Comment by nenau-again** [comment]
Now that you've solved your openblas problem, do you manage to compile? If not, what is the next error?

**Comment by UncombedCoconut** [comment]
> > I don't know what "meson build --force-fallback-for=SuiteSparse" is supposed to do.
> > Can you try:
> > `meson configure --force-fallback-for=SuiteSparse`
> > `meson configure --clearcache # out of superstition, not for real reasons :)`
> > `meson compile`
> > and let us know what happens?
> 
> WARNING: The source directory instead of the build directory was specified.
> WARNING: Only the default values for the project are printed, and all command line parameters are ignored.
> [amylaar@localhost naev]$ meson compile
> 
> ERROR: Current directory is not a meson build directory: `/home/amylaar/naev`.
> Please specify a valid build dir or change the working directory to it.
> It is also possible that the build directory was generated with an old
> meson version. Please regenerate it in this case.
> [amylaar@localhost naev]$ cd build
> [amylaar@localhost build]$ meson compile
> 
> ERROR: Current directory is not a meson build directory: `/home/amylaar/naev/build`.
> Please specify a valid build dir or change the working directory to it.
> It is also possible that the build directory was generated with an old
> meson version. Please regenerate it in this case.

As the error message says, it's a mistake to try `meson configure` before you `cd` into the build directory, i.e. the directory specified in the initial `meson setup` command (which is the only commonly used one that's run from the source dir).
However, it looks like some aggravating factors are confusing the situation:

- Meson does honor `meson build`... as a shortcut for `meson setup build .`. So any comments about `meson setup` commands apply to that one.
- Although this means `~/naev/build` is your build dir, `meson` commands may not work inside it until the `meson setup` command (disguised or otherwise) has succeeded at least once. Until then, it must be repaired with `meson setup --wipe build [options]` or by deleting and starting over.

It's a bit tricky to write recovery instructions for every type of broken Meson build. We can probably do better. We can also delete the phrase `meson build` from all Naev documentation to minimize confusion.

**Comment by amylaar** [comment]
> Now that you've solved your openblas problem, do you manage to compile? If not, what is the next error?

You, I did (just on the Fedora 34 system, I left the Fedora 33 one for now).

**Comment by bobbens** [comment]
Seems to be mainly dealt with. Closing, thanks!
