### ISSUE TITLE
Get 3D ships ready for use!

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1894]
# Getting started

Naev will use a 3D ship model for rendering if it's found in the game data.
Because the feature isn't ready for prime time, your `naev/artwork` initially won't contain these models.
You can set them up as follows:

```bash
[naev]$ cd ../naev-artwork/3D
[3D]$ BLENDER=blender-2.7 ./export2obj.sh
[3D]$ cd ../../naev/artwork/gfx/ship
[ship]$ # optionally, edit update.sh to skip the 3 .webp files in copy_over()
[ship]$ ./update.sh
```

# Missing graphical features

- [x] Material: map_Ke
- [x] Material: map_Ks
- [ ] Material: map_Tr
- [ ] Material: map_\* -s ... (texture scaling)
- [ ] Lighting: in the `naev-artwork` repo, `3D/render.py` sets the light sources for all spritesheet renders. There are ambitions to clean that up too; regardless, Naev's `material` shader should be consistent.

# Missing integration features

- [x] Merge https://github.com/ids1024/naev-model-view into utils/ and have it share GLSL code with Naev
- [x] Update all Naev code currently accessing the spritesheets so they can also use the model
- [x] Bypass spritesheet loading at startup if the model 
- [ ] Reduce log spam: like other subsystems, we should emit 
- [ ] Use 3D models for stations/hypergates as well
- [x] Integrated engine-glow / trail coloration
- [x] Integrated engine-glow / trail positioning; also, use the z-value "for real" so the GL depth test can properly decide what's drawn on top
- [x] A quick and dirty object-wide scissor test was added to object.c; fix it.
- [x] Generate collision polygons from the models instead of the sprites
- [ ] Maybe: review the size/sprite-dim values in `naev-artwork/3D/dim.sh` and `naev/dat/ship/*.xml` for redundant or unused data
- [ ] Maybe: introduce Emperor's Wrath as a flyable ship. Previously, the necessary spritesheet size was prohibitive
- [ ] Future: raytracing / dynamic lighting, blinky lights, procedural damage maps, bump mapping, fancier lighting, animated parts, fancy effects for ships falling apart in explosions / getting pierced by beams/bolts

# Models to fix

- [x] These models embed broken references to texture images on some Vega Strike developer's file system:  archimedes, derivative, rhino, rhino_pirate, vigilance, vigilance_dvaered, watson. The textures are still available, but it's unclear if they're truly used. We should strip out textures that aren't used in rendering.
- [x] Ditto `viper[1-5]`, though they aren't used.
- [x] Similarly, `kahan` references `m:/NATHAN/TRAVAUX PERSO/3D/AACOMPLETFILE/kahan/KAHAN copie.png` which might be available in the Vega Strike Assets-Masters repo.... or useless. In this case it's unclear which file matches this one.
- [x] All 3 phalanx models refer to `C:/Users/Ender/Desktop/dvaeredcorvetteSTAGE3_Cube.tga`.
- [x] `vendetta_dvaered` - where'd the coloration go?
- [x] (per Bobbens): dvaered goddard has trails off in 3D, meaning the model isn't exactly the same as the spritesheet position-wise
- [ ] Nonexistent models: https://github.com/naev/naev-artwork/issues/8

# Models to test

Note: Thurion and Sirius are initially getting the worst results due to missing graphical features described above.

- [ ] admonisher
- [ ] admonisher_empire
- [ ] admonisher_pirate
- [ ] ancestor
- [ ] ancestor_dvaered
- [ ] ancestor_pirate
- [ ] apprehension
- [ ] archimedes
- [ ] arx
- [ ] certitude
- [ ] derivative
- [ ] zalek_diablo
- [ ] divinity
- [ ] dogma
- [ ] drone
- [ ] zalek_drone_heavy
- [ ] fidelity
- [ ] gawain
- [ ] goddard_dvaered
- [ ] goddard
- [ ] hawking_empire
- [ ] hawking
- [ ] zalek_hephaestus
- [ ] hyena
- [ ] ira
- [ ] kahan
- [ ] kestrel
- [ ] kestrel_pirate
- [ ] koala
- [ ] lancelot_empire
- [ ] lancelot
- [ ] llama
- [ ] marauder
- [ ] zalek_mephisto
- [ ] mule
- [ ] nyx
- [ ] pacifier_empire
- [ ] pacifier
- [ ] peacemaker
- [ ] perspicacity
- [ ] phalanx_dvaered
- [ ] phalanx
- [ ] phalanx_pirate
- [ ] preacher
- [ ] quicksilver
- [ ] reaver
- [ ] rhino_pirate
- [ ] rhino
- [ ] schroedinger
- [ ] scintillation
- [ ] shaman
- [ ] shark_empire
- [ ] shark_pirate
- [ ] shark
- [ ] zalek_sting
- [ ] taciturnity
- [ ] vendetta_dvaered
- [ ] vendetta_pirate
- [ ] vendetta
- [ ] vigilance_dvaered
- [ ] vigilance
- [ ] virtuosity
- [ ] watson

**Comment by UncombedCoconut** [comment]
History: #511, https://github.com/ids1024/naev-model-view, #1895.

**Comment by V-ktor** [comment]
My Thurion ship models should be fine. Which graphical features are missing? I guess missing glow is a problem for them.
Most other models I made are not suitable to be used in-game as they are high poly and not unwrapped yet. So it's probably a lot of work to make low poly versions with baked textures.

**Comment by UncombedCoconut** [comment]
> My Thurion ship models should be fine. Which graphical features are missing? I guess missing glow is a problem for them.
> Most other models I made are not suitable to be used in-game as they are high poly and not unwrapped yet. So it's probably a lot of work to make low poly versions with baked textures.

Right, it's a glow problem, and not the models' fault. Until the new code can handle `map_Ke` and `map_Ks` in materials, it will draw Thurion ships incorrectly. (They'll look extremely dark.)

Although the models aren't optimized for poly count, Naev seems to run OK when using them. I guess it helps that outer space scenes usually aren't packed full of ships. Of course, this could change if bobbens stages a battle royale in the Taiomi system with tons of explosions and debris everywhere. :)

**Comment by bobbens** [comment]
I'd like to point out that the thurion ships render fine, but there seems to be weird things in their materials. In particular for perspicacity we can see:
```
newmtl Material
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2
map_Bump fighter05_normal.webp
map_Kd fighter05_diffuse.webp
map_Ke fighter05_emission.webp
map_Ks fighter05_specular.webp
```
So this material is using an emission map, but `Ke` is set to 0.0. From what I understand of the equations, this should equate to no emission, because it is `Ke * map_Ke`.

Furthermore, another general problem is that the engine glow have ambient and diffuse components when they should probably be emission only. They look much better when changed by hand, and closer to what we see in the blender renders. We might have to rely on blender for the vertices and stuff like that and use hand-edited material definitions to get better results.

**Comment by bobbens** [comment]
Another issue is that to do proper bump mapping we need to compute a tangent frame for each vertex. This can be done when loading the object. Reference: https://learnopengl.com/Advanced-Lighting/Normal-Mapping

**Comment by UncombedCoconut** [comment]
Obvious in hindsight: there's also the issue of what should happen when two ships overlap in the plane. The current approach will show them pass right through each other, as they're all made of triangles with the same range of z coordinates. We probably just need to give each ship its own slice of the z axis, which its trails will inherit. Some caution is necessary to keep the order stable and to avoid round-off artifacts. (We'll have 24 significant bits to work with.)

**Comment by bobbens** [comment]
Simplest would be to just use `pilot->id * small_value`. Just have to make sure the small value ensures they don't clip. I don't think overflowing will be an issue but it can be handled if necessary by resetting id generator on player load/creation and/or lowering to the largest persistent id+1 when entering a system. Only issue I can think of with this last approach is that you might wind up in the weird situation where a mission had a pilot stored, and then due to ID reuse another pilot ends up with the same id and that causes the mission to do weird stuff, but that would likely only happen in bug cases.

**Comment by bobbens** [comment]
Might be a better topic for another issue, but 3D could probably be extended to missiles too. It would be nice to have the imperator / caeser missiles have blinking LEDs and such to be more visible. However, this is less important given the fact they are much smaller spritesheets.

**Comment by fra9000** [comment]
Hey, just a question here. Will this feature affect the minimum requirements? Planning to install NAEV on my MacOSX 10.4.11 iMac G3 CXE 700MHz, 2GB RAM, SSD and ATI Rage128 16MB VRAM. Will this still be possible on 0.10 version?. TY/BR

**Comment by UncombedCoconut** [comment]
> Hey, just a question here. Will this feature affect the minimum requirements? Planning to install NAEV on my MacOSX 10.4.11 iMac G3 CXE 700MHz, 2GB RAM, SSD and ATI Rage128 16MB VRAM. Will this still be possible on 0.10 version?. TY/BR

I've had and loved one of those (minus the SSD), but its age is going to catch up to it.
I'd expect Naev 0.7 to be the latest version portable to a machine with a Rage 128; 0.8 and up require newer than OpenGL 1.2.

**Comment by fra9000** [comment]
@UncombedCoconut Thanks for the quick reply. Could I perform any kind of source compilation of later versions to avoid usage of >1.2 of opengl? or anything you could deactivate as a graphic option skipping the more advanced effects as a change request for 0.10? Just trying :)

**Comment by bobbens** [comment]
OK, with 3D ships merged and most of the issues solved, I think we can close this issue and create new ones as necessary.
