### ISSUE TITLE
Line Breaking in Japanese language.

### ISSUE THREAD

**Issue by oo13** [naev/naev#1897]
Naev doesn't support the line-breaking in Japanese language, which is not the space-separated layout. I suggest Naev supports [Unicode Line Breaking Algorithm](https://unicode.org/reports/tr14/).

Naev does break a Japanese text into the lines, but I suspect it forces to break lines in order just to avoid overflow.

IMO, the following rules are enough to break lines in Japanese. Unicode Line Breaking Algorithm supports them.
- [Characters Not Starting a Line](https://www.w3.org/TR/2009/NOTE-jlreq-20090604/#en-subheading2_1_7)
- [Characters Not Ending a Line](https://www.w3.org/TR/2009/NOTE-jlreq-20090604/#en-subheading2_1_8)
- [Unbreakable Character Sequences](https://www.w3.org/TR/2009/NOTE-jlreq-20090604/#en-subheading2_1_10)

**Comment by bobbens** [comment]
Potential library that could handle this for us: https://github.com/adah1972/libunibreak

**Comment by bobbens** [comment]
Fixed in main! Thanks!
![unibreak](https://user-images.githubusercontent.com/54677/132853659-f58fcaf7-b1fe-4151-aea6-88acee7c4e7b.png)
