### ISSUE TITLE
Some texts are wrapped at the character one before a position ALLOWBREAK.

### ISSUE THREAD

**Issue by oo13** [naev/naev#1908]
This bug is introduced by a82f1ca87eea15b96c1526a305c6a4f43fbeed34.

The previous implementation results incorrect layout, because Unicode Line Breaking Algorithm (UAX #14) wraps a text after SPACE or NL but Naev expects there is SPACE or NL at the beginning of the line. For the line breaking, the previous implementation results currectly. By the way, there is a bug that the result of the width of the text is the shorter by one character, so some displayed texts overflow.

a82f1ca87eea15b96c1526a305c6a4f43fbeed34 causes proper vertical and horizontal layout, because there is SPACE or NL at the beginning of the line and it returns the right width of the line, but a82f1ca87eea15b96c1526a305c6a4f43fbeed34 may wrap at the character one before a position ALLOWBREAK.

**Comment by UncombedCoconut** [comment]
Hi! I'm looking to refactor all of Naev's line breaking code to be more robust and simpler to use.
However, there's a risk that l'll introduce bugs in the process, even the same ones you already fixed in PRs, because I don't have relevant test cases to look at. Is there a reasonable way for you to share examples of these recent problems? (I don't speak Japanese, but if I have the right po file / window size / screenshot, it's easy to compare the results.)

**Comment by oo13** [comment]
Thank you for the reply.
I should share a way to reproduce it.

OS: Linux
PO File: #1909
Fonts: https://www.dropbox.com/s/04fyvuk0tk2v8p5/japanese-fonts-for-naev.zip?dl=1
Screen Size: 1280x1024

Screen shot of the intro:
![naev_intro_ja_1280x1024](https://user-images.githubusercontent.com/22392249/133077252-c0676355-e573-4a4f-9fc3-bb1a6a6dec6a.jpg)

Japanese texts may break the line at almost any position, but it does not allow some characters to place at the beginning or the end of the line.

**Comment by UncombedCoconut** [comment]
Great, thank you! I think I know what we need to do now.

**Comment by UncombedCoconut** [comment]
Hi, I committed a change which "Should fix #1908." At that point, GitHub confidently closed the issue, though I'm not quite so certain.
Please feel free to reopen or add comments if anything is still amiss.

**Comment by oo13** [comment]
Thank you, the issue is fixed, but It seems the calculation of the text width is incorrect.
Should I open a new issue?

The first dialog in the tutorial mission:
![naev too wide tutorial](https://user-images.githubusercontent.com/22392249/133989454-095fe223-4f47-4766-9bba-86af16a08267.jpg)

A civilian speaks the following in a space bar:
![naev space bar dialog](https://user-images.githubusercontent.com/22392249/133989475-f0ae482f-4d83-4232-a4b5-3c9cd1d47a82.jpg)
The second and fourth lines have only one character.

The translation data:
```po
#: dat/events/neutral/npc.lua:79
msgid ""
"\"They say Eduard Manual Goddard is drifting in space somewhere, entombed "
"amidst a cache of his inventions! What I wouldn't give to rummage through "
"there...\""
msgstr ""
"｢エドアルド・マニュエル・ゴダードは宇宙のどこかをさまよってるんだって言われて"
"るよ。発明品の隠し場所に葬られてさ！　どうにかそのなかを徹底的にあされないも"
"のかな……｣"
```

**Comment by UncombedCoconut** [comment]
No need for a new issue. I'll try to get this fixed today. Thanks.

**Comment by UncombedCoconut** [comment]
It's theoretically fixed now... :)
