### ISSUE TITLE
Weblate excessively correct some translated texts.

### ISSUE THREAD

**Issue by oo13** [naev/naev#1912]
Naev project in the Weblate doesn't seem to allow some space characters at the beginning and end of the text unless the original text has space characters at the same positions.

I would like to use some space characters to lay out texts in Japanese. Could you disable the auto correction? The auto correction is probably controlled by AUTOFIX_LIST.

I uploaded the following, but Weblate deleted SIX-PER-EM SPACE at the end of the msgstr.
```po
#: dat/assets/aesir_iv.xml:2
msgid "Aesir IV"
msgstr "アシール IV "
```

**Comment by UncombedCoconut** [comment]
I've updated our "Translation flags" to `ignore-begin-space,ignore-end-space`. Available options are documented [(here)](https://docs.weblate.org/en/latest/admin/checks.html#custom-checks).

I think you're saying that the Roman numerals should be wrapped in spaces no matter where the translation of "Aesir IV" appears, right? (Whether it's in the middle of a sentence, used as a map label on the overlay, etc.?) As long as it's universally a good idea, I agree, you should be free to do it. Let us know if any other flags can help. Thanks.
