### ISSUE TITLE
Hired escorts are not present in space when playing the game in Japanese language.

### ISSUE THREAD

**Issue by oo13** [naev/naev#1916]
Hired escorts are not present in space when playing the game in Japanese language.

A way to reproduce:
1. Hire a pilot in a space bar.
2. Take off from the planet.
3. There is no escort in space.

naev.sh outputted the following message to the console:
```
(snip)
Reached main menu
Warning: [faction_get] Faction '傭兵' not found in stack.
Warning: [event_runFunc] Event 'Hired Escort Handler' -> 'enter': [string "events/hired_escorts.lua"]:244: Faction '傭兵' not found in stack.
stack traceback:
	[C]: in function 'get'
	[string "events/hired_escorts.lua"]:244: in function <[string "events/hired_escorts.lua"]:221>
Warning: [hook_runEvent] Hook [enter] '5' -> 'enter' failed
[Thread 0x7fff88fda640 (LWP 28159) exited]
(snip)
```

'傭兵' is Japanese translation of 'Mercenary'.

OS: Debian GNU/Linux Testing
Naev Version: 3ff2ba25b498bc629fdb606117a82dfbfe03dd62

**Comment by bobbens** [comment]
Should be fixed in main, thanks!
