### ISSUE TITLE
Get rid of 0 values in the shipyard

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1920]
So with the move to core outfits, the shipyard is always polluted with 0 values, most being define by outfits with some rare cases in which the ship adds some value like armour. Since these values are not really helpful to the player, I think it would be best to show something like the ship's stats with the default outfits plus show explicitly what the ship itself is adding. Another option would be to just not display the 0 values. Anything that is less confusing than the current system should work.
![zero](https://user-images.githubusercontent.com/54677/135460234-c0d0469e-770f-4811-bb9c-08680028fe8b.png)

**Comment by UncombedCoconut** [comment]
"Another option" now implemented. Before closing, I'll allow time for us to ask ourselves, "but does this 'anything' _really_ work?" (Also, the implementation doesn't try to suppress regen values of 0.0 MW unless the corresponding energy/etc. stat is 0 MJ.)
