### ISSUE TITLE
Missing some NL characters in po/naev.pot.

### ISSUE THREAD

**Issue by oo13** [naev/naev#1921]
xgettext seems to delete some NL characters in the XML files.

po/naev.pot has the following entry:
```po
#: dat/outfits/launchers/teracom_mace_launcher.xml:9
msgid ""
"The Mace class unguided rocket is a cheap, expendable weapon used to boost "
"peak firepower in tight situations. It is far better at dealing damage to "
"light targets than most fighter sized energy cannons, but comes with the "
"disadvantage of running out of ammunition after only a short time of fire. "
"TeraCom's Mace launcher uses an advanced reload mechanism that allows the "
"launcher to fire more rockets in less time."
```
This msgid has no '\n' but should have two, so Naev doesn't use it even if you provide the msgstr.

The description in dat/outfits/launchers/teracom_mace_launcher.xml:
```XML
  <description>The Mace class unguided rocket is a cheap, expendable weapon used to boost peak firepower in tight situations. It is far better at dealing damage to light targets than most fighter sized energy cannons, but comes with the disadvantage of running out of ammunition after only a short time of fire.

TeraCom's Mace launcher uses an advanced reload mechanism that allows the launcher to fire more rockets in less time.</description>
```

I don't understand what po/its/translation.its means exactly, but I add the following line in the file and it seems to work fine.
```XML
<its:preserveSpaceRule selector="/outfit/general/description" space="preserve"/>
```

I wonder other selectors have worked fine in German translation. I have not checked all msgids yet.

**Comment by UncombedCoconut** [comment]
Wow, that's a good find, thanks. We don't ever want xgettext tampering with whitespace (since, as you point out, this causes translation lookups to fail), so I'll use a selector of `//*` in the rule.
