### ISSUE TITLE
gl_shader_compile reports floating point constant overflow.

### ISSUE THREAD

**Issue by oo13** [naev/naev#1922]
gl_shader_compile reports floating point constant overflow, and naev.sh outputs a lot of 'Warning: [gl_checkHandleError] OpenGL error...'

The compile error causes at the line:
326:    float d = 1e1000;

Naev version: 3db01cfd547fec6edd6c19dbfb322456efc9d866  (latest version I noticed it)
OS: Debian GNU/Linux Testing with NVIDIA driver

stderr
[b.log](https://github.com/naev/naev/files/7293571/b.log)

stdout
[a.log](https://github.com/naev/naev/files/7293574/a.log)

**Comment by bobbens** [comment]
Thanks for the report, should be fixed in main.
