### ISSUE TITLE
Handle low% translations appropriately

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1934]
Naev has many translations started, and few complete enough to really use.
In official releases, we'll want to offer truth in advertising (perhaps: [83%] de, ..., [5%] fr, [1%] pt_BR, [1%] pt_PT) and potentially even disable translations beneath some threshold.
Also, while it's probably harmless to set up a 99%-English game because of a user's system locale, it may be undesirable.

A script can check completeness by parsing `msgfmt` output:
```bash
$ msgfmt --statistics po/de.po -o /dev/null
10348 translated messages, 783 fuzzy translations, 859 untranslated messages.
```

**Comment by bobbens** [comment]
True. What about the following?
1. Showing completion %
2. Sorting by completion %
3. Disable automatic detection of locale and/or ask the user if they want to use their system locale (with % completion rate) or English on first launch

**Comment by UncombedCoconut** [comment]
Sounds good. I created this after realizing it was a release task I'd forgotten about.

**Comment by UncombedCoconut** [comment]
I've realized that I'm scared of Meson i18n and not too interested in doing this right by end November. But actually we might be in decent shape if we just add disclaimer text to the Options dialogue? (Issue should not be closed after that, just maybe kicked to post-0.9.)

**Comment by UncombedCoconut** [comment]
Alternative, outrageous implementation:

`po/fr.po`:
```
#: src/options.c:291
msgid "Translation status: complete!"
msgstr "Statut de la traduction : merde."
```
etc.

**Comment by bobbens** [comment]
Then it might be best to at least ignore system preferences for now? Force English by default and punt to 0.10.0?

**Comment by UncombedCoconut** [comment]
Actually, new strategy: grab statistics at build time from only naev.pot (easy for Meson). There's our denominator. The .mo files have a string count in the header. There's our numerator. In case of mods we can sum before dividing. Since we're supposed to behave wrt physfs and mods, this is the obvious Right Way To Do It. There will be some implementation complexity, though, which is a shame.

**Comment by UncombedCoconut** [comment]
OK, the stats are now visible. No other rules are implemented, but they can be experimented with.
In terms of code readability, I feel like I might have created a monster, though. But hopefully only options.c code particularly needs to be cleaned up.

**Comment by PhoenixRiver** [comment]
A bit late to the party but I presume that the user still has an
option as to which language to install in? Probably the most
irritating thing I have to deal with day to day is apps and installers
assuming that since I run Windows in Japanese that I want that as the
installed language... I can't read Japanese at all well but I know
Windows like the back of my hand and most installs can be done in
English (though many require "special" treatment to get it to work
first time! ;) but I live in Japan and have to have a machine that can
handle Japanese natively... yes, it will get converted to Linux as
soon as the situation allows, but until then *sigh* It doesn't help my
little one prefers thigns o be in French for her stuff...

Phoenix

**Comment by UncombedCoconut** [comment]
> A bit late to the party but I presume that the user still has an option as to which language to install in?
Good news / bad news: our installer won't give you a choice, because its job is to install *everything*.
If we mistake any users' language preferences (which is inevitable), they'll have a chance to fix it in the Options window.

**Comment by PhoenixRiver** [comment]
> Good news / bad news: our installer won't give you a choice, because its job
> is to install *everything*.
> If we mistake any users' language preferences (which is inevitable), they'll
> have a chance to fix it in the Options window.

Cool, at least it doesn't mean a reinstall or hunting the lang file
down and dropping it into the right place... you'd have thought
commercial software would be better than this, right? *sigh*

Thank you :)
