### ISSUE TITLE
Improve landing/boarding autonav approach

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1943]
Landing/boarding approaches are a bit wonky especially with reverse thrusters. Autonav seems to do much worse of a job than a pilot would. Need to investigate why and potentially improve the reverse thrusters approach code.

**Comment by UncombedCoconut** [comment]
major progress in https://github.com/naev/naev/commit/2684e254fd82ab5510cb45c9c5a6f79f0fe6e67e -- reportedly still has issues if you start auto-boarding at very close range.

**Comment by UncombedCoconut** [comment]
Re close range:
> Yes, it sometimes has oddities. I'd say it's minor. One would need to clean the function much more (because RN it's a copypaste patchwork) but the fix isn't trivial I would say.

(Quoted from [here](https://discord.com/channels/661743268505190400/671163057161895947/914248856810717184).)

This issue wasn't about general refactoring, so closing.
