### ISSUE TITLE
Pilots are spawning without leaders

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1948]
For the past few months or so, the spawning code hasn't been setting formation leaders, so players don't see ships flying around in formation anymore. This was accidental. (nenau looking at it, reports there are related issues after directly addressing the leader issue.)

**Comment by UncombedCoconut** [comment]
> I do not understand. I abandon for today. Here is what I understood : when the leader has bays, the followers don't use the PD controller. Instead, they use what seems to be the raw follow function (or a PD with something not working) towards their prescripted position in formation. However, I've seen that the AI anyway enters the function `follow_accurate`...

(quoted from [here](https://discord.com/channels/661743268505190400/671163057161895947/914246508797386812).)

**Comment by nenau-again** [comment]
I'll let you close it to be sure, but my tests suggest @UncombedCoconut solved it a few hours ago.

**Comment by bobbens** [comment]
Since it seems solved, closing.
