### ISSUE TITLE
Make "Pirate Hyena" an actual ship

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1949]
Most pirate pilots will show up with names like "Pirate Admonisher", because they come in pirate-flavored ship types. But the Hyena is different; it's a standard ship type used by civilians and pirates alike.
Having a distinct "Pirate Hyena" ship could keep things consistent, allow for cleanup of Lua scripts which enforce this consistency manually (`git grep '_("Pirate Hyena")'`), and play nice with the pirate reputation logic (where it matters if the player has a "Pirate" ship or not).
Potential gotcha until there's separate `pirate_hyena` artwork: the "Ship Lover Quiz" event could become unfair.

**Comment by UncombedCoconut** [comment]
Hmm
```
dat/events/neutral/npc.lua:   _([["I've heard that pirates have to keep their reputations up with other pirates by flying pirate ships. The Hyena is considered a pirate ship and is easy to get, but as for the others, I have no idea where they get them from."]]),
```

**Comment by UncombedCoconut** [comment]
TODOs: graphics and other attributes in `dat/ships/pirate_hyena.xml` (marked by XML comments)
maybe the above npc text
maybe clone Hyena fighter outfits:
```
dat/outfits/fighter_bays/hyena_fighter_bay.xml:
dat/outfits/fighter_bays/hyena_fighter_dock.xml:
dat/outfits/fighters/hyena_fighter.xml:
dat/scripts/equipopt/templates/pirate.lua:   "Hyena Fighter Dock",
dat/scripts/equipopt/templates/pirate.lua:   "Hyena Fighter Bay",
dat/tech.xml:  <item>Hyena Fighter Bay</item>
dat/tech.xml:  <item>Hyena Fighter Dock</item>
dat/tech.xml:  <item>Hyena Fighter Bay</item>
dat/tech.xml:  <item>Hyena Fighter Dock</item>
```
(if so, the ["Hyena"] line in `dat/scripts/equipopt/templates/pirate.lua` can probably die.)

**Comment by bobbens** [comment]
Only really need new graphics now I think! I'll try to do that today.

**Comment by bobbens** [comment]
Not the best, but at least implemented.
