### ISSUE TITLE
Package macOS bundle in a DMG image.

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1967]
It seems that DMGs are the 'right way' to package macOS app bundles.

~~This should be doable in our macos environment with some tweaks. Installing `hfsplus-tools` and `dd` should get us the right tools for the job.~~

~~We should probably just keep this out of the build system for the sake of minimizing complexity.~~

~~Probably needed(tm) commands:~~
~~dd if=/dev/zero of=<output DMG>.dmg bs=1M count=16 status=progress~~
~~mkfs.hfsplus -v Install <output DMG>.dmg~~

~~mkdir -pv /mountdir~~
~~sudo mount -o loop <output DMG>.dmg /mountdir~~
~~sudo cp -av Naev.app /mountdir~~
~~sudo umount /mountdir~~

~~Not sure if mounting will work correctly in Docker, but let's cross that bridge when we get there~~

Will implement [node-appdmg](https://github.com/LinusU/node-appdmg) into our release workflows. Looks straightforward enough and should make our macOS install process seem far more 'legit'.

**Comment by ids1024** [comment]
I've used [node-appdmg](https://github.com/LinusU/node-appdmg) to build a macOS `.dmg` for the [System76 Keyboard Configurator](https://github.com/pop-os/keyboard-configurator). I think that gives you the sort of style typical of a app `.dmg`, with an icon and background.

There are a couple other similar scripts, but that seemed as good as any.

**Comment by ProjectSynchro** [comment]
> I've used [node-appdmg](https://github.com/LinusU/node-appdmg) to build a macOS `.dmg` for the [System76 Keyboard Configurator](https://github.com/pop-os/keyboard-configurator). I think that gives you the sort of style typical of a app `.dmg`, with an icon and background.
> 
> There are a couple other similar scripts, but that seemed as good as any.

That certainly looks very handy, should fit the bill nicely :)

**Comment by ProjectSynchro** [comment]
This should be working as of 29f88e951aa80c2ff5b8d5bfdc296d95349c65b8

To get this working in a mac-less environment I had to create a DMG on macOS (ironic isn't it), and transplanted the fancy assets into [`extras/macos/dmg_assets`](https://github.com/naev/naev/tree/main/extras/macos/dmg_assets). There is a script in [`extras/macos`](https://github.com/naev/naev/tree/main/extras/macos), that will generate a DMG using `genisoimage` from those assets and a Naev.app app bundle.

This probably could be integrated into meson at some point. but for now it can be run after a `meson install` if cross-compiling for macOS.
