### ISSUE TITLE
No display when using SDL's Wayland backend

### ISSUE THREAD

**Issue by physkets** [naev/naev#1984]
When I run the program with the environment variable to make SDL use the Wayland environment, there is nothing on-screen. The audio however, does startup. This is what I see when I run it on the terminal

```
$ SDL_VIDEODRIVER=wayland naev 
 Naev v0.9.0 (linux-x86_64)
AppImage not detected.
BFD backtrace catching enabled.
Trying default datapath: /usr/share/naev/ndata/dat
Loaded configuration: /home/user/.config/naev/conf.lua
Read locations, searched in order:
    /home/user/.local/share/naev/
    /usr/share/naev/ndata/dat
Cache location: /home/user/.cache/naev/
Write location: /home/user/.local/share/naev/

 Sea of Darkness

SDL: 2.0.18 [compiled: 2.0.18]

xdg_surface@27: error -1: invalid window geometry size (0x0)
Screen size too small, upscaling...
Warning: [gl_fboCreate] Error setting up framebuffer!
Warning: [gl_fboCreate] Error setting up framebuffer!
Warning: [gl_fboCreate] Error setting up framebuffer!
OpenGL Drawable Created: 0x0@24bpp
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 16384
vsync: yes
Renderer: AMD RENOIR (DRM 3.42.0, 5.15.11-arch2-1, LLVM 13.0.0)
Version: 4.6 (Core Profile) Mesa 21.3.2

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
OpenAL started: 44100 Hz
Renderer: OpenAL Soft
Version: 1.1 ALSOFT 1.21.1 with EFX 1.0

Loaded 66 Sounds
Loaded 57 Songs
Warning: [gl_fboCreate] Error setting up framebuffer!
Warning: [gl_checkHandleError] OpenGL error [gl_fboCreate:232]: GL invalid value
Loaded 8 Commodities
Loaded 23 Special Effects
Loaded 466 Outfits
Loaded 82 Ships
Loaded 37 Factions
Loaded 47 Events
Loaded 165 Missions
Loaded 42 AI Profiles
Loaded 77 tech groups
Loaded 439 Star Systems
       with 1142 Planets
Loaded 21 UniDiffs
Loaded 8 map decorators
Warning: [background_load] Background -> 'background' : [string "scripts/love/graphics.lua"]:622: Error setting up framebuffer!
stack traceback:
        [C]: in function 'new'
        [string "scripts/love/graphics.lua"]:622: in function 'newCanvas'
        [string "bkg/lib/starfield.lua"]:132: in function 'init'
        [string "bkg/default.lua"]:61: in function <[string "bkg/default.lua"]:28>
Reached main menu
```

and then when I attempt to quit with `Crtl+C`:

```
^C^CTexture leak detected!
   'nlua_canvas_001' opened 1 time
```

When I do not fore the use of that env. variable, the program crashes. I will make another issue for that.

**Comment by UncombedCoconut** [comment]
The challenge here is to figure out why this happened:
`xdg_surface@27: error -1: invalid window geometry size (0x0)`
From that point onward, Naev is dead but just doesn't realize it yet.
Possible ways to investigate:

- See if aur/sdl2-git does any better than extra/sdl2
- See if a different compositor makes a difference (e.g., try two of kwin/sway/gnome-shell if it's reasonably practical)
- Try to trace in debug mode and see what happens in SDL_CreateWindow

I'd love to do these steps for you, but I lack a system that reproduces this behavior.

**Comment by bobbens** [comment]
Seemingly related: https://github.com/libsdl-org/SDL/pull/5064

**Comment by UncombedCoconut** [comment]
> Seemingly related: [libsdl-org/SDL#5064](https://github.com/libsdl-org/SDL/pull/5064)

I think this is it, as I can reproduce the issue as follows:

- Install extra/sdl2 (currently 2.0.18-3).
- Start a "Plasma (wayland)" desktop session (currently extra/kwin 5.23.4-1).
- Configure Naev to start in fullscreen mode (options dialog or "fullscreen = true" in `~/.config/naev/conf.lua`).

All 3 steps are required. Per linked bug, whichever of sdl2 2.0.20 or kwin 5.23.5 is available first will fix this. Already aur/sdl2-git fixes it. Starting in windowed mode and switching into fullscreen later doesn't crash.

This user experience is so bad that I'm looking at workarounds on our end. Maybe we can try windowed if we get a fullscreen window with a 0x0 drawable. On the other hand, the impact may be limited to rolling-release distros that will have fixed sdl2 and kwin out soon.

**Comment by UncombedCoconut** [comment]
Bad news: we can detect the problem happening, but we can't seem to recover. Resetting the window mode and size came closest to working -- the errors went away -- but I couldn't get KWin to actually show the window, so it's still useless. Attempting to recreate the window (with or without reinits of SDL's video subsystem or GL library) fails with an error: "Could not initialize EGL".

**Comment by UncombedCoconut** [comment]
OK, I apologize but I think our best response is to wait this out.
This issue should only affect rolling-release distros like Arch: it looks specific to KWin 5.23.(<5) and SDL2 2.0.18 (maybe also .16).
They should get a fix from both KDE fix to come first ([2022-01-04](https://community.kde.org/Schedules/Plasma_5#Future_releases)) and SDL2's ([2022-01-07](https://github.com/libsdl-org/SDL/milestone/5)) soon; either fix is enough.
If the SDL2 release also enables the Wayland driver by default, we should be totally out of the woods. However, I suspect that will be pushed back.

**Comment by physkets** [comment]
KDE Plasma v5.23.5 is out and Naev works perfectly fine, with the `SDL_VIDEODRIVER=wayland` env. variable.
