### ISSUE TITLE
Heavy Weapon license not appearing after the Empire shipping Delivery mission

### ISSUE THREAD

**Issue by Bigrichman** [naev/naev#1986]
I have completed all of the long haul missions for the lieutenant, yet the Heavy Weapon license didn't show up, is it a bug or was it removed? I'm using the Steam Version.

**Comment by bobbens** [comment]
You should get the heavy weapons license from the `Empire Shipping 2` mission (delivering a package for Commander Soldner). The long distance missions don't give anything. Since 0.9.0 there are also two other ways to get the licenses.

**Comment by Bigrichman** [comment]
thanks, just got the mission and feeling kinda stupid, again, thanks.

**Comment by UncombedCoconut** [comment]
No worries! Closing the issue, since all is well.
