### ISSUE TITLE
Issue building on M1 Mac

### ISSUE THREAD

**Issue by treaves** [naev/naev#1991]
Following along from the Mac build instructions, the meson command fails with:

```
glpk| Run-time dependency zlib found: YES 1.2.11

subprojects/glpk-5.0/src/meson.build:188:3: ERROR: C shared or static library 'amd' not found

A full log can be found at /Users/treaves/Development/OpenSource/games/naev/build/meson-logs/meson-log.txt

```

From the log file,

```
Code:
 int main(void) { return 0; }

Compiler stdout:
 
Compiler stderr:
 ld: library not found for -lamd
clang: error: linker command failed with exit code 1 (use -v to see invocation)


subprojects/glpk-5.0/src/meson.build:188:3: ERROR: C shared or static library 'amd' not found

```

Searching the net for this error is pretty useless.  Any ideas?

**Comment by treaves** [comment]
This seems to be possibly due to the brew locations for software on M1.

```
export LDFLAGS="-L/opt/homebrew/opt/suite-sparse/lib/"
export CPPFLAGS="-I/opt/homebrew/opt/suite-sparse/include"

```

This resolves this issue.  Next one is:

`meson.build:330:3: ERROR: File artwork/gfx/ARTWORK_LICENSE.yaml does not exist.
`

**Comment by treaves** [comment]
Okay.  So basically I had to piece together stuff from the main README, the build README's for Linux, and Mac.

**Comment by UncombedCoconut** [comment]
Sorry your build experience was a pain, and thanks for reporting your experience on this platform.
I think we should update this wiki page (linked from the readme) based on your experience: https://github.com/naev/naev/wiki/Compiling-on-macOS
Was your successful build able to use the "glpk" package from Homebrew? Did you need extra flags/env-vars to make that work?
Was this warning in the current instructions accurate?
> Meson needs an extra argument to find Homebrew's `openal-soft` package: `--pkg-config-path=/usr/local/opt/openal-soft/lib/pkgconfig`.
In general, I'd like to share the Meson config that succeeded for you.

**Comment by treaves** [comment]
Ah, it wasn't awful.  If I wasn't fogged with a cold at the moment, I'd have figured it out sooner.

For completeness, this is what I did that wasn't covered.

`brew install --build-from-source --HEAD luajit
`
This is needed to get luajit, as the current release on doesn't support Mac ARM. And Brew on ARM doesn't use **/usr/local** unless you're using packages that require _Roessetta 2_.  It uses /opt/homebrew 

So next was:
```
export LDFLAGS="-L/opt/homebrew/opt/suite-sparse/lib/"
export CPPFLAGS="-I/opt/homebrew/opt/suite-sparse/include"
```
or it wouldn't find **libarm**.

Next,
```
meson setup --pkg-config-path=/opt/homebrew/opt/openal-soft/lib/pkgconfig -Dblas=Accelerate --prefix="$(pwd)"/build/dist/Naev.app --bindir=Contents/MacOS -Dndata_path=Contents/Resources --force-fallback-for=SuiteSparse build . 
cd build 
meson build
meson dist
meson install

```
The _meson dist_ wasn't needed; I guessed that'd build the app bundle.  It doesn't.  Install does.  But the dist id run the tests & whatnot, and ran fine.

So I do have the app now.  Going to play around with it now, to see it all works.  But it does run.

Thanks.

**Comment by eli-schwartz** [comment]
> The _meson dist_ wasn't needed; I guessed that'd build the app bundle. It doesn't. Install does. But the dist id run the tests & whatnot, and ran fine.

The `meson dist` performs the same role as autotools `make distcheck` -- it creates release tarballs suitable for uploading to Github Releases or to a website's custom "Download the Source Code" page, then unpacks them and verifies that they build and pass the tests correctly.

`meson install` performs the same role as any build system's `install` command.
