### ISSUE TITLE
v0.9.1 run issues on ubuntu 21.10

### ISSUE THREAD

**Issue by dwillmot20** [naev/naev#2002]
Hi I've just downloaded v0.9.1 and cant seem to run it (yes permissions set to allow as executable)
I tried running it using sudo nautilus and it came up with this
Naev v0.9.1 (linux-x86_64)
AppImage detected. Running from: /tmp/.mount_naev-07U59HA
Trying default datapath: /tmp/.mount_naev-07U59HA/usr/share/naev/dat
Loaded configuration: /root/.config/naev/conf.lua
Read locations, searched in order:
    /root/.local/share/naev/
    /tmp/.mount_naev-07U59HA/usr/share/naev/dat
Write location: /root/.local/share/naev/

 Sea of Darkness
ERROR ../source/src/opengl.c:275 [gl_createWindow]: Unable to create OpenGL context! Could not create GL context

 any thoughts?

**Comment by ProjectSynchro** [comment]
Hi,

My guess is that your driver may not have support for OpenGL 3.1 on your current device.
Naev currently requires at least OpenGL 3.1 or greater.

You can install glxinfo, from the mesa-utils package:
`sudo apt-get install mesa-utils`

And run this in a terminal to get the current supported OpenGL version
`glxinfo | grep "OpenGL version"`

If the available version is not at least 3.1 you can try running Naev in software mode.
e.g.
`LIBGL_ALWAYS_SOFTWARE=true naev-0.9.1-linux-x86-64.AppImage`

**Comment by UncombedCoconut** [comment]
Good morning, before the other suggestions please see if a different environment variable setting fixes it:
`SDL_VIDEODRIVER=wayland naev-0.9.1-linux-x86-64.AppImage`

If your desktop session is based on Wayland (which I think is the default in Ubuntu 21.10), launching without that is _supposed_ to go through Xwayland and more or less work. Sometime last yea, this behavior started happening instead. I haven't been able to figure out which package was responsible for that.

**Comment by dwillmot20** [comment]
Thank you guys. I've not had any luck upgrading to OpenGL3.1 yet. I think that my laptop is a bit too old (11years) for it. I've tried installing a new Mesa driver and I'll try again but I think the issue is with my hardware not the game's code.

**Comment by not-pyroman** [comment]
Ah that explains it, well here's to hoping you get a computer with OpenGL 3.1!
