### ISSUE TITLE
Reported issues with background after tabbing out of a full-screen game

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#2007]
Reported by @not-pyroman on Discord. Summary: "I've been noticing that tabbing out and back in occasionally doesn't update the background location and it gets shifted up and left".

This was under Gnome (X11), presumably Mutter managing Windows. Extra observations: "the resizing is visible when I tab out", "It loves moving the background especially when I am moving down and right", and opting into fancy backgrounds doesn't make a difference.

**Comment by UncombedCoconut** [comment]
Potentially fixed by https://github.com/naev/naev/commit/0ea7bace97d0eb7dc2ddae3230c6269d187d8de8 -- TBD.

**Comment by not-pyroman** [comment]
resizing is still observable with OBS when naev minimizes but AFAIK this seems fixed, but I'm sure I already said that when this was relevant
