### ISSUE TITLE
Reproducible failure to gc a mission's environment.

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#2008]
Just to simplify debugging a little (though this is not a truly reduced test case):

- A branch with extra debug-prints, more eager gc, and restriction to one specific mission is: naev:refdebug
- (Do not use the "paranoid" compile option, as this uses WARN() as a convenient way to log events of interest with the function name.)
- A save to start from is: [tester.ns.gz](https://github.com/naev/naev/files/7859267/tester.ns.gz)
- Steps are: L,L (load the save), alt-2 (bar), right,a (approach Crimson Gauntlet), Challenge, Warrior, Enter Arena, [fly directly to your death].

```
Reached main menu in 10.373 s
nlua_dobufenv: (null)
nlua_dobufenv: (null)
nlua_dobufenv: (null)
nlua_dobufenv: Crimson Gauntlet
Warning: [audioL_new] +1
Warning: [audioL_new] +1
Warning: [audioL_new] +1
Warning: [audioL_new] +1
Warning: [audioL_new] +1
Warning: [audioL_new] +1
Warning: [audioL_new] +1
Warning: [audioL_clone] +1
nlua_freeEnv: Crimson Gauntlet Challenge
nlua_dobufenv: Crimson Gauntlet
Warning: [audioL_new] +1
Warning: [audioL_new] +1
```

And that's it! We've leaked a ton of openal sources.
Interestingly, if I do a takeoff from this point, I do see something:
```
nlua_freeEnv: Crimson Gauntlet
Warning: [audioL_gc] -1
Warning: [audioL_gc] -1
```
So the environment of the new, not-yet-approached "Crimson Gauntlet" mission is able to get gc'd, but not that of the one I played. Playing the mission must have created a dangling reference at some point, which is able to keep everything alive until naev.c calls `lua_exit()`.

**Comment by UncombedCoconut** [comment]
https://github.com/naev/naev/commit/28d90a4f89afd5fa280904b78961a618e43bb35c fixed the failure to gc the "victory.ogg" audio object(s) in gauntlet.lua.
We can probably close this and delete the "refdebug" branch now, though there's one puzzle:
if I follow the above steps (and repeat the bar/gauntlet/enter/die steps) I see several audio objects created when the vn outro happens. The first time, these objects aren't gc'd. After the first time, they are.

I'm not sure what could be holding a reference to the first env (or first collection of audio objects). It doesn't make a ton of sense, and could be an unintended O(1) leak. But the O(n) leak seems to be dead.

**Comment by bobbens** [comment]
Closing as it seems to be solved.
