### ISSUE TITLE
frontier wars notes

### ISSUE THREAD

**Issue by biell** [naev/naev#2014]
# fw01
https://github.com/naev/naev/blob/15decf6a8c6f7fa677c0878119784ccebbd12c8c/dat/missions/dvaered/frontier_war/fw01_sabotage.lua#L275
Is this supposed to be "Johnson and Johnson" or "Johnson and Jhonson"?

# fw02
https://github.com/naev/naev/blob/05ea30455e42d764730c201b038798889c66339c/dat/missions/dvaered/frontier_war/fw02_escape.lua#L181
You can bypass Empire and Pirate deals in fw02 easily with a schroedinger(TeraCom Banshee, Milspec Orion 2301 Core, Air Freshener, Milspec Scrambler, Low Radiation Sensor Modulator, Nexus Stealth Coating, Hellburner, Tricon Zephyr, Nexus Light Stealth Plating, Improved Stabilizer) changeover when you land in Ganth to steal medical supplies. Travel to Vega, Ux (told to stop and talk to feathery agent, ignored that advice b/c the mission computer didn't have it listed as a milestone), Valerie, Shinnok, Pastor, Koralis, Quex, Enguoz (saw blockade, enabled stealth, flew behind them, then jumped out with extra 200% jump range), Hakoi, Trask, Qorel, Ekkodu, Blunderbuss (refuel), Verex, Darkstone, Beeklo, Dvaer.  Maybe just add some piece of 10 ton equipment necessary to infiltrate the Za'lek sting?  I would have been too lazy to change to a cargo hull, and just used my quicksilver.  Please note that I didn't read the code until after I completed the mission and wanted to know what the feathery agent was all about).  If that landing was added to the mission milestones, I would have landed somewhere.

Also, there are multiple mentions of "Alteris" which should actually be "Arcturus"

# fw03
https://github.com/naev/naev/blob/153a65abf8ac19ed9a359693f304b34d8ad09738/dat/missions/dvaered/frontier_war/fw03_sirius.lua#L96
I think the word "provide" should be removed:  "I'm counting on you to **provide arrive** with a lot of"

**Comment by UncombedCoconut** [comment]
I think "Johnson and Jhonson" could be intentional goofiness rather than an error, though I'm not sure what that would even mean for spoken dialogue. Also not sure of the most fun response to your blockade-running strategy. (Summoning @nenau-again...)
We can fix up the fw02/fw03 text errors right away.
Thanks!

**Comment by LJDude** [comment]
I assumed that "Johnson and Jhonson" was a joke as well as avoiding copyright and whatnot.

**Comment by UncombedCoconut** [comment]
There are fortunately no copyright or trademark problems with saying "Johnson and Johnson", if we want to.

**Comment by biell** [comment]
> Also not sure of the most fun response to your blockade-running strategy.

And, it doesn't have to be fixed, I was just noting it since the comment suggested it would be hard to do.  And, it was literally the first thing I tried.  As a note, I have taken this game to it's full, logical conclusion pretty much every version since 0.6.0, so I approach it differently than any new player might.

**Comment by nenau-again** [comment]
Hi all, and thanks @biell for feedback. So, my answers to the three remarks/issues:

1- Johnson and Jhonson is fully intentionnal. Nothing forbids to a Goddard-sewage plumber named Johnson to associate with an other Goddard-sewage plumber named Jhonson.
For record, this mission was scripted way before I knew the existence of the firm Johnson and Johnson (which name I find btw even more stupid than the one of my goddard-plumbers association). And when I heard that name last year, it recalled me something, but I have not been able to say why until right now.

2- The mission was also designed before stealth was implemented/mainstream and I was fearing something like that could happend. I guess spreading the guards a bit more around the jump point would solve the problem. Anyway, I had taken into account the fact that it might be possible that the player manages to skirt my blockade one way or an other so it's not a disaster. If someone finds a really odd and strange way to skirt the blockade that only a few weird players would have thought of, I won't take action against that, but here, stealthing with a Schroedinger sounds too mainstream to be allowed.

3- Agreed

This implies some changes on the mission code that I can do myself next Sunday. If anyone does it before, you're welcome.

**Comment by nenau-again** [comment]
I did the fix on fw03. I guess this issue is solved. I'll close soon if noone thinks more work has to be done.
