### ISSUE TITLE
Not sure if this is an issue or not... but...

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2023]
In events/start.lua there are these lines... but I'm running the Steam version of Naev, currently 0.9.2 ...

```
   -- TODO remove when releasing 0.9.0
   -- This line stops the tutorial updater from running
   var.push( "tut_update", "0.9.0" )
```

Apologies if it is just the comment that is outdated!

**Comment by bobbens** [comment]
It was a workaround to an update issue, but since it isn't necessary anymore, I'm removing it. Thanks for the reminder!
