### ISSUE TITLE
Typos... (Steam - 0.9.2)

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2024]
Apologies, I haven't the ability to do a pull request but here is a list of typo's I found in the tutorial stuff (some while looking for the right file for the starter tutorial!) so far... I'm being interupted before I can finish :/

missions/tutorial/tutorial.lua:
function create ():
   sai(fmt.f(_([["Congratulations on [snip] Always ready to be of ~~your~~ assistance."

   sai(_([["Anyway, from now on, I will be your ~~s~~**S**hip AI, [snip] If you have any question**s** or comment**s** about [...]
[The first instance of "Ship AI" does not capitalise "Ship" which seems to be inconsistant with the rest of the tutorial so far...]

   sai(fmt.f(_([["Alr**i**ght, [...]

   sai(_([["Let's now practice combat [snip] you won't end up ~~like~~**a** ship ornament like my late previous owner [...]

events/tutorial/tut_land.lua:
function outfit_buy( outfitname ):
      sai(fmt.f(_([["Looks like you just bought an #oAfterburner#0 [snip] lot of energy, so it is bes**t** to use

   _([["#oCruisers#0 are the smallest [snip] strategy of using fighter**s** to do the [...]

function ship_buy( shipname ):
   sai(fmt.f(_([["Congratulations on buying [snip] core outfits **e**quipped, so you should [...]

**Comment by bobbens** [comment]
Should be fixed, thanks!
