### ISSUE TITLE
Polaris Prime? Ship Quiz? ... Steam 0.9.2

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2028]
I have just landed on Polaris Prime in the Gamma Polaris system and I got a SIGENV (I think?) message - message from Bobbens "Universe Creator" ;) - I clicked "Yes" and then "OK" and then was dropped onto the Planet screen (which had already appeared behind the crash message panel)

I was able to continue without apparent problems except my ship log has a new entry under titles of "Ship Quiz" (which I don't remember ever having done); the only entry is "Empty" which when viewed contains a message of "Empty"... so I would hazard a guess that this "Ship Quiz" caused a soft crash... hopefully my save isn't corrupted!?

If I can provide any more details that might help feel free to contact me or if I have anything else that seems related happen then I'll comment here. I'd have liked to have provided some sort of error log or some such but I couldn't find where they might be stored, if they are?

P.S. I just remembered - I think the error message might have said the crash was in "libc"? But I'm not entirely sure but if it was something like that it'd explain why I forgot since I think that might entirely unhelpful? (Forgive me if I am wrong).

**Comment by bobbens** [comment]
It shouldn't be a problem, the log was creating when the event started instead of only when necessary (you probably just missed the character). I have pushed a fix that will find it's way into the next version to be less confusing. Thanks!

**Comment by PhoenixRiver** [comment]
Thank you - sorry I can't help more with the sigenv :(

**Comment by bobbens** [comment]
The SIGENV is just a joke event to encourage users to contribute, it's not an actual issue. Don't worry about it ;)

**Comment by PhoenixRiver** [comment]
Ah! :) - doh! ;)
