### ISSUE TITLE
Proposal: Get rid of physical units

### ISSUE THREAD

**Issue by bobbens** [naev/naev#2036]
Physical units were added to try to give a bit more a sense of immersion and realism quite a while back. However, not only do they not really make sense, they will never be able to really make sense without making gameplay horrible (e.g., if distances are realistic, you need relativistic speeds, if speeds are realistic, you need ridiculous accelerations, etc...). Looking at games like Escape Velocity series, they went the no physical units route and just went with numbers (500 thrust, 300 speed, etc...). It might make sense to revert the physical units labels and go with unit-less abstract quantities.

**Pros:**
* Less nonsense
* Shorter strings
* Leaves things up to the player's imagination

**Cons:**
* Harder to distinguish between temporal quantities (MW vs MJ)
* Harder to understand how things relate
* Can't use SI prefixes as naturally (MW vs GW, but I don't think they are really used in game as it can also be confusing)

**Comment by Generalyossef** [comment]
i never understood them anyways i only look at numbers

**Comment by PhoenixRiver** [comment]
The energy and armour units seem to make sense, ton too but I was confused by the Nx10<superscript>5</superscript> for planet populations, so hard to read!
So I think the technical stuff should stay technical but the nontechnical stuff shouldn't be, that way if players just want to look at the numbers they can but if they want the exact technicals (even if they have to suspend belief) they can... maybe it would be better to have this as an option... maybe a translation that doesn't include them? *shrug* sounds like an implimentation thing and I can't do that currently *frustrated sighs*

**Comment by Zireael07** [comment]
Never noticed the population thing, what many other space games do is count in thousands ("100K") or millions ("200 M") or even billions ('7.4B")

**Comment by bobbens** [comment]
> Never noticed the population thing, what many other space games do is count in thousands ("100K") or millions ("200 M") or even billions ('7.4B")

The main issue is while in English you can represent 20,000,000 as "200 M" or "200 million", in Japanese you would want to do it as 2000万, so it is non-trivial to generalize to all languages. That said, I do think it should be possible to have a solution for that with a fallback to current system as a fallback.

**Comment by PhoenixRiver** [comment]
I 100% sympathise with the issue of the number of tens to count... the Japanese system still throws me daily! However, would it not be possible to have a switch in the translation file?

I'm only aware of three and four "tens" counting though I presume there are others but as long as the counting systems are still decimal it shouldn't be an issue (and the current system doesn't help there either anyway!)

Given where it is on the page there is also plenty of room just to write it out in full (though then you have to worry about any spacer you might want to use and, again, where to put them, but maybe no spacer is just fine?)

**Comment by bobbens** [comment]
OK, so the physical units stuff has been reworked with the merge of #2391 , so I guess this is moot now.

Regarding population, I added `format.humanize` to the `dat/script/format.lua` library, so that would solve the number elegantly (it would display 100k as 100 thousand in English, and 10万 in Japanese), however, I haven't hooked that up to the C-side yet. I guess the easiest way would be to implement a hook to overwrite the population part in the spob Lua stuff, and allow Lua to handle it.
