### ISSUE TITLE
Outfit - Utility - Targetting Array technical description - Steam 0.9.2

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2039]
The Targetting Array, in contrast to, for example, the Emergency Shield Booster or the Combat Hologram Projector, does not give complete technical details about it's effects despite claiming to improve targetting in the general description below. It does mention it reduces firing rate as well as reducing heat production but that it allows faster target acquisition is omitted which, given its name, is a little weird! (Especially when contrasted to other non-standard outfits).

**Comment by PhoenixRiver** [comment]
cf "Targetting Conduit"

**Comment by bobbens** [comment]
I haven't really messed with them much, but they are sort of legacy outfits. So I believe it would make sense to either revamp it completely or remove it as it doesn't really fit in with the current utility outfit design.

**Comment by PhoenixRiver** [comment]
Fixed in #2078.
