### ISSUE TITLE
Outfit - Utility - Unicorp Scrambler technical/general description - Steam 0.9.2

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2040]
The Unicorp Scrambler technical description and general description partially contradict each other assuming a typo, otherwise they flat out contracdict each other; the technical description lists an improvement in evasion while the general description says "a scrambler reduces the distance at which the ship can be detected and scanned" ... this should probably be "a scrambler increases the distance" and the detection part is not reflected in the technical description.

The reduce/increase language is not replicated in the Milspec Scrambler however it, also, does not list an increase in detection... but then again, neither does it promise it! ;)

**Comment by bobbens** [comment]
Fixed, thanks!
