### ISSUE TITLE
Report: derelict events can boost rep in a visible but unsaved way.

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#2046]
Bug report via e-mail:
If I enter an abandoned ship and this is transferred to the museum of a faction, you get 3%. This works until you close NAEV. If you restart NAEV, all obtained % have disappeared. That's what happened to me several times with Za'lek ships. From 35% after a reboot against 2%. Today the same. As a ship I have a pirate Kestrel, equipped with legal accessories. Screenscuts enclosed.
now that I think of it, sounds like a bug with the fake transponder
they says it's not the fake transponder, but I'm not sure what it could be 

https://discord.com/channels/661743268505190400/661743739286585384/938445561189781504

**Comment by PhoenixRiver** [comment]
I had a look at this and the only thing I could think of was that they didn't land afterwards or that the apostrophe in the name "Za'lek" is doing something?

However after drilling down it looks like line 32 of the fake transponder (lua):
`      f:setPlayerStanding( f:playerStandingDefault() )`
resets the player's faction standing to the default as if they had never met the faction before?? I don't know this for sure and I'm not sure how to fix it but I think we need to keep the fake transponders fake faction standing seperate to the real one and make sure this line sets the real one back correctly... could anyone check me on this?
(I drilled down to work out what exactly PlayerStandingDefault referred to and reached the following in faction.c:
`   /* Player information. */`
`   double player_def; /**< Default player standing. */`
`   double player; /**< Standing with player - from -100 to 100 */`
within the definition of a faction.)

**Comment by bobbens** [comment]
Apostrophe shouldn't matter. It seems like it was the C side `NLUA_CHECKRW` doing bad stuff, but I don't quite understand why. However, it could be a different issue.

My theory is that the drop happens when you mess with the fake transponder afterwards, maybe variables not getting cleared or something. Since from the report itself it seems like there could still be an issue somewhere, I'll leave it open for a bit.

**Comment by bobbens** [comment]
This is probably fixed with #2091.
