### ISSUE TITLE
Report: offset in Slim GUI icons

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#2047]
slim seems to be bugged for the edge icons
The sides on the left, right, and top all line up to where they should be (clicking a ship or planet using their border icon) but the bottom used to be above your info bar, but now the area to click it is at the bottom of the window
Like their icons still appear above the info at the bottom, but the area to click them is below

https://discord.com/channels/661743268505190400/661743739286585384/938474486766895204

**Comment by bobbens** [comment]
Should be fixed in main.
