### ISSUE TITLE
The small menu can not be opened from vn

### ISSUE THREAD

**Issue by sigus** [naev/naev#2063]
Currently, the small menu can not be opened from vn. Possible implementation issues include double vn (through ship ai), bioships stuff mess with mission scripts etc. Easiest way is just temporarily disable or hide the info menu button.

**Comment by bobbens** [comment]
It is not openable from the VN. Some notes:
1. You can not save from the small menu opened from the VN.
2. If your "menu" key is set to escape, you can only view the overlay with 'tab'. Maybe another keybinding is also necessary?

Thanks!
