### ISSUE TITLE
Steam 0.9.2 - auto-landing oddity

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2068]
So, I have been using auto-land (by pressing "L") when arriving at planets and I thought that it was a little clunky but didn't realise how bad it was until another Rhino landed alongside me at a spacestation; the difference was that I have reverse thrusters on my ship and, despite that, the AI ship without them landed faster with it's last minute turn and decelerate, the reason being is that the reverse thruster landing target is the edge of a large planet, however when landing at a small planet, moon, space station or other smaller object the reverse thursters almost stop you at the edge of where the big planet would be and then does a series of small thursts and brakes until it gets in range of the landing animation working... this is not an issue with the non-reverse thruster slew-round and thurst with main engines to stop a ship since the AI targets the centre of the object and so (almost) always gets in close enough to land first time.
Generally this is just a bit of wasted time and looking a little weird / messy but it can occassionally be the difference between life and death.
Note that this is not an issue when arriving at jump gates since they are large enough (with a large enough jump radious) to avoid the problem.

I'm happy for this to be "not-a-bug" but then I'd prefer that the pirate ship with an engine that is describes as a nova hazard also actually occassionally blow up on the player so that I can add in a dodgy itinerant ship "repair" and soup-up salesman who can tweek your ship to beyond specs in return for the risk of the system or even ship "failing" (spectaularly or otherwise) : D ... or is that too much realism? : P

**Comment by bobbens** [comment]
It's probably quirks with the PID system. It's a bit tricky, but it would probably be beneficial to try to improve it more, maybe with a different parametrization or something.

**Comment by PhoenixRiver** [comment]
That's something I never messed with I'm afraid so I'm not sure I'm qualified unless you might be able to point me in the right direction, even a file name would help! : D

**Comment by PhoenixRiver** [comment]
I've also just noticed that despite the fact I have reverse thrusters when I get the autonav to board a ship it always uses the power-slide! Apparently it forgot I've got the reverse thursters?

**Comment by bobbens** [comment]
Should be fixed in main, thanks!
