### ISSUE TITLE
Nightly - Llama stats...

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2071]
The Llama lists "turn_mod" amongst its stats twice...

`<stats>`
`  <turn_mod>-20</turn_mod>`
`  <speed_mod>-10</speed_mod>`
`  <turn_mod>-10</turn_mod>`
`  <cargo_mod>20</cargo_mod>`
`  <armour_mod>10</armour_mod>`
`  <cargo_inertia>-20</cargo_inertia>`
`  <ew_hide>-10</ew_hide>`
` </stats>`

This seems wrong to me... but maybe it is okay?

**Comment by bobbens** [comment]
It's getting overwritten by the second one. I pushed a fix (remove first one). Thanks!
