### ISSUE TITLE
Fussy: check return values of pilotL_newtask, ai_newtask, etc.

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#2076]
As exhibited in #2074 -- these can return NULL if there's a problem with the pilot, and we have a bunch of functions that will happily dereference NULL when that happens. This can turn a mission-breaking bug into a crashing bug, which might be worse.

**Comment by bobbens** [comment]
Wouldn't it be possible to just throw an NLUA_ERROR? It assumes that it's being run from Lua and that should solve everything no?
