### ISSUE TITLE
Substitute Speaker: everyone is speechless

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2079]
After "You make your way to the institute where you are supposed to give the talk, following the signs. On arriving you ask around where you should head to for your talk. Apparently you were already awaited. You are lead to a rather small seminar room. Finally you are ready to give your talk and a few scientist take seat. Actually you expected more than 17 listeners. Maybe this talk is not such a big deal as you expected. They wouldn't just send you to an important presentation, right?",
the mission silently ends.  Except for some error messages:

warning: [cust_mouse] Custom dialogue internal error: [string "scripts/love/graphics.lua"]:463: bad argument #2 to 'printfWrap' (string expected, got nil)
stack traceback:
        [C]: in function 'printfWrap'
        [string "scripts/love/graphics.lua"]:463: in function 'getWrap'
        [string "scripts/vn/core.lua"]:639: in function '_init'
        [string "scripts/vn/core.lua"]:519: in function 'init'
        [string "scripts/vn/core.lua"]:1611: in function '_checkDone'
        [string "scripts/vn/core.lua"]:531: in function 'mousepressed'
        [string "scripts/vn/main.lua"]:10: in function <[string "scripts/vn/main.lua"]:9>
        [C]: in function 'custom'
        [string "scripts/love.lua"]:269: in function 'exec'
        [string "scripts/vn/core.lua"]:1635: in function 'run'
        [string "missions/zalek/neburesearch/neburesearch_03.lua"]:306: in function 'enter_ship'
        [string "missions/zalek/neburesearch/neburesearch_03.lua"]:107: in function <[string "missions/zalek/neburesearch/neburesearch_03.lua"]:94>

It appears somehow the variable strings passed to vn.na end up as nil.

**Comment by UncombedCoconut** [comment]
Thanks, do you have a save available to help a lazy developer? :)

**Comment by UncombedCoconut** [comment]
Never mind, I was able to test. Thanks.
