### ISSUE TITLE
Gullible Robert

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2080]
When I'm supposed to test the shielding prototype, I can just install it in an Admonisher in Sindbad and swap my ship to a Peacemaker.
At Cerberus, Robert nags about the prototype, but does not protest any further when I go on to Nasona in the Peacemaker.  The interaction there gets somewhat bizarre, considering I have > 50 MW non-experimental shield regeneration, but I get a free shielding prototype out of it.
[tst-shield3.ns.gz](https://github.com/naev/naev/files/8102919/tst-shield3.ns.gz)

**Comment by UncombedCoconut** [comment]
Thanks, fixed this on main (not 0.9.x) branch. However, I'm seeing other issues with the mission, to be investigated.
