### ISSUE TITLE
fake transponder permanently sets faction standing

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2084]
After I got the flf standing to 50, I ferried pirate cargo around in dvaered space for a while to improve my raven clan standing.
At some point, my standings for empire/za'lek/frontier alliance/goddard/sirius/soromid/dvaered (45/43/30/30/30/30/-100) got
all stuck at the fake transponder default.
Because the saved settings are not displayed, I couldn't tell when it happened.  I only found this later:

Warning: [outfitLRunWarning] Pilot 'Jitterbug''s outfit 'Fake Transponder' -> 'onremove':
[string "outfits/unique/fake_transponder.lua"]:41: bad argument #1 to 'setPlayerStanding' (number expected, got no value)
stack traceback:
        [C]: in function 'setPlayerStanding'
        [string "outfits/unique/fake_transponder.lua"]:41: in function 'disable'
        [string "outfits/unique/fake_transponder.lua"]:56: in function <[string "outfits/unique/fake_transponder.lua"]:55>

**Comment by PhoenixRiver** [comment]
#2046 related

**Comment by amylaar** [comment]
I started with something fedora 35 came up with - calls itself 0.9.0 - and then switched to current git as I encountered bugs.
But I don't think any permanent factions were removed.  Even the Collective rating sticks around after the eding of the empire/collective campaign, even though my standing increases a bit (-88 to --87.1 - not sure if that is from acting against Dveared or accidentally defending myself against one of the Pirate clans I have a negative standing with.

Of course, dynamic factions come and go all the way, not sure if they could end up in data the fake transponder processes.

Btw, I noticed that a scanning incident (not sure if it's the transponder or the contraband) can further worsen the standing you
have with a Pirate clan - I think a pirate hypocritically discovered something 'illegal'?

**Comment by amylaar** [comment]
I tried to go back to from just reaching flf 50 standing and then polishing up the pirate standings, and the standings glitch
happened again.  With a twist.  I went from Benteen to Omega Station, and my transponder got discovered in Fortitude (i.e. in empire space, just a bit before landing).  As I had positive empire standing, that shouldn't have been a problem.
I found on the station I still had the uncovered standings.  I tried reloading (esc-x-l-l) and the game hang; the console
showed a crash:

Thread 1 "naev" received signal SIGSEGV, Segmentation fault.
It seems like naev has crashed. Please debug with gdb now ;)
array_size (array=0xbff0000000000000) at ../src/array.h:179
179	   return c1[-1]._size;
(gdb) bt
#0  array_size (array=0xbff0000000000000) at ../src/array.h:179
#1  equipment_calculateSlots (p=p@entry=0x4c8cab0, bw=bw@entry=180, bh=bh@entry=813, 
    w=w@entry=0x7fffffffcac8, h=h@entry=0x7fffffffcac0, n=n@entry=0x7fffffffcabc, 
    m=m@entry=0x7fffffffcab8) at ../src/equipment.c:545
#2  0x00000000004591d6 in equipment_renderSlots (bx=1224, by=196, bw=180, bh=813, 
    data=0x6a7460 <eq_wgt>) at ../src/equipment.c:587
#3  0x000000000051001e in cst_render (cst=0x54a5da0, bx=<optimized out>, 
    by=<optimized out>) at ../src/tk/widget/cust.c:133
#4  0x00000000005040c7 in window_render (w=w@entry=0x5af4e10) at ../src/toolkit.c:1529
#5  0x0000000000510a14 in tab_render (tab=0x4bfac00, bx=213, by=111)
    at ../src/tk/widget/tabwin.c:367
#6  0x00000000005040c7 in window_render (w=w@entry=0x56ad120) at ../src/toolkit.c:1529
#7  0x000000000050428f in toolkit_render (dt=dt@entry=2.3603454369999999)
    at ../src/toolkit.c:1624
#8  0x00000000004e2d9a in render_all (game_dt=<optimized out>, 
    real_dt=2.3603454369999999) at ../src/render.c:241
#9  0x00000000004a2a66 in main_loop (update=update@entry=1) at ../src/naev.c:711
#10 0x00000000004a382b in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/naev.c:441

IIRC, I had similar crashes before, but ignored them because I had no idea what had caused the crash, and I have no
intention on digging into the rendering code.

I tried to trigger the crash again by loading the backup file, flying the same route and making sure to be discovered before landing - but everything seems fine.

OTOH, when I load the file saved at Omega Station just before before the crash (that file has various faket_* variables with the right standings), I get the same error message as quoted above in the initial bug posting as soon as I unequip the fake transponder, and the transponder default standings are still in effect.

[faket-discovered.tar.gz](https://github.com/naev/naev/files/8105800/faket-discovered.tar.gz)

**Comment by PhoenixRiver** [comment]
> I tried to go back to from just reaching flf 50 standing and then polishing up the pirate standings, and the standings glitch happened again. With a twist. I went from Benteen to Omega Station, and my transponder got discovered in Fortitude (i.e. in empire space, just a bit before landing). As I had positive empire standing, that shouldn't have been a problem. I found on the station I still had the uncovered standings. I tried reloading (esc-x-l-l) and the game hang; the console showed a crash: Reached main menu
> 
> Thread 1 "naev" received signal SIGSEGV, Segmentation fault. It seems like naev has crashed. Please debug with gdb now ;) array_size (array=0xbff0000000000000) at ../src/array.h:179 179 return c1[-1]._size; (gdb) bt #0 array_size (array=0xbff0000000000000) at ../src/array.h:179 #1 equipment_calculateSlots (p=p@entry=0x4c8cab0, bw=bw@entry=180, bh=bh@entry=813, w=w@entry=0x7fffffffcac8, h=h@entry=0x7fffffffcac0, n=n@entry=0x7fffffffcabc, m=m@entry=0x7fffffffcab8) at ../src/equipment.c:545 #2 0x00000000004591d6 in equipment_renderSlots (bx=1224, by=196, bw=180, bh=813, data=0x6a7460 <eq_wgt>) at ../src/equipment.c:587 #3 0x000000000051001e in cst_render (cst=0x54a5da0, bx=, by=) at ../src/tk/widget/cust.c:133 #4 0x00000000005040c7 in window_render (w=w@entry=0x5af4e10) at ../src/toolkit.c:1529 #5 0x0000000000510a14 in tab_render (tab=0x4bfac00, bx=213, by=111) at ../src/tk/widget/tabwin.c:367 #6 0x00000000005040c7 in window_render (w=w@entry=0x56ad120) at ../src/toolkit.c:1529 #7 0x000000000050428f in toolkit_render (dt=dt@entry=2.3603454369999999) at ../src/toolkit.c:1624 #8 0x00000000004e2d9a in render_all (game_dt=, real_dt=2.3603454369999999) at ../src/render.c:241 #9 0x00000000004a2a66 in main_loop (update=update@entry=1) at ../src/naev.c:711 #10 0x00000000004a382b in main (argc=, argv=) at ../src/naev.c:441
> 
> IIRC, I had similar crashes before, but ignored them because I had no idea what had caused the crash, and I have no intention on digging into the rendering code.
> 
> I tried to trigger the crash again by loading the backup file, flying the same route and making sure to be discovered before landing - but everything seems fine.

Is this crash maybe related to #2081?

**Comment by amylaar** [comment]
As soon as I switched the window with gdb to the top (less then 10 seconds, (CPU is i7-4500U @ 1.80GHz), I saw the crash message.  So it's not hanging there doing a lot of processing.  I don't know if there is any deeper connection.

**Comment by UncombedCoconut** [comment]
> Is this crash maybe related to #2081?

Fortunately, no. :)
Unfortunately, it's potentially tricky. bobbens is looking at this, and checking out a connection to a graphical feature (window fade-out, and whether it keeps the equipment screen "alive" in an unsafe way).

**Comment by PhoenixRiver** [comment]
*yay* ... *boo* 🤷 

Do you know if anyone has had a look at the fake transponder code? I tried but I'm having problems following it... which might explain why there are problems with it *sigh*

**Comment by bobbens** [comment]
OK, so I should have fixed both issues (crash and fake transponder) in main. I've run quick tests and it all seems to work fine now. Thanks!
