### ISSUE TITLE
Equipment locked after info screen

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2090]
This just appeared after I did a git pull now: when I'm landed on a spob, and go to the equipment screen, and use 'i' to see my standings, the ship equipment vanishes instantly.  It does not come back by closing the info screen.  I can make the ship equipment be shown again by selecting the ship, but I can't unequip any individual piece of equipment any more by clicking on it.  Going to the bar and coming back doesn't help either.  Only taking off and landing.

**Comment by LJDude** [comment]
Oh I think I had this exact same issue recently. I noticed that the equipment disappeared and that I couldn't remove anything, but I didn't figure out that they were tied to each other, nor did I notice that it was tied to the info menu.

**Comment by bobbens** [comment]
Fixed, thanks!
