### ISSUE TITLE
Boarding Derelict is a non-event

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2098]
I just boarded a derelict and it just said "Boarding ship Derelict." , but nothing else seemed to happen.  An attempt to board again said "Your target cannot be boarded again."
output from the window where I started naev.sh shows:

Warning: [ai_run] Pilot 'Jitterbug' ai 'player' error: [string "ai/core/control/generic.lua"]:264: Asteroid field '0' is out of range!
stack traceback:
	[C]: in function 'pos'
	[string "ai/core/control/generic.lua"]:264: in function 'handle_messages'
	[string "ai/core/control/generic.lua"]:251: in function <[string "ai/core/control/generic.lua"]:245>
Warning: [gl_getSpriteFromDir] Angle not between 0 and 2.*M_PI [-0.508565].
Warning: [gl_getSpriteFromDir] Angle not between 0 and 2.*M_PI [-0.508565].
Warning: [event_runFunc] Event 'Derelict' -> 'board': [string "events/neutral/derelict.lua"]:235: bad argument #1 to 'ship' (pilot expected, got no value)
stack traceback:
	[C]: in function 'ship'
	[string "events/neutral/derelict.lua"]:235: in function 'neutralevent'
	[string "events/neutral/derelict.lua"]:150: in function <[string "events/neutral/derelict.lua"]:122>
Warning: [hook_runEvent] Hook [p_board] '2201' -> 'board' failed

This is the save file from before taking off:
[autosave.ns.gz](https://github.com/naev/naev/files/8147704/autosave.ns.gz)

**Comment by bobbens** [comment]
I think I should have fixed this in main. Thanks!
