### ISSUE TITLE
PANIC when I equip the cargo pod too late

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2099]
When I try to accept a pirate cargo mission with too little cargo space left, it gets rejected; when I then equip a cargo pod to
get sufficient space, and then come back to accept the mission again, it shows a reward of (nil).  When I accept anyways, the
game ends with a panic:

PANIC: unprotected error in call to Lua API (attempt to index a number value)
[Thread 0x7fffd579e640 (LWP 46115) exited]
[Thread 0x7fffd5f9f640 (LWP 46111) exited]
AL lib: (EE) alc_cleanup: 1 device not closed
naev: /builddir/build/BUILD/openal-soft-1.19.1/Alc/ALc.c:800: LockLists: Assertion `ret == althrd_success' failed.
/home/joern/naev/git/naev/.gdbinit:17: Error in sourced command file:
Couldn't read debug register: No such process.
(gdb) [Thread 0x7fffd4224640 (LWP 46119) exited]
[Thread 0x7fffd4425640 (LWP 46118) exited]
[Thread 0x7fffc37ff640 (LWP 46117) exited]
[Thread 0x7fffe3038640 (LWP 46110) exited]
[Thread 0x7ffff3ec8500 (LWP 46106) exited]

FWIW, I've also noticed that some missions are absurd with their cargo space requirements, like aborting the missions altogether when
you land with a ship with too little cargo space, even though on the planet you can swap ships and/or equip outfits with extra space.

**Comment by amylaar** [comment]
One is missions/neutral/antlejos/ant_supplies.lua .  Well, it's not exactly aborting, but it refuses to do the loading, which is only done immediately on landing.  You can take off and land again, but if you have any time critical mission running in parallel, that
might not be a viable option.  I would expect the guys to ask me to meet them in the bar (if available) or back at landing main once I have the space prepared.

**Comment by amylaar** [comment]
The ancious merchant will disappear if you don't have the cargo space necessary at the point you talk to them.  That's particularily galling since the probability of them coming up is so low.

**Comment by bobbens** [comment]
Did anxious merchant mission (and upped appearing chance, 1% is really low).

**Comment by amylaar** [comment]
zalek/neburesearch/neburesearch_05.lua is also odd since it requires the player to present with a ship of at least corvette class to accept the mission, even though that ship is to be deployed quite a bit away, lest Dr. Mensing just goes away .  Well, it's not a big deal, since the probability is 100% and there's a shipyard, but I end up exiting the game and loading to make Dr Mensing come back, changing into a biggger ship, accepting the job, then changing back into my fast runabout to get to a shipyard near the mission location.

**Comment by amylaar** [comment]
missions/zalek/zlk_cargorun.lua is also a mission with only 10% chance that vanishes if you don't have the required cargo space.

**Comment by bobbens** [comment]
I'll close this as the main issue is fixed. Thanks again!
