### ISSUE TITLE
Derelict: map not found

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2101]
Warning: [outfit_get] Outfit 'Map: Local System Map' not found in stack.
Warning: [event_runFunc] Event 'Derelict' -> 'board': [string "events/neutral/derelict.lua"]:315: Outfit is invalid.
stack traceback:
	[C]: in function 'numOutfit'
	[string "events/neutral/derelict.lua"]:315: in function 'goodevent'
	[string "events/neutral/derelict.lua"]:152: in function <[string "events/neutral/derelict.lua"]:122>
Warning: [hook_runEvent] Hook [p_board] '3287' -> 'board' failed
Warning: [outfit_get] Outfit 'Map: Local System Map' not found in stack.
Warning: [event_runFunc] Event 'Derelict' -> 'board': [string "events/neutral/derelict.lua"]:315: Outfit is invalid.
stack traceback:
	[C]: in function 'numOutfit'
	[string "events/neutral/derelict.lua"]:315: in function 'goodevent'
	[string "events/neutral/derelict.lua"]:152: in function <[string "events/neutral/derelict.lua"]:122>
Warning: [hook_runEvent] Hook [p_board] '3314' -> 'board' failed

**Comment by bobbens** [comment]
Thanks! I was actually looking at the code and just found this issue. Should be fixed in main.
