### ISSUE TITLE
Alicias speech has become disingenious

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2102]
When escaping to the Thurions at the end of the flf catastrope, Alicia says, inter alia:
We very well might have some missions for you in the future. In the meantime, buy yourself one of our nebula-resistant ships, and make yourself comfortable.

With all the Thurion ships restricted, and the starting standing for Thurion set to 1, it is impossible to buy any of their ships now.
Even if missions should be added later that allow to improve your standing with the Thution, the order Alicia suggests is impossible.

**Comment by bobbens** [comment]
I've made it mention nebula-resistant coating for now, but most of the flf-dvaered campaign has to be reworked in the future. Thanks!
