### ISSUE TITLE
Empire cargo mission disappears when there is not enough free cargo space.

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2107]
When you select the mission without having enough cargo space, it disappears.
This happens regardless of the presence of an outfitter and/or shipyard, or if you have missions that you could chancel.

This also happens with the emipre long distance cargo mission.

**Comment by bobbens** [comment]
OK, I went through all the missions and changed them all to not finish. There are a couple of exceptions where the text explicitly ends the mission, but the rest should all leave the npc even if you have trouble. Hopefully I didn't miss anything. Thanks!
