### ISSUE TITLE
The Crimson Gauntlet doesn't work fine if the button texts are translated.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2112]
The Crimson Gauntlet doesn't work fine because the GUI uses the text as an ID in the Lua code.

Example PO date:
```po
#: dat/missions/dvaered/gauntlet/gui.lua:134
msgid "Skirmisher"
msgstr "小競りあい"

#: dat/missions/dvaered/gauntlet/gui.lua:134
msgid "Warrior"
msgstr "戦士"

#: dat/missions/dvaered/gauntlet/gui.lua:134
msgid "Warlord"
msgstr "軍閥領袖"

#: dat/missions/dvaered/gauntlet/gui.lua:190
msgid "Challenge"
msgstr "挑戦"
```

I noticed two errors.
(1) The button text compares a literal text at the line 132 in gui.lua:
```
   if newtype == "Challenge" then
```
(2) The button text uses as a key of a table at the line 341 in gauntlet.lua: (if I remember rightly)
```
local round_enemies = tables.wave_round_enemies[mem.wave_category]
```
mem.wave_category comes from a button text.

**Comment by bobbens** [comment]
Should be fixed in 7b81301be468919576b30f1ad936c193b244aa21 . Tested it locally in Japanese and it seems to work, thanks!
