### ISSUE TITLE
Steam 0.9.2 - Commodity Delivery doesn't mark planet...

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2115]
When doing a Commodity Delivery the destination planet is not shown in the overlay unlike Shipments, etc. (i.e. everything else) even though it is marked in the Mission OSD...

**Comment by PhoenixRiver** [comment]
Also doesn't happen for the "Help the Drunkard" mission...

**Comment by PhoenixRiver** [comment]
I think this should now be fixed via #2116

**Comment by bobbens** [comment]
Closed via merge of #2116, thanks!
