### ISSUE TITLE
Horrendous Lag ingame for some reason

### ISSUE THREAD

**Issue by dbt0815** [naev/naev#2120]
hard fps problems. strong laggs. makes it unplayable for me.
wanted to try it out since i read about it on twitter. :(

Ram: 8gb
Cpu: AMD 3020e (2x 1,6ghz) with integrated Radeon Graphics

im using the latest version of the game. 9.2.0

The CPU isnt that good i suppose, but considering i can play minecraft almost flawlessly (java), i wonder if its me or the game making problems.

Thank you in advance.

**Comment by LJDude** [comment]
Wow, that cpu is even weaker than my 2017 pentium. The igpu is better, but from my understanding, naev isn't a graphics heavy game at all.
That cpu is probably your issue. You may want to mess around with the video settings to see if there's something you can do for better performance.

**Comment by dbt0815** [comment]
as i stated, im very confused about the fact, that i can play several other games without issue but not this.. sad life. it seems as naev would be my type of game.

**Comment by bobbens** [comment]
Can you give more details? What operating system are you running? Could you past the full logs? They should be located at https://github.com/naev/naev/wiki/Bugs#log-location

**Comment by PhoenixRiver** [comment]
> as i stated, im very confused about the fact, that i can play several other games without issue but not this.. sad life. it seems as naev would be my type of game.

Unfortunately most games have (for a long time) been heavy on the graphics side of things... Naev is different in that respect, it is a bit CPU heavier - that said, reducing the graphics settings could help - maybe reduce the resolution, that might have the biggest impact...

**Comment by dbt0815** [comment]
I just wanted to mention that i tried the latest nightly of Naikari. A fork from NAEV which runs perfectly, so im still not quite sure whats the problem there. :/
Just thought it could be interesting.

**Comment by not-pyroman** [comment]
> I just wanted to mention that i tried the latest nightly of Naikari. A fork from NAEV which runs perfectly, so im still not quite sure whats the problem there. :/
> Just thought it could be interesting.

Naikari has split off somewhere at 0.8's development if i recall correctly, and while they did fork it from naev, they mostly only did their own development separate from Naev for the most part, with the occasional commit being fetched, but it is far different enough from naev to where it is not a very good comparison

**Comment by not-pyroman** [comment]
Also like bobbens asked it would greatly help us narrow down any potential problems if you sent the log files

**Comment by bobbens** [comment]
Either this is solved by the new faster collision code, or it can be solved by using the same solution in https://github.com/naev/naev/issues/2339 if it is an issue with the circuit shader. If it is an issue with another shader, we would need to debug it. Since we have no additional information to narrow it down, closing the issue for now.
