### ISSUE TITLE
Text positioning in overlay map... - 0.9.2 Steam : Windows

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2130]
So, when you look at the overlay map and have a Sightseeing or Patrol mission that is marking spobs to pass over then you'll notice that the text "Attraction" or "Patrol Point" (respectively) overlays the name of the spob in almost all cases. It does not overlay it when the name of the spob would overlay another spob or _its_ name ... needless to say that the mission text does car and overlays everything.

I have hunted this down and have traced it to beyond Lua fixable, the C code does not allow the Lua code to add text anywhere but (apparently) to the right of the spob. Digging into the C code it appears that this function: static void ovr_optimizeLayout in map_overlay.c is responsible for jiggling the text name of a spob so that it doesn't get messy... however it appears to default to putting that text to the right of the spob... would it be possible to have it default to the left or even above or below? This way the Lua code for missions could continue to play its text tot the right which would now work for almost all cases (excepting the difficult edge cases which the huge above C function can't even always get right!)

I'd fix it but I am both tired and this C function is picky and appears carefully balanced and I really don't have the skill right now to try and understand it to fix it.

So I guess this is a suggestion and a bug.

**Comment by bobbens** [comment]
Yeah, the dynamic system marker name positions don't get optimized to avoid overlap. The proper solution would be to integrate it into the optimization thing. Shouldn't be too unreasonable. A more short-term solution could be to do like what you say and just displace the position to below or above, or even just displace it C-side.

**Comment by bobbens** [comment]
OK< so the text positioning should be better for system markers and such. Still have to handle this for pilot names, but I guess it's an improvement for now.
