### ISSUE TITLE
Tarball for 0.9.3 untars to 0.9.2

### ISSUE THREAD

**Issue by heirecka** [naev/naev#2139]
It seems to be different from 0.9.2 and contain changes matching the tags in github, it unpacks to naev-0.9.2. Which is a tad annoying when packaging and a bit surprising/confusing in general.

**Comment by ProjectSynchro** [comment]
Hi, it looks like the project version in Meson wasn't bumped to 0.9.3, I'll reupload a fixed tarball shortly.

**Comment by ProjectSynchro** [comment]
Just an update on this,
I have re-tagged v0.9.3, this should have up-to-date metainfo and the tarball should extract to the correct version.

You can view the release status here: https://github.com/naev/naev/actions/runs/2086653135
When it's finished you can grab the tarball from here: https://github.com/naev/naev/releases/tag/v0.9.3

Sorry about that.
