### ISSUE TITLE
Some merged msgids that come from different contexts are hard to translate for Japanese language.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2140]
Gettext merges same messages into a single msgid. Some merged msgid that comes from different contexts cannot translate into a single msgstr.
I recommend that Naev have a way to distinguish different contexts, such as msgctxt in GNU gettext or "Caret hints" in Wesnoth. ("Caret hints" is almost same as msgctxt but the separator character is '^', so it needs no different function forms such as pgettext(msgctxt, msgid).) Translators can post PRs that add a msgctxt to the msgid as needed once Naev support the context mechanism. I notice Naev currently seems to support msgctxt in C (only literal) and XML, but not in Lua. Could you create a support to msgctxt in Lua?

<details><summary>For now, these msgids that I would like to translate into multiple msgstrs:</summary><div>

1. I would like to add a msgctxt into C
1.1 Impossible to translate
```PO
#: dat/factions/standing/lib/base.lua:37 src/info.c:870
msgid "Legend"
```

2. Lua
2.1 Very hard to translate properly
```PO
#: dat/missions/neutral/antlejos/ant_supplies.lua:62 src/outfit.c:307
msgid "Small"

#: dat/missions/neutral/antlejos/ant_supplies.lua:64 src/outfit.c:309
msgid "Medium"

#: dat/missions/neutral/antlejos/ant_supplies.lua:66 src/outfit.c:311
msgid "Large"

#: dat/missions/pirate/blackcat.lua:269
#: dat/missions/zalek/blackhole/zbh02.lua:121
#: dat/missions/zalek/blackhole/zbh02.lua:138
msgid "\"Yes.\""
```

2.2 Very odd
```PO
#: dat/commodities/iron.xml:3 dat/scripts/pilotname/pirate.lua:87
msgid "Iron"

#: dat/scripts/pilotname/generic.lua:26 dat/scripts/pilotname/pirate.lua:283
#: src/menu.c:594
msgid "Death"
```

2.3 odd, or funny
```PO
#: dat/missions/minerva/kex3.lua:312 dat/missions/minerva/maikki2.lua:479
#: dat/missions/minerva/maikki2.lua:760
msgid "\"What do you want?\""

#: dat/missions/minerva/kex3.lua:334 dat/missions/zalek/blackhole/zbh02.lua:70
#: dat/missions/zalek/blackhole/zbh03.lua:84
#: dat/missions/zalek/blackhole/zbh04.lua:63
#: dat/missions/zalek/blackhole/zbh05.lua:64
#: dat/missions/zalek/blackhole/zbh07.lua:53
#: dat/missions/zalek/blackhole/zbh08.lua:71
#: dat/missions/zalek/blackhole/zbh09.lua:66
#: dat/missions/zalek/blackhole/zbh11.lua:65
msgid "\"OK. I'll be here if you change your mind.\""

#: dat/missions/minerva/kex4.lua:157 dat/missions/zalek/blackhole/zbh10.lua:218
msgid "\"What?\""
```

2.4 Both Ship AI and Nelly speak politely because they give a same explanation at a single point, but I afraid you intend that Nelly speaks with more familiarity overall.
```PO
#: dat/events/shipai.lua:134 dat/missions/tutorial/nelly02.lua:543
msgid ""
"\"Each ship has three important electronic warfare statistics:\n"
"- #oDetection#0 determines the distance at which a ship appears on the "
"radar.\n"
"- #oEvasion#0 determines the distance at which a ship is fully detected, "
"that is, ship type and faction are visible. It also plays a role in how "
"missiles and weapons track the ship.\n"
"- #oStealth#0 determines the distance at which the ship is undetected when "
"in stealth mode\""
```

2.5 acceptable, but slightly odd
```PO
#: dat/ai/advertiser.lua:103 dat/scripts/pilotname/pirate.lua:232
msgid "Ass"

#: dat/events/start.lua:35 dat/scripts/factions/dvaered.lua:20
msgid "Vagabond"

#: dat/scripts/common/shadow.lua:9 dat/scripts/pilotname/generic.lua:76
msgid "Shadow"

#: dat/scripts/factions/soromid.lua:17 dat/scripts/pilotname/generic.lua:43
#: dat/scripts/pilotname/pirate.lua:328
msgid "Hunter"

#: dat/scripts/factions/soromid.lua:26 dat/scripts/pilotname/pirate.lua:176
msgid "Violent"

#: dat/ships/zalek_drone_scout.xml:2 dat/missions/minerva/pirate2.lua:106
msgid "Za'lek Scout Drone"

#: dat/missions/dvaered/frontier_war/fw01_sabotage.lua:434
#: dat/missions/dvaered/frontier_war/fw04_meeting.lua:206
msgid "Come on!"

#: dat/missions/zalek/blackhole/zbh09.lua:407
#: dat/missions/zalek/particlephysics/zpp03.lua:177
msgid "Watch out!"

#: dat/missions/neutral/antlejos/ant01.lua:81
#: dat/missions/zalek/zlk_cargorun.lua:93 src/land.c:993
msgid "Equipment"

#: dat/missions/zalek/blackhole/zbh08.lua:33
#: dat/missions/zalek/blackhole/zbh08.lua:117
msgid "Sensor Upgrades"
```

3. Input tab in Option panel, it may be in C code?
The key bindings in the Input tab in Option panel shows the translated texts, although there are not the source locations in naev.pot. Do you think the key bindings should show the translated texts?

```PO
#: dat/scripts/pilotname/pirate.lua:146
msgid "Space"

#: dat/events/discovery.lua:30
msgid "Home"

#: src/dev_sysedit.c:1662 src/dev_sysedit.c:1805 src/info.c:1563 src/load.c:488
#: src/load.c:554
msgid "Delete"

#: src/input.c:110
msgid "Pause"
```

4. XML
I think it needs to add no context, but it's a bit odd in Japanese language.

```PO
#: dat/commodities/gold.xml:3 dat/ssys/gold.xml:2
msgid "Gold"
```

</div></details>

**Comment by bobbens** [comment]
Added `pgettext` and `p_` support to Lua. If we identify the places that need disambiguation it should be able to use `pgettext` to distinguish them. It may be possible to run some regex voodoo to identify all short strings and add context support.

**Comment by oo13** [comment]
Thank you, but the first parameter of pgettext in Lua seems to be different from GNU pgettext(msgctxt, msgid). gettext_pgettext() in C apparently takes the string concatinated msgctxt, '\x04', and msgid instead of msgctxt as first parameter. Could you modify the function into compatible with GNU pgettext?

I think it's enough to make translators report a problem in their language and then you accept it because almost msgids have no problem. I will post a PR before long.

**Comment by UncombedCoconut** [comment]
> Thank you, but the first parameter of pgettext in Lua seems to be different from GNU pgettext(msgctxt, msgid). gettext_pgettext() in C apparently takes the string concatinated msgctxt, '\x04', and msgid instead of msgctxt as first parameter. Could you modify the function into compatible with GNU pgettext?

Sure! Done.
