### ISSUE TITLE
Naev 0.9.4 crashes on startup on Mac

### ISSUE THREAD

**Issue by dixius99** [naev/naev#2160]
Testing out 0.9.4 on macOS (Monterey), and upon launch, I get a macOS Problem Report.

I can post the whole report, but it appears to be due to a missing dylib: **libgcc_s.1.1.dylib**

Looking in Contents > Frameworks, I see that this file isn't there, while on 0.9.3, the libgcc dylib is there (**libgcc_s.1.dylib**), and it works fine.

**Comment by UncombedCoconut** [comment]
Thanks for the report! I'll update the bundle.py script which takes care of packing these libraries, and look into replacing just the macOS install image.

**Comment by UncombedCoconut** [comment]
https://github.com/naev/naev/releases/download/v0.9.4/naev-0.9.4-macos.dmg is now updated (also over 40 MB smaller -- we forgot to backport an optimization). We're about to update the Steam and itch.io releases as well. Thanks again.
