### ISSUE TITLE
desc_extra in outfits/bioship is not translatable.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2174]
Some outfits of the bioships have <desc_extra> attribute, but it's not translatable, because naev.pot doesn't have the original texts.

<details><summary>We need the texts that are replaced {damages:.1f} in weapon.xml.template with some proper values.</summary><div>

stinger_organ_i.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 8.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
stinger_organ_ii.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 13.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
stinger_organ_iii.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 18.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
talon_organ_i.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 10.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
talon_organ_ii.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 20.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
talon_organ_iii.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 30.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
talon_organ_iv.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 40.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
tentacle_organ_i.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 30.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
tentacle_organ_ii.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 36.7 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
tentacle_organ_iii.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 43.3 of damage over 5 seconds on the target.&lt;/desc_extra&gt;
tentacle_organ_iv.xml:  &lt;desc_extra&gt;Plasma burns deal an extra 50.0 of damage over 5 seconds on the target.&lt;/desc_extra&gt;

</div></details>

**Comment by bobbens** [comment]
I've made it so that Lua supports `desc_extra` (with the `descextra` function). It should be translatable now (and more flexible), thanks!
