### ISSUE TITLE
Brushed GUI shows the incorrect weapon's list at the begin of the game.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2178]
I selected weapon set#2 and landed, ended, loaded, and took off, and then Brushed GUI shows weapon set ID 2 and the active weapons in weapon set#1.

You need to press "1" and "2" to get correct weapon's list after taking off.

![1](https://user-images.githubusercontent.com/22392249/184478861-b29de432-52ca-4224-8bcb-252be6023fc5.jpg)

**Comment by bobbens** [comment]
Should be fixed in main, thanks for the report!
