### ISSUE TITLE
Asteroids disappear when NPCs drill them

### ISSUE THREAD

**Issue by bobbens** [naev/naev#2186]
Not sure why this happens, outfit code is the same as the player. Testing in Lua console doesn't replicate the issue... They should fade out and disappear instead.

**Comment by UncombedCoconut** [comment]
I think it's just because asteroid.c applies the fade-out logic to asteroids the player has scanned? That's a prerequisite for the player drilling one, but not an NPC.
I'm not sure I really understand why the fade is a "scan" fade, though. :)

**Comment by bobbens** [comment]
Really? From what I see the `scan_alpha` only affects the text, not the asteroid itself.

**Comment by UncombedCoconut** [comment]
OK, not really.
Better hypothesis: If nothing stops them, AIs will just spam their drill outfit at superhuman speeds. (If they're actually in range and it does anything, great.)
Adding a debug-print to `asteroidL_setTimer` shows something like this happening in what might be the span of 4 frames -- too fast for me to follow, anyway:
```
Asteroid 17: timer=-1.000000, timer_max=86.430110 state=ASTEROID_FG
Asteroid 17: timer=-1.000000, timer_max=3.977049 state=ASTEROID_FG_TO_BG
Asteroid 17: timer=-1.000000, timer_max=27.564310 state=ASTEROID_BX
Asteroid 17: timer=-1.000000, timer_max=1.264143 state=ASTEROID_BG_TO_XX
```
I notice the player gets the asteroid un-targeted pretty much instantly after dropping it out of FG state.
I'm not sure if that happens by a mechanism shared with AIs though?

**Comment by bobbens** [comment]
Issue was the AI chain using the outfit without any validity check of the asteroid in the middle.
