### ISSUE TITLE
Mission "Za'lek Test" has never been offered in a Japanese environment

### ISSUE THREAD

**Issue by oo13** [naev/naev#2192]
The mission's &lt;cond&gt; is always false because spob.cur():services()["outfits"] in a Japanese environment is a translated text which is not equal to "Outfits".

A mission &lt;cond&gt; should evaluate spob.cur():services()["outfits"] as boolean or/and it should be an untranslated text.

I'm not sure the latter change has any side effects, but Naev Lua API document says nothing about the value of the elements in the table.

&lt;cond&gt; in "Za'lek Test":
```
 <cond>faction.playerStanding("Za'lek") &gt; 5 and spob.cur():services()["outfits"] == "Outfits"</cond>
```

Usage of spob.services(p) in Naev Lua API:
```
if p:services()["refuel"] then -- Spob has refuel service.
```

**Comment by bobbens** [comment]
I've done a quick grep and it seems like the za'lek test mission is the only one doing this. I've changed it to treat it as a boolean, so it should fix the issue. I guess the correct way is to use `p:services()["refuel"] ~= nil` in conditionals (so it becomes a boolean) and `if p:services()["refuel"] then` elsewhere. I've pushed a fix for this mission. Thanks!
