### ISSUE TITLE
Chapter 1 softlocks when landing on a planet with no shipyard

### ISSUE THREAD

**Issue by bobbens** [naev/naev#2213]
```
Lemuria the Illegal Waste Dumper
 — 
今日 06:05
Start of Chapter 1 softlocks me when I land on a planet with no ability to manage the fleet
```

Probably some ships are getting somehow marked as deployed before the event is run and then the bug happens. Possible solutions:
1. Reset deployment when first adding fleet capacity
2. Make sure that nothing can be marked as deployed with no fleet capacity

**Comment by a-random-lemurian** [comment]
P.S. I am `Lemuria the Illegal Waste Dumper`, `Lemuria#0685`, for future reference.

**Comment by bobbens** [comment]
Should not be possible to soft-lock anymore. Made it so you can't deploy without fleet capacity, and the event clears deployment just in case, followed by rescue script also handling deployment.
