### ISSUE TITLE
Weirdly formatted text: "You see a <person name>"

### ISSUE THREAD

**Issue by VorpalBlade** [naev/naev#2257]
It seems that "Nelly" is supposed to be a proper noun (a name), but in the text on the side (indicated by red arrow) there is the phrase "a Nelly".

OS: Arch Linux (rolling release distro, so no version number)
Version: 0.10.0-1 (installed from Arch Linux packages)

![image](https://user-images.githubusercontent.com/3315306/209566757-15649c4d-1b12-495c-84ed-62d258711d85.png)

**Comment by bobbens** [comment]
Thanks for the report, should be fixed!
