### ISSUE TITLE
Inconsistent units for in game volume levels

### ISSUE THREAD

**Issue by VorpalBlade** [naev/naev#2258]
The top two volume levels are in the range 0-1 and also show attenuation in dB (which makes perfect sense, and is a nice nerdy thing to do). The engine volume is listed in percent (which also makes sense, but is a bit boring in comparison).

I do think it should be consistent however.

![image](https://user-images.githubusercontent.com/3315306/209567251-4d38c1ce-da37-4550-b022-97d32c5f7d0b.png)

**Comment by bobbens** [comment]
Should be fixed, thanks!
