### ISSUE TITLE
Sec status vs docking rights for hauler missions to match faction standings

### ISSUE THREAD

**Issue by naev** [naev/naev#226]
Original [issue 42](https://code.google.com/p/naev/issues/detail?id=42) created by GlennnDa... on 2010-01-20T06:31:34.000Z:

<b>Write a brief description of the feature you would like to request, why you</b>
<b>would want it and how you think it would be best to be implemented (broad</b>
<b>design).</b>

Yarrrr!!

I'm a pirate.  I got tired of the failed jorek and the failed flf 
infiltrate mission .   so i killed all the dvareans until my security 
status changed to meet pirate and flf rebel green status

I am now a Dirty scoundrel in new haven.   Market is stocked, but no 
mission sets.

How does a unemployed pirate turn a buck?

I designed a new 3ds pirate ship and talking to Del about designing pirate 
missions  one problem

Missions needed to be coded on availability according to sec status.  for 
the docking rights.  Currently you have to pay bribes to do it.

Cheers.

**Comment by onpon4** [comment]
Ping-pong! I believe this issue has been solved by some of my recent commits, if I understand what the original author was saying correctly. You're now able to do pirate missions just by landing on a pirate stronghold, and some can even be done from neutral planets.
