### ISSUE TITLE
Game Closes itself when Boarding hidden Pristine Derelicts

### ISSUE THREAD

**Issue by HGScout** [naev/naev#2264]
starting from about roughly yesterday (about 20 hours ago at time of posting), my game just closes on itself without warning whenever I try to board the hidden derelicts. hearing tipsy patrons, moving to a system, scanning and following trails work fine, but as soon as I try to board some of the derelicts that spawn the game just closes itself. no warning, no error log, just kicked out to the desktop screen.

oddly, no error logs were generated to the directory(all files starting from yesterday ends with 'stdout', not 'stderr'). the game just closes the moment I decelerate and initiate boarding. Due to this, I will try to describe what happend at the moment:

currently have all shop items from Mizi, and have 2 datacores. no ship modification from Mizi chosen yet.

First encounter of Bug was in Solene, in the gap below soromid  and empire space. roughly 20 hours before from time of posting.
Derelict was Koala, game closed immediately apon boarding attempt.
tried again an hour and a half ago, game closed again. Quest abandoned.

Second encounter of bug was in Treacle, in the northeastern part of soromid space. roughly hour and a half from time of posting.
Derelict was Koala, game closed immediately apon boarding attempt.
tried again after the success of third derelict boarding attempt, game closed again. Quest still active.

Third derelict boarding attempt was in the NGC-8468 system Northwestern of soromid space
Derelict was Mule. boarding, minigame, and reward dialog progressed without problem. obtained credits.

No new error logs were generated during testing.

**Comment by bobbens** [comment]
Thanks for the report. What version are you getting this on? If you have a save it may be helpful in tracking down the issue

**Comment by HGScout** [comment]
the attempts with the first derelict was the 0.10.0 I think, later attempts happened after today's update.

I guess I should upload my save file in this repository?

**Comment by bobbens** [comment]
You should be able to attach it here. If it doesn't work with the .ns extension, you can zip it first. Thanks!

**Comment by HGScout** [comment]
[Kestrel.zip](https://github.com/naev/naev/files/10320040/Kestrel.zip)

oh thats how you do it
here it is

**Comment by bobbens** [comment]
Talked a bit about it in discord below. tl;dr either release build or OS-specific issue we have to further debug
```
H.G.Scout
 — 
2022/12/30 00:12
it closes as if I clicked on the x button, there's no text box or prompt popping up
Justin Blanchard
 — 
2022/12/30 00:13
release builds might not
H.G.Scout
 — 
2022/12/30 00:13
just closes and nothing
Justin Blanchard
 — 
2022/12/30 00:13
maybe that's an overconfident design decision 🙂
so, depending on which version of the game is installed and how, trying a nightly might be a good step
bobbens
 — 
2022/12/30 00:16
would be "fun" if it was a release vs debug issue
H.G.Scout
 — 
2022/12/30 00:19
currently playing the v0.10.1 version
Justin Blanchard
 — 
2022/12/30 00:20
If it's via Steam, beta settings allow for trying a nightly build (which hopefully can emit more debugging info when it dies).
And if it's not, it's still an option, just a little more manual.
Amusingly, nightly is less recent than release this morning, but I wouldn't expect it to cause any issues.
bobbens
 — 
2022/12/30 00:21
(at least not for POI)
H.G.Scout
 — 
2022/12/30 00:36
no crash this time, it was the same second attempt koala
Justin Blanchard
 — 
2022/12/30 00:36
oh joy
H.G.Scout
 — 
2022/12/30 00:37
boarding, hacking, and loot dialog went without problems, it was a ship filled with smelly goo and some white screen change and a note about an iguana caretaker who got his fingers bitten off or something 
using nightly build thingy from steam
Justin Blanchard
 — 
2022/12/30 00:38
so it's either a release-build issue or a nondeterministic issue. that makes it harder to solve.
H.G.Scout
 — 
2022/12/30 00:38
anything else I can do to help?
Justin Blanchard
 — 
2022/12/30 00:38
just so we know which build was doing this (at least on your machine) - which OS?
H.G.Scout
 — 
2022/12/30 00:39
Windows 10. closing happened on the today's update build and before, nightly build let the quest happen. 
```

**Comment by UncombedCoconut** [comment]
This is pretty definitely fixed by https://github.com/naev/naev/commit/f9bf9244b76cbc087bef1dbc4629cc11fd3ccafc - to be released as soon as we're ready to do a release, more or less.
