### ISSUE TITLE
In Trader Escort mission, some escorted ships don't land at the destination.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2272]
In Trader Escort mission, when the caravan reaches the destination, some escorted ships often don't land.

I'm not quite sure, but I guess it happens when the leader's ship (_escort_convoy[1]) lands before other ships do.

**Comment by bobbens** [comment]
I was able to reproduce and narrow down the bug. It should be fixed in both 0.10.x and main. Thanks!
