### ISSUE TITLE
Mission Incompatibility Crash

### ISSUE THREAD

**Issue by JamesDeMonet** [naev/naev#2282]
**Summary:** When attempting to land on the planet "The Wringer" with two story missions both pointing to that location, the game crashes every time.

**Detail:** When landing on "The Wringer" with a (possibly related) combination of mission steps pending, the message update for "The Return" is displayed ('sorry we missed you...here's some cash...' etc - note that this does not require entering the bar, it shows up on the Landing Main page).  Upon clicking "OK" to the mission's update, the game instantly crashes (no error given, complete program closure, no windows exception reported by the OS, but the event is visible in the Event Viewer).

**Open Mission List:**
Dark Shadow (Look for Jorek on The Wringer in the Suna system)
The Return (Fly to The Wringer in the Suna system and deliver the message)
Sirius Rehabilitation (You need to gain 0 more reputation)

**Ship:** Vigilance
**Cargo Space Available:** 100

**Game Version:** v0.10.2

**Repeatability:** 4/4

**Class:** A - Showstopper

**Windows Event Data:**
Faulting application name: naev.exe, version: 0.10.2.0, time stamp: 0x63bf97ac
Faulting module name: lua51.dll, version: 0.0.0.0, time stamp: 0x63bf9758
Exception code: 0xc00000fd
Fault offset: 0x0000000000020d9f
Faulting process id: 0x24f4
Faulting application start time: 0x01d927eb75f78cb8
Faulting application path: D:\Program Files (x86)\Steam\steamapps\common\Naev\naev.exe
Faulting module path: D:\Program Files (x86)\Steam\steamapps\common\Naev\lua51.dll
Report Id: d730d024-0627-4915-bd02-0916bbac11be
Faulting package full name: 
Faulting package-relative application ID:

**Comment by JamesDeMonet** [comment]
If I abort "The Return" mission, I can safely land on The Wringer and complete "Dark Shadow".  If I attempt to abort "Sirius Rehabilitation" (prior to travelling to The Wringer), the game crashes (repeatability 2/2).  It my be an issue with reputation change caused by "The Return" while having a rehab mission open.

**Comment by bobbens** [comment]
Could you upload your save here if possible please?

**Comment by JamesDeMonet** [comment]
[Crash-Prone Mission Combo.zip](https://github.com/naev/naev/files/10419831/Crash-Prone.Mission.Combo.zip)

**Comment by bobbens** [comment]
OK, thanks! I was able to reproduce and fix it. Should be out in the next version.

**Comment by JamesDeMonet** [comment]
Sounds good!  Thanks!
