### ISSUE TITLE
Dvaered reputation limit after Sindbad

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2283]
After accomplishing the destruction of Sindbad the player gets +5% standing for the Dvaered. E.g. from 40 to 45%. These were my numbers in the standings tab.

After saving and reloading, I still have a standing of 45% but the maximum reputation is down at 40% in the standings tab.
[Dvaered-45.zip](https://github.com/naev/naev/files/10420520/Dvaered-45.zip)

By the way: You've done an incredibly good job with Naev. Congratulations! I like the irony and the way "the creator" and other aspects are woven in.

**Comment by bobbens** [comment]
Thanks for the detailed report! Should be fixed in the next version which should be out soonish given we found some other nasty bugs.
