### ISSUE TITLE
Daphne's Leap and Emergency Shield Booster cause SIGSEGV.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2285]
I notice the problem in main, 0.10.x, and v0.10.3 on Linux (local build).

How to reproduce:
1. Rename [autosave.ns.txt](https://github.com/naev/naev/files/10480374/autosave.ns.txt) to autosave.ns and load it.
2. Take off and jump to Arandon.
3. push '8' and activate Booster.

**Comment by bobbens** [comment]
Oops, that's not good. Should be fixed, probably should push another point release for this :/
