### ISSUE TITLE
Bug? Strange process of the operation Cold Metal

### ISSUE THREAD

**Issue by oo13** [naev/naev#2286]
I played it on v0.10.3 and main.

The process of the operation Cold Metal:
1. The collective drones almost ignore the empire fleet and go to a jump point.
2. The empire fleet easily destroys Starfire.
3. The collective drones destroy Fuel Tanker.
4. The empire fleet goes toward the jump point and the actual battle begins.

Is it intentional?

**Comment by not-pyroman** [comment]
Definitely doesn't sound intentional just from memory, I'm pretty sure the intention was for the empire to kill the drones before starfire

**Comment by bobbens** [comment]
I've retouched and fixed, it should be working much better now. Thanks!
