### ISSUE TITLE
NAEV 0.10.4 released as Win64 installer does not work on my W10

### ISSUE THREAD

**Issue by Mutos** [naev/naev#2291]
Hello all,

Having problems with compiling NAEV 0.10.4 on Windows 64 on my W10 laptop, I finally downloaded the pre-packaged file :
https://github.com/naev/naev/releases/download/v0.10.4/naev-0.10.4-win64.exe

I ran the installer and everything was fine, no error.  But when running naev.exe, I got the attached screen, showing a buggy NAEV window w/ green lines over the NAEV screen.

As far as I could try, the keyboard answered, I could navigate the menus, but the screen is garbeld and the game unplayable.
![W10-Error](https://user-images.githubusercontent.com/3622670/217009592-ef15ad5b-3a2f-4f24-8524-766f0b79513d.png)

Thanks for any hint as to the possible cause and solution for this problem.

@+
Benoît 'Mutos' Robin

**Comment by UncombedCoconut** [comment]
This still looks like a bug, but I'm unclear on what's going on.
It almost looks like a pitch issue (mistaken math around where the R,G,B,A bytes for each line should be). Except I'm not sure why one would occur and whether the graphical artifacts could look like that.

**Comment by Zireael07** [comment]
@UncombedCoconut the pic reminds me of another issue where it was an Intel graphics drivers bug

**Comment by Mutos** [comment]
Hi @Zireael07, hi @UncombedCoconut, thanks for your replies, my integrated display is indeed Intel, so that's consistent... Now I'll try to do the same thing on my W7 machine, might work...

**Comment by Zireael07** [comment]
@Mutos if you have the issue on two different machines but both have Intel, it's even more likely my memory is right
