### ISSUE TITLE
Patrols and bounty mission do not get paid/completed (today's alpha snapshot)

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2304]
Three simulatanious patrols in Zemur, completed all of them, but they are not completed by the system. Another parallel mission was a bounty mission which was ignored as well.

Please find the attached filed before and after the "incident" in Zemur ;-) 

Best wishes,
BM-W1
[Archiv.tar.gz](https://github.com/naev/naev/files/10951697/Archiv.tar.gz)

**Comment by BM-W1** [comment]
It seems to me that Empire missions in Bolero are regarded as independent missions? please check

**Comment by BM-W1** [comment]
One more comment: I'm no longer sure, if I got the missions on Antleos and not on Bolero. This would mean that there was no problem. In this case, sorry!

**Comment by bobbens** [comment]
Yeah, looking at the save, it seems like the missions you have are independent. Landing on an independent planet fixes them. It does raise the question of whether independent missions should be able to be completed on any non-hostile to independent spob, which I'll probably change for 0.11.0. Thanks!
