### ISSUE TITLE
Strange behavior of equipment counter in the "shop"

### ISSUE THREAD

**Issue by naev** [naev/naev#231]
Original [issue 47](https://code.google.com/p/naev/issues/detail?id=47) created by Angelo.L... on 2010-02-20T08:58:13.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
Version 0.4 from PlayDeb on Ubuntu 9.10 

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>
I don't know if is a WAD, but...
If you buy a seeker launcher and several seeker but do not equip them, you
can see, in the &quot;shop&quot; how many missiles do you have. But as soon as you
equip them, the total amount of missiles do not appears any more in the shop.
Indeed, the counter restart from 0 and start increasing while you buy
missiles; as soon as you select another object, the counter returns to 0.

Finally, as soon as you unequip the launcher, in the &quot;shop&quot; the counter
show the right number of missiles you own.

<b>Please attach the console output or paste it.  Thank you for your bug</b>
<b>report.  See http://code.google.com/p/naev/wiki/Debugging for help getting</b>
<b>more useful information in case of a segfault or infinite loop.</b>

**Comment by bobbens** [comment]
No ammunition anymore.
