### ISSUE TITLE
Issues in VN text window

### ISSUE THREAD

**Issue by oo13** [naev/naev#2312]
1. VN closes the window at the moment of opening if the player holds the DOWN key. The window should not be closed.
    [test_vn.zip](https://github.com/naev/naev/files/11111751/test_vn.zip) plugin opens a VN window three seconds after taking off, if the player holds the DOWN key in order to stop their ship the VN closes the window immediately.
2. Feature request: PageUp/PageDown keys scroll the text almost one page at a time, instead of a single line.
3. Feature request: The mouse wheel scrolls the text.
4. Minor problem in Japanese: VN text window cuts off the upper side of some Japanese and European characters on the first line. Would you expand the scissor area? Probably, most Japanese characters can be covered by extra two pixels to upper side. If you would resolve it for any fonts, the line height should be larger than the sum of winAscent and winDescent parameters, which are generally used as the hard limit to draw the glyphs.

For example in Cabin-SemiBold.otf ([test_vn.zip](https://github.com/naev/naev/files/11111751/test_vn.zip) shows it):
![VN_text_EN](https://user-images.githubusercontent.com/22392249/228843186-da190da2-c776-4cf7-a9a3-6e0faea6bb99.png)

For example in IBMPlexSansJP-Medium.otf:
![VN_text_JA](https://user-images.githubusercontent.com/22392249/228843342-4979703d-cd8f-486d-96dc-c41719b1f228.png)
It's obvious that the circle of "パ" is breaking, although no serious problem...

My estimation of the way to draw in VN window and some instances of winAscent and winDescent:
![Diagram2](https://user-images.githubusercontent.com/22392249/228844374-0ffbaf7b-1b63-4c1e-a4da-a1a68824075f.png)

**Comment by bobbens** [comment]
Found a bit more time and did 3 too.

**Comment by bobbens** [comment]
Was a bit more work than expected but fixed 1 too so this issue should be closed. Thanks!
