### ISSUE TITLE
switching ships problem because of cargo 

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2317]
problem in Taiomi at the One-Wing Goddard: I am unable to change the ship because there is too much Therite in my hold. 
possible solution: the drones take the complete Therite load (and may optionally pay for it)
alternative: the more Therite, the fewer ships to destroy as the next task

[cargo.tar.gz](https://github.com/naev/naev/files/11141712/cargo.tar.gz)

**Comment by bobbens** [comment]
I've made it so they take all the excess therite and pay you well for it. Thanks!
