### ISSUE TITLE
Smuggler's Deal: unexpected foes

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2320]
Protecting the smuggler's from Arrakis in Dune turns them into foes (see screenshot). 
After a fight with an enemy pirate ship, they turn to foes and fire at me a few shots but go on flying in the convoy order. After jumping to Gamel their behaviour is set back to friendly. 
![Screenshot_20230405_190211](https://user-images.githubusercontent.com/122737685/230153525-f5f976b4-2b85-42b1-ba1a-08adcb97f290.png)

In Gamel during the fight with Soromid ships my Za'lek drones attacked the convoy ships. I suppose, because they turned foes there as well. I couldn't take a screenshot as the situation was too hot. ;-)

**Comment by bobbens** [comment]
Should be fixed, thanks!
