### ISSUE TITLE
Awowa: jump point and planet selected together

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2322]
Taking off from Odonga m1 in Awowa and clicking on the jump point to Ginger on the overlay map selects both Odonga (planet) and Ginger jump point.
![Screenshot_20230405_204334](https://user-images.githubusercontent.com/122737685/230175393-461eb28d-a5e8-4e32-bdc2-0661dfb27bc6.png)

**Comment by BM-W1** [comment]
I've tried several times to reproduce it myself - to no avail. I've noticed that now Odonga appears further to the NE than on the screenshot. I suggest you ignore this. I don't know what had happened. Thanks for trying to reproduce.
![Screenshot_20230407_001943](https://user-images.githubusercontent.com/122737685/230504308-eddfea73-9719-42fb-a0ff-8885d202d009.png)

**Comment by BM-W1** [comment]
Hi bobbens, I hope you can reproduce in this case:

Selecting a jump point as well as a planet happens in some cases after starting from Qoman in Kesher: Click on either the jump point to Urbanus or to Oxuram. You will get highlighted both the jump point and Qoman. It depends if the jump point is located close to the edge of the planet's image on the screen. This seems to depend on the direction of the ship. I hope my safefile will help you reproducing this.

I don't regard this issue as something important as I usually choose my route by selecting the destination on the map and clicking "Autonav". This evades that problem, of course.

[Qoman.tar.gz](https://github.com/naev/naev/files/11205356/Qoman.tar.gz)

**Comment by bobbens** [comment]
Managed to get it. Should be fixed now, thanks!
