### ISSUE TITLE
Some sound effects become louder at changing the time compression.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2328]
A way to reproduce:
- Push Toggle Speed key immediately after activating Blink Drive.

Revision: Current main (6db43fb7c4775a028c6c4f7e1e4431ac12dfebaa), Local build
OS: Debian GNU/Linux Testing

I'm not sure what `svolume` means but it might resolve the problem:
```diff
--- a/src/sound.c
+++ b/src/sound.c
@@ -2096,7 +2096,7 @@ static void al_volumeUpdate (void)
    soundUnlock();
 
    /* Do special effects. */
-   spfxL_setSpeedVolume( svolume_speed );
+   spfxL_setSpeedVolume( svolume * svolume_speed );
 }
 
 /**
```

**Comment by bobbens** [comment]
I've doubled checked the code and it looks like an oversight. Thanks for the fix!
