### ISSUE TITLE
two-digit number of missions not shown completely

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2329]
The number of 10 missions is not shown completely (neither 0 nor closing bracket), please see screenshot. I'm using the slim GUI.
It is getting harder to find issues - you must be doing a really good job ;-)

![Screenshot_20230510_225444](https://github.com/naev/naev/assets/122737685/c1836948-4ade-415a-87eb-2bc03dbae465)

**Comment by bobbens** [comment]
Thanks for the report. Should be fixed! Seems like the line wrapping wasn't really working in the first place :)
