### ISSUE TITLE
Scavengers on Minerva Station - broken dialogue

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2330]
Sometimes scavengers turn up on Minerva. The only thing they do is this part(?) of a dialogue. To me it seems to be pointing to a bug. Please find attached my savefile. The scavengers, however, do not appear regularly. I hope this information may help you.

![Screenshot_20230514_002521](https://github.com/naev/naev/assets/122737685/a52fd017-5270-49f0-b034-a86e6710dee7)
[scavengers.tar.gz](https://github.com/naev/naev/files/11470778/scavengers.tar.gz)

**Comment by bobbens** [comment]
I guess it is a bit confusing, but this is not a bug. If you finish the minerva quest where you meet the scavengers and don't kill them, they will sometimes appear at Minerva station (albeit do nothing). I thought it was cute, but if it was confusing, it could be removed.

**Comment by bobbens** [comment]
OK, did that. Thanks!
