### ISSUE TITLE
Za'lek Particle Physics campaign doesn't award heavy_weapons_license and heavy_combat_vessel_license

### ISSUE THREAD

**Issue by Partmedia** [naev/naev#2338]
After playing *missions/zalek/particlephysics/zpp03.lua* and *missions/zalek/particlephysics/zpp06.lua*, the text and ship log indicate that I should have received a `heavy_weapons_license` and `heavy_combat_vessel_license`. However, I didn't have these licenses added to my ship.

I'm playing v0.10.5 and did not have any medium licenses before I played these quests.

**Comment by Partmedia** [comment]
Quick inspection shows that I have the diffs applied:
```
 <diffs>
  <diff>heavy_weapons_license</diff>
  <diff>heavy_combat_vessel_license</diff>
  <diff>hypergates_3</diff>
  <diff>antlejosv_2</diff>
  <diff>sigma13_fixed2</diff>
 </diffs>
```
But that doesn't award me the license:
```
  <licenses>
   <license>Light Combat Vessel</license>
  </licenses>
```

**Comment by LJDude** [comment]
Pretty sure it's only supposed to make them available to buy. If it's saying that it gave the items themselves to you in the log, then that would be a bit of text to fix.

**Comment by Partmedia** [comment]
Ah, maybe I misunderstood what the reward was supposed to be. Let me try to find out what the intent was supposed to be and see if the text needs adjusting.

**Comment by bobbens** [comment]
Yes, they become "available for sale", however, it is a bit weird and maybe it would be better to just give the licenses directly to the player without making them jump through hoops.

**Comment by bobbens** [comment]
OK, decided to go with an explicit message saying you can now buy the licenses instead of giving them directly, but still somewhat on the fence. At least this should minimize the issue raised here. Thanks!
