### ISSUE TITLE
Scale issues

### ISSUE THREAD

**Issue by naev** [naev/naev#234]
Original [issue 50](https://code.google.com/p/naev/issues/detail?id=50) created by etenil on 2010-02-28T20:09:57.000Z:

I run version 0.4.2 on Linux x86_64

There is, IMHO, some problems with the scale of things in NAEV.

For instance, the biggest ships are not much bigger than the fighters.

Also, the planets and other celestial bodies should be huge compared to the
spaceships and space stations, but they're about the same size.

Modifying the sprites sizes would increase a bit the realism of the game's
graphics (especially for the planets).

This also has some impact on the realism of the gameplay too. For instance,
it should be very easy to target the large cruisers, and difficult for them
to destroy fighters (without any turrets that is).

Boarding a ship would also be affected. Boarding a cruiser in a hurry (what
pirates would do in reality) should be very easy for a small ship, due to
the manoeuvrability and size differences.

Landing on a planet is not difficult even for cruisers as the planet is
gigantic (usually). However, docking on a space station requires much more
dexterity from the pilot.

**Comment by bobbens** [comment]
Closing.
