### ISSUE TITLE
[Bug]: Game Fails to Start on Steam

### ISSUE THREAD

**Issue by jonathan-gruber-jg** [naev/naev#2340]
### Observed Behavior
Version 10.6 of the Game on Steam fails to start on Steam. In particular, when I click "Play" in the game's page in my Steam library, Steam tries to start the game, but the game crashes before any window is even displayed. The game itself did not generate any logs over this, but I was able to capture the stdout and stderr from Steam an save them to a file named "steam-log.txt" that I have attached.

I am not quite sure what the problem is, but line 89 of the attached log file mentions "error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory". I am not the most familiar with where Steam puts its libraries, but I did find a file named libpng12.so.0 in the directories ~/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu, ~/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu, and ~/.local/share/Steam/ubuntu12_64/steam-runtime-heavy/lib/x86_64-linux-gnu.

The problem does not seem to occur with version 10.5 on Steam or with the nightly builds available via Steam, so it seems to be specific to version 10.6 on Steam.

In case it becomes relevant for fixing this bug, the Linux distro that I am running is EndeavourOS, an Arch-Linux-based distro.

### Expected Behavior
Steam successfully launches the game.

[steam-log.txt](https://github.com/naev/naev/files/11992358/steam-log.txt)

### Version

10.6 on Steam

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UncombedCoconut** [comment]
I confirm the game is getting linked differently, and for the worse (2 references to libpng, different versions).
I'm not sure if we event meant to statically link libSDL2_image (as opposed to getting it from the Steam runtime). @ProjectSynchro is likely more familiar. I will look into it unless he swoops in...

```diff
        /lib64/ld-linux-x86-64.so.2
        libSDL2-2.0.so.0 => /lib64/libSDL2-2.0.so.0
-       libSDL2_image-2.0.so.0 => /lib64/libSDL2_image-2.0.so.0
        libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1
-       libbrotlienc.so.1 => /lib64/libbrotlienc.so.1
        libbz2.so.1 => /lib64/libbz2.so.1
        libc.so.6 => /lib64/libc.so.6
        libdl.so.2 => /lib64/libdl.so.2
        libfreetype.so.6 => /lib64/libfreetype.so.6
        libgcc_s.so.1 => /lib64/libgcc_s.so.1
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0
        libgraphite2.so.3 => /lib64/libgraphite2.so.3
        libharfbuzz.so.0 => /lib64/libharfbuzz.so.0
-       libhwy.so.1 => /lib64/libhwy.so.1
-       libjbig.so.2.1 => /lib64/libjbig.so.2.1
-       libjpeg.so.62 => /lib64/libjpeg.so.62
-       libjxl.so.0.7 => /lib64/libjxl.so.0.7
        liblzma.so.5 => /lib64/liblzma.so.5
        libm.so.6 => /lib64/libm.so.6
        libogg.so.0 => /lib64/libogg.so.0
        libopenal.so.1 => /lib64/libopenal.so.1
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0
+       libpng12.so.0 => /lib64/libpng12.so.0
        libpng16.so.16 => /lib64/libpng16.so.16
        libpthread.so.0 => /lib64/libpthread.so.0
-       libsharpyuv.so.0 => /lib64/libsharpyuv.so.0
+       librt.so.1 => /lib64/librt.so.1
        libstdc++.so.6 => /lib64/libstdc++.so.6
-       libtiff.so.5 => /lib64/libtiff.so.5
        libvorbis.so.0 => /lib64/libvorbis.so.0
        libvorbisfile.so.3 => /lib64/libvorbisfile.so.3
-       libwebp.so.7 => /lib64/libwebp.so.7
        libxml2.so.2 => /lib64/libxml2.so.2
        libz.so.1 => /lib64/libz.so.1
-       libzstd.so.1 => /lib64/libzstd.so.1
        linux-vdso.so.1
```

**Comment by UncombedCoconut** [comment]
OK - I think the problem is that we were supposed to include commit 6d7fb4a8704f921d553374d0899866f3a366a53b in the 0.10.x branch. I'll give that a try.

**Comment by UncombedCoconut** [comment]
Sorry, looks like it's not fixed and I'm out of time to investigate for now.

**Comment by UncombedCoconut** [comment]
Forgot to mention a workaround: anyone impacted by this issue can go to "Betas" in the settings (from the Stream library page) to revert to the last working version.
But hopefully we can actually fix it soon.

**Comment by ProjectSynchro** [comment]
Howdy

This is happening due to the fact that the fact that I forgot to update the release workflows to build 0.10.6 using Steam's `sniper` runtime, and it's being built on the older `scout` runtime

The reason we've had SDL2_image building separately in the past  is due to an issue with libwebp in the 'scout' runtime. There is no support for libwebp in SDL2_image as available in the `scout` runtime.

I'll backport the workflow changes  from main and attempt another build shortly.. If you are using the 'Steam Native Runtime' from Arch's repos try using the normal Steam Runtime launcher for Steam, Steam will pull in the `sniper` runtime automatically when you download the game.

Sorry about that!

**Comment by ProjectSynchro** [comment]
Alrighty, so as of c1957cd26018a98872149d3c81a6055e114f53db, this is fixed!

If you restart Steam you should see an update.

Thanks for the report :smile:
