### ISSUE TITLE
[Bug]: Compile error in vn.transitions.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2342]
### What happened?

The event "sirius_awakening" shows a compile error.

The causes may be blinkin and blinkout.

```
Warning: [gl_shader_compile] compile_status==0: (null): [[
0:563(30): error: `p' undeclared
...
```
```
563:    vec4 c1 = Texel( texprev, p );
```

### Version

2e1911513 + #2341 (current main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Should be fixed in main, thanks a bunch!
