### ISSUE TITLE
[Bug]: The player receives a confusing message after trading in some minerva tokens.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2369]
### What happened?

1. Trade in some minerva tokens for an item at Minerva Station.
2. Take off
3. You receive a message "Gambling Bounty".

I suspect the cause is the line 355 of "events/minerva/station.lua".
```
            player.msg( _("Gambling Bounty"), fmt.reward(ti[1]))
```

### Version

main (b14e0edbc), local build

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
I'm not actually sure what I intended to do with that message, so I have removed it. Thanks for pointing it out!
