### ISSUE TITLE
[Proposal]: Consistency with the hyperspace target and the route in the map panel.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2378]
### Suggestion

Swapping ships, the hyperspace target is cleared, but the map panel shows the route yet.

I suggest making player_swapShip() call map_clear() or not clear the hyperspace target.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Made it so the hyperspace target gets restored but the other targets get cleared. Thanks!
