### ISSUE TITLE
[Bug]: A missile seems to pass through Retribution occasionally.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2386]
### What happened?

Retribution follows the player ship that flies straight and fires Za'lek Hunters, and then the missiles pass through Retribution occasionally. It seems to depend on the direction to fly.

I'm not quite sure, but the polygons file "retribution_dvaered.xml" seems to include wrong <polygon> nodes, such as the second <polygon> node.

### Version

main (local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
It seems like a lot of the polygons are wrong. I'm double checking.

**Comment by bobbens** [comment]
OK, I've fixed a ton of ships that seemed to have weirdly generated ship polygons. Hopefully, this should also fix the retribution issue. Thanks for the report!
