### ISSUE TITLE
[Bug]: SIGSEGV is caused in pilot_weapSetName().

### ISSUE THREAD

**Issue by oo13** [naev/naev#2408]
### What happened?

A way to reproduce it:
1. Go to Equipment tab in Land panel.
2. Open Weapons tab in Info window.
3. Set some weapons to Switch mode and close the window.
4. Swap to another ship in Equipment tab.
5. Click the previous ship that set some weapons in Info window.
6. Remove all weapons from the Weapon slots.
7. Click SwapShip button.

### Version

9302a06c6 (Current main, local build)

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Thread 1 "naev" received signal SIGSEGV, Segmentation fault.
0x00005555558a9fbb in pilot_weapSetName (p=0x61d000132e80, id=0)
    at ../src/pilot_weapon.c:498
498	         base = _(o->name);
(gdb) p o
$1 = (const Outfit *) 0x0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report! I've fixed it in main.
