### ISSUE TITLE
[Bug]: weapons ionizer

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2411]
### What happened?

After automatic activation of the ionizer in a fight, it is not possible to switch it off permanently for destroying a ship. I suppose that after each shot it is activated again (see attached file). This only seems to happen in 0.11.0 since I don't know when (sometime in the last two months, I guess). In 0.10.5 the ionizer could be switched off after the automatic activation. 
[ionizer.zip](https://github.com/naev/naev/files/13059199/ionizer.zip)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report! It seems like the outfit Lua code was not being properly run in some cases when turning off. Should be fixed in main.
