### ISSUE TITLE
[Proposal]: Remove key binding for Hyperbolic Blink Engine jump forward

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2421]
### Suggestion

if manoeuvring with an active Hyperbolic Blink Engine, this will happen sometimes: I want to accelerate cautiously and press the up key twice in a short interval. That causes a jump forward which is counterproductive because I want to follow a ship with a certain speed. 
This proposal has its pros and cons, I know. So feel free to ignore it.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
For the hyperbolic blink engine, the double tap forward is a bit forced, so I've removed it. But the double tap forward/left/right I think is better for flicker/blink drives, so I'll keep it there. Thanks!
