### ISSUE TITLE
[Bug]: Dr. Mensing Conference

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2423]
### What happened?

There is a circular dialogue with Dr. Mensing (see screenshot). The result of pressing 1 is ignored and the dialogue is repeated.
![Screenshot_20231025_222829](https://github.com/naev/naev/assets/122737685/8a7d931d-0bb0-44b3-b000-be2a97b21dd7)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BM-W1** [comment]
In order to get out of that circular dialogue I had to press 2. Now I've just noticed that the mission is nevertheless in my mission list.

**Comment by BM-W1** [comment]
one more thing: Empire ships are shooting at me now.

**Comment by BM-W1** [comment]
Here's the savefile
[conference.zip](https://github.com/naev/naev/files/13170469/conference.zip)

**Comment by bobbens** [comment]
Oops, should be fixed, thanks!
