### ISSUE TITLE
[Proposal]: no semitransparent 

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2425]
### Suggestion

The small windows of the equipment section in a station are kind of semi transparent (see screenshot). It does not look like bad, but is it intended? It seems to me that all other kinds of windows do not have this property. Just to let you know.
![Screenshot_20231026_215859](https://github.com/naev/naev/assets/122737685/35e58bab-8b7c-435e-aa67-b73a7d936cb3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BM-W1** [comment]
I've just noticed that the same thing happens with the marks of the stars in the outfit icons.
![Screenshot_20231026_222011](https://github.com/naev/naev/assets/122737685/3d8f504d-ee84-4489-a8a3-29640b6e3c7e)

**Comment by bobbens** [comment]
OK, I was looking at this since yesterday, finally found the issue to be the framebuffer blending mode. So it should be fixed now, thanks!
