### ISSUE TITLE
[Bug]: The System Info window doesn't show the outfits and ships.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2426]
### What happened?

The System Info window doesn't show the outfits and ships.
A tooltip is shown if you point there:
![2023-10-27-19:49:58 fjR](https://github.com/naev/naev/assets/22392249/3ae677f4-4960-4e5d-a27e-4a3ac461757c)

The bug was introduced by dc3c0a43b6c7a7bab1ac042ebd8e59d0040ff893.

### Version

f008f1ae9 (Current main, Local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, sorry about that. Should be fixed! Thanks!
