### ISSUE TITLE
[Bug]: Dvaered Negotiation 1 - saboteurs do not leave "Siren of Halir"

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2428]
### What happened?

The team does not get off the "Siren of Halir", which goes on circulating in Arcturus until the mission ends with this message.  
![Screenshot_20231027_231903](https://github.com/naev/naev/assets/122737685/9b2bb584-5c8b-411a-84d0-693923d80d7e)
Should be possible to reproduce with this snapshot (with any ship). 
[dv-n1.zip](https://github.com/naev/naev/files/13193425/dv-n1.zip)
Even disabling the "Siren of Halir" and retrieving the saboteur team does not help.

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
OK, the player_only flag of gatherables wasn't being respected, so the Siren of Halir was picking up the commandos. Should be fixed now, thanks!
