### ISSUE TITLE
[Bug]: Shadow Vigil Rebina disappearing in Pas

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2429]
### What happened?

If you land on Shangris Station in Pas before the rendevouz with Rebina, she is gone after the take-off from the station. One has to leave the system and reenter to make her visible again. Would be more logic if she stayed in place.

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Should be fixed in main, thanks!
