### ISSUE TITLE
[Bug]:Dvaered Shopping error 

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2431]
### What happened?

Returning from Zhiru with the convoy is not possible because the convoy "escapes" at the jump point and cannot be followed. See attached savefile.
[dv_shopping.zip](https://github.com/naev/naev/files/13227493/dv_shopping.zip)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Should be fixed, sorry about that. Thanks for the report!
