### ISSUE TITLE
[Bug]: Gauntlet Supreme has no effect without the unguided launcher.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2432]
### What happened?

Probably "gauntlet_supreme.lua" needs 'notactive = true'?

If it's added, an unguided launcher makes launch_damage of any launchers, including a guided launcher, +10.25% instead of +10%.

### Version

e57b5a8ad (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
The `notactive = true` was needed, but also there was no `po:clear()` to remove the effect when unequipped. I also took care to make sure the bonus becomes 10% instead of 10.25%. Thanks!
