### ISSUE TITLE
[Bug]: Minerva - Zuri/Kex/Maikki Missions do not continue

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2434]
### What happened?

Could it be that Zuri does not turn up any more after the destruction of the Za'lek Drone Hacking Centre due to a bug? I'm asking because she says she would in the  debriefing. 
I've got the impression that all Minerva missions (Kex, Mailki, Zuri) are stuck at this point (see the attached snapshot). Please check if you find some time.
By the way, I very much appreciate your gorgeous job of developing/implementing new stories with those interesting and funny dialogues! :-)
[minerva.zip](https://github.com/naev/naev/files/13301847/minerva.zip)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, the mission was disabled as if it was still being tested. It should be playable now. Thanks for the report!

 BTW, the campaign was recently finished, so you can play until the conclusion :)

**Comment by BM-W1** [comment]
I'm going to joyfully do so next week. Thanks a lot, you're doing a great job!
