### ISSUE TITLE
The toggle weapon-set cannot reactivate the fighter bay and the launcher after deactivating them.[Bug]: 

### ISSUE THREAD

**Issue by oo13** [naev/naev#2437]
### What happened?

A way to reproduce:
1. Allocate a fighter bay a weapon-set that is set to toggle.
2. Take off.
3. Activate the weapon-set.
4. Deactivate the weapon-set.
5. Recall all fighters.
6. Try to activate the weapon-set, but no fighters are launched.

The fighter bay and the launcher seem to be PILOT_OUTFIT_COOLDOWN state forever, instead of PILOT_OUTFIT_OFF.

### Version

66c1b0de6 (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report. Should be fixed!
