### ISSUE TITLE
[Bug]: Limbo Mayhem & Judgement (Typos)

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2438]
### What happened?

Info window, description of mission: "Zuri wants you _t_o (not: do) ..."

Besides that: great mission! This mission takes a different approach. Makes you curious, how you have to react. You can just wait and see until the battle starts. That makes it more exciting.

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BM-W1** [comment]
In Minerva Judgement: Shouldn't Zuri say: "I have no idea _what_ to expect out of ..."

**Comment by BM-W1** [comment]
At Jade Court: presentation of Minerva CEO: " and _not_ looking very well."

**Comment by BM-W1** [comment]
Suggestions: Would it be more consistent if Zuri apprears right after the end of Jade Court in the Sparceport Bar? I had to get off and land again to find her there.

**Comment by BM-W1** [comment]
At Logania: Maikki: "You sense a (out) some ..."

**Comment by UncombedCoconut** [comment]
Above typos are fixed, leaving the question 2 comments above about the actual script.

**Comment by BM-W1** [comment]
Minerva Station Redux: 
Typo of Guard: "[H]elp me! We ain't got time"

**Comment by UncombedCoconut** [comment]
> Minerva Station Redux: Typo of Guard: "[H]elp me! We ain't got time"

That one's not a typo. :) The word starts with an apostrophe (like a contraction) -- hinting that the guard spoke with an accent that dropped the "h" sound.

**Comment by BM-W1** [comment]
Thanks! By the way, a very nice and varied mission. Absolutely great! Still need to go th New Haven though  ;-)

**Comment by bobbens** [comment]
> Suggestions: Would it be more consistent if Zuri apprears right after the end of Jade Court in the Sparceport Bar? I had to get off and land again to find her there. What about if one had to talk to a special person in the spacebar bridging the time. After that Zuri appears in the spacebar.
> 
> A similar situation appears on Regensburg with Maikki. Start and reland necessary. I wonder if there could e.g. be a mission objective like "come back in x periods to meet Maikki."

OK, this was an oversight due to the missions doing stuff from NPCs, which was after landing missions were generated, making the player reland to trigger them. I've modified it so the previous missions trigger the next ones so the NPCs should be there already. Thanks for the feedback and glad you enjoyed it :)
