### ISSUE TITLE
[Bug]: Za'lek as Dvaered Ships?

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2440]
### What happened?

In Urbanus the Dvaered ships seem to be generated as Za'lek ships. I hope you can reproduce with the attached snapshot. It may be related to Minerva Station being handed over to the Za'lek. 
[Z-as-D.zip](https://github.com/naev/naev/files/13363239/Z-as-D.zip)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report! OK, there have been a few bugs related to this that I just fixed. So it should look like less of a problem. In particular, fleets in general were spawning too many pilots. That should be toned down now.
That said, Za'lek spawning in Urbanus is fine. They should spawn in much much smaller numbers now (after the bug fix), so it shouldn't be that pronounced. Also they can take off / land on Dvaered assets, which is on purpose now, but potentially could fixed.
