### ISSUE TITLE
[Bug]: Blackjack and Chuck-a-luck at Minerva

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2444]
### What happened?

Blackjack with a new dealer after Kex cannot be played. None of the items 1-3 leads to anything.

Approaching Chuck-a-luck requires pressing the right arrow key twice to go to the next dialogue window. I believe this started some time during the Maikki/Zuri campaign already. The same with Blackjack, if I remember correctly. 

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report, should have fixed it!
