### ISSUE TITLE
[Bug]: Shipps killed at Assault on Unicorn

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2445]
### What happened?

Ships killed by my drones are not counted as killed by myself / compesated althouth these ships count in the info tab in the information window. I don't know if "killed by drones" is intended to be excluded from the count. In my opinion it may be more consistent to count these ships. I also have the impression that ships killed but attacked by other ships before, do not count either.

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UncombedCoconut** [comment]
Applied oo13's fix. Please reopen if you still see issues.
