### ISSUE TITLE
[Bug]: The beam turret always rotates toward the mouse cursor.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2456]
### What happened?

Even if you disable the manual aiming mode, the beam turret rotates toward the mouse cursor while the cursor is present.

The bug seems to be introduced by d2db29b1c.

### Version

2f1d7ca58 (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, should be fixed, thanks!
