### ISSUE TITLE
[Bug]:start of Academy hack 02 

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2458]
### What happened?

I've got the impression that academy hack 02 does not start. I tried often in or around Churchill. It has, however, never spawned. 
Am I guessing right that 
`if spob.get("Violin Monastery"):system():jumpDist() &gt;= 4 then
      return false
   end`
means that it shoud start at a distance of 4 systems from Violin Monastery?

Please see the attached snapshot.
[Academy Hack2.zip](https://github.com/naev/naev/files/13468384/Academy.Hack2.zip)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, should be fixed now. Thanks!
