### ISSUE TITLE
Use `glslangValidator` for (CI) checks of shaders

### ISSUE THREAD

**Issue by ids1024** [naev/naev#2469]
https://www.khronos.org/opengles/sdk/tools/Reference-Compiler

Glslang is the references implementation of GLSL from Khronos. It should catch some issues with shaders that certain implementations may be less strict about. For https://github.com/naev/naev/pull/2396, it could provide a way to statically check that the shaders are correct for the required OpenGL and OpenGL ES version of GLSL.

It has include support, but apparently doesn't handle includes with `/` in them. And `--glsl-version` doesn't seem to be doing anything for me? So we'd need to pre-process.

My current attempt at this, for the shaders in `dat/glsl`:

```python3
import os
import re
import subprocess

def preprocess(shader):
    lines = shader.splitlines()
    lines = ["#version 150 core"] + lines

    i = 0
    while i < len(lines):
        m = re.match('#include\s+"([^"]+)"', lines[i].strip())
        if m:
            with open("dat/glsl/" + m.group(1)) as f:
                contents = f.read()
            lines = lines[:i] + contents.splitlines() + lines[i+1:]
        i += 1

    return '\n'.join(lines)

for i in os.listdir("dat/glsl"):
    if i.endswith(".vert"):
        s = "vert"
    if i.endswith(".frag"):
        s = "frag"
    else:
        continue

    with open("dat/glsl/" + i) as f:
        contents = preprocess(f.read())

    print(f"{i}:")
    p = subprocess.Popen(["glslangValidator", "--stdin", "-S", s, "--enhanced-msgs"], stdin=subprocess.PIPE)
    p.communicate(contents.encode())
    p.wait()
```

This errors with `emp.frag` and `spark.frag`. I guess those expect the defines provided in `dat/scripts/love/graphics.lua`? `spobmarker_base.frag` also fails since it's a base to be included by other shaders and not used directly.

So this also needs to cover the shaders located elsewhere, and it needs to know in what context shaders are used if that changes the defines. Perhaps things could be moved around to follow stricter directory conventions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
- [ ] Check for app in meson
- [ ] Integrate into pre-commit
- [ ] Fix false positives (either add comment override or whatever)
- [ ] Detect love2d shaders and add needed variables (`dat/scripts/love/graphics.lua`)
- [ ] (optional) rip out shaders stored as strings into separate files from Lua code so they also get checked

**Comment by bobbens** [comment]
I've implemented this based on your original implementation in `utils/nglslValidator.py`. It needed a few tricks, but it now passes on all the current files. Should be possible to use this now to detect incompatibilities with OpenGL ES or whatever. Thanks!
