### ISSUE TITLE
[Proposal]: Pirate missions optional listing

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2472]
### Suggestion

Maybe the pirate missions (courier etc.) on ordinary planets could be hidden as an option. If I do not want to do these, I would prefer not to having listed them. 
I am not referring to the missions on pirate planets.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Implemented in main. You can also sort the missions too. Thanks!
