### ISSUE TITLE
[Bug]: achack 04

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2476]
### What happened?

Please see screenshot.
![Screenshot_20231207_004740](https://github.com/naev/naev/assets/122737685/b37f255d-e0ba-49de-9230-a4f9ed8ccee5)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BM-W1** [comment]
Harja has not face. At least in the bar. Maybe the vision is blurring after too many pints. ;-)
![Screenshot_20231207_010810](https://github.com/naev/naev/assets/122737685/cf6e50c8-30a1-44c6-a318-7c4b714aa766)

**Comment by bobbens** [comment]
Oops, should be fixed. Thanks!
