### ISSUE TITLE
[Bug]: 0.11 Beta (MacOS) Hangs On Launch

### ISSUE THREAD

**Issue by MisterKimo** [naev/naev#2478]
### What happened?

On launch, the Mac version of the beta (and all subsequent nightly builds) hangs with the progress bar indicating it is Initializing Outfits.  I have not been able to bypass this and have had to terminate the process to exit.

This was not an issue with nightly build "Naev vO.11.0-alpha.4+881g5be3c8b6f debug" which launches smoothly.  

### Version

v0.11.0-beta.1

### What operating system are you seeing the problem on?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wraitii** [comment]
Can confirm the bug. The problem is that the outfit / ship reading threads both call `naev_renderLoadscreen`.
This crashes on MacOS as it's illegal to call event-related APIs like `` from a non-main-thread.
Simply commenting out both calls fixes the issue.

Here is a stack-trace when running a debug build:
```
2023-12-10 19:27:17.110 naev[66790:3223226] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018b103154 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x000000018ac224d4 objc_exception_throw + 60
	2   AppKit                              0x000000018e2af368 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2844
	3   libSDL2-2.0.0.dylib                 0x000000010525dbb0 Cocoa_PumpEventsUntilDate + 84
	4   libSDL2-2.0.0.dylib                 0x000000010525dd60 Cocoa_PumpEvents + 56
	5   libSDL2-2.0.0.dylib                 0x00000001051d9064 SDL_PumpEventsInternal + 64
	6   libSDL2-2.0.0.dylib                 0x00000001051d917c SDL_WaitEventTimeout_REAL + 88
	7   naev                                0x0000000104a5b908 naev_doRenderLoadscreen + 556
	8   naev                                0x0000000104ad4878 ship_parseThread + 244
	9   naev                                0x0000000104b00de8 vpool_worker + 28
	10  naev                                0x0000000104b00e9c threadpool_worker + 108
	11  libSDL2-2.0.0.dylib                 0x0000000105217eec SDL_RunThread + 48
	12  libSDL2-2.0.0.dylib                 0x000000010526e2f4 RunThread + 12
	13  libsystem_pthread.dylib             0x000000018afabfa8 _pthread_start + 148
	14  libsystem_pthread.dylib             0x000000018afa6da0 thread_start + 8
)
libc++abi: terminating due to uncaught exception of type NSException
Naev received SIGABRT!
```

**Comment by bobbens** [comment]
> Can confirm the bug. The problem is that the outfit / ship reading threads both call `naev_renderLoadscreen`. This crashes on MacOS as it's illegal to call event-related APIs like `` from a non-main-thread. Simply commenting out both calls fixes the issue. Original commit appears to be `8e6c08d390ab1f001ade797612b63268547845f4`. I think you'll have to be fancier and ping the main thread (or something along those lines), but simply toggling this OFF on mac should fix the issue.

Could you try commenting out the `while (SDL_PollEvent(&event));` line in `naev_doRenderLoadscreen()`? Should be line 588 in naev.c. If it's enough to remove that, we don't need too much refactoring, but I have a feeling the `SDL_GL_SwapWindow` and `naev_resize` lines could also be at fault...

**Comment by bobbens** [comment]
Looking at the documentation, it only seems to be documented that SDL_PollEvents can be a bad idea on other threads. The other functions don't to seem to have warnings. If this works, I'll just commit it then :)
Thanks a bunch!

**Comment by wraitii** [comment]
No worries, had to fix that same bug in 0 A.D. once upon a time. Thanks for fixing it quickly and the native mac support, I know it's kind of (super) annoying
