### ISSUE TITLE
[Bug]: Inconsistent use of UK/US English

### ISSUE THREAD

**Issue by awest03** [naev/naev#2482]
### What happened?

Some parts of the game content are written in UK English whereas others in US English. The Wiki doesn't seem to say which one to use, however it would be good to consolidate this. #2215 assumes UK English as the default. Searching the `dat/events` `dat/missions` directories for "color" and "colour" yields multiple results each.

### Version

nightly

### What operating system are you seeing the problem on?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
OK, I've used a mix of sed plus manual editing to change all the remaining cases, including API and the likes (although for love2d I've kept the "real API" too). Probably a bit reckless of a thing to do for a beta, but life is short :)
Thanks!
