### ISSUE TITLE
[Bug]: The trader's ships fly with the full speed in "Trader Escort."

### ISSUE THREAD

**Issue by oo13** [naev/naev#2485]
### What happened?

The trader's ship leaves the fellow ships as well as the player ship.

### Version

8ed49ec2a (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Managed to fix it. `pilot.setSpeedLimit` was broken, plus the escort script was reseting the speed. Thanks!
