### ISSUE TITLE
[Bug]: The torpedo cannot be launched.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2486]
### What happened?

I suspect the bug introduced by 895bb6b59. Doesn't the forward weapon with 0 swivel have a very low chance to fire?

### Version

058e4a4b8 (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, nice catch. Thanks!
I've made it so for non-turret launchers it uses the arc if it is larger than swivel. It seems to work fine now. Thanks again!

**Comment by oo13** [comment]
b1d95ebea seems to make Mace Rocket, Banshee, and Electron Burst Cannon jammed.

**Comment by bobbens** [comment]
Oh man, it's not my day today is it. Should have fixed it. Thanks!
