### ISSUE TITLE
[Bug]: Macchiavellian Misi no equipment numbers

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2488]
### What happened?

Macchiavellian Misi does not show the numbers of items owned by the player (any more) ;-)

### Version

0.11.0 beta-3

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Do you have a screenshot? I've just tested and it seems normal?

**Comment by bobbens** [comment]
OK, so modified it so stores show amounts while equipment window does not for unique outfits. Thanks!
