### ISSUE TITLE
[Bug]: Dvaered  Propaganda Mission - landing on target planet

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2494]
### What happened?

... your eye is "catched" .. needs to be "caught"

### Version

0.11.0 beta-3

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Fixed, thanks! Also ran a spellchecker and caught a ton of other mistakes.
