### ISSUE TITLE
[Bug]: When using autonav, the pilot will be lost when landing, accelerating, or slowing down

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#2529]
### What happened?

Initially reported on Discord by dakkad.:
> FYI 
Since the update today, the game crashes everytime I try to dock or jump or travel to a target.
Worked awesome before!!  Love the game. 
 I have re-installed and verified files and the problem persists.
take care.

Video of me reproducing the issue:

https://github.com/naev/naev/assets/5131712/0cda2f27-04b3-4c6e-bc80-e2cf20487c05

In my own testing I have seen this happen on Windows specifically whenever autonav is active. This can happen mid flight, when landing, when accelerating, etc.

This appears to happen on Windows, and within WINE, and manifests itself intermittently. Some users do not see it happen at all. 

### Version

v0.11.1

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
When this happens to AI pilots the stdout is spammed with:

Warning: [ai_run] Pilot 'Empire Pacifier' ai 'empire' error: [string "ai/core/misc/lanes.lua"]:56: t
able index is nil

When this happens to a player pilot, OpenAL has a fit:

[ALSOFT] (WW) Error generated on context 000001f472fbf0d0, code 0xa003, "Listener orientation out of
 range"
[ALSOFT] (WW) Error generated on context 000001f472fbf0d0, code 0xa003, "Listener orientation out of
 range"
[ALSOFT] (WW) Error generated on context 000001f472fbf0d0, code 0xa003, "Listener position out of ra
nge"
[ALSOFT] (WW) Error generated on context 000001f472fbf0d0, code 0xa003, "Listener velocity out of ra
nge"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ProjectSynchro** [comment]
This is fixed as of: https://github.com/naev/naev/commits/v0.11.2/

**Comment by Kenionatus** [comment]
This frequently happens to me (or a bug that manifests the same way), but only when jumping out. My game version (acording to the main menu) is 0.11.2 (so if I understand correctly I should have the fix mentioned above?). I'm playing on 64 bit Windows 10 via Steam. The errors in stout look like below, but I've also seen the Pilot ai error mixed in.
```
[ALSOFT] (WW) Error generated on context 000002741e440730, code 0xa003, "Listener velocity out of range"
[ALSOFT] (WW) Error generated on context 000002741e440730, code 0xa003, "Listener orientation out of range"
[ALSOFT] (WW) Error generated on context 000002741e440730, code 0xa003, "Listener position out of range"
[ALSOFT] (WW) Error generated on context 000002741e440730, code 0xa003, "Listener velocity out of range"
```

**Comment by Kenionatus** [comment]
Oh, I've just now watched the reproduction video and my game doesn't actually hard crash like in the video. It hangs indefinitely while spamming stdout but the escape menu still functions and allows me to go back to the main menu.
