### ISSUE TITLE
Extents of nebulae should be visible in the hyperspace map

### ISSUE THREAD

**Issue by naev** [naev/naev#253]
Original [issue 69](https://code.google.com/p/naev/issues/detail?id=69) created by stephan.... on 2010-12-02T17:44:37.000Z:

The hyperspace map would look a lot more interesting if the extents of nebulae (possibly subject to a fog-of-war-style shroud) were drawn... it'd also make it easier to remember what was where by giving extra landmarks.

**Comment by onpon4** [comment]
Hmm, this might be best done with the thing we're  using to indicate faction locations...

**Comment by onpon4** [comment]
Fixed this in #1057.
