### ISSUE TITLE
[Bug]: CTD when selling Quicksilver that is part of fleet

### ISSUE THREAD

**Issue by SharkyNebula** [naev/naev#2539]
### What happened?

lead ship is shark

1) unequip quicksilver
2) sell quicksilver
3) game crashes

quicksilver is part of the fleet

I expect the quicksilver to be sold

Removing the quicksilver from the fleet first avoids the crash

### Version

0.11.3

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
stdout.txt
Trying default datapath: /__w/naev/naev/build/windows/./dat
Trying default datapath: G:\SteamLibrary\steamapps\common\Naev\/dat
Loaded configuration: C:\Users\W\AppData\Roaming/naev/conf.lua
Read locations, searched in order:
    C:\Users\W\AppData\Roaming\.\naev\
    G:\SteamLibrary\steamapps\common\Naev\/dat
Write location: C:\Users\W\AppData\Roaming\.\naev\

 Sea of Darkness
Reached main menu

stderr.txt is empty
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report! Sorry about that, it's already fixed and should be out with 0.11.4 when we get around to that. For now, avoid selling deployed ships.
