### ISSUE TITLE
[Proposal]: Block stacking of patrol like missions

### ISSUE THREAD

**Issue by clintonmead** [naev/naev#2546]
### Suggestion

Allowing stacking of patrol style missions (like Empire patrol, Dvaered counting) is not only a bit cheesey, but also bit unrealistic. Why would the Empire pay someone multiple times to do one patrol?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Yes, I think something like that could be done. The tricky bit is how complicated we want it to be. Easiest way would be to just have a patrol mission detect if there's another one active when accepting and block it. Could also be blocked on a faction-basis or using more complicated criterion, but that is less easy to do.

**Comment by bobbens** [comment]
I can look at it later, but a PR would also be welcome :)

**Comment by bobbens** [comment]
Implemented the easy "only one mission at a time" solution  in main. Thanks!
