### ISSUE TITLE
[Proposal]: Translation for Bahasa Indonesia

### ISSUE THREAD

**Issue by AntimatterReactor** [naev/naev#2552]
### Suggestion

Hi! I'm a bored Indonesian person willing to translate the game into Bahasa.

- [x] I have checked the weblate

Unfortunately, I can't add new languages in weblate (it instructs me to see `Instructions for translators` which is---as of yet---unhelpful).

I know the basic mechanism is to create a new `.po` file, but since I'm not used to the project, I think it'd be better for existing maintainers to add it so that nothing breaks?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntimatterReactor** [comment]
Also, I know that there are more urgent stuff to do other than adding more translation, but it's the little things you know?

**Comment by UncombedCoconut** [comment]
Thanks! Weblate just wanted a project admin (like me) to add the language.
You many now go through https://hosted.weblate.org/projects/naev/naev/id/ or work with the newly created `po/id.po` file. Let us know if we can help further.

**Comment by AntimatterReactor** [comment]
Nice! Thank you very much!
