### ISSUE TITLE
Missing Jumps?

### ISSUE THREAD

**Issue by biell** [naev/naev#2560]
https://github.com/naev/naev/blob/c9bfbf96926476391dafae81f2aa9c601da06409/dat/outfits/maps/map_flf_pirate_route.xml#L10-L17

Isn't this map supposed to also open up the hidden jumps between Tormulex and Anger?  There are no jump tags within each system to make these live, leaving a long route to get to Anger from Tormulex.  The jumps were removed in commit 4fda811  but I really think that was a mistake.

It is used in:  https://github.com/naev/naev/blob/main/dat/missions/flf/dvk/flf_dvk02.lua#L133

**Comment by bobbens** [comment]
Yes, that was an oversight. Fixed, thanks!
