### ISSUE TITLE
[Bug]: Mission with escorts can't succeed if encounter with Green Goatee

### ISSUE THREAD

**Issue by biell** [naev/naev#2562]
### What happened?

On the second Four Winds mission,  you have to travel through Surano.  But, the Green Goatee was waiting there, which kept the escorts & diplomat from arriving.  Clearing all the pirates doesn't help, and the mission is stuck.  I had to load the snapshot, and go to Surano first to kill the pirates before then meeting up with the escorts in Shakar.

Either the Green Goatee needs to not be there when another mission including escorts is in-progress (probably the best alternative), the escorts can enter after the pirates are killed and the blockade is cleared, or they have to at least arrive and you need to protect them while also dealing with the pirates.  Alternatively, you could make clearing Surano a prerequisite for the mission, something that needs to be done before heading to Shakar.

### Version

0.11.3

### What operating system are you seeing the problem on?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
I wanted to do a more permanent solution, and not just for this mission. However, it's a bit too much work, and just changed the final destination so it doesn't try to path through Surano. Thanks!
