### ISSUE TITLE
Flatpak does not Launch Correctly

### ISSUE THREAD

**Issue by bullkang** [naev/naev#2574]
### What happened?

Screen appears with title "Naev Sea of Darkness" plays some music while displaying an image and loads some files, when it reaches the end of loading it exits, without indicating any errors. I launched it with the "-v" option for flatpak and no error appears. It simply closes without explanations.

### Version

0.11.5

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Trying default datapath: /app/share/naev/dat
Loaded configuration: ~/.var/app/org.naev.Naev/config/naev/conf.lua
Read locations, searched in order:
    ~/.var/app/org.naev.Naev/data/naev/
    /app/share/naev/dat
Write location: ~/.var/app/org.naev.Naev/data/naev/

 Sea of Darkness
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bullkang** [comment]
But, nevermind, the appimage 0.11.5 works :)

**Comment by ProjectSynchro** [comment]
I'll reopen this since the Flatpak not launching is still a bit of an issue.

I'll take a look and see what is going on.

**Comment by ProjectSynchro** [comment]
I can't seem to reproduce the issue, could you post the logs that are in: `~/.var/app/org.naev.Naev/data/naev/logs/`?

**Comment by bullkang** [comment]
[stderr.txt](https://github.com/user-attachments/files/15875776/stderr.txt)
[stdout.txt](https://github.com/user-attachments/files/15875778/stdout.txt)

**Comment by ProjectSynchro** [comment]
Hmm there doesn't seem to be anything in those logs that would give any hints :/

Glad the AppImage works for you! If someone else runs into this issue again I'll reopen this.

**Comment by bullkang** [comment]
> Hmm there doesn't seem to be anything in those logs that would give any hints :/
> 
> Glad the AppImage works for you! If someone else runs into this issue again I'll reopen this.

That's what I thought. I don't know whether it has anything to do with the fact that I reallocated the flatpak folder from /var to my home folder ~/.var, (I did this some time ago cause I was running out of space since I had /var on its own partition).
