### ISSUE TITLE
[Bug]: Auto generated naev.py syntax error

### ISSUE THREAD

**Issue by RisingLeaf** [naev/naev#2577]
### What happened?

During compiling the game I found a syntax error in naev.py that I had to fix:
from this
`            "--one-line", f"command script import {os.path.join(build_root, "lldbinit.py")}",`
to this:
`            "--one-line", f"command script import {os.path.join(build_root, 'lldbinit.py')}",`

Note that I have no clue about meson, and I am not sure if it is the projects fault.

### Version

latest

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
File "/home/pi/Documents/GitHub/naev/builddir/./naev.py", line 66
    "--one-line", f"command script import {os.path.join(build_root, "lldbinit.py")}",
                                                                     ^^^^^^^^
SyntaxError: f-string: unmatched '('
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, looks good. Thanks!
