### ISSUE TITLE
Capital ships should support missile reload without requiring an outfitter

### ISSUE THREAD

**Issue by naev** [naev/naev#258]
Original [issue 74](https://code.google.com/p/naev/issues/detail?id=74) created by naasking on 2010-12-30T21:07:50.000Z:

I understand the need for a landing to reload missile launchers on smaller ships since they're hanging outside in space, but I doubt very much this would be the case for capital ships. Capital ships would behave more like Navy destroyers or carriers, not fighters.

**Comment by bobbens** [comment]
Fixed with regenerating ammo.
