### ISSUE TITLE
[Bug]: Icarus' reunion is softlocked at a certain cutscene

### ISSUE THREAD

**Issue by 1000101011100** [naev/naev#2589]
### What happened?

After fighting off the feral bioships and meeting with Icarus a cutscene softlocks the game. 

### Version

v0.11.5

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Warning: [misn_runFunc] Mission 'Za'lek Black Hole 9' -> 'heartbeat_ferals': [string "Za'lek Black Hole 9"]:497: Pilot 'Feral Bioship' is not on manual control.
Warning: [hook_runMisn] Hook [timer] '79920' -> 'heartbeat_ferals' failed
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by 1000101011100** [comment]
Seems to be fixed in the latest nightly

**Comment by bobbens** [comment]
I think it's related to something happening like disabling the ferals or something. Either way, pushed a fix that should address this, but I haven't been able to reproduce (just running away though). Thanks for the report!
