### ISSUE TITLE
[Bug]: Typo in Zack's speech.

### ISSUE THREAD

**Issue by hyperagon** [naev/naev#2597]
### What happened?

Typo when talking to Zack where it says "at some of the of the damage". This picture
shows it:
![Screenshot at 2024-08-23 22-46-14](https://github.com/user-attachments/assets/78edfd73-ef58-4589-ba52-a8ea2e3461bd)

### Version

0.11.5

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Unnecessary.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, thanks. Fixed!
