### ISSUE TITLE
[Bug]: The missile doesn't rotate the body when turning the direction.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2606]
### What happened?

The body of Za'lek Reaper keeps the direction at launching even if it changes the running direction to the moving target.

The first bad commit may be cea0f618e9b6c50cbd998ee43ae3f6db9712360a.

This seems to be fixed it:
```
--- a/src/weapon.c
+++ b/src/weapon.c
@@ -903,9 +903,12 @@ static void weapon_render( Weapon *w, double dt )
                gl_renderSpriteInterpolate( tex, gfx->tex_end,
                                            w->timer / w->life, w->solid.pos.x,
                                            w->solid.pos.y, w->sx, w->sy, &c );
-            else
+            else {
+               if (gfx->tex != NULL)
+                   gl_getSpriteFromDir( &w->sx, &w->sy, gfx->tex->sx, gfx->tex-
>sy, w->solid.dir );
                gl_renderSprite( tex, w->solid.pos.x, w->solid.pos.y, w->sx,
                                 w->sy, &c );
+            }
          } else {
             double r, z;
```

### Version

ad3a63dd1a (current main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report. Oops, does seem like a regression. I've fixed it in `weapon_update` instead of `weapon_render` which should give more correct behaviour for the collision code when the game is lagging or time compressing. Thanks!
