### ISSUE TITLE
[Bug]: The VN option may cause an error.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2609]
### What happened?

The VN option may cause an error.

A way to reproduce it:

1. Start Naev
2. Load a player.
3. Go to a bar.
4. Approach a NPC.
5. Click the gear icon to open the VN option.
6. It doesn't open the VN option and outputs an error log.

### Version

477a90b423 (current main, local build)

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
WARNING ../src/nlua_tk.c:612 [cust_render]: Custom dialogue internal error: [string "scripts/luatk/core.lua"]:211: attempt to index field '_canvas' (a nil value)
stack traceback:
	[string "scripts/luatk/core.lua"]:211: in function 'draw'
	[string "scripts/vn/options.lua"]:20: in function 'draw'
	[string "scripts/vn/core.lua"]:323: in function 'draw'
	[string "scripts/vn/main.lua"]:30: in function 'draw'
	[string "scripts/love.lua"]:121: in function <[string "scripts/love.lua"]:112>
	[C]: in function 'custom'
	[string "scripts/love.lua"]:291: in function 'exec'
	[string "scripts/vn/core.lua"]:1933: in function 'run'
	[string "Totoran Station Events"]:119: in function <[string "Totoran Station Events"]:112>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, should be fixed now. Thanks!
