### ISSUE TITLE
Defensive systems around planets/space docks

### ISSUE THREAD

**Issue by naev** [naev/naev#261]
Original [issue 77](https://code.google.com/p/naev/issues/detail?id=77) created by naasking on 2010-12-30T21:25:41.000Z:

A bit of a departure from how things currently work, but would be more realistic: space docks and planets would very likely have their own defensive systems, and not have to rely on supporting ships to kill pirates when they get close enough to the planet/dock.

Not a big deal, but would add a whole new dimension of play. If you eventually support taking over systems like in EV, these defenses would also have to be overcome as well.

**Comment by bobbens** [comment]
Idea to be replaced with safety lanes when that's ready. Closing.
