### ISSUE TITLE
Beam turret doesn't retarget

### ISSUE THREAD

**Issue by naev** [naev/naev#263]
Original [issue 79](https://code.google.com/p/naev/issues/detail?id=79) created by naasking on 2010-12-30T21:56:20.000Z:

<b>What version of NAEV are you using? On what operating system?</b>

Naev 0.4.2 on Windows 7

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>

The Ragnarok beam turret doesn't retarget very well. If you destroyed your original target and you switch to a new target, even one right next to the original, it should swivel almost immediately like every other turret, but it doesn't.

The beam weapon is theoretically great for point defense against small fighters, but the fact that it doesn't swivel properly makes it rather useless, particularly given the very high costs of mounting it. You're always better off just getting two ion turrets, because they have a higher rate of fire, cause comparable damage, and they swivel instantly, or just getting the front-facing beam weapon and turn your ship using auto-targeting.

**Comment by bobbens** [comment]
I don't think this is applicable anymore.
