### ISSUE TITLE
[Bug]: In the mission "Dvaered Propaganda", the enemy warlord doesn't take offense.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2656]
### What happened?

The enemy warlord was only words.

I suspect that faction_setReputation() called by dynFact:setReputationGlobal() doesn't work because the dynamic faction is FACTION_STATIC.

### Version

133bfb76fc (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Should be fixed in 1b9439c037fc6bc8037a167193dde254b6bde91a . Thanks!
