### ISSUE TITLE
[Bug]: The list in the HOLO-archives wraps around the text if it's too long.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2657]
### What happened?

It seems one character is wrapped and more characters cut off correctly. I suggest just cutting off one more character.
![2024-11-10-19:36:26 6fK](https://github.com/user-attachments/assets/f7ed3e0d-3494-4b79-bd36-b9565f2efdb8)

In Japanese language, the width of the list is not enough to show the entire text. English seems to have no problem.

### Version

133bfb76fc (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Should be fixed, thanks!
