### ISSUE TITLE
[Bug]: No weapons hit Sirius Divinity when it faces to some angles.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2658]
### What happened?

No weapons hit Sirius Divinity when it faces to some angles.

Four examples I found:
![2024-11-23-20:39:01 7cH](https://github.com/user-attachments/assets/a6c05996-4179-4c10-ba24-d02a0565763f)
![2024-11-23-20:37:55 KUI](https://github.com/user-attachments/assets/830a3360-254f-42f5-be32-b320a0aeec6b)
![2024-11-23-20:35:35 dkz](https://github.com/user-attachments/assets/b8f58269-7381-4a90-8066-a0d4e5f1ae92)
![2024-11-23-20:22:49 znH](https://github.com/user-attachments/assets/325444f3-f2cb-4929-93f7-cbff316fc8c9)

### Version

8c29d9658d (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
I can confirm that there are a few angles that the polygons are being generated incorrectly (you can see with `naev.debugCollisions()`). Let me see if I can fix it, thanks!

**Comment by bobbens** [comment]
I should have fixed it now. Thanks again!
