### ISSUE TITLE
[Bug]: on dvaer prime appear sometimes on missions: Shipnet to NULL dnA NLL warning invalid formating detected

### ISSUE THREAD

**Issue by gerardchab** [naev/naev#2675]
### What happened?

A bug happened!

### Version

12 beta 2

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report! This is not a bug and the mission is made to look like an error, it is probably too well done though.
