### ISSUE TITLE
[Bug]: Reset the weaponset when loading

### ISSUE THREAD

**Issue by oo13** [naev/naev#2688]
### What happened?

The weaponset is reset when loading the pilot.
The cause may be 595804c637.

A way to reproduce it:
1. Change a weaponset manually.
2. Exit to Title
3. Load the player.
4. See the weaponset.

### Version

b80fa0d71d (Current main, Local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report. Pushed a fix that seems to work on my end.
