### ISSUE TITLE
[Bug]: certain missions hidden on HUD despite corresponding option being unchecked

### ISSUE THREAD

**Issue by HyperSoop** [naev/naev#2697]
### What happened?

![image](https://github.com/user-attachments/assets/177a94e8-1a95-46eb-adbd-d61cdd9e3d11)

### Version

0.12.0

### What operating system are you seeing the problem on?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
They didn't have the OSD on purpose, but since they have a marker anyway, I just went ahead and added the OSD too. Thanks!
