### ISSUE TITLE
Audio Priority

### ISSUE THREAD

**Issue by naev** [naev/naev#309]
Original [issue 125](https://code.google.com/p/naev/issues/detail?id=125) created by bobbens on 2011-05-19T09:53:24.000Z:

Sounds should have audio priority so that combats where everyone have shredders and other fast weapons don't cancel out the big explosions too. They could also be handled by distance in case of a priority match so nearby sounds are always heard.

**Comment by bobbens** [comment]
Don't think this is really an issue anymore. Closing.
