### ISSUE TITLE
OpenAL crackling, popping and errors on Mac OS X

### ISSUE THREAD

**Issue by naev** [naev/naev#315]
Original [issue 131](https://code.google.com/p/naev/issues/detail?id=131) created by stephan on 2011-06-01T22:20:26.000Z:

This is on mac OS X 10.6.7, on an iMac with Intel HDA. The OpenAL implementation is whatever is the default; it's a reasonably fresh OS X install. The problem occurs with NAEV 0.5.0b2 and current master (b619f61d246c965bf1cd).

During startup, OpenAL is reported as:

```
OpenAL started: 32767 Hz
Renderer: Software
Version: 1.1 without EFX
```

The SDLMix backend doesn't have these problems. With OpenAL, both loud sound effects and music sound crackling and overdriven. Occasionally also popping noises are heard, sounding like a fight, though no fight is on nearby.

On the console, tons of these are spat:

```
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
```

Also several of these in between:

```
Warning: [al_checkHandleError] OpenAL error [sound_al_playGroup]: unknown error
```

And on exit, once the following:

```
Warning: [al_checkHandleError] OpenAL error [music_al_exit]: the requested operation is not valid
```

**Comment by onpon4** [comment]
Seems this is probably obsolete.

**Comment by bobbens** [comment]
Doesn't seem to be an issue anymore, closing.
