### ISSUE TITLE
Universe map could use some love

### ISSUE THREAD

**Issue by naev** [naev/naev#318]
Original [issue 134](https://code.google.com/p/naev/issues/detail?id=134) created by stephan on 2011-06-01T22:46:51.000Z:
- Perhaps a side effect of my screen resolution, but it's very difficult to see on the universe map what the current system is.
- Lines and circles on the map are jaggy. (No AA?)
- The nebula, or the systems in it, should be indicated on the map somehow.

**Comment by bobbens** [comment]
Should be improved, closing.
