### ISSUE TITLE
game does not start after disabling video - black screen

### ISSUE THREAD

**Issue by naev** [naev/naev#370]
Original [issue 186](https://code.google.com/p/naev/issues/detail?id=186) created by COsegued... on 2012-03-20T23:30:18.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
0.5.1 - Windows

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>
Opening the program.

<b>Please attach the console output or paste it.  Thank you for your bug</b>
<b>report.  See http://code.google.com/p/naev/wiki/Debugging for help getting</b>
<b>more useful information in case of a segfault or infinite loop.</b>

 Naev v0.5.1
 git HEAD at naev-0.5.0-1530-gd5744e7
 Sea of Darkness

SDL: 1.2.15 [compiled: 1.2.15]

Available fullscreen modes:
  2048 x 1536
  1920 x 1440
  1920 x 1200
  1920 x 1080
  1856 x 1392
  1600 x 1200
  1600 x 900
  1536 x 2048
  1440 x 1920
  1400 x 1050
  1392 x 1856
  1280 x 1024
  1280 x 960
  1280 x 768
  1280 x 720
  1280 x 600
  1200 x 1920
  1200 x 1600
  1152 x 864
  1080 x 1920
  1050 x 1400
  1024 x 1280
  1024 x 768
  960 x 1280
  900 x 1600
  864 x 1152
  800 x 600
  768 x 1280
  768 x 1024
  720 x 1280
  640 x 480
  640 x 400
  600 x 1280
  600 x 800
  512 x 384
  480 x 640
  400 x 640
  400 x 300
  384 x 512
  320 x 240
  320 x 200
OpenGL Window Created: 512x384@32bpp fullscreen
r: 8, g: 8, b: 8, a: 8, db: yes, fsaa: 0, tex: 2048
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: Intel 845G
Version: 1.3.0 - Build 4.14.10.4342

Sound is disabled!
Loaded 16 Nebula Layers
Loaded 32 Commodities
Loaded 28 Factions
Loaded 31 AI Profiles
Loaded 59 Missions
Loaded 28 Events
Loaded

**Comment by bobbens** [comment]
Very old, closing.
