### ISSUE TITLE
0.5.2 Sprite errors 

### ISSUE THREAD

**Issue by naev** [naev/naev#374]
Original [issue 190](https://code.google.com/p/naev/issues/detail?id=190) created by ArcLagoo... on 2012-04-13T20:56:36.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
Win32

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>

By installing NAEV, and then downloading the N data.

The game will start up, and then freeze. After it unlocks, the main menu's planet will be scrambled looking. And so does every sprite in the game. Making it look like a garbled mess

**Comment by bobbens** [comment]
Very old, closing.
