### ISSUE TITLE
no setting-saving

### ISSUE THREAD

**Issue by naev** [naev/naev#379]
Original [issue 195](https://code.google.com/p/naev/issues/detail?id=195) created by westleyt... on 2012-05-21T12:26:25.000Z:

When I start naev after a newstart of my PC, the graphic-stettings are not saved. If i change it, it will be saved untill i restart the system.

<b>What version of NAEV are you using? On what operating system?</b>
I use 0.5.3 on the rpm-packet for SUSe Linux 12.1

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>

After every restart

<b>Please attach the console output or paste it.  Thank you for your bug</b>
<b>report.  See http://code.google.com/p/naev/wiki/Debugging for help getting</b>
<b>more useful information in case of a segfault or infinite loop.</b>

**Comment by bobbens** [comment]
Don't think this is applicable anymore.
