### ISSUE TITLE
NAEV Crash Report in Lua

### ISSUE THREAD

**Issue by naev** [naev/naev#382]
Original [issue 198](https://code.google.com/p/naev/issues/detail?id=198) created by sirius on 2012-07-07T12:39:03.000Z:

 Naev v0.5.3
 git HEAD at naev-0.5.3
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 1.2.15 [compiled: 1.2.14]

Available fullscreen modes:
  1680 x 1050
  1440 x 900
  1400 x 1050
  1280 x 1024
  1280 x 960
  1280 x 854
  1280 x 800
  1280 x 720
  1152 x 768
  1024 x 768
  848 x 480
  800 x 600
  720 x 480
  640 x 480
OpenGL Window Created: 1680x1050@24bpp fullscreen
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 8192
vsync: yes, vbo: yes, mm: yes, compress: no, npot: yes
Renderer: Gallium 0.4 on AMD RV635
Version: 2.1 Mesa 8.0.3

OpenAL started: 48000 Hz
Renderer: OpenAL Soft
Version: 1.1 ALSOFT 1.14 with EFX 1.0

Loaded 35 sounds
Loaded 43 songs
Loaded 16 Nebula Layers
Loaded 32 Commodities
Loaded 28 Factions
Loaded 31 AI Profiles
Loaded 61 Missions
Loaded 30 Events
Loaded 139 Outfits
Loaded 60 Ships
Loaded 90 Fleets
Loaded 41 tech groups
Loaded 190 Star Systems with 549 Planets
Naev received SIGSEGV (address not mapped to object)!
./naev-0.5.3-linux-x86-64() [0x48a532] debug_sigHandler(...):1234 /naev/src/naev.c
/lib/x86_64-linux-gnu/libc.so.6(+0x324f0) [0x7f8a6f85c4f0] ??(...):0 ??
./naev-0.5.3-linux-x86-64() [0x4a2202] systemL_isknown(...):674 /naev/src/nlua_system.c
./naev-0.5.3-linux-x86-64() [0x59ec8b] luaD_precall(...):320 /naev/lib/lua/ldo.c
./naev-0.5.3-linux-x86-64() [0x5b3f36] luaV_execute(...):591 /naev/lib/lua/lvm.c
./naev-0.5.3-linux-x86-64() [0x59ef34] luaD_call(...):379 /naev/lib/lua/ldo.c
./naev-0.5.3-linux-x86-64() [0x599909] f_call(...):801 /naev/lib/lua/lapi.c
./naev-0.5.3-linux-x86-64() [0x59de7f] luaD_rawrunprotected(...):119 /naev/lib/lua/ldo.c
./naev-0.5.3-linux-x86-64() [0x59f34b] luaD_pcall(...):464 /naev/lib/lua/ldo.c
./naev-0.5.3-linux-x86-64(lua_pcall+0x16a) [0x599a75] lua_pcall(...):821 /naev/lib/lua/lapi.c
./naev-0.5.3-linux-x86-64() [0x463f49] gui_runFunc(...):1930 /naev/src/gui.c
./naev-0.5.3-linux-x86-64() [0x463e8e] gui_doFunc(...):1880 /naev/src/gui.c
./naev-0.5.3-linux-x86-64(gui_setNav+0x1a) [0x464029] gui_setNav(...):1963 /naev/src/gui.c
./naev-0.5.3-linux-x86-64(map_jump+0x150) [0x47b7e0] map_jump(...):1250 /naev/src/map.c
./naev-0.5.3-linux-x86-64(player_brokeHyperspace+0x164) [0x4d3e2f] player_brokeHyperspace(...):1675 /naev/src/player.c
./naev-0.5.3-linux-x86-64(player_runHooks+0x14) [0x4d5aca] player_runHooks(...):2627 /naev/src/player.c
./naev-0.5.3-linux-x86-64(hook_exclusionEnd+0x74) [0x4668a8] hook_exclusionEnd(...):233 /naev/src/hook.c
./naev-0.5.3-linux-x86-64(update_routine+0x67) [0x489b71] update_routine(...):879 /naev/src/naev.c
./naev-0.5.3-linux-x86-64() [0x489aa8] update_all(...):840 /naev/src/naev.c
./naev-0.5.3-linux-x86-64(main_loop+0x5a) [0x489713] main_loop(...):711 /naev/src/naev.c
./naev-0.5.3-linux-x86-64(main+0x86e) [0x488f52] main(...):431 /naev/src/naev.c
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd) [0x7f8a6f848ead] ??(...):0 ??
./naev-0.5.3-linux-x86-64() [0x42dee5] _start(...):0 ??
Report this to project maintainer with the backtrace.
AL lib: ReleaseALC: 1 device not closed

&gt; What version of NAEV are you using? On what operating system?
Version 0.5.3 on Linux x86-64 (downloaded from Sourceforge).

&gt; Can you reproduce the bug? If so, how can you reproduce the bug?
(Un?)fortunately restarting from the last save and repeating the same actions does not repeat the crash. Maybe the traceback gives enough information to spot the bug....

**Comment by bobbens** [comment]
Very old, closing.
