### ISSUE TITLE
Sigsegv when activating afterburners

### ISSUE THREAD

**Issue by naev** [naev/naev#389]
Original [issue 205](https://code.google.com/p/naev/issues/detail?id=205) created by justi.n.... on 2012-09-07T02:49:15.000Z:

Naev, latest dev build, on ubuntu 12.04.
The issue seems system independent, and I have received it multiple times. It happens sometimes when I double tap the forward key to activate afterburners, but I have no afterburners installed. Heres the stderr:
Naev received SIGSEGV (address not mapped to object)!
naev() [0x47b033] debug_sigHandler(...):1241 /home/justin/git/dev/src/naev.c
/lib/x86_64-linux-gnu/libc.so.6(+0x364c0) [0x7fd7609d34c0] ??(...):0 ??
naev(pilot_afterburn+0xc0) [0x4c2b0c] pilot_afterburn(...):1280 /home/justin/git/dev/src/pilot_weapon.c
naev() [0x45c957] input_key(...):729 /home/justin/git/dev/src/input.c
naev() [0x45ecd7] input_keyevent(...):1086 /home/justin/git/dev/src/input.c
naev(input_handle+0x145) [0x45f922] input_handle(...):1310 /home/justin/git/dev/src/input.c
naev(main+0x865) [0x479a21] main(...):441 /home/justin/git/dev/src/naev.c
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7fd7609be76d] ??(...):0 ??
naev() [0x41dbe9] _start(...):0 ??
Report this to project maintainer with the backtrace.

**Comment by bobbens** [comment]
Probably irrelevant now, closing.
