### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by naev** [naev/naev#391]
Original [issue 207](https://code.google.com/p/naev/issues/detail?id=207) created by k0s_J532... on 2012-09-17T12:32:44.000Z:

 Naev v0.6.0
 git HEAD at naev-0.5.3-473-ga59929c
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 1.2.15 [compiled: 1.2.15]

ERROR opengl.c:462 [gl_createWindow]: Unable to create OpenGL window: Could not create GL context
Naev received SIGABRT!
naev() [0x80acbb5] music_mix_setPos(...):0 ??
linux-gate.so.1(__kernel_rt_sigreturn+0) [0xb77aa40c] ??(...):0 ??
linux-gate.so.1(__kernel_vsyscall+0x10) [0xb77aa424] ??(...):0 ??
/usr/lib/libc.so.6(gsignal+0x4f) [0xb714f5df] ??(...):0 ??
/usr/lib/libc.so.6(abort+0x143) [0xb7150ec3] ??(...):0 ??
naev(gl_init+0x9f4) [0x80ca3d4] gl_init(...):0 ??
naev(main+0x357) [0x8061fb7] main(...):0 ??
/usr/lib/libc.so.6(__libc_start_main+0xf5) [0xb713a605] ??(...):0 ??
naev() [0x8062c6d] _start(...):0 ??
Report this to project maintainer with the backtrace.

After updating git build I get this message on every startup.

Naev 0.6.0 (git build from git://github.com/BTAxis/naev).

Arch Linux
xorg-server 1.12.4-1
nvidia-drivers 173.14.35

**Comment by bobbens** [comment]
Likely irrelevant, closing.
