### ISSUE TITLE
Naev crashes on mission abort

### ISSUE THREAD

**Issue by naev** [naev/naev#392]
Original [issue 208](https://code.google.com/p/naev/issues/detail?id=208) created by justi.n.... on 2012-09-20T19:30:02.000Z:

I'm developing a mission for the heretic campaign, and the game save currently has the same mission twice. When I abort both (not just one, but both), the game crashes. Heres the full gdb text. Please note, all the [pack_openfromcache] have been happening for a while, and have not been affecting gameplay in any way.

(gdb) run
Starting program: /usr/local/bin/naev 
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/lib/x86_64-linux-gnu/libthread_db.so.1&quot;.
 Naev v0.6.0
 git HEAD at naev-0.5.3-469-gc503b89
[New Thread 0x7ffff1a22700 (LWP 29675)]
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 1.2.14 [compiled: 1.2.14]

OpenGL Window Created: 1024x600@32bpp window
r: 8, g: 8, b: 8, a: 8, db: yes, fsaa: 0, tex: 16384
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: AMD Radeon HD 6520G
Version: 4.2.11627 Compatibility Profile Context

Sound is disabled!
Loaded 16 Nebula Layers
Loaded 35 Commodities
Loaded 29 Factions
Loaded 32 AI Profiles
Loaded 70 Missions
Loaded 31 Events
Loaded 262 Outfits
Loaded 61 Ships
Loaded 99 Fleets
Loaded 51 tech groups
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Loaded 294 Star Systems with 958 Planets
Warning: [pack_openFromCache] File 'prng.lua' not found in packfile.
Warning: [pack_openFromCache] File 'proximity' not found in packfile.
Warning: [pack_openFromCache] File 'dat/scripts/proximity' not found in packfile.
Warning: [pack_openFromCache] File 'proximity' not found in packfile.
Warning: [pack_openFromCache] File 'dat/scripts/proximity' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.
Warning: [pack_openFromCache] File 'jumpdist.lua' not found in packfile.
Warning: [pack_openFromCache] File 'cargo_common.lua' not found in packfile.
Warning: [pack_openFromCache] File 'nextjump.lua' not found in packfile.
Warning: [pack_openFromCache] File 'numstring.lua' not found in packfile.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000509573 in sweeplist (L=0x292b9170, p=0x292b9170, 
    count=18446744073709551067) at lgc.c:412
412     if (curr-&gt;gch.tt == LUA_TTHREAD)  /\* sweep open upvalues of each thread */
(gdb) bt full
# &nbsp;0  0x0000000000509573 in sweeplist (L=0x292b9170, p=0x292b9170,

```
count=18446744073709551067) at lgc.c:412
    curr = 0x160
    g = 0x292b9228
    deadmask = 64
```
# &nbsp;1  0x0000000000509965 in luaC_freeall (L=0x292b9170) at lgc.c:487

```
    g = 0x292b9228
    i = 0
```
# &nbsp;2  0x0000000000512a61 in close_state (L=0x292b9170) at lstate.c:108

```
    g = 0x292b9228
```
# &nbsp;3  0x0000000000512f79 in lua_close (L=0x292b9170) at lstate.c:212

No locals.
# &nbsp;4  0x0000000000473efa in mission_cleanup (misn=0x782b80) at mission.c:537

```
    i = 0
    ret = 0
    __func__ = &quot;mission_cleanup&quot;
```
# &nbsp;5  0x0000000000488267 in misn_runFunc (misn=0x782b80, func=0x52e671 &quot;abort&quot;,

```
nargs=0) at nlua_misn.c:285
    i = -16640
    ret = 2
    errf = -2
    err = 0x292d10b8 &quot;__done__&quot;
    L = 0x292b9170
```

---Type &lt;return&gt; to continue, or q &lt;return&gt; to quit---
        misn_delete = 1
        cur_mission = 0x782b80
        **func** = &quot;misn_runFunc&quot;
# &nbsp;6  0x0000000000487fa8 in misn_tryRun (misn=0x782b80, func=0x52e671 &quot;abort&quot;)

```
at nlua_misn.c:167
```

No locals.
# &nbsp;7  0x000000000045b5d1 in mission_menu_abort (wid=35,

```
str=0x5375cb0 &quot;btnAbortMission&quot;) at info.c:1061
    pos = 0
    misn = 0x782b80
    ret = 32767
```
# &nbsp;8  0x00000000004ea79e in toolkit_mouseEventWidget (w=0x29362c30,

```
wgt=0x13ca0850, type=6, button=1 '\001', x=62, y=19, rx=0, ry=0)
at toolkit.c:1795
    ret = 0
    inbounds = 1
```
# &nbsp;9  0x00000000004ea52c in toolkit_mouseEvent (w=0x29362c30,

```
event=0x7fffffffc130) at toolkit.c:1706
    wgt = 0x13ca0850
    type = 6
    button = 1 '\001'
    x = 552
    y = 89
```

---Type &lt;return&gt; to continue, or q &lt;return&gt; to quit---
        rx = 0
        ry = 0
        ret = 0
# &nbsp;10 0x00000000004ea26b in toolkit_inputWindow (wdw=0x29362c30,

```
event=0x7fffffffc130, purge=0) at toolkit.c:1607
    ret = 0
    wgt = 0x0
```
# &nbsp;11 0x00000000004f85db in tab_raw (tab=0x6ba6d60, event=0x7fffffffc130)

```
at tabwin.c:160
    wdw = 0x29362c30
    ret = 0
    __func__ = &quot;tab_raw&quot;
```
# &nbsp;12 0x00000000004ea1e5 in toolkit_inputWindow (wdw=0x29343110,

```
event=0x7fffffffc130, purge=1) at toolkit.c:1588
    ret = 0
    wgt = 0x6ba6d60
```
# &nbsp;13 0x00000000004ea188 in toolkit_input (event=0x7fffffffc130)

```
at toolkit.c:1571
    wdw = 0x29343110
```
# &nbsp;14 0x000000000045f848 in input_handle (event=0x7fffffffc130) at input.c:1277

```
    ismouse = 1
```
# &nbsp;15 0x0000000000479a21 in main (argc=1, argv=0x7fffffffe288) at naev.c:441

```
    buf = &quot;/home/justin/.config/naev/conf.lua&quot;, '\000' &lt;repeats 2518 times&gt;,---Type &lt;return&gt; to continue, or q &lt;return&gt; to quit---
```

 &quot;J\021\336\367\377\177&quot;, '\000' &lt;repeats 75 times&gt;&quot;\200, \001\000\000\000\000\000\204v\001\000\000\000\000\000\204v\001&quot;, '\000' &lt;repeats 13 times&gt;, &quot;\005\000\000\000\000\000\000\000\000\200!\000\000\000\000\000\000\240!\000\000\000\000\000`\222!\000\000\000\000\000x\272!\000\000\000\000\000\000\200\001\000\000\000\000\000\003&quot;, '\000' &lt;repeats 16 times&gt;, &quot;p\001\000\000\000\000\000xe\001\000\000\000\000\000xe\001&quot;, '\000' &lt;repeats 13 times&gt;, &quot;\005&quot;, '\000' &lt;repeats 16 times&gt;, &quot;0+\000\000\000\000\000\324$+\000\000\000\000\000\324$+&quot;, '\000' &lt;repeats 13 times&gt;...
        **func** = &quot;main&quot;
        vidinfo = 0x785e00
        oldconfig = 0
        event = {type = 6 '\006', active = {type = 6 '\006', gain = 0 '\000', 
            state = 1 '\001'}, key = {type = 6 '\006', which = 0 '\000', 
            state = 1 '\001', keysym = {scancode = 252 '\374', 
              sym = SDLK_UNKNOWN, mod = KMOD_NONE, unicode = 0}}, motion = {
            type = 6 '\006', which = 0 '\000', state = 1 '\001', x = 764, 
            y = 417, xrel = 0, yrel = 0}, button = {type = 6 '\006', 
            which = 0 '\000', button = 1 '\001', state = 0 '\000', x = 764, 
            y = 417}, jaxis = {type = 6 '\006', which = 0 '\000', 
            axis = 1 '\001', value = 764}, jball = {type = 6 '\006', 
            which = 0 '\000', ball = 1 '\001', xrel = 764, yrel = 417}, 
          jhat = {type = 6 '\006', which = 0 '\000', hat = 1 '\001', 
            value = 0 '\000'}, jbutton = {type = 6 '\006', which = 0 '\000', 
---Type &lt;return&gt; to continue, or q &lt;return&gt; to quit---
            button = 1 '\001', state = 0 '\000'}, resize = {type = 6 '\006', 
            w = 27329276, h = 0}, expose = {type = 6 '\006'}, quit = {
            type = 6 '\006'}, user = {type = 6 '\006', code = 27329276, 
            data1 = 0x0, data2 = 0x0}, syswm = {type = 6 '\006', msg = 0x0}}

**Comment by onpon4** [comment]
This is probably fixed by now. (Most likely just a memory access bug somewhere.)
