### ISSUE TITLE
Shipyard: overlapping text

### ISSUE THREAD

**Issue by naev** [naev/naev#398]
Original [issue 214](https://code.google.com/p/naev/issues/detail?id=214) created by todurov on 2012-10-19T10:35:15.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
Git commit 2b08ad6e00bc53ec38ec4f9837e3613287d0e713
./naev --version says
 Naev v0.6.0
 git HEAD at naev-0.5.3-492-g2b08ad6
Arch Linux 64-bit

Longer text in ship stats (like price) tends to overlap with the ship mod percentages.

**Comment by bobbens** [comment]
Don't think this is applicable anymore.
