### ISSUE TITLE
Shipyard: unaligned data

### ISSUE THREAD

**Issue by naev** [naev/naev#399]
Original [issue 215](https://code.google.com/p/naev/issues/detail?id=215) created by todurov on 2012-10-19T10:36:26.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
Git commit 2b08ad6e00bc53ec38ec4f9837e3613287d0e713
./naev --version says
 Naev v0.6.0
 git HEAD at naev-0.5.3-492-g2b08ad6
Arch Linux 64-bit

In shipyard, you can't buy any ships because the data fields (including ship's price) is misaligned -- your current funds end up in the ship's price, the license required ends up in your current funds etc.

**Comment by bobbens** [comment]
Don't think this is applicable anymore.
