### ISSUE TITLE
Ubuntu 13.04 package - getdeb will not be updated

### ISSUE THREAD

**Issue by naev** [naev/naev#402]
Original [issue 218](https://code.google.com/p/naev/issues/detail?id=218) created by capsel on 2013-05-02T09:48:47.000Z:

http://en.wikipedia.org/wiki/GetDeb

**Comment by CloCkWeRX** [comment]
Is this still relevant? The links to the old issue are broken, so not much context is avail

**Comment by ids1024** [comment]
I'm not sure what this was about, but it doesn't look like there's an issue: http://www.playdeb.net/game/NAEV

I'm not on Ubuntu, so I haven't tested the packages there, it seems to have the latest Naev version, and the latest Ubuntu.

**Comment by Fayti1703** [comment]
@ids1024 
Ubuntu does indeed have the latest version up on the repositories. It just took ~3 days for them to be updated last time, which is acceptable.
Though you don't really need to install those anymore if you have Steam.

**Comment by PhoenixRiver** [comment]
Though Steam is not the easiest thing to get working with various
versions and flavours of Ubuntu and Ubuntu based distros...
