### ISSUE TITLE
Fuel text is near-unreadable in slimv2 when 100 fuel is left

### ISSUE THREAD

**Issue by naev** [naev/naev#414]
Original [issue 230](https://code.google.com/p/naev/issues/detail?id=230) created by almikes on 2015-02-22T19:45:40.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
0.6.0-beta1

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>
Yes.

Use the GUI “slimv2”. Make sure you only have 100 fuel left. Look on the fuel bar.

The fuel text on the fuel bar becomes unreadable, it looks like there is only a red bar. If you look closely you can read “100 (1 jumps)” [sic!] in a red font. Too bad the bar is also red, so it is very hard to read.

**Comment by bobbens** [comment]
GUI was rewritten.
