### ISSUE TITLE
Bad map overlay in slimv2

### ISSUE THREAD

**Issue by naev** [naev/naev#415]
Original [issue 231](https://code.google.com/p/naev/issues/detail?id=231) created by almikes on 2015-02-22T19:55:36.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
0.6.0-beta1

The map overlay (press Tab key) is sub-optimal when using the slimv2 GUI.
Part of the map may be overlayed over the normal GUI and some symbols may become hard to see.

I noticed this in the Sikh system, where the jump gate symbol for Acheron was placed directly over the GUI elements, making this symbol kinda tricky to see.

**Comment by onpon4** [comment]
I think this bug can be said to be basically obsolete as a problem since we're not using Slimv2.

**Comment by bobbens** [comment]
GUI was rewritten.
