### ISSUE TITLE
Afterburner overheating not shown in slimv2 GUI

### ISSUE THREAD

**Issue by naev** [naev/naev#416]
Original [issue 232](https://code.google.com/p/naev/issues/detail?id=232) created by almikes on 2015-02-22T19:59:47.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
0.6.0-beta1
on GNU/Linux (same OS for all my other issues, sorry, I forgot to mention that earlier).

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>
Yes.

First, use the slim GUI.
Get an afterburner, then use it for a while and cause a bit heat in the afterburner. This should make the afterburner symbol go red.

Now switch to the slimv2 GUI. The afterburner heat is not shown in this GUI, which is not good IMO.

**Comment by ids1024** [comment]
This issue can be closed. PR #437 fixed it.
