### ISSUE TITLE
Sound breaks down if a large number of projectiles are fired

### ISSUE THREAD

**Issue by naev** [naev/naev#418]
Original [issue 234](https://code.google.com/p/naev/issues/detail?id=234) created by almikes on 2015-02-23T02:49:57.000Z:

If there are many, many projectiles fired by many, many ships, it can happen that the sound breaks down for a while. The sound first sounds really bad, then goes off entirely. If the firefight is over, the sound comes again.

<b>What version of NAEV are you using? On what operating system?</b>
0.6.0-beta1 on GNU/Linux

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>
Kinda. It seems to happen most often in nebulae, around the systems Raelid, Arcanis, Zylex and Doeston.

**Comment by onpon4** [comment]
I think this is solved? I haven't experienced this bug at any rate.
