### ISSUE TITLE
Nebulae in different colors

### ISSUE THREAD

**Issue by naev** [naev/naev#423]
Original [issue 239](https://code.google.com/p/naev/issues/detail?id=239) created by almikes on 2015-02-28T19:53:41.000Z:

I suggest that systems with a nebula sould have a nebula in some other colors than only blue. The color would be different on a per-system basis then.
It would certainly add to the game's atmosphere a bit.

**Comment by bobbens** [comment]
Implemented and given some different colours for some different areas. Closing.
