### ISSUE TITLE
Changing size of a force-maximized (?) window breaks cursor position

### ISSUE THREAD

**Issue by naev** [naev/naev#424]
Original [issue 240](https://code.google.com/p/naev/issues/detail?id=240) created by almikes on 2015-03-06T15:05:42.000Z:

<b>What version of NAEV are you using? On what operating system?</b>
0.6.0-beta2 on GNU/Linux.

The bug:
Resizing the window via the options menu makes Naev fail to “see” the correct cursor position when the window wax maximized.

I use the XFCE window manager and it only happens if I have the window in “maximized” mode. If it is non-maxized, it works fine.
So it seems that Naev is not prepared for this.
Note that XFCE _forces_ a window to be maximized if it is in maximized. I am not sure if this is a bug in XFCE or in Naev or in something else.

<b>Can you reproduce the bug? If so, how can you reproduce the bug?</b>
Yes.
Start in windowed mode, but use a maximized window, then go to Options, Video and set any resolution, but not fullscreen. Click OK. Now hover with the mouse over the new dialog. The hovering of the button will not match the mouse position, it will be slightly misplaced. You could also click on “Yes” (or hit the [Y] key) and check it further on the main menu.
As soon as you resize the window manually, the bug is gone.

For me, I have cursor slightly below the button and it is hovered, when it is on the button, the button is not hovered and clicking has no effect.

**Comment by bobbens** [comment]
Not likely still an issue.
