### ISSUE TITLE
Also a crash report:

### ISSUE THREAD

**Issue by aaps** [naev/naev#430]
From time to time i secretly check in on naev, it is a nice game, better it is still getting developed
I ran into this crash when i accept any mission from the bar or cargo.
It is a lua thing i guess, hope this helps

 Naev v0.6.0
 git HEAD at naev-0.6.0-6-g5f921f9
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 1.2.14 [compiled: 1.2.14]

OpenGL Window Created: 1024x768@24bpp window
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 4096
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: Gallium 0.4 on llvmpipe (LLVM 0x300)
Version: 2.1 Mesa 8.0.4

SDL_Mixer Started: 44100 Hz Stereo
Renderer: pulse
Version: 1.2.11 [compiled: 1.2.11]

Loaded 35 sounds
Loaded 47 songs
Loaded 16 Nebula Layers
Loaded 41 Commodities
Loaded 30 Factions
Loaded 33 AI Profiles
Loaded 77 Missions
Loaded 32 Events
Loaded 264 Outfits
Loaded 77 Ships
Loaded 108 Fleets
Loaded 59 tech groups
Loaded 373 Star Systems with 1106 Planets
Warning: [intro_fade_image_in] Intro scrolling too fast!
Naev received SIGSEGV (address not mapped to object)!
./naev() [0x80b6743] debug_sigHandler(...):0 naev.c
[0xb76fa40c] ??(...):0 ??
./naev() [0x80b09de] _array_private_container(...):0 mission.c
./naev(mission_addMarker+0x41) [0x80b10a6] mission_addMarker(...):0 ??
./naev() [0x80c25aa] misn_markerAdd(...):0 nlua_misn.c
./naev() [0x81326a2] luaD_precall(...):0 crtstuff.c
./naev() [0x8144da2] luaV_execute(...):0 crtstuff.c
./naev() [0x81328d6] luaD_call(...):0 crtstuff.c
./naev() [0x812e2e4] f_call(...):0 lapi.c
./naev() [0x8131b97] luaD_rawrunprotected(...):0 crtstuff.c
./naev() [0x8132c0b] luaD_pcall(...):0 crtstuff.c
./naev(lua_pcall+0x12f) [0x812e418] lua_pcall(...):0 ??
./naev(misn_runFunc+0x2a) [0x80c2227] misn_runFunc(...):0 ??
./naev(misn_run+0x27) [0x80c2131] misn_run(...):0 ??
./naev(mission_accept+0x16) [0x80b0d41] mission_accept(...):0 ??
./naev() [0x80d310b] npc_approach_giver(...):0 npc.c
./naev(npc_approach+0x68) [0x80d31db] npc_approach(...):0 ??
./naev() [0x80a0814] bar_approach(...):0 land.c
./naev() [0x81189ac] toolkit_mouseEventWidget(...):0 toolkit.c
./naev() [0x8118778] toolkit_mouseEvent(...):0 toolkit.c
./naev(toolkit_inputWindow+0xb9) [0x8118509] toolkit_inputWindow(...):0 ??
./naev() [0x8125f0a] tab_raw(...):0 tabwin.c
./naev(toolkit_inputWindow+0x40) [0x8118490] toolkit_inputWindow(...):0 ??
./naev(toolkit_input+0x2b) [0x811844b] toolkit_input(...):0 ??
./naev(input_handle+0x5f) [0x809e1c0] input_handle(...):0 ??
./naev(main+0x875) [0x80b506c] main(...):0 ??
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0xb70994d3] ??(...):0 ??
./naev() [0x805f501] _start(...):0 ??
Report this to project maintainer with the backtrace.

**Comment by Deiz** [comment]
Can you verify that this crash still happens as of 155a7fda? This likely stems from the same issue that that commit fixed.

**Comment by aaps** [comment]
8245fa36fa3952e120b79a4fc27700e0d1618923
gets me into trouble all before is fine

**Comment by aaps** [comment]
have also been looking at some unit tests for c, as to prevent this problem in the future.
Unit tests in c are NOT as easy as they are in python :(

**Comment by Deiz** [comment]
155a7fda is a later commit than 8245fa36. The issue was introduced in 173bad4a and should be fixed as of 155a7fda.

**Comment by aaps** [comment]
I could have sworn i tested the latest commit, well yes 155a7fd works.
