### ISSUE TITLE
Crash with player.swapship() when landed

### ISSUE THREAD

**Issue by ids1024** [naev/naev#433]
@l0k1 has mentioned this bug on irc. It occurs at the end of the fourth Goddard/Krain mission that is currently under development (see [this forum post](https://forum.naev.org/viewtopic.php?f=8&t=1064)). In a land hook, player.swapship() is called with remove=true, but this does not remove the ship from the outfitter display. If the ship is then selected, naev segfaults.

**Comment by Deiz** [comment]
Fixed in 34651062.
