### ISSUE TITLE
Empire hcvl mission error

### ISSUE THREAD

**Issue by wurzelderzwerg** [naev/naev#434]
What version of NAEV are you using? On what operating system?

naev-0.6.0-win64 on Windows 7 and Windows 8.1

Can you reproduce the bug? If so, how can you reproduce the bug?

The mission is displayed correctly in the Spaceport bar, approaching the Empire official fails to open the mission description.

A stderr_ file is created, containing (on both systems):

Warning: [misn_runFunc] Mission 'Empire HCVL' -> 'accept': [string "dat/factions/equip/helper.lua"]:249: attempt to call method 'ship' (a nil value)
stack traceback:
	[string "dat/factions/equip/helper.lua"]:249: in function 'equip_parseWeapons'
	[string "dat/factions/equip/helper.lua"]:157: in function 'equip_ship'
	[string "pilot/pirate.lua"]:89: in function <[string "pilot/pirate.lua"]:55>
	(tail call): ?
	[string "dat/missions/empire/emp_hcvl.lua"]:185: in function 'pir_generate'
	[string "dat/missions/empire/emp_hcvl.lua"]:56: in function <[string "dat/missions/empire/emp_hcvl.lua"]:54>

**Comment by Deiz** [comment]
Already fixed, will be released in 0.6.1. See [this forum thread](https://forum.naev.org/viewtopic.php?t=1072) if you'd like to apply the fix before the official release.
