### ISSUE TITLE
Outfits lost when CPU exceeded

### ISSUE THREAD

**Issue by mattvchandler** [naev/naev#446]
If adding an outfit will exceed the ship's CPU cap, the outfit dissapears.
The lua console says: Warning: [pilot_addOutfitTest] Pilot '<my ship>': Not enough CPU to add outfit '<outfit name>'
This is in v .0.6.0 on linux

**Comment by Deiz** [comment]
Fixed in 47eac6c9 (which we re-tagged 0.6.0 for). If you grabbed a binary off SourceForge very shortly after release, redownloading it will fix the issue.

I believe it's still present in the Desura builds, so if you've installed via Desura it'll be fixed in 0.6.1.
