### ISSUE TITLE
Hitman 3 fails to start

### ISSUE THREAD

**Issue by Taknamay** [naev/naev#447]
Hi, when I try to start hitman 3, I get this error in my terminal. Can someone else try to start the quest?

Warning: [misn_runFunc] Mission 'Hitman 3' -> 'create': [string "dat/factions/equip/helper.lua"]:249: attempt to call method 'ship' (a nil value)
stack traceback:
	[string "dat/factions/equip/helper.lua"]:249: in function 'equip_parseWeapons'
	[string "dat/factions/equip/helper.lua"]:157: in function 'equip_ship'
	[string "pilot/empire.lua"]:102: in function <[string "pilot/empire.lua"]:68>
	(tail call): ?
	[string "dat/missions/pirate/hitman3.lua"]:199: in function 'emp_generate'
	[string "dat/missions/pirate/hitman3.lua"]:51: in function <[string "dat/missions/pirate/hitman3.lua"]:48>

**Comment by Deiz** [comment]
This was fixed in e025a85f which will make it into 0.6.1. If you'd like the fix now, see [this forum thread](https://forum.naev.org/viewtopic.php?t=1072).
