### ISSUE TITLE
Kill stats

### ISSUE THREAD

**Issue by lightonflux** [naev/naev#448]
I really like naev, but it is really hard to get a feeling for the Combat Rating. It would be nice if the board computer (key "i") could not only display the combat rating and faction standing, but also kill stats.

Another game i played (ascii sector) has it, sadly the game is closed source and the development halted. But it was always surprising how many pirates you "accidentally" killed when you cross many systems. Or sometimes even allied faction ships.

Screenshot:
![auswahl_098](https://cloud.githubusercontent.com/assets/1377943/6927563/9bdc874e-d7ee-11e4-9b41-5ff23f4855e4.png)

**Comment by bobbens** [comment]
Kill stats do not seem too inline with the current Naev philosophy, closing.
