### ISSUE TITLE
Approach person via double click

### ISSUE THREAD

**Issue by lightonflux** [naev/naev#449]
Naev has great mouse and keyboard controls. Many action can be activated with a mouseclick and sometimes a bit faster via double click.

Double clicking on persons in the spacebar would save some time and allow shorter mouse paths.

**Comment by Corax** [comment]
Doesn't right-clicking already do what you propose?

**Comment by lightonflux** [comment]
Oh it does. I never tried, because double clicking is a shortcut for planets etc. so i never thought of right clicking.

There is a small glitch when you right click:

![naev - sea of darkness_115](https://cloud.githubusercontent.com/assets/1377943/7430417/40e14cfc-f013-11e4-86ad-e1dd9d987245.png)
