### ISSUE TITLE
Crash on startup: Unable to create rwops from Nebula image

### ISSUE THREAD

**Issue by 3axapm** [naev/naev#467]
Windows 8.1

Warning: [loadNebula] Unable to create rwops from Nebula image: nebu_bg_1280x697_00.png
Warning: [loadNebula] Unable to create rwops from Nebula image: nebu_bg_1280x697_00.png
Warning: [loadNebula] Unable to create rwops from Nebula image: nebu_bg_1280x697_00.png
Warning: [nebu_init_recursive] Unable to generate nebula after 3 attempts, something has really gone wrong!
ERROR naev.c:371 [SDL_main]: Unable to initialize the Nebula subsystem!
AL lib: (EE) alc_cleanup: 1 device not closed

 Naev v0.6.0
 git HEAD at naev-0.6.0
 Sea of Darkness

SDL: 2.0.3 [compiled: 2.0.3]

OpenGL Window Created: 1280x720@32bpp window
r: 8, g: 8, b: 8, a: 8, db: yes, fsaa: 0, tex: 16384
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: Intel(R) HD Graphics 4400
Version: 4.2.0 - Build 10.18.10.3308

OpenAL started: 48000 Hz
Renderer: OpenAL Soft
Version: 1.1 ALSOFT 1.16.0 with EFX 1.0

Loaded 35 sounds
Loaded 47 songs
No nebula found, generating (this may take a while).
Generating Nebula of size 1280x697x16
Nebula Generated in 8946 ms
No nebula found, generating (this may take a while).
Generating Nebula of size 1280x697x16
Nebula Generated in 8891 ms
No nebula found, generating (this may take a while).
Generating Nebula of size 1280x697x16
Nebula Generated in 8897 ms
No nebula found, generating (this may take a while).
Generating Nebula of size 1280x697x16
Nebula Generated in 8793 ms

**Comment by BTAxis** [comment]
It sounds like Naev doesn't have permissions to write to the default data location. You can try running the game with administrator privileges, though a better solution might be to configure the game as a portable application. See:
http://wiki.naev.org/wiki/Portable_Mode
Make sure you have write permissions in the location you specify.

**Comment by 3axapm** [comment]
Run the game with administrator privileges not helps.
Portable application working well.
Thank you.
