### ISSUE TITLE
Bugged Empire Bounties

### ISSUE THREAD

**Issue by Kharrus** [naev/naev#496]
I started a new character after downloading 0.6.0, and finished the empire missions.  I need to run the bounty offers to get my medium and heavy ship licenses, but whenever I approach the officer who offers bounties in the bar, he disappears without anything happening.

help! I love the new build and tried it out on a new machine without any older characters, so I need this fixed to progress.  Any ideas what could be going on?

**Comment by toams** [comment]
this is a known bug: see https://forum.naev.org/viewtopic.php?t=1072 for a fix, or wait for 6.1

**Comment by Kharrus** [comment]
Thank you very much.  I'm not very familiar with coding or file manipulation, so I'm replacing the ndata file with an older version without the bug, getting the appropriate licenses that way, then placing the current version back in as a stopgap measure.

**Comment by bobbens** [comment]
We will be releasing 0.6.1 so I'll close this report. Thanks!
