### ISSUE TITLE
Pirate Ship Stealing mission crashes if target planet has no bar

### ISSUE THREAD

**Issue by dev-random** [naev/naev#497]
I've reported this bug on forums a few years ago, but apparently it was wrong place to do so.

If you try to steal a ship from a planet with no bar (e.g. Zaren), game crashes after naming it.

Event "neutral/news.lua" calls newsL_rm() which calls bar_regen() (if landing is finished, i.e. land_loaded is set).
land_getWid(LAND_WINDOW_BAR) called by bar_regen() returns 0 (planet doesn't have bar), and this 0 is passed to bar_genList().
bar_genList() calls strdup(window_getFocus(wid)) where wid is 0 and window_getFocus(wid) is NULL.
strdup(NULL) segfaults.

Normally, the call to bar_regen() is skipped because "neutral/news.lua" is called before landing finishes. In this mission, player_swapShip() calls land_genWindows() through gui_load() and prematurely finishes landing.

Proposed fix:

```diff
diff --git a/src/land.c b/src/land.c
index 1f30f64..0bbb3d5 100644
--- a/src/land.c
+++ b/src/land.c
@@ -628,6 +628,10 @@ static int bar_genList( unsigned int wid )
    int w, h, iw, ih, bw, bh;
    int n, pos;
 
+   /* Sanity check */
+   if (wid == 0)
+      return 0;
+
    /* Get dimensions. */
    bar_getDim( wid, &w, &h, &iw, &ih, &bw, &bh );
```

**Comment by bobbens** [comment]
Sorry for the late response. Yes, I don't go into the forums at all, too busy with silly real life stuff these days. Looks good, thanks for the patch. It'll make its way into 0.6.1 release.
