### ISSUE TITLE
Mac build of 0.6.0 stable appears to actually be Beta 1

### ISSUE THREAD

**Issue by GuamBomb** [naev/naev#505]
Simply put, what the title says. 

To be more detailed, when I download the Mac stable binary from SourceForge, what I actually get is a binary that is indistinguishable from beta 1 of 0.6.0.  In comparison, Beta 2 for Mac includes the new features added after Beta 1, which the stable lacks.  Finally, the main screen in the Mac binary marked as stable still actually says Beta 1 on it.

**Comment by ids1024** [comment]
@meric
