### ISSUE TITLE
Holding down Secondary Weapon key disables thrust/steering

### ISSUE THREAD

**Issue by GuamBomb** [naev/naev#507]
Disclaimer:  This is a bug report for beta 2 for Mac, since I'm currently unable to play the stable on Mac (see other bug report).  If this bug has been fixed in the stable (I can't confirm this, but anyway), then disregard.

The issue I'm reporting is as the subject says.  More specifically, when I am in a combat situation and find myself having to use a secondary weapon (the Ion Cannon in this case), if I hold down the secondary weapon key for any more than a quick tap, I temporarily lose steering and thrust control until a short delay after I release the secondary weapon key.  This is highly undesirable when involved in space combat.

**Comment by bobbens** [comment]
Try binding it to other keys. This could be a hardware issue as some keyboards do not register all keypresses when doing certain combinations. You could also try testing this in another application.

**Comment by GuamBomb** [comment]
I have tried binding other keys, and it persists. I should note that I usually change NAEV's keyboard layout to loosely match Escape Velocity, and I've never had issues using these keys in that game.

**Comment by onpon4** [comment]
Just want to note that I've never seen this in these last 5 years. Sounds a lot like ghosting to me.

Pedantic:

> some keyboards do not register all keypresses when doing certain combinations

Change that "some" to "most". :wink: A keyboard without ghosting is rare, even most gaming keyboards will give you some level of ghosting (just less to the point it typically isn't a problem).
