### ISSUE TITLE
Weapon disappearing when mounting them, if not enough CPU time

### ISSUE THREAD

**Issue by Signy3** [naev/naev#510]
Hi,

I landed on a planet with a shipyard. I bought a new (fancy) ship and started to mount it with new gear.
I have a problem when installing weapons. I bought weapon, yet, when mounting them, some just vanish.
I uploaded my save game file and described the procedure to reproduce the bug using my files.

Procedure : 
Load "Nathanael" save,
Go to outfits, buy MK3 laser turret (I don't have the CPU time for it),
Go to equipment,
Try to mount it,
In my case, it just disappears and nothing happens.

This does not happen when I have enough CPU time for the weapon.

Something that may help (a lot): 
My console output : 
Warning: [pilot_addOutfitTest] Pilot 'Youpi': Not enough CPU to add outfit 'Laser Turret MK3'

Files:
http://lesterresdelest.free.fr/dl/Nathanael.ns
http://lesterresdelest.free.fr/dl/Nathanael.ns.backup

System : Ubuntu 14.04 LST 2
Game version : 0.6.0

Nath'

**Comment by PhilmacFLy** [comment]
Its not only on Weapons, this also happens with Structures and Utilites

**Comment by BTAxis** [comment]
I cannot reproduce this on git master. The issue sounds familiar to me, I believe this has already been fixed.
