### ISSUE TITLE
Ships missing after completing Za'lek mission in the Dohriabi system

### ISSUE THREAD

**Issue by argarak** [naev/naev#512]
I recently compiled the Git version of Naev using the `naev-git` package in the [AUR](https://aur4.archlinux.org/packages/naev-git/) on the *8th of August*.

I travelled to the Dohriabi system and met the Za'lek scientists on the Niflheim station. I completed the misson and travelled to Bastion Station in Pultatis to swap my ships. At the time, I owned three ships;

- a Pacifier (used to complete the misson),
- a Quicksilver (for shipping missons)
- and a Collective Drone.

I looked at the 'Equipment' tab and found that only my Pacifier was there. All the other ships were missing after completing the misson.

I looked at my backup save, but they were gone from there too. I used the 'naev' package from my official repositories but I encountered issue #434. I heard that it was fixed in the Git version so I compiled it and played it on my stable 0.6.0 save. Everything was fine until I completed that misson. 

The logs look fine. They don't show any errors. [Logs (hosted by paste2.org)](http://paste2.org/tnXvnJng).

Computer Specifications:

- Processor		: 2x AMD Athlon(tm) II X2 240 Processor
- Memory		: 10245MB (2206MB used)
- Operating System		: Parabola GNU/Linux-Libre
- Resolution		: 3280x1080 pixels (two monitors)
- OpenGL Renderer		: Gallium 0.4 on AMD RV730

Thanks.

**Comment by argarak** [comment]
Nevermind, I came on a different system and they all came back. No idea why they did not show up on the other systems.

**Comment by pydsigner** [comment]
Those are the worst stations. Well, I guess the ones without Outfitters are worse.
