### ISSUE TITLE
Cannot exicute binary file

### ISSUE THREAD

**Issue by cramjaco** [naev/naev#561]
I had been running naev for a while. Last time I tried to run it I got the error message when I run `.naev` "bash . .: naev: cannot exicute binary file". Am I doing this wrong, or did it stop working for some reason. I'd post this to the forums rather than here, but I need to be able to run the game to look up the subtitle (which is required to register).

**Comment by ids1024** [comment]
Perhaps one of the libraries the binary is linked agaist was updated? What distro are you running? If it is Ubuntu, you can try installing from playdeb, which packages naev: http://www.playdeb.net/

**Comment by toams** [comment]
copy pasta from [here](http://superuser.com/questions/435988/how-can-i-resolve-the-error-cannot-execute-binary-file):
>Usually that error message means Linux doesn't recognize the file as a shell script or as an executable file.
>Typically the cause is running an executable on the wrong architecture - if you try to run x86 executables on an ARM CPU, this message comes up.

So there is something wrong with your naev binary. can you try installing again?
