### ISSUE TITLE
Game crashes with slim-v2 if active cooldown is on.

### ISSUE THREAD

**Issue by entd** [naev/naev#565]
Game crashes with slim-v2 if active cooldown is on. Autostoping activates corectly. Might be bug on cooldown bar?

**Comment by ids1024** [comment]
I think this is already fixed in git by commit a3e03a8fdf260c21f79e09d15fcbaf61e0856eb4.

**Comment by bobbens** [comment]
Yes, should be fixed. We should be releasing soon so this should stop being an issue.
