### ISSUE TITLE
Missing dll's

### ISSUE THREAD

**Issue by MandaKK** [naev/naev#574]
After installing the game, be it as portable or not-portable installation, whenever I try to open it, I get an  error stating that I'm missing the following 2 dll's:
-libzip-4.dll
-lua51.dll

Now I don't know if this is valid but if I download those dll's and place them in the game directory I then get an error that says: The application was unable to start correctly (0xc000007b).

I have Windows 10 64bits and this happens with the latest 0.6.1 version.

**Comment by BTAxis** [comment]
Huh, I just packaged with the same dlls as before. The libzip dll
    must have changed name (it was libzip-2.dll previously) and lua
    didn't use to be be needed because we package our own. I'll have to
    re-upload the installers.
    
    On 2015-11-13 17:18, MandaKK wrote:
    
    
      After installing the game, be it as portable or not-portable
        installation, whenever I try to open it, I get an error stating
        that I'm missing the following 2 dll's:
        -libzip-4.dll
        -lua51.dll
      Now I don't know if this is valid but if I download those dll's
        and place them in the game directory I then get an error that
        says: The application was unable to start correctly
        (0xc000007b).
      I have Windows 10 64bits and this happens with the latest 0.6.1
        version.
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by BTAxis** [comment]
And done. Please re-download the installer and reinstall the game. You don't have to re-download ndata.
