### ISSUE TITLE
Player not rendering correctly

### ISSUE THREAD

**Issue by lokiteitor** [naev/naev#578]
compiling the game directly from git. Player sprite shows a wrong image
![captura de pantalla de 2015-11-16 00-24-36](https://cloud.githubusercontent.com/assets/4691381/11175501/869eac36-8bf8-11e5-9533-ddff18954d9b.png)

**Comment by bobbens** [comment]
What opengl implementation and graphic card are you using? Could you also paste the naev output?

**Comment by lokiteitor** [comment]
from $lspci | grep -i vga
01:00.0 VGA compatible controller: NVIDIA Corporation GT218M [NVS 3100M] (rev a2)

from $glxinfo | grep -i opengl
OpenGL vendor string: nouveau
OpenGL renderer string: Gallium 0.4 on NVA8
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.4 (git-ec14e6f)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.0.4 (git-ec14e6f)
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.0.4 (git-ec14e6f)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

the naev output of the terminal 
 Naev v0.6.1
 git HEAD at naev-0.6.1-20-g9007995
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 1.2.15 [compiled: 1.2.15]

OpenGL Window Created: 1024x768@24bpp window
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 8192
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: Gallium 0.4 on NVA8
Version: 3.0 Mesa 11.0.4 (git-ec14e6f)

Warning: [sound_init] SDL_mixer support not compiled in!
Warning: [sound_init] Unknown/Unavailable sound backend 'sdlmix'.
Warning: [sound_init] Sound disabled.
Loaded 16 Nebula Layers
Loaded 44 Commodities
Loaded 30 Factions
Loaded 34 AI Profiles
Loaded 92 Missions
Loaded 32 Events
Loaded 267 Outfits
Loaded 77 Ships
Loaded 111 Fleets
Loaded 59 tech groups
Loaded 373 Star Systems with 1106 Planets
Warning: [intro_fade_image_in] Intro scrolling too fast!

**Comment by lokiteitor** [comment]
compile from a clean directory and apparently solve the problem may not install either a dependency
