### ISSUE TITLE
zlk_test missions cannot be run simultaneously

### ISSUE THREAD

**Issue by ThrosturX** [naev/naev#579]
``` lua
function rmTheOutfit()
   if isMounted("Za'lek Test Engine") then
      player.pilot():rmOutfit("Za'lek Test Engine")
   end
   while isOwned("Za'lek Test Engine") do  --to avoid remaining test engines if some error occures
      player.rmOutfit("Za'lek Test Engine")
   end
end
```

It's very obvious what will happen here if the player accepts 2 missions that both supply the engine. The player will only be able to complete one of the missions because the engines will be removed both from the ship and from the inventory. I would recommend adding a conditional checking whether additional instances of the mission exist.

**Comment by BTAxis** [comment]
Perhaps this should be done via the claim system, which currently only works on systems. A mission could claim any or all of the player's slots and fail to generate if such a claim fails. Perhaps this could extend to other forms of mutexing as well.

**Comment by bobbens** [comment]
Conditional check on the mission would work for this case, but if there is another engine swapping mission it will screw up. In that case a claim would be necessary. However, for claims we would have to start enforcing assumptions we make such that each ship has only one of these unique slot types (engine, etc...) and you claim that.

I'm thinking maybe a more simple way would be to just make some sort of meta-tags that you can claim. So if you want to block the engine you would use the "engine" tag, and it would work exactly like the system claim. Only tricky thing is developers have to agree on using the same tags (such as engine, etc...). So they would have to be documentated and maintained. How dous that sound?

**Comment by BTAxis** [comment]
That sounds good to me. The trick, probably, is designing it in such a fashion that it can be extended to other parts of the game we haven't necessarily anticipated without too much fuss.

**Comment by bobbens** [comment]
Well if it is just a string, you can have it represent anything you want. However, it then becomes the mission developer's job to keep it sane. I mean with just a string, you could also have the current claim system just be a particular case of the string case.

**Comment by BTAxis** [comment]
It could probably be somewhat de-obfuscated by creating a helper script for the purpose that simply contains a table of such strings, along with descriptions (in comments) of what each string represents, and the "proper" way to use claims is to claim an element from that table.

**Comment by idobox** [comment]
I have an issue that might be related.
I accepted two test missions using a quicksilver, and now its speed is limited to 19. Changing engines, or swapping ships doesn't fix it, but it doesn't affect other ships.

**Comment by bobbens** [comment]
OK, implemented arbitrary string claims, and used them to not allow two missions to simultaneously exist that claim the engine core slot.
