### ISSUE TITLE
"Too slow" mission warning considers hidden jump points

### ISSUE THREAD

**Issue by mark7** [naev/naev#591]
There is a convenience warning that fires if the player tries to accept a mission that he does not have enough time to do in his current ship, telling the player that his mission is impossible:

> Too slow
> 
> This shipment must arrive within %s, but it will take at least %s for your ship to reach %s, missing the deadline.

Given that this is intended to be a convenience and hidden jump points aren't accessible to a player, they probably should not be factored in: if a player knows about a hidden jump point, so should his character.

(Arguably, the same should be done for not-yet-known jump points, but it's possible to infer the existence of these from the map.)

**Comment by nenau** [comment]
I agree that hidden jumps shouldn't be taken into account, but imho unknown jumps need to be taken into account in order to let the player do timed missions to unknown systems.

**Comment by Gartral** [comment]
IMHO it should spit out something absolutely ridiculous like; "WHAT? "Where even *IS* that?"!? YOU DON'T KNOW HOW TO GET TO %system? GET OUT OF MY SIGHT YOU WET-EARED ROOKIE!". You know, just for immerssion's sake and making the player actually explore!

**Comment by bobbens** [comment]
So I was thinking about this, and find it sort of leads inconsistencies depending on how you implement it, as the reward distance is always calculated on the "optimal distance" excluding hidden jumps (which was the reason behind this bug report). So I can see the following scenarios:
1. As it is the warning is computed on the "optimal distance" and is consistent.
2. We compute the warning based on the player known routes, which leads to discrepency in reward / delay warning distance. Furthermore, if the player knows no route, we cannot compute anything, meaning we would probably use the "optimal distance" above, leading to furthermore inconsistency depending on whether or not the player knows the route.
3. Compute both on the player's known distance, which is silly and also changes as the player learns more systems.

So given that hidden jump poinst are not taken into account, I will add API to only return the "known" shortest distance and leave the rest as is. Thanks for the report.
