### ISSUE TITLE
[Final Mission of] Collective Campaign Sequence Breaking

### ISSUE THREAD

**Issue by aHick** [naev/naev#597]
Once you get to C-00 in the final mission of the Collective campaign (ec06 as far as I know), the script tells you to "Meet with the Imperial Fleet." However, if you don't do that, you can just go around them and take out every single one of the opposing fleet's members, (they don't wake up when you shoot at them) then return to base.

If you go back to where the fleet is after destroying the opposing fleet, of course it will go to the second part of the mission, which will render the mission unfinishable due to the Starfire and Trinity already being destroyed.

A good solution to this would either be to move the Imperial fleet back into C-28 near the jump and have them all jump through to C-00 to fight the fight, or have them really close to the jump point at C-00 so that you can't go around them, so that the battle starts as soon as you enter.

If a fix is not created a really good while after I've posted this (which one will :)), I will attempt to change the file to a better working thing.

This was running Naev 6.1 on Xubuntu 15.

**Comment by Fayti1703** [comment]
Have you tried landing on Omega Station after you've gone back to the Imperial fleet?

**Comment by aHick** [comment]
I believe that I did, and it continued as it would've done if I hadn't skipped the fight. I'm unsure, so I'll check again as soon as I get the opportunity to do so.

**Comment by onpon4** [comment]
This mission doesn't have any difficulty anyway. You can literally do nothing and the Empire ships are more than enough to wipe out all the collective drones plus both possible bosses. I tried to come up with a way to make it difficult, but I couldn't.

**Comment by bobbens** [comment]
Should be fixed in master. Thanks @onpon4 !
