### ISSUE TITLE
Shark07 is non-functional

### ISSUE THREAD

**Issue by aHick** [naev/naev#598]
The final mission in the Shark's Teeth campaign doesn't appear to do anything when accepted, except for make a blank entry in your mission info page.

At first I thought it might be to an issue in group rankings, (I had +18 for pirates) but no, that didn't fix anything when I hacked the save file to change that. I had a Trader Rehabilitation mission going, (Same reason for both, I had just done the Pirate Hitman missions) thought that might be screwing with something, so I finished it and went back.. Nothing changed. 

I've looked in the script, and I can't seem to tell anything differently done in shark07 that is different than any functional mission like it. (My knowledge of the naev lua api is a lot less than flawless) I don't know why this happens, in other words. 

Naev .6.1 Running on Xubuntu 15.

**Comment by PhoenixRiver** [comment]
I have cleaned up the shark missions and submitted a pull request so you can see if those fixes help... the fixes were in cleaning up hooks once you've completed the previous missions, I'm not sure that this is an issue but it needed done anyway so I did it. I also changed a couple of features that the original author wanted (according to his/her comments) but hadn't yet done - the pirates now spawn in random systems :) - well within a certain distance anyway! ;)
Hope this helps :)

**Comment by aHick** [comment]
Righty, thanks

**Comment by PhoenixRiver** [comment]
Shark missions now cleaned up in the repo - do you mind trying it again to see if it works for you?

**Comment by aHick** [comment]
Works perfectly. I mean, only took me a year to get back around to testing that, sorry (where does the time go!!?!!), but the fix most certainly does work. Closed.
