### ISSUE TITLE
The 'slim' GUI needs a complete makeover

### ISSUE THREAD

**Issue by zorun** [naev/naev#617]
When the current amount of fuel is non-integer (e.g. when asking a ship to refuel or stealing fuel by boarding a ship), the slim GUI displays the amount of fuel with a lot of digits, which is somewhat ugly.  The displayed amount should probably be rounded to the nearest integer.

Example of display: "Fuel: 603.86679141746"

**Comment by BTAxis** [comment]
The slim GUI has far more issues than that. It really needs a complete makeover to be updated to the current feature set.

**Comment by zorun** [comment]
Ok, thanks.

**Comment by bobbens** [comment]
Made over.
