### ISSUE TITLE
The refueling "tanker" at the end of Cold Metal leaving the system

### ISSUE THREAD

**Issue by onpon4** [naev/naev#656]
Before I discovered that you don't actually need to do anything to make this mission succeed, I decided to use a small, fast ship to distract the swarm of drones so that the Empire ships could focus on the main targets first. That caused them to be destroyed while a bunch of drones were left over, and at that time, the refueling ship would appear and offer to refuel. Only one problem: there were dozens of Collective drones still in the system. So I decided to wait until the Collective drones were destroyed so as not to endanger the refueling ship, and... it left.

This is a bad design. The refueling ship should remain in the system indefinitely. There should not be a time limit for refueling, *especially* considering that there is no other way to refuel for three systems.

I'm opening this as an issue instead of a pull request because I honestly couldn't figure out how to prevent the refueling AI from jumping out of the system.

**Comment by ids1024** [comment]
I haven't looked at the code for the mission, but I think `pilot.control` followed by `pilot.brake` should make a ship stay in place indefinably.

**Comment by onpon4** [comment]
I don't think that would work. The AI needs to be controlling the ship so that it can fly over to the player and refuel. At least, I think it does.

**Comment by ids1024** [comment]
Hm, fair enough. `pilot.setNoJump()` then?

**Comment by onpon4** [comment]
Ah, yeah, that should work.

**Comment by onpon4** [comment]
Alright, fixed in #661.

**Comment by bobbens** [comment]
Fix merged into trunk.
