### ISSUE TITLE
Saving Games

### ISSUE THREAD

**Issue by DjRay2016** [naev/naev#674]
Attached are my last 2 log files.  Having an issue saving the game after taking off.
[stdout_2016-08-15_15-06-04.txt](https://github.com/naev/naev/files/418920/stdout_2016-08-15_15-06-04.txt)
[Uploading stderr_2016-08-15_15-06-04.txt…]()

**Comment by ids1024** [comment]
The second link seems to be broken.

**Comment by DjRay2016** [comment]
Resending

**Comment by PhoenixRiver** [comment]
> Resending

Did you mean you are resending the stderr in future or was this
another broken link? (sorry :(

If it's just text you could always just copy / paste it into a message
if you're having problems...

Johann *<:@)

**Comment by DjRay2016** [comment]
Here is the log file.


________________________________
