### ISSUE TITLE
Use Travis-CI to build lua API documentation

### ISSUE THREAD

**Issue by ids1024** [naev/naev#687]
The http://api.naev.org site has a tendency of getting out of date since it has to be manually updated. It would be better to automate that. Travis-CI seems like a good way to achieve that.

I've gotten this to work with my own server at https://github.com/ids1024/naev/tree/travis.  It will need to be updated to work with the official naev repository and the server naev.org is hosted on, and there are some small improvements to the .travis.yml that should be made (uploading docs only when building the master branch, etc.), so I haven't created a PR yet.

Does this sound like a good idea?

**Comment by bobbens** [comment]
I think it would be cool, although I am not familiar at all with travis-cl and not entirely sure about the downsides there might be.

**Comment by ids1024** [comment]
Closing. `api.naev.org` has been built by Travis for a few months now.
