### ISSUE TITLE
Planet Takeoff Save Error

### ISSUE THREAD

**Issue by kitmerkley** [naev/naev#690]
Upon Takeoff from a planet I'm getting a Failure to Save Game message. Any idea how to fix this or how to perform a manual save?

**Comment by BTAxis** [comment]
You might not have write permissions for the default user data directory. Try changing the location of this directory by setting Naev up to be a portable application.
http://wiki.naev.org/wiki/Portable_Mode

**Comment by kitmerkley** [comment]
Thank you so much for the quick response! I'll give it a try.

**Comment by Secondlt2** [comment]
i dont understand how this kind of programming or coding works but i do believe that other people will be able to fix this problem if they saw you doing it in a video. preferably in Youtube of course, and if you even partner up with youtube you'll even gain from it. who knows? :) although please make a demonstration as to how to fix this problem cause i really dont understand how to make this 
(datapath = "path_to_data_files") code work

**Comment by bobbens** [comment]
Closing given that it's likely a permission error.

**Comment by Secondlt2** [comment]
ok so i found a way to fix this, all you have to do is drag the LUA file "datapath" into your "naev-data" file
which is located in the Naev directory and naev directory should be by default located in 
---------------------------------------------"C:\Program Files\Naev\" ---------------------------------------------
if it still doesnt work for you then copy your "saves" file which is usually located again in the "naev-data" file
after that paste it to your desktop then reinstall naev, after reinstalling naev drag your "saves" file back to "naev-data"
did i make it understandable? i hope i did
