### ISSUE TITLE
Version 0.6.1 - Stabilizer Description is "0 tons", yet it causes me to go 7-8 tons lower.

### ISSUE THREAD

**Issue by mark-c** [naev/naev#708]
I am not sure how to understand this--is this some kind of balance? Is there a bug? Does the description pull the value (if not, why not)?

Test: Load a Schroedinger with this equipmen, or any ship, any equipment:   
https://puu.sh/upv1E/72af0407a3.png  

Add an Improved Stabilizer like this:  
https://puu.sh/upvfL/32ac0ba373.png

And the result is -3 tons on the limit.

Version: 0.6.1. win-x64

**Comment by nenau** [comment]
It's not a bug. In the past, Stabilizers used to be a very good option for capships, whitch was not desired. So a -15% (or -10% ?) max mass penalty was added.
Actually, you are right that it's not written in the outfit's stats...

**Comment by mark-c** [comment]
Now I cannot put it on my Schroedinger or Ingenuity without reverting to some terrible starting armor, or I go over mass.

**Comment by nenau** [comment]
Do you know, you can still take off even if your ship is too heavy ? The only thing is that you'll have a max velocity penalty.
The general idea of balance in naev is to have the player to make choices. Right now, on your Schroedinger, all your systems except for the scrambler are the top of what you can get.

**Comment by Lineth** [comment]
Yeah, a 2% drop is nothing. Try flying a combat spec Kestrel with Remige engines without a 20% speed penalty (torpedoes will be your friend).
