### ISSUE TITLE
Swapping ships occasionally causes segfaults

### ISSUE THREAD

**Issue by onpon4** [naev/naev#719]
Basically, *sometimes*, swapping ships causes Naev to segfault. It always seems to come out of nowhere, and when I go back into the game and do the exact same thing, it doesn't happen again. So I haven't the slightest idea what's causing it or even how to reproduce it. And it's so rare that running the game in the debugger for a couple hours isn't even going to find it. I think it's happened to me, in total, around 3 or 4 times over the last year or so.

So I don't expect this to get solved any time soon, but just opening a report about it so that everyone is aware. Maybe someone will get lucky and stumble across it while they're debugging something else.

**Comment by BTAxis** [comment]
If it happens only sometimes, that could be an indication the game is reading corrupt data from memory. Something trying to reference an object that doesn't exist anymore, maybe?

**Comment by bobbens** [comment]
I tried to reproduce. Haven't been able to.
I ran naev under valgrind to see if it would catch something (valgrind logs memory and can detect illegal read/writes), but it came up clean also. Only thing I can think of is that at some point, when you get more ships, the vector in which the ships are stored gets realloc'd and then stray pointers become invalid and it blows up. Did you buy a ship before swapping?

**Comment by onpon4** [comment]
Hm... I think so. It always happens so suddenly, though, so I'm not sure.

**Comment by onpon4** [comment]
Huh, I didn't realize this was something I found out since I submitted this bug report, but I've found that this tends to happen only when I transport a ship and then swap it (again, though, not usually, only sometimes). So it's the ship location/transportation system that probably needs to be looked at for corruption.

Honestly, I'm not even entirely sure the ship location system is worthwhile. I wonder if it might be better to just remove that feature and have all ships available wherever you go, like outfits are.

**Comment by bobbens** [comment]
That might be for the best. On a side note, probably getting rid of missile ammunition too would be good. Less micromanagement is good.

**Comment by PhoenixRiver** [comment]
> That might be for the best. On a side note, probably getting rid of missile
> ammunition too would be good. Less micromanagement is good.

Though that brings up the issue of balance as generally the need for
ammunition is the reason that missiles are less appealing than lasers
but pack a bigger punch, especially since I don't think the missiles
add to your thermal load like lasers do... of course if less
micromanagement maybe we should remove the thermal system?

River

**Comment by onpon4** [comment]
I don't know about removing the thermal system. It's not so much micromanagement as "don't be an idiot with your weapons". But probably the biggest problem with missiles isn't so much the buying part, it's the fact that when you run out, you stay out until you land again. The only way I can think of to truly address that is to have ammo pick-ups from other ships a la Project: Starfighter, but that would be incredibly unusual for this game so I don't know if it would actually be a good idea.

**Comment by onpon4** [comment]
By the way, @bobbens, am I understanding correctly? My interpretation of your post was that you wanted to remove the buying of missiles so it's just a limit while you're out in space. That seems to me like a good idea, infinite missile ammo not so much.

**Comment by bobbens** [comment]
I think I discussed this ages ago, but my idea was to have missiles "regenerate" over time. This could be controlled by the type of launcher with bonuses for bombers and stuff like that.

Regarding the thermal system, I think it could just be implemented such that if you are not in combat for a good while, it clears accelerates the cooling down.

My reasoning on both this changes would be to penalize permanent combat (which would happen in extremely hostile territory), while not penalizing doing a couple of skirmishes, given that the enemies always start at max everything.

**Comment by onpon4** [comment]
Huh, that actually sounds like a nice idea.

**Comment by onpon4** [comment]
Well, looks like this segfault problem is still there. I just experienced it. :(
