### ISSUE TITLE
(0.6.1) Pirates in Disabling tutorial don't disable you sometimes

### ISSUE THREAD

**Issue by aHick** [naev/naev#727]
Occasionally, once you've gotten up to the point where the Pirate Vendettas are supposed to shoot and disable you, they'll just come over and shoot a few bullets in your direction, then proceed to circle your ship and do nothing afterwards. You can't move, so nothing will allow you to progress in the tutorial, and its effectively a softlock. 

It's odd that I never had this happen before, seeing as I've done pretty much everything in this version from flying past Sol to destroying the collective with a stock Llama only (but the bug I used to beat it was already fixed on the latest branch, I believe), which means that I've also done the tutorial multiple times; I don't know what makes this happen, but it happened as I was introducing a family member to the game, and I walked by as they were doing the tutorial, stopped for a while, watched them, and while I was watching them, the Pirates decided to not do what they always did. 
Since I didn't directly influence this, I'm going to do a bit of research on what could possibly be causing this a day or two from now, since I'm a bit barren as far as ideas of what to do about this and info on the issue at the moment.

This was on Ubuntu 16.04, with the 64bit binary; but I don't think the problem is lodged there, since the ndata is the same for all, and this was a problem with AI, or so it would seem.

**Comment by bobbens** [comment]
OK, I added a lot more spawning pirates, and with the new AI it seems like this should no longer be an issue in master. Thanks for the report.
