### ISSUE TITLE
Interface scaling on high DPI displays.

### ISSUE THREAD

**Issue by tnnf** [naev/naev#728]
Hello,

The user interface is very small and the text hard to read as a result when playing on a high DPI display. In my case that's a 4k monitor.

Any chance you could add an option to change the size of the Interface?

**Comment by bobbens** [comment]
There is an option, although I still have to put it in the options window. Try using "-X2" from the command-line, it will scale everything by 2.

**Comment by tnnf** [comment]
Oh, that's much better!

Thank you!
