### ISSUE TITLE
Missing source tarball

### ISSUE THREAD

**Issue by jdieter** [naev/naev#732]
I'm the Fedora packager of Naev and I was planning to upgrade to 0.7.0.  The Fedora packages are split into naev and naev-data (with the contents ndata.zip) so that small updates to naev don't require re-releases of the data.  Unfortunately, while the 0.7.0 release has ndata.zip, it doesn't have any source tarball for us to build, and the github auto-generated source tarball has all the contents of ndata.zip as well.

Is there any chance you would publish a source tarball as well as the binary ones for this release?

**Comment by bobbens** [comment]
Sorry about that, I was pretty sure I had uploaded the tarball, but must have missed it. It should be up on the sf download pages and for future reference you can build it with make dist-bzip2.

**Comment by jdieter** [comment]
Thanks so much for the upload and for the heads-up on how to build it myself.

**Comment by jdieter** [comment]
I'm building the new version for Fedora now
