### ISSUE TITLE
(linux) New dependencies for building l10n 

### ISSUE THREAD

**Issue by kernhe** [naev/naev#734]
In order to build the l10n branch, you need the following additional packages: 
- autopoint (>0.19) 
- intltoolize (>0.51) 
... and this is not checked by ./configure script. 

Simple solution e.g. apt-get install autopoint intltoolize

**Comment by bobbens** [comment]
Ok, added dependencies to the wiki. It is not possible to check for these dependencies at compile-time because they are necessary for autogen.sh.

**Comment by kernhe** [comment]
Solved for me.

**Comment by Fayti1703** [comment]
@bobbens Would it not be possible to at least check for the existence of those two commands via
```Bash
if ! type autopoint &>/dev/null then
  printf "Missing dependency: autopoint"
  exit 127
elif ! type intltoolize &>/dev/null then
  printf "Missing dependency: intltoolize"
fi
```

**Comment by bobbens** [comment]
@Fayti1703  Thanks for the advice. Did something along those lines.

**Comment by Fayti1703** [comment]
Though perhaps with this issue relating to the l10n branch, merging it into that might be nice.

**Comment by bobbens** [comment]
As I merged that branch into master a while back (to minimize future merge conflicts), I have instead deleted the l10n branch.
