### ISSUE TITLE
DIY-nerds story reward confict

### ISSUE THREAD

**Issue by asl97** [naev/naev#736]
The reward is currently an `Unicorp PT-100 Core System` but that is in conflict with the story.

[Line 69](https://github.com/naev/naev/blob/99b1c21682fb5a4e1a8801ea18ddf6fa302ac911/dat/missions/neutral/diy-nerds.lua#L69):
> That aristocratic ass of a bored teenager! He snatched the prize from us! It wasn't even fair play. His box wasn't home built. It was a brand new ship's processing unit, on which he banged his hammer until it looked acceptable.

This is the main issue, the wining competition cheated with an store bought processing unit (core system?) and the reward '**home-made**' box turns out to be an widely available core system which can be bought pretty much everywhere.

[Line 89](https://github.com/naev/naev/blob/99b1c21682fb5a4e1a8801ea18ddf6fa302ac911/dat/missions/neutral/diy-nerds.lua#L89)
> We'll modify our box so that it can be used as a ship's coprocessor

It's suppose to be a coprocessor so I would expect it to be a modifier instead of a core.

[Line 96](https://github.com/naev/naev/blob/99b1c21682fb5a4e1a8801ea18ddf6fa302ac911/dat/missions/neutral/diy-nerds.lua#L96)
> Now you're the proud owner of the system's only home-made coprocessing unit

It should be an unique one of a kind item, something that shouldn't be possible to buy from shops.

(There could be better coprocessor by other company though)
____

Readding the APU with an additional unique lower spec APU seem to be the best way to handle this issue.

<details> 
  <summary>Additional Off-topic Information (click to open/close)</summary><p>
  There could even be mission which require the unique item like 'fine tuning' (since it was modified in under half a STP) so that the performance is comparable with the other APU (2nd tier).

  Then maybe the unique item can to be 'sold' to someone in a mission, that someone would get interested and want to meet the creators, by getting the nerds to met with that person, it will unlock a new set of APU (3rd tier) after a few tens of STP (founding of a new company, possible using Universe Diffs? it's just adding a new tech to an asset (planet))
  </p>
</details>
<br />
But the comment in the commit which removed it seem to suggest it's unwanted.

> You have been a thorn in my side for far too long, APUs! I banish you to the world of Pagan.

https://github.com/naev/naev/commit/d537a6186df717a3cfa9c95cbc09eda2a5fb0a05

**Comment by bobbens** [comment]
Yes, I'm a big fan of adding unique outfits only obtainable through missions/events. APU were used before core systems, but basically made it a no-brainer to stuff your ship full of APUs and took away any tradeoffs with using other outfits. While adding APUs back in general would seem like a bad idea, I wouldn't be against having a unique outfit that would be an APU in this sense.
On adding more missions that continue and improve the unique outfit, I would not be against that. More missions are always good.

**Comment by asl97** [comment]
> but basically made it a no-brainer to stuff your ship full of APUs and took away any tradeoffs with using other outfits.
If that is the case, isn't the answer simply limiting it to one APU?

I don't know the api well but this commit suggest it's possible: https://github.com/naev/naev/commit/f2ba6db4275f18e0951b789c31aea669b8311245

Seem like it wouldn't be that bad of an idea to bring back the whole APU set.

**Comment by bobbens** [comment]
Limiting to one APU overlaps a lot with the core outfit "systems" slot, which is the way we balance CPU atm. If you want a high-cpu build, it'll come with tradebacks and such. Also a one-APU limit would pretty much require your ship to dedicate one uitlity slot to the APU. I think in this case, the best way (and in general something I want to encourage) would be to use a unique APU-like outfit for light utility slots.

**Comment by asl97** [comment]
> If you want a high-cpu build, it'll come with tradebacks and such

Unless I am misunderstanding the tradebacks you are talking about, energy usage can be increase so that it wouldn't be better to use an high-energy core with an APU compare to simply using an high-cpu core.

If I remember correctly, when APU was around, I loaded my ship with APU and reactors so that my ship could be fully loaded with powerful weapon and is able to continuously fire them.

Limiting it to one APU should prevent that too.

> Also a one-APU limit would pretty much require your ship to dedicate one uitlity slot to the APU

There is no need to dedicate a slot for the APU unless you actually need it.
It would be much more useful to use other utility unless you really need the extra cpu.

Not to mention, the reverse thruster and others are limited to just a single one on the ship too, just because it there doesn't mean you have to use it.

I would also expect that the Core System, especially low end cores, wouldn't have multiple port to connect huge amount of APU.

It's like how most computers only has a single slot for the GPU.

> I think in this case, the best way (and in general something I want to encourage) would be to use a unique APU-like outfit

I think it wouldn't be realistic for a bunch of nerds to be able to jury rigged their box in such a short amount of time so that it can be linked with any core if the core doesn't have any support for an external coprocessor.

And if it does support external coprocessor, it can be expected there would be some on the market.

**Comment by onpon4** [comment]
So, since this issue was opened, the "ship's coprocessor" line has been changed:

> "Ok, we have just solved our problem. See, that ass of a champion won the contest with a ship's processing unit. We can do it the other way round. We'll modify our box so that it can be used as a ship's core system, and you can have it as a compensation for your troubles. Interested?"

Of course the core system is listed as a Unicorp core system, but I think that's an acceptable simplification and it would be reasonable to say that this issue is solved. What do you think, @bobbens?

🕵️

**Comment by onpon4** [comment]
Closing this as I think this is solved now (as mentioned by Emmy above, the dialogue no longer mentions a "coprocessor" and instead mentions a core system.

🕷️
