### ISSUE TITLE
Duplicate screen resolutions in option menu

### ISSUE THREAD

**Issue by xrogaan** [naev/naev#737]
This might be due to a lack of filtering, as the list of viable modes given by windows is quite extensive.

[stdout.txt](https://github.com/naev/naev/files/1158112/stdout.txt)

![naev_screenres](https://user-images.githubusercontent.com/74860/28352248-930f48c4-6c55-11e7-8ada-9a080bf8a4da.png)
![explorer_2017-07-19_07-14-43](https://user-images.githubusercontent.com/74860/28352219-6e8c271a-6c55-11e7-8a8f-faade1af1a51.png)

**Comment by Fayti1703** [comment]
This also happens on Ubuntu 16.04.

**Comment by BTAxis** [comment]
Can you do a bisect to see which commit introduced this behavior?

**Comment by Fayti1703** [comment]
Iirc this behavior has been present for a while, so there might be quite a bit of history to go through here...

**Comment by bobbens** [comment]
I don't think a bisect is necessary, as I'm pretty sure it's duplicate resolutions with different color spaces and things like that. Would just have to filter them out and only show one. Will see what is going on.

**Comment by bobbens** [comment]
Should be fixed in master.

**Comment by Fayti1703** [comment]
Can confirm fixed in master branch. Thanks @bobbens.
![image](https://user-images.githubusercontent.com/5366784/28717961-2e7d7f1a-73a4-11e7-9e71-eb3f60d48674.png)

**Comment by bobbens** [comment]
Ok, closing!
