### ISSUE TITLE
Armor Modifier Mass Bug

### ISSUE THREAD

**Issue by ZeroHundred** [naev/naev#738]
I noticed this bug when trying to balance out the mass of my new ship, I had bought Plasteel Plating armor modifiers noticing the green label +5% Mass, thinking this meant mass capacity, however when I added it to my ship, it actually increased the amount of Mass my ship had in it. I think this either needs to be changed to +5% Mass Capacity or changed to a red modifier or something, considering the mod itself weighs 0 tons.

These are links to some screenshots showing the Mass difference with each plating installed:
Outfitter Mod Page: http://steamcommunity.com/sharedfiles/filedetails/?id=1082820351
Ship w/o Plating Mods: http://steamcommunity.com/sharedfiles/filedetails/?id=1082820239
1 Mod Installed: http://steamcommunity.com/sharedfiles/filedetails/?id=1082820275
2 Mods Installed: http://steamcommunity.com/sharedfiles/filedetails/?id=1082820311
3: http://steamcommunity.com/sharedfiles/filedetails/?id=1082820334
All: http://steamcommunity.com/sharedfiles/filedetails/?id=1082829303

As you can see each installment brings my Mass even more over capacity, I hope this helps the devs.

**Comment by bobbens** [comment]
OK, made it a negative attribute (shows up in red) and changed name from "Mass" to "Ship Mass". Hopefully it should be clearer. Thanks for the bug report.
