### ISSUE TITLE
Compiling Naev on Ubuntu 16.04

### ISSUE THREAD

**Issue by ValerioCietto** [naev/naev#740]
I can't compile Naev on Ubuntu16.04.

Output of ./autogen.sh && ./configure
`autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --install -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking for ranlib... ranlib
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cut... cut
checking for doxygen... no
checking for ldoc... no
checking for git... git
checking whether we are building utils... yes
checking whether we have docs... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking if we need a __unix__ define... no
checking whether to enable debug mode... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for bfd_init in -lbfd... yes
checking bfd.h usability... yes
checking bfd.h presence... yes
checking for bfd.h... yes
checking whether to use SDL2 instead of SDL... yes
checking whether to use OpenAL... yes
checking whether to use SDL_mixer... yes
checking whether to use libzip... yes
checking which lua to use... luajit
checking for path to ndata... /usr/local/share/naev/ndata
checking for SDL... yes
checking for XML... yes
checking for FREETYPE... yes
checking for FONTCONFIG... yes
checking for VORBIS... yes
checking for VORBISFILE... yes
checking for PNG... yes
checking for ZIP... yes
checking for LUA... no
configure: WARNING: Lua is set to LuaJIT but can not find library; using internal Lua
checking for library containing sqrt... -lm
checking for cs_spalloc in -lcsparse... no
checking for cs_di_spalloc in -lcxsparse... no
checking AL/al.h usability... yes
checking AL/al.h presence... yes
checking for AL/al.h... yes
checking for alGenSources in -framework OpenAL... no
checking for alGenSources in -lopenal... yes
checking for SDLMIXER... no
checking for library containing IMG_Load... no
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking GL/glu.h usability... yes
checking GL/glu.h presence... yes
checking for GL/glu.h... yes
checking for glGenTextures in -framework OpenGL... no
checking for glGenTextures in -lGL... yes
checking for glOrtho2D in -framework OpenGL... no
checking for glOrtho2D in -lGLU... yes
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking for off_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for feenableexcept... yes
checking for clock_gettime... yes
checking for ov_read_filter... yes
checking for the current Git commit identifier... unknown
checking for sed... sed
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating src/Makefile
config.status: creating src/tk/Makefile
config.status: creating src/tk/widget/Makefile
config.status: creating build/shave
config.status: creating utils/Makefile
config.status: creating utils/mkspr/Makefile
config.status: creating docs/Makefile
config.status: creating lib/lua/Makefile
config.status: creating lib/csparse/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands

configure: prefix:      /usr/local
configure: ndata:       /usr/local/share/naev/ndata

configure: SDL2:        yes

configure: sound backends:
configure:   OpenAL:    yes
configure:   SDL_mixer: no

configure: lib:
configure:   csparse:   internal
configure:   lua:       internal
configure:   libzip:    yes

configure: utils:       yes
configure:   mkspr:     no

configure: debug mode:  yes
configure:   bfd:       yes
`

Output of make:
`Making all in lib
Making all in lua
Making all in csparse
Making all in src
Making all in tk
Making all in widget
  OBJC   naev
/usr/bin/ld: impossibile trovare -liberty
collect2: error: ld returned 1 exit status
Makefile:880: set di istruzioni per l'obiettivo "naev" non riuscito
make[3]: *** [naev] Errore 1
Makefile:1068: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make[2]: *** [all-recursive] Errore 1
Makefile:780: set di istruzioni per l'obiettivo "all" non riuscito
make[1]: *** [all] Errore 2
Makefile:616: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make: *** [all-recursive] Errore 1
`

I think there are multiple issues in the dependances.

**Comment by bobbens** [comment]
Hello, could you try recompiling with the following command and pasting the output please?
```
LC_ALL=C ./configure --disable-shave && make
```

**Comment by ValerioCietto** [comment]
Here it is:
>  LL_ALL=C ./configure --disable-shave && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking for ranlib... ranlib
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cut... cut
checking for doxygen... no
checking for ldoc... no
checking for git... git
checking whether we are building utils... yes
checking whether we have docs... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking if we need a __unix__ define... no
checking whether to enable debug mode... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for bfd_init in -lbfd... yes
checking bfd.h usability... yes
checking bfd.h presence... yes
checking for bfd.h... yes
checking whether to use SDL2 instead of SDL... yes
checking whether to use OpenAL... yes
checking whether to use SDL_mixer... yes
checking whether to use libzip... yes
checking which lua to use... luajit
checking for path to ndata... /usr/local/share/naev/ndata
checking for SDL... yes
checking for XML... yes
checking for FREETYPE... yes
checking for FONTCONFIG... yes
checking for VORBIS... yes
checking for VORBISFILE... yes
checking for PNG... yes
checking for ZIP... yes
checking for LUA... no
configure: WARNING: Lua is set to LuaJIT but can not find library; using internal Lua
checking for library containing sqrt... -lm
checking for cs_spalloc in -lcsparse... no
checking for cs_di_spalloc in -lcxsparse... no
checking AL/al.h usability... yes
checking AL/al.h presence... yes
checking for AL/al.h... yes
checking for alGenSources in -framework OpenAL... no
checking for alGenSources in -lopenal... yes
checking for SDLMIXER... no
checking for library containing IMG_Load... no
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking GL/glu.h usability... yes
checking GL/glu.h presence... yes
checking for GL/glu.h... yes
checking for glGenTextures in -framework OpenGL... no
checking for glGenTextures in -lGL... yes
checking for glOrtho2D in -framework OpenGL... no
checking for glOrtho2D in -lGLU... yes
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking for off_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for feenableexcept... yes
checking for clock_gettime... yes
checking for ov_read_filter... yes
checking for the current Git commit identifier... unknown
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating src/Makefile
config.status: creating src/tk/Makefile
config.status: creating src/tk/widget/Makefile
config.status: creating build/shave
config.status: creating utils/Makefile
config.status: creating utils/mkspr/Makefile
config.status: creating docs/Makefile
config.status: creating lib/lua/Makefile
config.status: creating lib/csparse/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands

configure: prefix:      /usr/local
configure: ndata:       /usr/local/share/naev/ndata

configure: SDL2:        yes

configure: sound backends:
configure:   OpenAL:    yes
configure:   SDL_mixer: no

configure: lib:
configure:   csparse:   internal
configure:   lua:       internal
configure:   libzip:    yes

configure: utils:       yes
configure:   mkspr:     no

configure: debug mode:  yes
configure:   bfd:       yes
Making all in lib
make[1]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/lib"
Making all in lua
make[2]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/lib/lua"
make[2]: Nessuna operazione da eseguire per "all".
make[2]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/lib/lua"
Making all in csparse
make[2]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/lib/csparse"
make[2]: Nessuna operazione da eseguire per "all".
make[2]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/lib/csparse"
make[2]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/lib"
make[2]: Nessuna operazione da eseguire per "all-am".
make[2]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/lib"
make[1]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/lib"
Making all in src
make[1]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/src"
make  all-recursive
make[2]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/src"
Making all in tk
make[3]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/src/tk"
Making all in widget
make[4]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/src/tk/widget"
make[4]: Nessuna operazione da eseguire per "all".
make[4]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/src/tk/widget"
make[4]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/src/tk"
make[4]: Nessuna operazione da eseguire per "all-am".
make[4]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/src/tk"
make[3]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/src/tk"
make[3]: ingresso nella directory "/home/valerio/Scrivania/naev/naev-master/src"
gcc     -o naev ai.o array.o background.o board.o camera.o claim.o collision.o colour.o comm.o cond.o conf.o console.o damagetype.o debris.o dev.o dev_outfit.o dev_planet.o dev_ship.o dev_system.o dev_sysedit.o dev_uniedit.o dialogue.o economy.o equipment.o escort.o event.o explosion.o faction.o fleet.o font.o gui.o gui_omsg.o gui_osd.o hook.o info.o input.o intro.o joystick.o land.o land_outfits.o land_shipyard.o land_trade.o load.o log.o map.o map_find.o map_overlay.o md5.o menu.o mission.o music.o music_openal.o music_sdlmix.o naev.o ndata.o nebula.o news.o nfile.o nlua.o nlua_bkg.o nlua_camera.o nlua_cli.o nlua_col.o nlua_commodity.o nlua_diff.o nlua_evt.o nlua_faction.o nlua_gfx.o nlua_gui.o nlua_hook.o nlua_jump.o nlua_misn.o nlua_music.o nlua_naev.o nlua_news.o nlua_outfit.o nlua_pilot.o nlua_planet.o nlua_player.o nlua_rnd.o nlua_ship.o nlua_system.o nlua_tex.o nlua_time.o nlua_tk.o nlua_tut.o nlua_var.o nlua_vec2.o nmath.o nondata.o npng.o npc.o nstring.o ntime.o nxml.o nxml_lua.o nzip.o opengl.o opengl_ext.o opengl_matrix.o opengl_render.o opengl_tex.o opengl_vbo.o options.o outfit.o pause.o perlin.o physics.o pilot.o pilot_cargo.o pilot_ew.o pilot_heat.o pilot_hook.o pilot_outfit.o pilot_weapon.o plasmaf.o player.o player_autonav.o player_gui.o queue.o rng.o save.o ship.o shipstats.o slots.o sound.o sound_openal.o sound_sdlmix.o space.o spfx.o start.o tech.o threadpool.o toolkit.o unidiff.o utf8.o weapon.o   -lm ../src/tk/widget/libwidget.a -lbfd -liberty -rdynamic -ldl ../lib/csparse/libcsparse.a -lSDL2 -lxml2     -lfreetype -lfontconfig -lfreetype ../lib/lua/liblua.a -lvorbis -lvorbisfile     -lpng12 -lzip -lz -lGL -lGLU -lopenal -lm 
/usr/bin/ld: impossibile trovare -liberty
collect2: error: ld returned 1 exit status
Makefile:880: set di istruzioni per l'obiettivo "naev" non riuscito
make[3]: *** [naev] Errore 1
make[3]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/src"
Makefile:1068: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make[2]: *** [all-recursive] Errore 1
make[2]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/src"
Makefile:780: set di istruzioni per l'obiettivo "all" non riuscito
make[1]: *** [all] Errore 2
make[1]: uscita dalla directory "/home/valerio/Scrivania/naev/naev-master/src"
Makefile:616: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make: *** [all-recursive] Errore 1

**Comment by ValerioCietto** [comment]
no, I didn't, now works thanks :)
