### ISSUE TITLE
Overflow when loading game

### ISSUE THREAD

**Issue by afxgroup** [naev/naev#751]
I'm porting NAEV on AmigaOS4 with SDL2 and OpenGLES
When the game starts and load all stuff the memory goes down to zero once ships are reached.
That's because when the surface is created it is stored in RAM and my system has only 1GB of RAM. 
Is the graphic loaded entirely in ram? Is there a way to load sprites only when they are needed?

**Comment by ids1024** [comment]
Yeah, the way this works currently is inefficient; https://github.com/naev/naev/pull/511 should help if it is ever finished.

**Comment by afxgroup** [comment]
But it is not committed in the master. Is this working? If I understend correctly also the 3d models needs to be created with blender?

**Comment by ids1024** [comment]
As I said, "if it is ever finished".

That branch still has a couple issues; some rendering issues with certain models, and collisions need to be implemented based on the 3D models. And although all the ship sprites are rendered from 3D models, some of the models are not in the artwork repository, so they need to be obtained from the artists, if possible.

So, there's no immediate solution to this. It is probably also possible to reduce what is loaded into memory at one time, as you are suggesting.

**Comment by bobbens** [comment]
Closing as this is not something we are going to directly fix.
