### ISSUE TITLE
Crash when system locale uses comma instead of dot as decimal seperator

### ISSUE THREAD

**Issue by ids1024** [naev/naev#754]
Originally reported by nenau in the forum: https://forum.naev.org/viewtopic.php?f=10&t=1315

This seems to have been caused in https://github.com/naev/naev/commit/b8e0b724c3, when the line `setlocale(LC_ALL, "");` was added.

I'm not sure what the correct solution for this is, but removing the `setlocale` call should fix it (I presume that has some use though?) as should running with a different locale.

**Comment by bobbens** [comment]
Mmmm, so we are using now properly gettext and doing that sort of stuff but it seems like Lua isn't so it is unable to read the commas. Not sure if it's better to hack Lua to read with commas or hack conf.c to save with dots :/

**Comment by bobbens** [comment]
Ok, tried setting the locale for everything except the numeric, which "should" solve the issue.
