### ISSUE TITLE
Better graphics for mining debris and mining in general.

### ISSUE THREAD

**Issue by bobbens** [naev/naev#761]
Mining debris should rotate, more types of useless debris should be added with it being visibly clear what you can use and what you can't.

**Comment by nenau** [comment]
And yes, for now, debris simply disappear at the edge of a field. I didn't make them shrink in size. The reason was that as some of them are in forderground, seeing them shrink, is odd. THe solution IMO is to make them fade to transparency.

**Comment by bobbens** [comment]
They blow up, so I guess this is solved?
