### ISSUE TITLE
Allow loading language data from ndata

### ISSUE THREAD

**Issue by bobbens** [naev/naev#772]
It seems like it's not possible to load the gettext stuff from memory, it has to be in a laid out file structure. One work around is to create a temporary directory, unpack the language stuff into it, then set that directory for gettext to be able to load language data from the ndata directly. Open for other suggestions though.

**Comment by Fayti1703** [comment]
Perhaps a temporary pipe could be used instead of a temporary file?

**Comment by bobbens** [comment]
As far as I know, bindtextdomain(...) requires a path, which would probably require creating a temporary directory and using the absolute path there. Would love to know if there is a better way though.

**Comment by gunchleoc** [comment]
There is https://github.com/GNOME/gcompris that's also using Autotools, gettext and C. Maybe you can get some code from there. I had some problems with the dependencies though, so I couldn't test whether it works without installing.

I can conform that `make install` fixes the problem for naev.

**Comment by bobbens** [comment]
Since we are probably moving to non-ndata closing.
