### ISSUE TITLE
Eliminate fleet.xml, superceeded by Lua

### ISSUE THREAD

**Issue by ids1024** [naev/naev#775]
`fleet.xml` in it's current form isn't very useful, and should probably be removed.

**Comment by ids1024** [comment]
Most entities in the file are of this form:

```xml
<fleet name="$faction $ship">
 <ai>$faction_ai</ai>
 <faction>$faction</faction>
 <pilots>
  <pilot name="$faction $ship" ship="$faction $ship"></pilot>
 </pilots>
</fleet>
```

So I think these are the necessary steps:
* Modify any missions using `fleet.xml` to spawn fleets of more than one pilot to use a lua solution instead
* Add an `<ai>` field to `faction.xml` to specify the default AI used by a faction
* Move the `ai` argument of `pilot.addRaw()` to the end, and make it optional (otherwise using the default for the faction)
* Remove `pilot.add()` and rename `pilot.addRaw()` to `pilot.add()`
* Update all `pilot.add()` calls
* Remove `fleet.xml` and `fleet.c`

I don't know if I'm forgetting anything.

**Comment by bobbens** [comment]
I am for these changes. However, we must make sure similar functionality exists and is used in the Lua code. That is, code to allow easily defining and creating fleets, that "should" be able to fly together and act as a single unit.

**Comment by onpon4** [comment]
Mentioned this on Discord:

Pilot name should also be a parameter of addRaw for convenience, and should be the ship name by default. Arguments should also be rearranged so that leaving out optional arguments isn't too clunky. I propose this ordering of arguments: `shipname, faction, param, pilotname, ai`.

First step would be to add that AI field to faction.xml.

🕵️

**Comment by UncombedCoconut** [comment]
OK, the new pilot.addRaw() / addRawShips() signature should be working and in use.
Converting fleet spawns to raw spawns will be a bit of a project. The completed steps have left `pilotL_addFleetFrom` in a hideous state, so it's worth following through.

**Comment by UncombedCoconut** [comment]
This might be done, or it might be considered undone until it's easier to share/reuse addShips() specs on the Lua side.

**Comment by bobbens** [comment]
fleet.xml is dead so I guess it's good enough to be considered "done, yet improvable" :)
