### ISSUE TITLE
Handle newlines in font rendering code

### ISSUE THREAD

**Issue by ids1024** [naev/naev#776]
Newlines seem to be causing issues with the console:

![naev-console](https://user-images.githubusercontent.com/2263150/39416287-af690cc2-4c00-11e8-8394-c387216c9478.png)

This particular issue is easy to mitigate, but ideally the font rendering code should go to the next line when it reaches a newline.

The lua `print` function on Naev achieves this with strtok (in `cli_printCore`).

**Comment by bobbens** [comment]
Seems like you fixed it, so I'm closing this. Thanks!
