### ISSUE TITLE
Fuel remains at 99.9999999 for the last jump in autonav

### ISSUE THREAD

**Issue by amusedberry** [naev/naev#779]
When using autonav sometimes fuel drops to 99.999999 during the last jump, producing the cancellation of the autonav feature and forcing to refuel in a planet.

If you are running against the clock, like in several urgent missions, then you will miss the deadline, as stoping in a planet spends 1 cycle.

![image](https://user-images.githubusercontent.com/32961675/39610555-db17bd14-4f16-11e8-9d1d-9618cb49b6eb.png)
![image](https://user-images.githubusercontent.com/32961675/39610595-1e596f50-4f17-11e8-80cf-443441274437.png)

**Comment by spectrevil** [comment]
Hi. I'm still not completely sure, but this issue only seems to happen when there is an Afterburner equipped. I have been testing with mules filled with fuel pods and it does not happen even if autonav is set to 8-10 jumps.

**Comment by bobbens** [comment]
Ok, it's likely a rounding issue somewhere or other. I think it might make more sense to just stop using floating point for fuel.
