### ISSUE TITLE
naev on leap 15 fails to load after successfully compiling.

### ISSUE THREAD

**Issue by Mirppc** [naev/naev#780]
./naev
 Naev v0.7.0
 git HEAD at 123059640
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 2.0.8 [compiled: 2.0.8]

OpenGL Window Created: 1920x1030@24bpp window
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 32768
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: GeForce GT 1030/PCIe/SSE2
Version: 4.6.0 NVIDIA 396.24

Using default font '/usr/share/fonts/truetype/arial.ttf'
Naev received SIGSEGV (address not mapped to object)!
./naev() [0x490953] debug_sigHandler(...):1433 /home/~/bin/naev/src/naev.c
/lib64/libc.so.6(+0x36160) [0x7fad4dc00160] ??(...):0 ??
[0x40942e8c] ??(...):0 ??
Report this to project maintainer with the backtrace.

i did a Git pull as of 7/11/2018.  unsure what the issue is and how to proceed in diagnosing it.

**Comment by bobbens** [comment]
The backtrace gives pretty much no information. Could you try running naev in gdb and seeing if that gives a different trace? Call naev with "gdb ./naev", then you type "run" and hit enter. When it crashes, type "bt full" and paste the result here.

**Comment by Mirppc** [comment]
Thanks for the tip.  Here is the backtrace.

#0  0x00000000400a2e8c in ?? ()
No symbol table info available.
#1  0x00007fffec43ddd4 in ?? () from /usr/lib64/libnvidia-glcore.so.396.24
No symbol table info available.
#2  0x00007fffec004fe8 in ?? () from /usr/lib64/libnvidia-glcore.so.396.24
No symbol table info available.
#3  0x0000000000444da1 in background_renderStars (dt=dt@entry=0) at background.c:301
        i = <optimized out>
        hh = <optimized out>
        hw = <optimized out>
        h = <optimized out>
        w = <optimized out>
        x = <optimized out>
        y = <optimized out>
        m = <optimized out>
        b = <optimized out>
        brightness = <optimized out>
        z = 0.5
        sx = <optimized out>
        sy = <optimized out>
        shade_mode = 0
        j = <optimized out>
        n = <optimized out>
        __func__ = "background_renderStars"
#4  0x0000000000490d64 in loadscreen_render (done=done@entry=0, msg=0x6ff90d "Initializing subsystems...") at naev.c:615
        col = {r = 1.90577992e-40, g = 0, b = 1.02830827e-38, a = 0}
        bx = <optimized out>
        by = <optimized out>
        x = <optimized out>
        y = <optimized out>
        w = <optimized out>
        h = <optimized out>
        rh = <optimized out>
        event = {type = 512, common = {type = 512, timestamp = 512}, window = {type = 512, timestamp = 512, windowID = 2733993984, event = 200 '\310', padding1 = 71 'G', 
            padding2 = 59 ';', padding3 = 226 '\342', data1 = 14317600, data2 = 0}, key = {type = 512, timestamp = 512, windowID = 2733993984, state = 200 '\310', 
            repeat = 71 'G', padding2 = 59 ';', padding3 = 226 '\342', keysym = {scancode = 14317600, sym = 0, mod = 31, unused = 0}}, edit = {type = 512, 
            timestamp = 512, windowID = 2733993984, 
            text = "\310G;\342 x\332\000\000\000\000\000\037\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000p\334\377\377", start = 32767, length = 0}, text = {
            type = 512, timestamp = 512, windowID = 2733993984, 
            text = "\310G;\342 x\332\000\000\000\000\000\037\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000p\334\377\377"}, motion = {type = 512, 
            timestamp = 512, windowID = 2733993984, which = 3795535816, state = 14317600, x = 0, y = 31, xrel = 0, yrel = 8}, button = {type = 512, timestamp = 512,

**Comment by bobbens** [comment]
Ok, running same driver version. Looking at the code it "seems" like a driver bug. With valgrind I was able to pinpoint the following:

```
==21994== Invalid read of size 4
==21994==    at 0x402AE8C: ??? (in /tmp/.glLehTZG (deleted))
==21994==    by 0x11016DD3: ??? (in /usr/lib/libnvidia-glcore.so.396.24)
==21994==    by 0x10BDDFE7: ??? (in /usr/lib/libnvidia-glcore.so.396.24)
==21994==    by 0x1766A0: background_renderStars (background.c:301)
==21994==    by 0x1C73D4: loadscreen_render (naev.c:615)
==21994==    by 0x16FD17: main (naev.c:340)
==21994==  Address 0x1252ec50 is 0 bytes after a block of size 4,096 alloc'd
==21994==    at 0x4C2F0FF: realloc (vg_replace_malloc.c:785)
==21994==    by 0x1EF33B: gl_vboData (opengl_vbo.c:150)
==21994==    by 0x19EDD7: gl_fontAddGlyphTex (font.c:304)
==21994==    by 0x19EDD7: gl_fontGetGlyph (font.c:1131)
==21994==    by 0x1A074C: gl_fontInit (font.c:1370)
==21994==    by 0x16FC22: main (naev.c:331)
==21994==
==21994== Invalid read of size 4
==21994==    at 0x402AE8E: ??? (in /tmp/.glLehTZG (deleted))
==21994==    by 0x11016DD3: ??? (in /usr/lib/libnvidia-glcore.so.396.24)
==21994==    by 0x10BDDFE7: ??? (in /usr/lib/libnvidia-glcore.so.396.24)
==21994==    by 0x1766A0: background_renderStars (background.c:301)
==21994==    by 0x1C73D4: loadscreen_render (naev.c:615)
==21994==    by 0x16FD17: main (naev.c:340)
==21994==  Address 0x1252ec54 is 4 bytes after a block of size 4,096 alloc'd
==21994==    at 0x4C2F0FF: realloc (vg_replace_malloc.c:785)
==21994==    by 0x1EF33B: gl_vboData (opengl_vbo.c:150)
==21994==    by 0x19EDD7: gl_fontAddGlyphTex (font.c:304)
==21994==    by 0x19EDD7: gl_fontGetGlyph (font.c:1131)
==21994==    by 0x1A074C: gl_fontInit (font.c:1370)
==21994==    by 0x16FC22: main (naev.c:331)
```

It is performing an invalid read. On my machine it does not cause a crash. When I have a bit more time will have to figure out what's going on. Seems a bit weird.

**Comment by Mirppc** [comment]
Thanks,  I will likely do a Git Pull on the 27th of July just to test.

**Comment by bobbens** [comment]
Likely irrelevant, closing.
