### ISSUE TITLE
Naev in Flatpak (via Flathub)

### ISSUE THREAD

**Issue by rrigby** [naev/naev#781]
Hi, I've submitted Naev to flathub which will bundle the game as a flatpak for distribution through the flatpak system. 

https://github.com/flatpak
https://github.com/flathub

If you're interested in maintaining the flatpak manifest jump in here and let us know to get admin access to the repository.
https://github.com/flathub/flathub/pull/535

**Comment by bobbens** [comment]
Thanks for the information, closing as non-issue.
