### ISSUE TITLE
Za'lek cruiser has more armour penalty than Za'lek carrier

### ISSUE THREAD

**Issue by devastator-pc** [naev/naev#823]
I have been updating the wiki recently, and I have noticed that:

- Za'lek Diablo (**Carrier**) has Armour Mod -30%
- Za'lek Mephisto (**Cruiser**) has Armour Mod -40%

According to the general ship types, the Cruisers should have more armour than Carriers, so shouldn't that be the other way around? Or perhaps just less penalty for cruiser?

**Comment by onpon4** [comment]
Is that so? I think all carriers have higher armor than similar cruisers (e.g. Peacemaker has more armor than Goddard and Hawking), so the Za'lek ships are in line with that.

**Comment by bobbens** [comment]
I don't think this is necessarily an issue as there are no "hard" things and having carriers with less armour penalty than cruisers seems to sensible.
