### ISSUE TITLE
Non-convex asteroids field ends up messed up by convex subsets generation

### ISSUE THREAD

**Issue by Mutos** [naev/naev#826]
I'm currently adding an Asteroids Fields display to the System Editor Map. It now displays OK for convex and non-convex fields by using the convex subsets.

However, I found out that a non-convex asteroids field is loaded OK, displayed OK, but is saved incorrectly after opening and closing the System Editor. The # of corners is still OK, but the corners coordinates are messed-up with seemingly random numbers.

The issue was already present in master branch, commit b75cf4e91, to find it out, I did the following :
- Checkout master branch,
- Modify Hakoi to have a non-convex field, like in my branch 'error-convex-asteroids',
- Edit system Hakoi, only check automatic save, and close System Editor,
- Inspect the hakoi.xml file : it is now messed-up.

I created a branch 'hakoi-test' in my repo Mutos/naev, with only the hakoi.xml file changed, for you to inspect.

**Comment by Mutos** [comment]
I tracked the error out of the Editors...

I logged asteroids fields properties upon entering Universe Editor, before any change can be made.

Here is the result for my test field on Hakoi :
  [stderr.txt](https://github.com/naev/naev/files/3168983/stderr.txt)

It shows the convex are generated OK, but the corners coordinates are different from what is in the file. This occurs BEFORE entering the Universe Editor.

So my next target is convex generation...

**Comment by Mutos** [comment]
By logging at the system loading stage, I found out the issue lies in convex subsets generation.

Now to fix it, I'll have to dive into it and it can take some time...

[stderr.txt](https://github.com/naev/naev/files/3169014/stderr.txt)

**Comment by Mutos** [comment]
Issue fixed, you just have to merge the PR to get it.

**Comment by bobbens** [comment]
Closing as it seems the fix was merged.
