### ISSUE TITLE
Does Naev have a roadmap?

### ISSUE THREAD

**Issue by ghost** [naev/naev#829]
Hello,

Judging from the number and date of commits, as well of the releases, it seems that development for Naev has stopped in 2012, with exception of small bumps in 2015 and in 2017 for the 0.6 and 0.7 releases.

I do not ignore that there were commits in between, though in small quantities.

Therefore, as the title implies, I wonder if Naev have a roadmap. The game is indeed playable, but in my humble opinion, it still feels rather incomplete.

Best regards.

**Comment by ids1024** [comment]
> stopped

I personally wouldn't say "stopped" for a project that generally has at least a slow trickle of commits, but yeah; pretty much a fair assessment.

I don't think it's really up-to-date, but here's the roadmap: http://web.archive.org/web/20170911165642/http://wiki.naev.org/wiki/Roadmap

Other plans are scattered on the forum and IRC.

> The game is indeed playable, but in my humble opinion, it still feels rather incomplete.

Definitely. The Empire campaign seems to be far from complete, and I believe all the others are much less complete than it is. That's probably the main way it's incomplete; though various improvements to the engine could certainly help as well. I think there are tentative plans for all of this, though not necessarily organized in one place.

**Comment by onpon4** [comment]
I can say as regards to this issue, I've got a *lot* of ideas yet. :wink: (Also the most complete campaign right now is the FLF campaign, which is finished, though I'm hoping to give them a sort of comeback later on.)

**Comment by onpon4** [comment]
Is this issue needed at this point, @bobbens? We don't have an outlined roadmap of any sort but development is more active than it's ever been now, so this looks anachronistic.

🕵️

**Comment by bobbens** [comment]
We can use the projects tab as a sort of roadmap (which we are sort of doing now). I don't really want to have a really rigid system, as it can make development less thrilling. So I'm guessing this can be closed.
