### ISSUE TITLE
Readme has broken URLs

### ISSUE THREAD

**Issue by Tsunder** [naev/naev#851]
Readme.md contains broken links.  Specifically, to wiki.naev.org. The website is no longer reachable as per #825 . 

Suggestions:
* removing the URLs
* cloning the content in:
* * a github wiki
* * the readme itself.

Additionally: 
Consider addressing all references to naev.org in the repository, perhaps as a separate issue.

Related to #825

**Comment by bobbens** [comment]
Manually copied some of the old wiki pages to the github wiki and fixed the links.
