### ISSUE TITLE
Travis CI Builds on Pull Requests fail

### ISSUE THREAD

**Issue by Fayti1703** [naev/naev#853]
The command `git fetch origin +refs/pull/<pull id>/merge:` as part of the setup fails, causing pull request builds to fail, even if the same code in the master branch successfully builds.

The most recent example of this is #852 [(failed Travis builds)](https://travis-ci.org/naev/naev/builds/580683063), which landed in master via acf9eef [(successful Travis builds)](https://travis-ci.org/naev/naev/builds/580683261)

**Comment by bobbens** [comment]
Travis has been fixed I believe, closing.
