### ISSUE TITLE
Swapping ships occasionally (rarely) leads to a segfault

### ISSUE THREAD

**Issue by onpon4** [naev/naev#866]
This may seem like a deja-vu moment: no, your eyes do not deceive you, yes, you are seeing #719 again.

Yeah, it's not solved unfortunately. :/ I just experienced one of these crashes again. The thing that sucks about this bug is that it's so rare and impossible to produce that it's impossible to know it's broken until you specifically see it failing.

So, just a recap: the bug is that Naev very very rarely segfaults when you swap ships. I've not been able to gather much info beyond that over the years, though I have noticed that when I swap ships multiple times it's more likely to trigger it.

Previously I thought #836 might have fixed this, but sadly I was wrong on that. So! Back to square 1. 🤷‍♀️

**Comment by bobbens** [comment]
Full gdb backtrace please! Just run it always under gdb (recommended) and whenever it triggers if you show me the output of "bt full" it should be much easier to debug.

**Comment by onpon4** [comment]
I finally had this happen with gdb running!

https://pastebin.com/4XmMwHfA

Unfortunately my build is optimized and without debug symbols (I forget how to compile without optimization and with debug symbols...), but it's something I guess!

**Comment by bobbens** [comment]
The second link shows the game crashing because a planet doesn't have a texture and it is trying to get it. Do you have any warnings when starting the game?

**Comment by bobbens** [comment]
I have added checks in the code so it shouldn't crash when the Lua tries to load a planet graphic that doesn't exist. It should properly give a Lua error because the texture is nil instead.

**Comment by onpon4** [comment]
Huh, interesting. No, I never did notice any warnings. But I'll be on the lookout for warnings and errors now!

It seems so weird that this would be a problem with planet textures of all things, but there you go. 😆

**Comment by onpon4** [comment]
#908 fixes this. 🙂
