### ISSUE TITLE
Improving Outfitting with Optimization

### ISSUE THREAD

**Issue by bobbens** [naev/naev#872]
An interesting point was raised in #870  about using optimization to find good outfit sets from outfit sets for pilots. As mentioned, this is a hard problem to do exhaustive search due to the combinatoric nature, however, I think it can be addressed in many different ways. To sum up, let us define the problem:

* `s`: ship
* `O`: set of possible outfits
* `o_i`: set of possible outfits for slot `i` with `o_i` being a subset of `O`
* `x`: set of outfits (with `x_i` being outfit for slot `i`, and `x_i` in `o_i`)
* `f`: function defining criteria to outfit a ship, for example focus on maximizing damage to a certain target while minimizing energy usage, subject to CPU limit, etc...

The optimization problem would simple be
```
x* = argmax_x f( x | s, O )
```
The idea would be to:
1. define the function `f` and set of outfits `O` per ship or use sort of prototypes for faction.
1. filter the outfits per slot to obtain `o_i`
1. randomly initialize `x`
1. optimize by finding `x*` that maximizes `f`

As mentioned, this has the downsides of being slow and in generally a hard optimization problem, but I think it can be implemented as follows:
1. Use greedy approach for optimization (although exhaustive might be feasible in many cases)
1. Perform the computation offline and save results to Lua equip files (can make use of existing framework)
1. Should be deterministic so that when it is reoptimized, if nothing changes it will result in the same output.

Ideas that would also be possible:
1. Add a penalty on outfit cost to `f`, thus allowing "poor" pilots to exist and not have everyone be optimal
1. Randomly swap outfits out for suboptimal parts
1. Use different weights in the function `f` to allow for different optimal builds
1. Implement it in python to generate Lua code, allowing to use existing optimization libraries

Benefits of this approach:
* No need to do low level script editing. If it works, you just have to define `f` and `O` and it will automatically do the rest.
* Automatically handles new ships and outfits and changes.
* Can implemented to automatically take into account ship bonuses by adding them to `f` calculations!

**Comment by BTAxis** [comment]
One aspect that has not been mentioned here is the possibility of combined arms, meaning that a ship's loadout might be chosen based on other ships in the same fleet. For example, think of having dedicated missile ships that try to stand off while more energy-focused ships engage the enemy at close range. I imagine this would be handled in some higher level system that governs the weights used by the actual outfitting algorithm.

**Comment by bobbens** [comment]
> One aspect that has not been mentioned here is the possibility of combined arms, meaning that a ship's loadout might be chosen based on other ships in the same fleet. For example, think of having dedicated missile ships that try to stand off while more energy-focused ships engage the enemy at close range. I imagine this would be handled in some higher level system that governs the weights used by the actual outfitting algorithm.

That's a good point. Theoretically, the same framework could be done to optimize for multiple ship loadouts at a time using a single objective function, so that the ships can cover each other weaknesses. It will, however, significantly increase the optimization complexity, but if done periodically offline, it should be still possible.

**Comment by ids1024** [comment]
Of course, that kind of fleet fanciness is also dependent on having AI to take advantage of it.

I imagine, say, empire ships would have fairly standard configurations. Though there could be more than one configuration of a ship optimized for different purposes.

Whereas pirates should be all over the place. The cheapest ship possible. Or the absolute most expensive advanced design. Or a random combination of outfits (perhaps stolen/scavenged) that doesn't particularly make sense. And then a fleet of pirates could be either a well designed system optimized to work together, or perhaps more often a chaotic mix of ships with only mildly coordinated pilots.

**Comment by bobbens** [comment]
[GLPK](http://www.gnu.org/software/glpk/glpk.html) seems like a good candidate for a linear program library to linked to. Also has a [fairly straight-forward and easy to use API](https://en.wikibooks.org/wiki/GLPK/Using_the_GLPK_callable_library). For generating the optimization programs, we can either have Lua do that online (maybe once per start-up using `naev.cache()`? Could be also possible to cache it and regen as necessary), or have a python / C script generate that for us, although I do think having Naev do it would be easiest and most future-proof.

**Comment by bobbens** [comment]
Merged into main!
