### ISSUE TITLE
gatherable_getClosest() returns uninitialized memory if gatherable_nstack==0

### ISSUE THREAD

**Issue by ids1024** [naev/naev#873]
Found using valgrind. I'm not sure exactly what the fix is since I'm not sure I understand how `aiL_getGatherable()`, which calls this, is supposed to work.

**Comment by bobbens** [comment]
Thanks, should be fixed! (now AI should just create Lua errors instead of crashing)

**Comment by ids1024** [comment]
Now the game just segfaults in `gatherable_getPos`, which tries to access `gatherable_stack[-1]`.

This solution is correct, but `aiL_getGatherable()` also needs to be changed in some way. I'm not sure exactly how...

**Comment by bobbens** [comment]
My sleep-deprived made inverted a check in my mind. It should now not return a valid position in the AI when there are no gatherables left. However, I don't think the AI will handle this case and will probably throw errors.

**Comment by bobbens** [comment]
Should be fixed (although AI doesn't handle it properly likely, it'll just find a new task to do).
