### ISSUE TITLE
[Proposal] Ship-to-ship scanning

### ISSUE THREAD

**Issue by bobbens** [naev/naev#898]
(taken from the [old wiki](https://web.archive.org/web/20170815201022/http://wiki.naev.org/wiki/Ship_to_Ship_Scanning))

This is a proposal about scanning objects such as ships, asteroids or even planets.

## Goals
* Create room for more outfit content
* Facilitate Contraband
## Active scanning
By "active scanning", we understand a mechanic that requires the player to explicitly request information about a certain object, as opposed to being offered that information automatically on the on-screen interface. Without active scanning, the information about any ship is limited to basic data such as the ship's name, type an class, and the distance to that ship.

Active scanning may reveal detailed information, such as the weapons the ship has installed, the cargo it is carrying, what abilities the ship has, and any special conditions set for that ship. By "special conditions" we should think of mission-defined properties, such as "has VIP on board" or "is rigged to explode".

Active scanning might also apply to objects other than ships. For instance, asteroids may be scanned for mineral content, or planets may be scanned for signs of life. We shall assume that all mechanics discussed below apply to these objects also.

## Implementation
Active scanning should make use of the activated outfit infrastructure. A ship scanner can be either on or off, and while on, it will drain energy. While the scanner is on, it will attempt to scan whatever ship the pilot has targeted. The ship must be within the sensor's range for actual scanning to take place. If these conditions are met, then the scanner will initiate an active scan. An active scan should take time, and while the scanner is doing its job a progress meter should be displayed, either below the scanner's icon in the outfit bar, or underneath the ship that's being scanned. While the scan is in progress the scanning pilot must remain within scanning distance of his target, or the scan will abort. The will also abort if the pilot loses or changes his target. The time needed for the scan to complete depends on the scanner's efficiency and the target's electronic warfare capabilities.

Once the active scan is complete the scanning pilot has access to all the information the scanner is meant to uncover, although a Lua function to override this is probably going to come in useful for mission scripters. Once scanned, a ship stays scanned and the information can be called up at any time even if the scanner has been turned off.

It might be useful if the player could tell he is being scanned by an AI ship, for example by means of a pulsating message on the screen to that effect.

## The ship information screen
The ship information screen should work in much the same way as the hail screen, in that it is a modest toolkit window displayed in the center of the playing field. It will interrupt gameplay, but this is not a concern. In fact it is quite probably a desirable thing.

**Comment by PhoenixRiver** [comment]
I'd also suggest that AI ships take an active scan as a shot across
the bows; possible hostile ships would attack and cargo ships would
flee. There would probably need to be a minimum time that the scan is
active on a target otherwise flipping between targets could make
everything in the system suddenly hostile!

Phoenix

**Comment by bobbens** [comment]
An alternate proposal is in #1687 . Basically the idea is to automatically scan ships that are within a distance instead of using an active scanner. This would avoid another specialized outfit, and might be better.

**Comment by bobbens** [comment]
Mainly implemented as in #1687 , meaning done automatically. The player can't use this interface atm, but the AI does fairly well.
