### ISSUE TITLE
Gprof lists planet_exists as the most expensive function in the game

### ISSUE THREAD

**Issue by ids1024** [naev/naev#902]
```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
 14.63      1.34     1.34   449585     0.00     0.00  planet_exists
 13.65      2.59     1.25  1911404     0.00     0.00  pilot_update
...
```

Am I reading this wrong, or is this seriously claiming `planet_exists()` accounts for 14.6 percent of game's CPU time? This seems rather absurd. (It should be a very insignificant component).

It's called in various places, including (perhaps significantly) the definition of `planet_isKnown()`. I'm not really sure why it's used there. But it is definitely not desirable for that to invoke a O(n) function that performs up to `planet_nstack` string comparisons.

**Comment by bobbens** [comment]
It should be fairly trivial to change the planets to be sorted by name and then perform binary search. This would change from O(N) to O(logN) without any downsides (just have to make sure to resort when adding/removing a planet and to make sure all the pointers are sane). On a side note, I am not certain that the planet_exists check is needed for planet_isknown.

**Comment by nenau-again** [comment]
Just for record, it seems to have been addressed in https://github.com/naev/naev/commit/4c97513ad5a9020765ac626875ec1073195814c6. Are there other places where binary search would make us save CPU time ?

**Comment by bobbens** [comment]
> Just for record, it seems to have been addressed in [4c97513](https://github.com/naev/naev/commit/4c97513ad5a9020765ac626875ec1073195814c6). Are there other places where binary search would make us save CPU time ?

Most of the Lua API calls objects by name to get userdata. Most of them are not sorted by name, but could be trivially sorted such as planets/systems, etc. and changed to do binary search when looking at names.

**Comment by ids1024** [comment]
> Most of them are not sorted by name, but could be trivially sorted such as planets/systems

Right. Probably grep the code for `_stack` and `_nstack`. I don't know if any of them are major performance bottlenecks now, but using binary searches would generally be good (given most of these are things created once at the start of the game).

**Comment by bobbens** [comment]
> > Most of them are not sorted by name, but could be trivially sorted such as planets/systems
> 
> Right. Probably grep the code for `_stack` and `_nstack`. I don't know if any of them are major performance bottlenecks now, but using binary searches would generally be good (given most of these are things created once at the start of the game).

In general you can't assume they don't change, however, in most cases they will only change when a unidiff is applied, which is very rare.

**Comment by ids1024** [comment]
> In general you can't assume they don't change

Right. I should have said, they rarely change. So it should be programmatically possible to insert and delete at any time, but it doesn't need to be efficient.

By the way, @nenau-again, I don't know if you've noticed, but Naev now has a Discord server linked to on http://naev.org. We've been having some development discussions there.

**Comment by UncombedCoconut** [comment]
`planet_exists` specifically must have been addressed for quite a while.
`planet_isKnown` got simplified here: https://github.com/naev/naev/commit/e67d67689d977bf915b978a30eea31f4c60692db
I've done some profiling and seen no evidence these linear scans are a problem. See below for one caveat, though.
I suspect that modern CPU caching/prediction can unfairly diminish/reverse the advantage of better algorithms over linear scans -- not with high confidence, but I'd want to measure, and the measurable gain just isn't in evidence.

Here's the catch: it's convenient to configure debug builds which compile with flags like -g -O0 -fsanitize=address -DDEBUGGING.
In that case, standard array™ loops like `for (i=0; i<array_size(my_array); i++)` get *murdered*. Every `array_size()` needs a real function call plus magic ASan checks.
But any good compiler will turn those into normal loops, if allowed to.

FWIW I've been using techniques like this to profile how we're using CPU resources: http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html
(Attached a quick run, using a debugoptimized build type with ASan on.)
[debugopt-20200217.svg.gz](https://github.com/naev/naev/files/5993440/debugopt-20200217.svg.gz)

I think this issue is closable, but it could also follow one of these tangents.

**Comment by ids1024** [comment]
I think with the number of planets in the game, a binary search would probably be faster. But it's not really important if profiles doesn't currently show it taking much time.

> In that case, standard array™ loops like for `(i=0; i<array_size(my_array); i++)` get murdered. Every `array_size()` needs a real function call plus magic ASan checks.

That could probably be solved by more manual optimization:

```
int size = array_size(my_array);
for (i=0; i<size; i++)
```

Valid if the array size doesn't change during iteration (which is probably assumed in such cases anyway), and could be an optimization even on optimized builds if the compiler can't verify that itself.

Do you need to use `-O0`? https://clang.llvm.org/docs/AddressSanitizer.html seems to generally suggest `-O1`.

**Comment by UncombedCoconut** [comment]
Of course, that manual optimization will work on non-resizing loops (which is nearly all of them). In most places it also harms readability, so I'd only consider it in hot spots.

I almost never need -O0. It makes tracing much better (than even -Og), but most of the time I only need stack traces from crashes anyway. I think bobbens prefers -O0. Ideally we should pick a good default and recommend it in Readme.md.

**Comment by UncombedCoconut** [comment]
As far as I can tell, https://github.com/naev/naev/commit/e22e40b1c58f4dde12a0ab2835cfe4b7d64effc3 systematically fixes the array_size problem. I updated the Readme, which suggests unoptimized first.
Profiles are showing ~0 time spent looping through lists now. Any objection to closing the ticket?
(We could transition to current profiler targets, but it's a less tidy story.)

**Comment by ids1024** [comment]
Seems fine to close. We can re-open if we see evidence again of this having a significant cost.
