### ISSUE TITLE
Link errors with latest bfd

### ISSUE THREAD

**Issue by ids1024** [naev/naev#925]
```
/usr/bin/ld: naev.o: in function `debug_translateAddress':
/home/ian/Devel/src/naev/src/naev.c:1363: undefined reference to `bfd_get_section_flags'
/usr/bin/ld: /home/ian/Devel/src/naev/src/naev.c:1366: undefined reference to `bfd_get_section_vma'
/usr/bin/ld: /home/ian/Devel/src/naev/src/naev.c:1367: undefined reference to `bfd_get_section_size
```

This seems to be a result of https://github.com/bminor/binutils-gdb/commit/fd3619828e94a24a92cddec42cbc0ab33352eeb4. It looks like it should be a fairly simple fix to change the calls to use the newer version of the functions, though it will need to be done conditionally with some version test, to still support older versions.

**Comment by bobbens** [comment]
Man, you wish they would leave it a year with deprecation warnings so we could handle it at our leisure...

**Comment by bobbens** [comment]
Should be solved in latest git.
