### ISSUE TITLE
Miscellaneous graphical effects

### ISSUE THREAD

**Issue by ids1024** [naev/naev#928]
With Naev's rendering migrating to shaders (#885), we can try using OpenGL for some neat graphical effects. A few things like that are listed in the (rather dated) [TODO file](https://github.com/naev/naev/blob/master/TODO).

Here are some things that come to mind:
* Better engine glow, perhaps using some kind of particle system
* Particle effects could also provide better explosions
* Miscellaneous improvement to the nebula effect
* Thurion cloaking effect (an idea I've had that seems particularly fun)
   - Ship is invisible
   - Sometimes/always produces some slight distortion to the space around it
   - Have this interact in some way with the nebula effect
   - Using weapons/generating heat results in visibility
   - Maybe sometimes part of the ship (or it's outline) is semi-visible?
* Lighting effects for beams (could reflect, diffuse, etc. off certain surfaces)
* A more interesting jump effect? The current rapid speed plus fade to white is fine, but probably there are more interesting possibilities...

Any effects that are graphically intensive should have an option to disable, of course.

If anyone has ideas for effects they'd like, feel free to comment. Though obviously we can't have everything.

**Comment by bobbens** [comment]
Most of this has been implement already. Closing.
