### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by Lineth** [naev/naev#957]
Followed the instructions from the wiki. Unfortunately, it doesn't seem to be working. Not sure what the problem is. On Win10 64 bit.
```
 $ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force --install -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:11: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:11: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:11: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
autoreconf: Leaving directory `.'
./autogen.sh: line 12: intltoolize: command not found
Generating configuration files failed!
Make sure you have the following packages installed:

   automake
   autopoint (gettext tool)
   intltool
```

**Comment by BTAxis** [comment]
It's still working for me, on the latest git master and with a freshly updated msys2.

Have you done as it said and made sure you have the autotools packages? You can check using

pacman -Ss automake
pacman -Ss gettext
pacman -Ss intltool

It should tell you at least one package for each of these is installed. If not, install the appropriate package using pacman -S.

Possibly our wiki instructions are out of date.

**Comment by Lineth** [comment]
I seem to have the files, but it didn't help. I also reinstalled Msys2 entirely and that did not work either.

**Comment by BTAxis** [comment]
I've just tested it with a completely fresh MSYS2, following the instructions on the wiki. A few packages were missing from the list. These are: intltool, fontconfig and LuaJIT (the last one is a soft dependency). I have updated the instructions and they should work now.

I have successfully built the git version via the instructions, though right now Windows compilation is broken in master, but that'll get fixed soon I'm sure.

**Comment by Lineth** [comment]
Yeah, it seems broken. Same error.
`$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
/usr/bin/autopoint: line 485: /usr/share/gettext/archive.dir.tar.xz: No such file or directory
tar.exe: gettext-0.18: Not found in archive
tar.exe: Error exit delayed from previous errors.
autopoint: *** infrastructure files for version 0.18 not found; this is autopoint from GNU gettext-tools 0.19.8.1
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
Generating configuration files failed!
Make sure you have the following packages installed:

   automake
   autopoint (gettext tool)
   intltool
`

**Comment by BTAxis** [comment]
Okay, I'll try it in a VM to see if I can reproduce this.

**Comment by BTAxis** [comment]
Okay, I reproduced it and it turns out the setup doesn't include tar. For some reason. So:
pacman -S tar

That should do it.

**Comment by Lineth** [comment]
Well, autogen worked, but did give a warning. Posting just in case it's important:
`configure.ac:11: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:11: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:11: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
autoreconf: Leaving directory `.'
You should update your 'aclocal.m4' by running aclocal.`

./configure went off without a problem. No issues there.

However, at make, it went partially through the program before this happened:
`In file included from ../../../src/opengl.h:14,
                 from ../../../src/font.h:11,
                 from ../../../src/tk/widget/text.h:11,
                 from ../../../src/tk/widget.h:12,
                 from ../../../src/tk/toolkit_priv.h:14,
                 from button.c:12:
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:68:78: error: expected ')' before '*' token
 void APIENTRY gluQuadricCallback(GLUquadric *qobj,GLenum which,void (CALLBACK *fn)());
                                                                              ^~
                                                                              )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:78:78: error: expected ')' before '*' token
 void APIENTRY gluTessCallback(GLUtesselator *tess,GLenum which,void (CALLBACK *fn)());
                                                                              ^~
                                                                              )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:94:74: error: expected ')' before '*' token
 void APIENTRY gluNurbsCallback(GLUnurbs *nobj,GLenum which,void (CALLBACK *fn)());
                                                                          ^~
                                                                          )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:96:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUquadricErrorProc)(GLenum);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:97:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessBeginProc)(GLenum);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:98:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEdgeFlagProc) (GLboolean);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:99:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessVertexProc)(void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:100:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEndProc)(void);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:101:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessErrorProc)(GLenum);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:102:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessCombineProc)(GLdouble[3],void*[4],GLfloat[4],void**);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:103:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessBeginDataProc)(GLenum,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:104:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEdgeFlagDataProc) (GLboolean,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:105:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessVertexDataProc)(void *,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:106:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEndDataProc)(void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:107:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessErrorDataProc)(GLenum,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:108:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessCombineDataProc)(GLdouble[3],void*[4],GLfloat[4],void**,void*);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:109:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUnurbsErrorProc)(GLenum);
                       ^~
                       )
make[4]: *** [Makefile:463: button.o] Error 1
`

**Comment by ids1024** [comment]
@Lineth BTAxis just reported that issue on Discord, and I reverted the change that caused it: https://github.com/naev/naev/commit/02131c05aa2060a475253f8e621af6565316179c

**Comment by BTAxis** [comment]
To get that latest change, you need to update your local repo:
git pull origin master

**Comment by Lineth** [comment]
Already did so. Doesn't seem to have worked, unfortunately.


$ make
Making all in po
Making all in lib
Making all in csparse
Making all in src
Making all in tk
Making all in widget
  CC    button.o
In file included from ../../../src/opengl.h:14,
                 from ../../../src/font.h:11,
                 from ../../../src/tk/widget/text.h:11,
                 from ../../../src/tk/widget.h:12,
                 from ../../../src/tk/toolkit_priv.h:14,
                 from button.c:12:
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:68:78: error: expected ')' before '*' token
 void APIENTRY gluQuadricCallback(GLUquadric *qobj,GLenum which,void (CALLBACK *fn)());
                                                                              ^~
                                                                              )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:78:78: error: expected ')' before '*' token
 void APIENTRY gluTessCallback(GLUtesselator *tess,GLenum which,void (CALLBACK *fn)());
                                                                              ^~
                                                                              )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:94:74: error: expected ')' before '*' token
 void APIENTRY gluNurbsCallback(GLUnurbs *nobj,GLenum which,void (CALLBACK *fn)());
                                                                          ^~
                                                                          )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:96:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUquadricErrorProc)(GLenum);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:97:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessBeginProc)(GLenum);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:98:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEdgeFlagProc) (GLboolean);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:99:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessVertexProc)(void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:100:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEndProc)(void);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:101:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessErrorProc)(GLenum);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:102:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessCombineProc)(GLdouble[3],void*[4],GLfloat[4],void**);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:103:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessBeginDataProc)(GLenum,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:104:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEdgeFlagDataProc) (GLboolean,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:105:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessVertexDataProc)(void *,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:106:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEndDataProc)(void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:107:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessErrorDataProc)(GLenum,void *);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:108:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessCombineDataProc)(GLdouble[3],void*[4],GLfloat[4],void**,void*);
                       ^~
                       )
C:/msys64/mingw64/x86_64-w64-mingw32/include/GL/glu.h:109:23: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUnurbsErrorProc)(GLenum);
                       ^~
                       )
make[4]: *** [Makefile:463: button.o] Error 1
make[3]: *** [Makefile:421: all-recursive] Error 1
make[2]: *** [Makefile:1183: all-recursive] Error 1
make[1]: *** [Makefile:886: all] Error 2
make: *** [Makefile:649: all-recursive] Error 1

**Comment by ids1024** [comment]
Are you sure you're on the latest commit? With that change reverted, `glu.h` shouldn't be included at all.

**Comment by BTAxis** [comment]
Consult
git log
Which should tell you the newest commit is 02131c0. If not, you haven't successfully pulled it.

**Comment by Lineth** [comment]
You were right, the pull didn't update properly. Had to delete the repo entirely and re-fork (thanks, Github Desktop 😒 ). Seems to have worked now.

**Comment by BTAxis** [comment]
You can either run the game with the `--devmode` flag, or you can edit your conf.lua and set devmode = true.
