### ISSUE TITLE
Add CI that tests on Windows

### ISSUE THREAD

**Issue by ids1024** [naev/naev#959]
The build often ends up breaking on Windows, in some minor way. We currently have Travis CI test on OS X and Linux. It would be good to have some kind of CI that does Windows builds.

I tried to set up AppVeyor a couple years ago. Travis also has experimental support for Windows now.

**Comment by onpon4** [comment]
I think this is solved as of #1170 (and the others that followed shortly after)?

**Comment by ProjectSynchro** [comment]
Yes, this should be solved as of that PR.

**Comment by onpon4** [comment]
Alrightie, closing this then.

🕵️
