### ISSUE TITLE
Options not saving after client close

### ISSUE THREAD

**Issue by Lineth** [naev/naev#961]
Title says it all, really. Options do not seem to be saved when I exit the game and boot it again.

**Comment by ids1024** [comment]
You can try running Naev from a terminal, and seeing if it displays any errors.

**Comment by BTAxis** [comment]
This is most likely a permissions issue. You can get around it by running Naev as an administrator, or using the portable mode, which involves adding a datapath.lua file in your Naev root, which contains the path to your user directory. For example:

datapath = "./.naev"

**Comment by Lineth** [comment]
welp, now I feel silly. That got it.
