### ISSUE TITLE
Doesn't build under Linux 16.04 LTS but OK for win32 and win64

### ISSUE THREAD

**Issue by Mutos** [naev/naev#962]
Hello,

It's been long I haven't tried to build NAEV. I just got latest commit 64fafe9dbef218c1a5527f4432a5ddb540080d8b and tried to built it OOT with my usual method :
- autogen.sh
- make bin/win32, bin/win64, bin/lin64
- with the appropriate system, cd to bin/<arch>
- ../../configure
- make

For win32 and win64 it works OK using Win10 and MinGW<arch>, but in Linux, the one OS on which I didn't expect a problem, it fails with the attached errors.

[make.log](https://github.com/naev/naev/files/4401487/make.log)

The errors are in "bfd_section_*"  parts of the code. I just don't know what they are and what they do, and as the forum is no more, I have to log an issue to tell you. Don't know if it can be solved by code or if it requires my system to be updated... 

I checked my Ubuntu, it's up-to-date, of course for a 16.04...

I'll try to understand what is this bfd_ stuff, but one of you devs could well be faster than me on that one ^-^

Thanks in advance !

Benoît 'Mutos' Robin

**Comment by ids1024** [comment]
Hm, I guess the change in https://github.com/naev/naev/commit/a8a5dcb47b0f37b4943c16680e9cda94f76d5651, which was needed to fix newer BFD versions, (https://github.com/naev/naev/issues/925), isn't backwards compatible. Annoying.

`./configure --disable-debug` will disable the relevant code (and some other code). Reversing the changes in that commit should also work.

I guess we need some sort of conditional compilation to support both versions....

**Comment by Mutos** [comment]
Hi ids1024,


Thanks for the answer ! For now I'll try with debug disabled. Indeed we would need a conditional compile, but how could we test the condition of binutils version ? Is there a variable or something like that, that could be accessed from within a condition ?


@+

Benoît 'Mutos' Robin

**Comment by ids1024** [comment]
I'm not sure if there's an easy way to check the bfd version.

I believe one of the core features of autoconf is checking if a function is defined and setting a variable based on that, which might be the best solution for this sort of thing. If the newer function name is found, use it; otherwise use the old one.

**Comment by bobbens** [comment]
With the new LTS coming out in a month, and Ubuntu 16.04 being over 4 years old, I'm not sure if we could just stop supporting debugging on 16.04 in this case.

**Comment by PhoenixRiver** [comment]
> With the new LTS coming out in a month, and Ubuntu 16.04 being over 4 years
> old, I'm not sure if we could just stop supporting debugging on 16.04 in
> this case.

I'd find that to be a shame... though I suppose waiting for the new
LTS (which _might_ solve the problem) is not the end fo the world -
though this problem would seem to be a general one rather than
specific to this build (though, again, more with older OS builds).

River

**Comment by bobbens** [comment]
Should have added support for older BFD in  d60f699cf51f5b716295f5f0d5a98293841582a0 , however, I am unable to test it with older Ubuntus.

**Comment by Mutos** [comment]
In fact, commits 51ee399648bf1ae007454c956dc0944c9d59c4b0 through 8454fd85b816354dd2326deed87d476e09c1756e compile OK on the same machine. I haven't tested on my other machines (16.04 and 18.04) or under Windows.

**Comment by bobbens** [comment]
Ok, it seems like it is compiling so I'll close this issue.
