### ISSUE TITLE
Raelid and other nebula systems causes a CTD.

### ISSUE THREAD

**Issue by Lineth** [naev/naev#963]
Been trying to find a crash file, but I can't, unfortunately.

**Comment by BTAxis** [comment]
You could try making a backtrace with a debugger like gdb.

**Comment by Lineth** [comment]
How would I do that (Sorry, my coding knowledge is nearly non-existent)?

**Comment by BTAxis** [comment]
I'm unsure if you've got gdb installed by default, if not grab it from pacman. Then, from your msys terminal, invoke gdb with
`gdb naev`
Then, when you're in gdb run the program with
`run`
Then play until you hit the crash, which gdb will report as a segmentation fault. You can get the backtrace with 
`backtrace -full`
Post the output that gives you.

**Comment by Lineth** [comment]
`Starting program: /c/Users/Jeff/Documents/Github/naev/naev
Error creating process /c/Users/Jeff/Documents/Github/naev/naev, (error 740).
`

**Comment by BTAxis** [comment]
As far as I can tell that seems to be permission related. I don't know though, I've never encountered it.

**Comment by Lineth** [comment]
Well, I think I got around that by running MinGW as an administrator, but now it coughs up another error. 🤦‍♂️
`# gdb naev
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'libstdcxx'
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from naev...done.
`

**Comment by BTAxis** [comment]
Hmm, one thing I notice in that is that your gdb is configured as "x86_64-pc-msys", while mine is configured as "x86_64-w64-mingw32". That suggests to me that your gdb lives in msys2 and doesn't interact with MinGW.

You can check this by asking `which gdb`, which in my case returns `/mingw64/bin/gdb`. See if you can run that one manually, or if it doesn't exist, install the relevant package via pacman. It should be mingw-w64-i686-gdb.

**Comment by Lineth** [comment]
```
AL lib: (EE) alc_cleanup: 1 device not closed
[Thread 13596.0x2c7c exited with code 3]
[Thread 13596.0x2e8c exited with code 3]
[Thread 13596.0x1214 exited with code 3]
[Thread 13596.0x920 exited with code 3]
[Thread 13596.0x1f24 exited with code 3]
[Thread 13596.0xeb4 exited with code 3]
[Thread 13596.0x22ec exited with code 3]
[Thread 13596.0x341c exited with code 3]
[Thread 13596.0x2574 exited with code 3]
[Thread 13596.0x3430 exited with code 3]
[Thread 13596.0x26fc exited with code 3]
[Thread 13596.0x1f74 exited with code 3]
[Thread 13596.0x381c exited with code 3]
[Thread 13596.0x3fa8 exited with code 3]
[Inferior 1 (process 13596) exited with code 03]
(gdb) backtrace -full
No stack.
(gdb)

```

**Comment by BTAxis** [comment]
That's not a segfault, that looks more like a normal game shutdown.

**Comment by BTAxis** [comment]
Though, a normal shutdown would be code 0.

**Comment by Lineth** [comment]
Any idea why the nebula would be forcing the game to quit?

**Comment by BTAxis** [comment]
No, it doesn't do so for me. The only thing I can think of is the OpenAL backend, because the nebula uses it for reverb effects. You can try switching to sdlmix in the options and see if it makes a difference.

**Comment by Lineth** [comment]
Yay! That did it, good guess and thanks.

**Comment by ids1024** [comment]
Perhaps this is the same issue as #806.

**Comment by kjc** [comment]
I encountered this same problem on an older Fedora installation, and I ``solved'' it with a similar workaround...

Naev 0.7.0 crashes reliably when entering the Raelid system.  The screen goes white briefly, then the game crashes to desktop.  I tried entering the system from 3 different routes, with or without mission destinations in the Raelid system, with no difference.

When I run `gdb naev`, jumping into Raelid still fails, but the game hangs on the white screen instead of exiting.  `gdb` catches the `SIGABRT` and reports the failure.

I can't run `backtrace -full` on this installation, but I can run the plain `backtrace`:

    $ naev --version
     Naev v0.7.0

    $ gdb naev
    GNU gdb (GDB) Fedora 8.3-7.fc30
    Copyright (C) 2019 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    Type "show copying" and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
        <http://www.gnu.org/software/gdb/documentation/>.

    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from naev...
    (No debugging symbols found in naev)
    Missing separate debuginfos, use: dnf debuginfo-install naev-0.7.0-8.fc30.x86_64
    (gdb) run
    Starting program: /usr/bin/naev
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
     Naev v0.7.0
    [New Thread 0x7ffff7089700 (LWP 3863)]
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    warning: Loadable section ".note.gnu.property" outside of ELF segments
    [New Thread 0x7ffff4b46700 (LWP 3864)]
     Sea of Darkness
    [New Thread 0x7fffe2faa700 (LWP 3865)]
    [Thread 0x7fffe2faa700 (LWP 3865) exited]
    [New Thread 0x7fffe2faa700 (LWP 3866)]
    [New Thread 0x7fffe27a9700 (LWP 3867)]
    [New Thread 0x7fffe25a8700 (LWP 3868)]
    AL lib: (WW) alGetError: Querying error state on null context (implicitly 0xa004)
    [New Thread 0x7fffe23a7700 (LWP 3869)]
    naev: /builddir/build/BUILD/openal-soft-1.19.1/Alc/filters/filter.c:25: BiquadFilter_setParams: Assertion `gain > 0.00001f' failed.

    Thread 6 "naev" received signal SIGABRT, Aborted.
    [Switching to Thread 0x7fffe27a9700 (LWP 3867)]
    0x00007ffff76bde35 in raise () from /lib64/libc.so.6
    (gdb)
    (gdb) backtrace -full
    No symbol table is loaded.  Use the "file" command.
    (gdb) file /usr/bin/naev
    A program is being debugged already.
    Are you sure you want to change the file? (y or n) n
    File not changed.
    (gdb) backtrace
    #0  0x00007ffff76bde35 in raise () from /lib64/libc.so.6
    #1  0x00007ffff76a8895 in abort () from /lib64/libc.so.6
    #2  0x00007ffff76a8769 in __assert_fail_base.cold () from /lib64/libc.so.6
    #3  0x00007ffff76b6566 in __assert_fail () from /lib64/libc.so.6
    #4  0x00007ffff78ab8e3 in ?? () from /lib64/libopenal.so.1
    #5  0x00007ffff78a9d2c in ?? () from /lib64/libopenal.so.1
    #6  0x00007ffff7898b18 in ?? () from /lib64/libopenal.so.1
    #7  0x00007ffff789ce24 in ?? () from /lib64/libopenal.so.1
    #8  0x00007ffff78c2901 in ?? () from /lib64/libopenal.so.1
    #9  0x00007ffff78c78cb in ?? () from /lib64/libopenal.so.1
    #10 0x00007ffff76674c0 in start_thread () from /lib64/libpthread.so.0
    #11 0x00007ffff7782133 in clone () from /lib64/libc.so.6

**Workaround:**  Changing the Options -> Audio -> Backends from `openal` to `sdlmix` allowed me to enter the Raelid system.  I haven't noticed any change to the sound quality using this backend so far.
