### ISSUE TITLE
Map item editor crashes the game

### ISSUE THREAD

**Issue by Mutos** [naev/naev#965]
On commit 64fafe9, when clicking on the button "Open" in the Map Outfits Editor crashes the game.

Here are the logs :
[stderr.txt](https://github.com/naev/naev/files/4432617/stderr.txt)
[stdout.txt](https://github.com/naev/naev/files/4432618/stdout.txt)

Since I initially developed the editor, I'll try to find where it bugs. However, it seems a memory allocation issue, which I'm quite bad at debugging. It seems to occur at different place in data loading, but always at the same code line : where freeing **name** variable.

**Comment by bobbens** [comment]
Can't reproduce. Could you try running with under valgrind? Something like `valgrind ./naev 2> v.txt` and post the output of v.txt?

**Comment by Mutos** [comment]
I finally setup a working repo in synch with my Mutos/naev and the main naev/naev repos, this time I think I've understood how to properly work with Git.

So I've created a bugfix-mapedit branch for working on that issue. I've setup some debugging output, tested and found the issue to be with map_qorel.xml.

I'll look at valgrind to see what that does and how to install, configure and use it, as I don't hope it'll work out of the box.

**Comment by Mutos** [comment]
I installed valgrind and ran the command, here is the result : 
[valgrind-naev-log.txt](https://github.com/naev/naev/files/4498501/valgrind-naev-log.txt)

**Comment by Mutos** [comment]
The issue is simpler than I thought : that map's description length (275) exceeds the MAPEDIT_DESCRIPTION_MAX constant (200). I set it at 300 and it works.

Quickfix : set it at 300. The real fix should be to make the string dynamic.

**Comment by Mutos** [comment]
I'll limit len by MAPEDIT_DESCRIPTION_MAX.

**Comment by Mutos** [comment]
Done, and I did the same for name and filename. Ready for the Pull Request !

**Comment by Mutos** [comment]
Thanks bobbens for the better fix ! I close the Issue !
