### ISSUE TITLE
Pass SDL_WINDOW_ALLOW_HIGHDPI when creating the Window

### ISSUE THREAD

**Issue by ids1024** [naev/naev#970]
When using Wayland on Linux (in particular, I'm testing with Sway), the compositor can have a per-display scale factor, for handling hiDPI displays. If this flag is not passed, on a 4k display Naev only gets a 1920x1080 drawable (which is automatically scaled up).

If this flag is enabled, `SDL_GetWindowSize` returns the size in "screen coordinates", which on a hiDPI display will be different from the actual size in pixels.

I believe this should work the same on MacOS devices with Retina displays.

Enabling this seems to cause a variety of small problems; or I would just have pushed a commit.

**Comment by ids1024** [comment]
The main problem I seem to come across with this is mouse input. The mouse position is in "screen coordinates", which is half the actual pixels with a 2x scale set by Sway. It seems this may require changes in various parts of the toolkit.

But if this works, devices that support this feature will get hiDPI without any program-specific scale factor (though that can be used as well).

**Comment by UncombedCoconut** [comment]
Note for posterity: According to []()

**Comment by UncombedCoconut** [comment]
Another possible pitfall, depending on how user settings are translated to window dimensions / fullscreen display modes, is [this "ABANDONED" bug](https://bugzilla.libsdl.org/show_bug.cgi?id=3433). If we care whether SDL_DisplayModes' w/h are "screen coordinates" just like hidpi-aware SDL_CreateWindow (units of scale_factor pixels) or pixels, it can depend on the combination of drivers, platforms, and workarounds. SDL2 always seems to *intend* pixels, but on Windows that requires the workaround described in the issue and on Wayland it requires setting SDL_VIDEODRIVER=wayland.

This problem goes away if we opt to split split conf.width and conf.height into separate settings for window dimensions and fullscreen modes. Thinking through some user interactions (like toggling out of fullscreen, resizing the window with the mouse, and toggling back), I think that could make sense.

On a related note, I think having gl_screen.desktop_w and gl_screen.desktop_h is also a source of trouble. (Why should they be constant? What if you drag the game window between monitors?) If it's uncontroversial, I think it makes sense to remove those fields and check on the fly.

**Comment by bobbens** [comment]
I believe this is solved ;)
