### ISSUE TITLE
ship go from Ksher to Sultan but just crash program....

### ISSUE THREAD

**Issue by universe-11** [naev/naev#972]
Naev v0.7.0 (x86_64-pc-linux-gnu)
 git HEAD at a2d958ab9
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 2.0.10 [compiled: 2.0.10]

OpenGL Window Created: 1920x1080@24bpp window
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 16384
vsync: yes, mm: yes, compress: no, npot: yes
Renderer: GeForce GT 710/PCIe/SSE2
Version: 3.2.0 NVIDIA 435.21

Using default font '/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf'
OpenAL started: 44100 Hz
Renderer: OpenAL Soft
Version: 1.1 ALSOFT 1.19.1 with EFX 1.0

Loaded 42 Sounds
Loaded 47 Songs
Loaded 16 Nebula Layers
Loaded 47 Commodities
Loaded 36 Factions
Loaded 37 AI Profiles
Loaded 121 Missions
Loaded 32 Events
Loaded 298 Outfits
Loaded 86 Ships
Loaded 134 Fleets
Loaded 61 tech groups
Loaded 373 Star Systems
       with 1140 Planets
Loaded 1 map decorators.
naev: /build/openal-soft-gstqns/openal-soft-1.19.1/Alc/filters/filter.c:25: BiquadFilter_setParams: Assertion `gain > 0.00001f' failed.
Naev received SIGABRT!
./naev(+0x90252) [0x556f59559252] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(+0x46470) [0x7fd21f348470] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7fd21f3483eb] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7fd21f327899] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(+0x25769) [0x7fd21f327769] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(+0x37006) [0x7fd21f339006] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(+0x39330) [0x7fd21f551330] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(+0x379ca) [0x7fd21f54f9ca] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(+0x267ce) [0x7fd21f53e7ce] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(+0x2ab5b) [0x7fd21f542b5b] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(+0x513c1) [0x7fd21f5693c1] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(+0x57b57) [0x7fd21f56fb57] ??(...):0 ??
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9669) [0x7fd21f2e8669] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fd21f424323] ??(...):0 ??
Report this to project maintainer with the backtrace.
AL lib: (EE) alc_cleanup: 1 device not closed
naev: /build/openal-soft-gstqns/openal-soft-1.19.1/Alc/ALc.c:800: LockLists: Assertion `ret == althrd_success' failed.
Naev received SIGABRT!
./naev(+0x90252) [0x556f59559252] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(+0x46470) [0x7fd21f348470] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7fd21f3483eb] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7fd21f327899] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(+0x25769) [0x7fd21f327769] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(+0x37006) [0x7fd21f339006] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(+0x23217) [0x7fd21f53b217] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libopenal.so.1(alSourcef+0x1c) [0x7fd21f53004c] ??(...):0 ??
./naev(+0x8ee5f) [0x556f59557e5f] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0x75720) [0x7fd21f9c5720] ??(...):0 ??
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0xee13d) [0x7fd21fa3e13d] ??(...):0 ??
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9669) [0x7fd21f2e8669] ??(...):0 ??
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fd21f424323] ??(...):0 ??
Report this to project maintainer with the backtrace.

**Comment by BTAxis** [comment]
Try changing your sound backend to sdlmix.

**Comment by ids1024** [comment]
This seems to be the same issue as #806.

**Comment by universe-11** [comment]
Thanks, I change the sound to sdlmix and it works.... I go to Blue world.

**Comment by bobbens** [comment]
Closing as duplicate.
