### ISSUE TITLE
Warning: [ai_run] Pilot 'Lancelot' ai

### ISSUE THREAD

**Issue by universe-11** [naev/naev#976]
Naev v0.7.0 (x86_64-pc-linux-gnu)
 git HEAD at a2d958ab9
BFD backtrace catching enabled.
 Sea of Darkness

SDL: 2.0.10 [compiled: 2.0.10]

OpenGL Window Created: 1920x1080@24bpp fullscreen
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 16384
vsync: yes, mm: yes, compress: no, npot: yes
Renderer: GeForce GT 710/PCIe/SSE2
Version: 3.2.0 NVIDIA 435.21

Using default font '/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf'
SDL_Mixer Started: 44100 Hz Stereo
Renderer: pulseaudio
Version: 2.0.4 [compiled: 2.0.4]

Loaded 42 Sounds
Loaded 47 Songs
Loaded 16 Nebula Layers
Loaded 47 Commodities
Loaded 36 Factions
Loaded 37 AI Profiles
Loaded 121 Missions
Loaded 32 Events
Loaded 298 Outfits
Loaded 86 Ships
Loaded 134 Fleets
Loaded 61 tech groups
Loaded 373 Star Systems
       with 1140 Planets
Loaded 1 map decorators.

Warning: [ai_run] Pilot 'Lancelot' ai -> 'hyperspace': [string "dat/ai/include/basic.lua"]:510: Jump point must be in current system.
stack traceback:
	[C]: in function 'sethyptarget'
	[string "dat/ai/include/basic.lua"]:510: in function <[string "dat/ai/include/basic.lua"]:502>

**Comment by nenau-again** [comment]
Did you notice any consequence in gameplay ?
If not, I'll simply add this one to my collection of unresolved warnings to solve eventually.

**Comment by universe-11** [comment]
The game still can play. I only notice when I exit it.

**Comment by bobbens** [comment]
Looking at it, it seems like somewhere a weird hyperspace target is getting set. Looking at the code I think this is only possible if set by an event/mission explicitly. So something must be doing that. However, it shouldn't be a practical issue as the Lancelot will just end up ignoring that and doing something else I guess. It doesn't spam message every frame right?

**Comment by bobbens** [comment]
Closing as it seems to be a non-issue gameplay-wise. If it pops up again please re-open.
