### ISSUE TITLE
Soromid ship improvements

### ISSUE THREAD

**Issue by bobbens** [naev/naev#994]
Possible vectors for improvement are:
1. Make special requirements / events to level up specific items.
2. Add a mini help-message when buying first organic ship (tutorial-ish).
3. Add more lore / dialogues / news for Soromid ships.
4. Organic-ship oriented missions, etc.
5. Possibly add more complicated RPG-like system just for Soromid ships.

**Comment by Zireael07** [comment]
Very happy to see Soromid ships being differentiated from the others! I wish I still had my notes from back when I proposed some Soromid-only outfits, years ago...

**Comment by osetrovich** [comment]
Just thought about ship training (key components levelling up) system

The main idea is that player takes the basic undeveloped version of key components (propulsion, hull, brain center) (and weapons?) and just does his own business, while the ship adapts itself to the player's style. Will require to get some specific statistics though.
Ship components upgrades are mutually exclusive (stealth ship won't get tough armor, highload cargo missions will improve cargo space but decrease maneuverability and speeds).
Maybe minor ship upgrades after prolonged usage (which wears off after unusing the ship for a long time).
Considerable making ship key components as activated outfits? (afterburning on engine, forced armor regeneration/cloaking, shield recovery). Each usage of active option influences the evolution path. Activated outfits dynamically affect the CPU. If insufficient - won't work or will decrease shield/energy systems.

Possible approach to upgrade system:

Each outfit ability increases/decreases depending on the way it is used.  There can be new stage of evolution on reaching checkpoint on any available option. Stages are irreversable, but until checkpoint is reached, abilities can be downgraded.
To help the outfits move in specific way, special outfit boosters and nutrition complexes might be implemented to buy (requires additional outfit making)

1. Hull

1.1 Hull Branches
- Stealth - avoiding fires, evading, (activating stealth helpers)
- Armor - tanking, receiving damage and then recovering, (activating regen stims)
- Cargo - doing cargo runarounds with cargo close to max
- Mass reduction - Light cargo travel, light hull damage
- General - something in the middle.

1.2 Hull evolution methods
  - Cargo usage close to max -> +Available Cargo space.
  - Severe armor hurts and repairs -> +armor&regen and mass
  - Evasion maneuvers - +cloaking (chameleon mode)
  - Active Cooldown - -AC durability, +cloaking
  - activated cloaking - +cloaking
  

2. Engines:

2.1 Engines Branches:
- Speed - Light cargo (<50% load) travel, afterburning
- Cargo - Heavy cargo (>75% load) travel
- Maneuverability - evasion maneuvers, not so much afterburning
- Afterburning - afterburning
- General - Moderate cargo (50% <= load <= 75%) travel, afterburning, some evasive.

2.2 Engine evolution methods
- Light cargo (<50% load) travel - -availMass, +speed, -energy_usage
- Heavy cargo (>75% load) travel - +availMass, -speed, +energy_usage
- Afterburning usage - +speed, +afterburning, -overheat_on_afterburning
- Hyperjumps - common, +fuel space(?)
- Chasing the target/Evading fire - +speed, +turn, +thrust, -availMass

3. CPU

3.1 CPU Branches:
-  Control abilities (same as CPU in classic ships) - Using different outfits, loading at maximum
-  Shields - tanking, receiving damage and recovering. (How to describe shields as an organic ship system?)
-  Energy - exhausting the energy tank and letting it recover after a while.
-  Mass reduction - Loading CPU at 50%, taking low damage, using little energy. 

3.2 CPU evolution methods.

-  Changing armaments and utilities of different type - +CPU power
-  Heavy CPU load (>=90%) - +CPU power
- Taking heavy shield damage (>=90%) - +shield_capacity
- Taking moderate (>=50%) shield damage and then recover fast  - +shield_regeneration
- Exhausting the energy tank - +energy_capacity
- Heavily using the energy tank (<=20%) and letting it recover - +energy_regeneration.
- Taking moderate (<50%) shield damage, slightly using CPU (<60%) and energy (<40%) - -mass, -CPU, -shields, -energy

4. Armaments.

4.1 Armament branches:
  - Swiwel degree increase - missing the target but shooting close to it (up to turret)
  - Damage increase - shooting the target multiple times
  - Range increase - shooting the target out of range but on detection.
  - Fire rate increase - shooting the evasive target and missing
  - Disability/destruction - severely damaging or killing the target
  - Energy/projectile - shooting the target out of maximum energy weapon range

4.2 Armament evolution methods
  - Missing the target but shooting close to it (5deg) - +swiwel degree
  - Hitting the same target more than 8 times and not killing/severely damaging - +damage
  - Shooting the target out of range by 100 more than 10 times - +range
  - Shooting the evasive target and missing (>60%) - +fire rate
  - Aborting damaging the target on dealing >80% hull damage - +disable, -damage
  - Shooting the target out of maximum available range by 200 or more - +projectile, -damage

**Comment by bobbens** [comment]
![screenshot029](https://user-images.githubusercontent.com/54677/146673810-c5a02bb4-bcee-461d-b93a-e627be0fbd7d.png)
OK, so I've been working on this. I've decided to try to keep it more simple. Current design is:
1. There are intrinsic "on level up" skills and player choosable skills.
2. Skills are split into 5 tiers, small ships get up to 3, medium up to 4, and large up to 5.
3. No mutually exclusive branches.
4. Skills focus on giving new abilities rather than just stat bonuses. See **The Bite** in the attached screenshot as an example.
5. Some skill sets are ship-dependent. So small ships get stealth/movement, and large ships get domination/adaptation and such.
6. Soromid ships get much fewer normal slots to compensate.

#### Current skill sets:
1. **Bite**: revolves around cannibalism and biting enemies to death
2. **Movement**: revolves around afterburning and movement bonuses (up to corvette only)
3. **Stealth**: gives stealth and damage after stealth bonuses (up to destroyer only)
4. **Health**: gives survival bonuses
5. **Attack**: revolves around feral rage and damage output
6. **Plasma**: revolves around increasing plasma damage over time effectiveness (#1820 ) (TODO)
7. **Misc**: random stuff that just gives utility like more cargo or faster jumping
8. **Domination**: will revolve around buffs to allies and primal yell skill (TODO) (cruiser or larger)
9. **Adaptability**: will revolve around getting more slots and cpu (TODO) (destroyer or larger)

Lots of it is WIP and will probably undergo a lot of new changes, however, I'm pretty happy with this new direction. Skill points are meaningful and open up new interesting gameplay directions. Plus it should be able to add other ways to get skillpoints or even skill sets or skill tiers, which probably should happen through the Soromid campaign.

**Comment by bobbens** [comment]
Closing as this is mainly implemented.
