### ISSUE TITLE
Align format of <asteroid><pos> tag in SSys files

### ISSUE THREAD

**Issue by Mutos** [naev/naev#999]
I'm currently playing with the new asteroids feature and discovered an inconsistency in the way their position is written in the XML files, relative to the way every other position is expressed in both asset.xml or ssys.xml files.

In all NAEV XML files, positions tags look that way :

```
<pos>
  <x>-1644.922880</x>
  <y>-220.059200</y>
 </pos>
```
Here is an asteroids anchors position tag :

```
   <pos x="0.000000" y="0.000000"/>
```
I suggest to align the format for asteroids anchors positions to the general format with subtags <x> and <y>.

**Comment by nenau-again** [comment]
That comes from the asteroid system simplifications that happened in https://github.com/naev/naev/pull/917

@onpon4

**Comment by Mutos** [comment]
Thanks nenau for the information !

The idea should be to "just" replace **xmlw_attr** by **xmlw_elem** in **system.c** when writing XML for the SSystem, then find the place where you read them (**dev_system.c** or **space.c** ?) and replace whatever reading equivalent function appears there.

Of course, I put quotes around "just" because there is never such a simple thing, this will probably have implications unthought of.

**Comment by nenau-again** [comment]
Yep, it's in function `system_parseAsteroidField` in `space.c`
And we'll have to make corresponding changes in the systems that contain asteroids. As there are not too many, it's largely doable.
But first, let's wait for the opinion of onpon on this, and of the devs.

**Comment by onpon4** [comment]
I actually made it like that because defining these X and Y positions as separate tags is bloated and makes the XML files needlessly harder to read and write. It's three extra lines per position, which can add up a lot for asteroid fields with a lot of sub-fields and/or exclusion zones. It also makes writing more tedious: more indentation levels, more text. I don't see how there's any advantage at all in completely ignoring XML attributes.

If anything I think all position tags should be changed to what I used for asteroids. But I didn't do that because it would have meant painstakingly going through all the files and manually replacing them. In those other applications the problem of spreading out positions into four lines doesn't build up as bad as it does for asteroids, so it didn't seem worthwhile to me to change them.

**Comment by Mutos** [comment]
Hi onpon4,

Thanks for your opinion !

In the meantime, I had seen other objects using attributes as well. I first thought the assets were the reference, but it didn't seem so. And you're right with the bloating factor.

So don't be afraid, I won't do anything stupid ^-^

In fact, consistency among all objects with positions could enable to have common IO for positions, like it was done in utilities, for instance in naevdata.py which comes with starmap. This would save code and prevent Issues like this one, where wondering why it's sometimes subtags, sometimes attributes, leads us to much ado about (nearly) nothing ^-^ 

So I'm in favour of having everything by attributes, not urgently but when it'll be possible.

As a solution for conversion, I would propose a simple python script, that would read the XML file from the assets folder into a minidom document object, change the position tag from subtags to attributes and rewrite the same file into an assets-new folder. This way, it can be fired and tested as many times as needed, files compared between the two folders, then once both code and converter script are ready, we convert the files, get rid of the original folder and rename assets-new folder into assets.

**Comment by onpon4** [comment]
Yup, that would work too. 🙂

**Comment by bobbens** [comment]
Sounds good. IIRC the libxml API makes you free all the attribute values manually, while the node values don't need an handling, which is a bit annoying, but it should be fairly trivial to add more stuff to nxml.h to make a transition easy.

**Comment by UncombedCoconut** [comment]
> Hi onpon4,
> [...]
> So don't be afraid, I won't do anything stupid ^-^

::raises hand::
Ooh, I will!

It looks like the easiest way to do this is with a Python script that updates the repo in place. (lxml.etree in pretty-printing mode seems to match the existing format well.) That way, anyone with their own fork of Naev can run the same script, and review, and commit, and hopefully experience no merge issues that weren't already there.
I've got some nxml macros ready to deal with typed attributes. They're already making the code a lot cleaner.
It looks like the XML change will *mostly* be flattening nested `<x>`,`<y>` elements into one node.

In case of UniDiff documents, I'm a little tempted to make the optional `x`,`y` attributes of `<jump>` into an optional `<pos>` sub-element. But it doesn't matter much (only user is named "test.xml") and the C code probably won't be markedly cleaner either way. Probably I'll keep this structure as is.

**Comment by bobbens** [comment]
Everything uses attributes in eb3c45e330f460e58d0fc5119a671f81d4ae3981 . Thanks!
